statsmodels/statsmodels

statsmodels/regression/mixed_linear_model.py

This should resolve #2102, at least in the given example.  I didn't realize that numpy.diag returns a reference.
Most users of 0.6.1 will never encounter this, because it only comes in to play when the starting values along the profile are outside the domain of PSD matrices.  The second notebook example is extremely close to the boundary, which leads to failures on some machines (it seems to work on others).

Fix bug causing problems with profile likelihood analysis

---

statsmodels/genmod/cov_struct.py
statsmodels/genmod/tests/test_gee.py

This PR adds a new covariance structure to GEE that allows the covariances among pairs of observations to be specified through a collection of equivalence classes.  All pairs of observations within an equivalence class have the same covariance.

EqClass covariance structure for GEE

---

statsmodels/base/model.py
statsmodels/regression/linear_model.py
statsmodels/regression/tests/test_robustcov.py

closes #2142  (I opened that issue for the record and to link to the mailing list discussions)
cov_type that allows fixing the scale in the linear model.
main use_case is when weights in WLS are actual inverse variances
see discussions on mailing list
Todo:
- check other results
- llf uses MLE scale
- AIC, ... ?
- docstring
- example
- unit tests for scale kwd
DONE except for llf/loglike which needs refactoring, in all 3 linear regression models 
Questions:  
Should we change the default to `use_t=False`?  answer on mailing list: Yes
I think so, but IIRC we don't do it now as part of cov_type.  (`use_t` was part of cov_type but is now mostly a separate, independent keyword.)
correction: we already have `use_t=False` as default for every cov_type except `'nonrobust'`, set in …

ENH: add cov_type fixed_scale to linear model

---

examples/notebooks/chi2_fitting.ipynb

This is an example notebook for the fixed scale covariance type @josef-pkt  is adding in #2137.
You can view the current version of the notebook online here:
http://nbviewer.ipython.org/github/cdeil/statsmodels/blob/statsmodels-chi2-fitting/examples/notebooks/chi2_fitting.ipynb
It's work in progress ... I get an error from `WLS` and the `curve_fit` results don't match the reference results from the paper.
Also ... is it already possible to fit non-linear models with this covariance type?
If not, maybe this can be added and then I include an example in this notebook?

Statsmodels chi2 fitting

---

statsmodels/base/covtype.py
statsmodels/regression/linear_model.py
statsmodels/regression/tests/test_robustcov.py

fixes #2168,  
cov_type cluster fails if groups has extra dimension, missing squeeze

BUG: clustered cov fails when groups are 2d vector. Closes #2168

---

statsmodels/genmod/families/family.py
statsmodels/genmod/families/links.py
statsmodels/genmod/families/tests/test_link.py
statsmodels/genmod/families/varfuncs.py
statsmodels/genmod/generalized_linear_model.py
statsmodels/genmod/tests/test_glm.py

closes #1736 and #1958, see also #1788 
This is a PR to allow GLM's to be fit using scipy optimizers.  It also fills some other gaps and corrects a few inconsistencies in the GLM implementation.  Here are the main points:
* The method keyword argument to fit can be IRLS (as before), or the name of any scipy optimizer.
* Several deriv2 implementations that were missing in family.py were falling back to numerical differentiation, which leads to issues with run time and big inaccuracies in some cases.  I have added most of the missing analytic deriv2 functions.
* I added tests for most of the links and associated functions (inverses, derivatives, etc.).
* I resolved inconsistencies in some of the signatures for the negative binomial family.
* I added a likelihood function that takes params …

ENH: Add gradient-based optimization for fitting GLM's

---

statsmodels/nonparametric/tests/test_lowess.py

REF: Don't use partial funcs in generators for nose. Closes #2121.

---

statsmodels/genmod/generalized_linear_model.py
statsmodels/genmod/tests/test_glm.py

This fills some gaps in the GLM test code.  For (almost) every valid link for every family we test the IRLS results versus the Newton's method results (comparing params, bse, llf, and scale).
Mostly things look good.  For some non-canonical links the results are very sensitive to the input data, but I was eventually able to find something that worked, except for the inverse_square link.  This suggests that the calculations in the code are OK.  However we should look into having better support for difficult cases.  
Another issue is that we only get agreement between IRLS and Newton when using the expected information to calculate bse after the Newton fit.  But the default is the observed information.  Thus most users will see a difference when they make the comparison (although the …

Test: Test GLM IRLS vs Newton using all links

---

statsmodels/genmod/generalized_linear_model.py
statsmodels/genmod/tests/test_glm.py

closes #2019
this allows the recreation of GLM models with exposure, same solution as for discrete CountModel.
replaces #2104  to be backwards compatible and consistent across models
However, exposure needs to change, see #2175 and other issues

REF/BUG: add _get_init_kwds to GLM to handle exposure

---

statsmodels/genmod/cov_struct.py
statsmodels/genmod/tests/test_gee.py

This PR has two main parts:
1. The equivalence classes can now be specified using a vector of labels, rather than by providing the pairs dictionary directly.  This is not as general, but much easier when it can be used.  For example, if there are two labels 'a' and 'b', the free parameters to be estimated are: cov(a, b), cov(a, a), cov(b, b), var(a) and var(b).  In this case cov(a, a) refers to the covariance between two different observations in the same group that fall into label class 'a', whereas var(a) is the variance.  cov(a, a) will generally be smaller than var(a).  An application where this would be useful is a situation where there are repeated measures on subjects, say of two biomarkers A and B measured at 3 time points, with 2 technical replicates at each time point.  Then …

ENH GEE equivalence class covariance structure enhancements

---

statsmodels/genmod/families/family.py
statsmodels/genmod/tests/test_glm.py

This fixes a minor bug in GLM link warnings (added in #2208) that led to safe links raising unnecessary warnings.  The bug is due safe_links containing aliases log, logit, etc. rather than the parent classes Log, Logit, which means that links such as cloglog which are subclasses of, say, Logit are not recognized as being subclasses of logit.
Also silence warnings in tests when we are deliberately testing unsafe links.
Resolves problems discussed in #2222.

BUG: GLM link warnings

---

docs/source/stats.rst

Adds medcouple, robust skewness and kurtosis and expected kurtosis to the docs
closes #2174
[skip ci]

DOC: Add robust skewness and kurtosis to docs

---

docs/source/release/version0.7.rst
statsmodels/genmod/generalized_estimating_equations.py
statsmodels/genmod/generalized_linear_model.py
statsmodels/genmod/tests/test_gee.py
statsmodels/genmod/tests/test_glm.py
statsmodels/graphics/_regressionplots_doc.py
statsmodels/graphics/regressionplots.py

This PR adds checks for matplotlib in regression plot tests for GLM and GEE.
In addition:
* It fixes a bug in the regression plot GLM/GEE results methods that occurs when calling from a model fit by a formula.
* It handles more carefully the conditional mean calculation for CERES residuals to avoid creating
a design matrix with redundant columns.
* Mention this new feature in the 0.7 release notes.

Regression plots issues including #2227

---

statsmodels/datasets/tests/test_utils.py

try to work around Ubuntu python xy testing problems, see issue #2233 
this should now be using http instead of https
If this still causes an error, then we add a skip-test

TST: webuse test try http location see #2233

---

statsmodels/base/model.py
statsmodels/base/tests/test_generic_methods.py
statsmodels/examples/ex_wald_anova.py
statsmodels/stats/contrast.py

wald test for terms that go over several columns
basic version tested for OLS, GLM and Poisson,  use_t=False only
It's not an ANOVA table, we ignore sum of squares or equivalent.
not clear: name of method, currently is `wald_anova`, alternative `wald_test_terms`  ??? DONE
I settled on `wald_test_terms` as the more explicit term.
**missing**
- ignored for now: Multinomial where several things don't work
**extension**
- multi-equation models as in BetaRegression, and others to come
**open**
should we add `wald_null` ?  
hypothesis: all slope coefficients are zero, only constant is non-zero
------------
**Design for results class**
still a bit messy, creates table DataFrame similar to `lm_anova` from where the design was initially taken.
partially adjusted the results class to have standard …

Wald anova

---

statsmodels/examples/ex_predict_results.py
statsmodels/genmod/_prediction.py
statsmodels/genmod/generalized_linear_model.py
statsmodels/regression/_prediction.py
statsmodels/regression/linear_model.py
statsmodels/regression/tests/tests_predict.py

adding `get_prediction` to linear_model RegressionResults
everything is written in standalone function for reuse in other models, but some things are linear model specific. (It's not a generic function.)
main issue for regression.linear model #719 
also several discussions on mailing list
SUMMary issue for extension to other models #2150 
some implementation discussion for wrapping #2145 
**Status**
so far mainly the basic outline, I'm trying to get that settled first
I didn't check much of the details yet. 
unit test against old sandbox function.
now also method for GLM with link handling, conf_int is endpoint-transformation, see #938
PR also contains `statsmodels.genmod._prediction.params_transform_univariate`, currently as a helper function for simple non-linear prediction
useful for …

Prediction interval

---

statsmodels/stats/sandwich_covariance.py
statsmodels/tools/grouputils.py

The way this is set up should make refactoring easier (removing `group_sum` from `sandwich_covariance` in favor of the one in `grouputils`). I found `pd.factorize` to be an order of magnitude faster than `np.unique` on large arrays, so I went with that.

BUG: make `group_sums` more mem efficient. Closes #2169.

---

statsmodels/stats/outliers_influence.py
statsmodels/stats/tests/test_diagnostic.py

closes #2148 outlier influence `_res_looo` predefined arrays with possibly wrong dtype
supersedes #2149

BUG dtype in outlier influence

---

statsmodels/genmod/tests/test_gee.py
statsmodels/tools/pca.py
statsmodels/tools/tests/test_pca.py

PCA incorrectly imported matplotlib which is not mandatory.  Also removes
unneeded import in GEE test.

TST: Make Matplotlib optional

---

statsmodels/tsa/statespace/_statespace.pyx.in

Fixes #2253. Bug caused by memoryview indexing (`array[i,j]`) used on pointer variable in little-used option. Corrected by referring to the memoryview rather than the pointer.

FIX: Cython indices error

---

statsmodels/tsa/statespace/mlemodel.py
statsmodels/tsa/statespace/sarimax.py
statsmodels/tsa/statespace/tests/test_sarimax.py

- remove cov_params method use inherited
- add df_resid, required by t_test, currently np.inf
- rename test class that didn't run with my nosetests
- lower precision a bit, switch an assert to `assert_allclose`  see #2257

BUG: fix t_test wald_test requirements

---

statsmodels/tsa/statespace/sarimax.py
statsmodels/tsa/statespace/tests/test_sarimax.py

see #2252 followup state space, SARIMAX
recreating a model, motivation: #1093
the current design for this is to define 
- `_init_keys` attribute list of keyword keys in `__init__` and 
- `_get_init_kwds` method to return dictionary with init keys and values. generic version is attached in `base`, can be used to overwrite specific values (e.g. log exposure in count and glm)
The problem is that here `endog` is transformed in some cases.
still test failures, I don't define and use specialized `_get_init_kwds` method yet

ENH/BUG: add update _init_keys (still test failure)

---

statsmodels/compat/python.py
statsmodels/datasets/__init__.py
statsmodels/datasets/tests/test_utils.py
statsmodels/datasets/utils.py

This kind of reverts https://github.com/statsmodels/statsmodels/pull/2241 to run tests only if internet is available.
The approach is pretty naive, so feel free to reject.

TST: Check internet availability before running tests

---

statsmodels/tsa/vector_ar/tests/test_var.py
statsmodels/tsa/vector_ar/var_model.py

closes #1636 
fix as proposed in comment of #1636 
unittests approximately verify correct irf.sterr()
(This PR took me some time to prepare because I ran into other VAR bugs)

BUG: var irf cov_alpha for trend and no constant

---

statsmodels/base/tests/test_data.py
statsmodels/tsa/tests/test_arima.py

see #2308
this fixes the unit tests
this does no solve the underlying problem that `missing='ignore'` might cause invalid linalg operations (and could crash or hang with some versions of BLAS/LAPACK)
see #2311 to add missing handling to the constant detection method (useful if used standalone), see my comments to #2311 
------------
question based on fixing the arimax test: do we have proper missing handling for initial conditions?.  nan was introduced by `exog.diff()` (by user/test not by ARIMA)
-> new issue #2338

TST fix test to avoid nans in exog if missing are ignored

---

statsmodels/regression/mixed_linear_model.py

There was a NumPy DeprecationWarning at line 160 (creation of a ``np.zeros`` array with length being a float instead of an integer).
```
/opt/Python-3.4.3_virtualenv/lib/python3.4/site-packages/statsmodels/regression/mixed_linear_model.py:160: DeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
self._params = np.zeros(self.k_tot)
```
According to source code, ``k_re2`` is the number of covariance parameters, hence should be an integer. Line 523 uses the floor division for creating ``k_re2``, while line 156 used the classic division (in Python 3). Changing from classic to floor division on line 156 removes the DeprecationWarning.

ENH: From classic to floor division for k_re2, removes NumPy DeprecationWarning

---

statsmodels/tsa/x13.py

closes #2411
python 3 compatibility fix, checked with example on python 3.4
(no travisCI test run because of missing dependency. I didn't use [ci skip] because it is a code change)

MAINT: tsa.x13 python 3 compat 

---

statsmodels/graphics/mosaicplot.py
statsmodels/graphics/tests/test_mosaicplot.py

rebased version of Kerby's PR #2286
adds a smoke test based on http://stackoverflow.com/questions/31031780/statsmodels-mosaic-plot-valueerror-cannot-convert-float-nan-to-integer
I also tried to remove the labels for empty cells, but didn't manage to remove all overlapping labels, and didn't add this change
in 
`@@ -454,11 +454,15 @@ def _create_labels(rects, horizontal, ax, rotation):`
```
-            level_ticks[value] = y_lab if side % 2 else x_lab
+            if W > 0:
+                level_ticks[value] = y_lab if side % 2 else x_lab
```

Mosaic cornercase rebased

---

statsmodels/regression/linear_model.py
statsmodels/regression/tests/test_regression.py

see #2444
I'm not closing 2444 in case I come up with the full solution, or sombody does.

BUG: OLS set fvalue to nan if implicit constant and robust cov 

---

statsmodels/regression/quantile_regression.py
statsmodels/regression/tests/test_quantile_regression.py

fixes #2377 (exception with zero residuals) by replacing sign with inequality, assigns zero residual to positive
see also #2485
this includes smoke and regression unit tests
comment on second test case: If I did it correctly during debugging, then the second example raised the exception in the 6th iteration on my computer. The final result doesn't contain zero residuals.

Bug quantreg zero residuals

---

statsmodels/genmod/families/family.py

closes #2037
NegativeBinomial
resid_dev has nan if endog = 0
avoid integer alpha     (I'm on python 3.4 and don't see integer division)
this doesn't add unit tests, we need a proper NegativeBinomial test case with zeros in endog

Bug glm NegativeBinomial fix for #2037

---

statsmodels/tsa/statespace/representation.py
statsmodels/tsa/statespace/sarimax.py
statsmodels/tsa/statespace/tests/test_sarimax.py

Fixes #2264. Quoting from there:
Currently, the Kalman filter initialization must be performed after construction. Need to add the ability to specify it during construction via keyword argument. Four new keywords (and then class attributes) would be specified:
Parameters
----------
initialization : {'approximate_diffuse','stationary','known'}, optional
Method
initial_variance : float, optional
If approximate diffuse initialization is used, the initial variance of states.
initial_state : array_like, optional
If known initialization is used, the mean of the initial state's distribution.
initial_state_cov : array_like, optional
If known initialization is used, the covariance matrix of the initial state's distribution.

ENH: Add initialization via keyword args to init.

---

statsmodels/tsa/statespace/kalman_filter.py
statsmodels/tsa/statespace/tests/test_kalman.py

Scipy 0.11 didn't have the `check_finite` argument to `cho_factor`.

COMPAT/TST: Statespace: Standardized residuals: fix compatibility with Scipy 0.11, add tests

---

statsmodels/sandbox/regression/gmm.py
statsmodels/sandbox/regression/tests/test_gmm.py

see #2446 t_test doesn't work - this should be fixed by this PR
see #2495  how should users specify cov_type - first part of refactoring to address this
this breaks some backwards compatibility and I had to change existing unit tests to use renamed `_cov_params` method
now with unit tests for t_test, tvalues pvalues, consistency and Stata
only smoke test for inherited wald test
required temporary hack to use `use_t=True` in one unit test case
possible candidate for 0.7

BUG gmm cov_params

---

statsmodels/genmod/cov_struct.py
statsmodels/genmod/generalized_estimating_equations.py
statsmodels/genmod/tests/test_gee.py

* Fix a bug that raised an exception when fitting ordinal and nominal GEE models with formulas
* Add two parameter-free covariance structures for nominal or ordinal data that are independent except between indicators derived from the same observation
* Refactor categorical covariance structures to descend from abstract base class
* Privatize ncut
* Move starting values calculations for categorical models in subclasses
* (Hopefully) accelerate GlobalOddsRatio by using outer minimum to replace two temporary arrays

ENH/BUG Various GEE improvements

---

statsmodels/tsa/statespace/kalman_filter.py
statsmodels/tsa/statespace/mlemodel.py
statsmodels/tsa/statespace/tests/test_options.py

Fixes the issue described #2514 by forcing filtering to use univariate or LU factorization (rather than Cholesky) whenever complex-step derivatives are calculated.

FIX: State space: Cholesky factorization with complex step derivatives

---

statsmodels/tsa/arima_model.py
statsmodels/tsa/tests/test_arima.py

closes #1691
I have some doubts about my approach here. It looks like exog_names was added to address Issue #626 back in the day, but it almost seems to assume that `_make_arma_names` (and hence `fit`) is run at most once against the model.

prevent _make_arma_names from adding exog_names when already present

---

statsmodels/tsa/statespace/mlemodel.py
statsmodels/tsa/statespace/representation.py
statsmodels/tsa/statespace/sarimax.py
statsmodels/tsa/statespace/tests/test_representation.py
statsmodels/tsa/statespace/tests/test_sarimax.py

Fixes #2545, and cleans up a couple of other minor state space issues:
- Non-time-varying matrices were not always returned in representation.__getitem__
- Bug in certain cases where there is only a single parameter.
- Removes some duplicate code (TestClark1989ConserveAll)

FIX: SARIMAX predict breaks when simple_differencing=True

---

examples/incomplete/glsar.py
statsmodels/regression/linear_model.py
statsmodels/regression/tests/test_glsar_stata.py

This is a version of #2269  with additional commits: fix empty history, additional unit tests, update example file
The last commit adds some refactoring, and adds whitening for the last fit. The last fit after convergence is still a duplicate that doesn't update the whitened endog and exog.
changed that history parameters numpy array has params in rows

Glar history add

---

statsmodels/tsa/statespace/kalman_filter.py
statsmodels/tsa/statespace/mlemodel.py
statsmodels/tsa/statespace/sarimax.py
statsmodels/tsa/statespace/tests/test_sarimax.py

See #2554 for description of the problem. If there are time-varying matrices and a subsample with `end < nobs` is selected, the time-varying matrices are never cut down to match the size of that subsample. Thus the time-varying matrix used for prediction still has time-dimension length of `nobs` even though it should have time dimension length of `end`.

BUG: Statespace: Error with dynamic predict over a subsample when time-varying matrices are present.

---

statsmodels/duration/hazard_regression.py
statsmodels/duration/tests/test_phreg.py

the PHSurvivalTime.surv object was getting overwritten when the number of strata is greater than 1. This commit fixes the bug. I did not include a test. I'm not that comfortable writing them yet.

surv object being overwritten bug

---

statsmodels/base/optimizer.py
statsmodels/tsa/arima_model.py
statsmodels/tsa/base/tsa_model.py
statsmodels/tsa/tests/test_arima.py

ARMA predict  (usability bugs, not incorrect numbers)
fixes #2587 pandas date handling in `end`
fixes #2589 1d exog
This also includes changing the default iprint to zero in lbfgsb optimizer.
This should solve several reported crashes when the lbfgsb fortran code tries to write to a file but is not able to.
(It looked like it didn't close the file handle when optimization finished. Two processes blocked each other for file write access and crashed/segfaulted.)

BUG: ARMA predict better input handling

---

statsmodels/tsa/statespace/mlemodel.py
statsmodels/tsa/statespace/tests/test_representation.py

Fixes #2611, by reducing the precision of `test_kalman_gain` and using pseudo-inverse instead of true inverse in covariance matrix calculations.

BUG: Statespace: Test failures on certain Travis builds.

---

setup.py
statsmodels/graphics/tests/test_mosaicplot.py
statsmodels/graphics/tests/test_tsaplots.py
statsmodels/graphics/tsaplots.py
statsmodels/tools/testing.py
statsmodels/tsa/ar_model.py

- fix old_behavior kw for numpy.correlate (was removed in 1.10.0). Closes gh-2667.
- fix deprecation warnings from pandas 0.17.0
- fix backwards compat break in pandas 0.17.0 (removal of ``pandas.version``)
Numpy PR that removed ``old_behavior`` kw: https://github.com/numpy/numpy/pull/5991

MAINT: fix some test issues due to numpy 1.10.0 and pandas 0.17.0

---

statsmodels/tsa/statespace/dynamic_factor.py
statsmodels/tsa/statespace/tests/test_dynamic_factor.py
statsmodels/tsa/statespace/tests/test_varmax.py
statsmodels/tsa/statespace/varmax.py

Fixes #2643 by adding `smooth` methods to multivariate models. First commit shows the test failures due to using the base object, second commit adds the `smooth` methods.

BUG: Statespace: `smooth` in multivariate should return corresponding results objects

---

.travis.yml
examples/python/discrete_choice_overview.py
examples/python/robust_models_1.py
setup.py
statsmodels/base/tests/test_data.py
statsmodels/compat/pandas.py
statsmodels/discrete/discrete_model.py
statsmodels/graphics/tests/test_mosaicplot.py
statsmodels/graphics/tsaplots.py
statsmodels/iolib/tests/test_foreign.py
statsmodels/sandbox/multilinear.py
statsmodels/tools/data.py
statsmodels/tools/print_version.py
statsmodels/tools/testing.py
statsmodels/tsa/statespace/dynamic_factor.py
statsmodels/tsa/statespace/mlemodel.py
statsmodels/tsa/statespace/representation.py
statsmodels/tsa/statespace/tests/test_dynamic_factor.py
statsmodels/tsa/statespace/tests/test_mlemodel.py
statsmodels/tsa/statespace/tests/test_representation.py
statsmodels/tsa/vector_ar/tests/test_var.py

Version 0.17 of pandas doesn't offer the 'version' module anymore. Instead, it provides the version via the default `__version__` attribute. I modified the `safe_version` function to allow for alternative means of finding the version for a given module. For example, to reliably get the version of pandas the call is:
safe_version(pandas, ['version', 'version'], '__version__')
And now it works again.

Corrected version detection for new pandas

---

statsmodels/datasets/anes96/data.py
statsmodels/datasets/cancer/data.py
statsmodels/datasets/ccard/data.py
statsmodels/datasets/co2/data.py
statsmodels/datasets/committee/data.py
statsmodels/datasets/copper/data.py
statsmodels/datasets/cpunish/data.py
statsmodels/datasets/elnino/data.py
statsmodels/datasets/engel/data.py
statsmodels/datasets/fair/data.py
statsmodels/datasets/grunfeld/data.py
statsmodels/datasets/heart/data.py
statsmodels/datasets/longley/data.py
statsmodels/datasets/macrodata/data.py
statsmodels/datasets/modechoice/data.py
statsmodels/datasets/nile/data.py
statsmodels/datasets/randhie/data.py
statsmodels/datasets/scotland/data.py
statsmodels/datasets/spector/data.py
statsmodels/datasets/stackloss/data.py
statsmodels/datasets/star98/data.py
statsmodels/datasets/statecrime/data.py
statsmodels/datasets/strikes/data.py
statsmodels/datasets/sunspots/data.py
statsmodels/iolib/foreign.py
statsmodels/iolib/openfile.py
statsmodels/iolib/smpickle.py
statsmodels/tsa/kalmanf/kalmanfilter.py
statsmodels/tsa/vector_ar/util.py

I started this when I got a warning about a lot of files being open during the tests. Checking the code, all the data loading had a dangling call to  'open'. Although this should be collected at some point, this may be delayed and it happened to me a few times.
This PR is to solve this by replacing all the call to the `open` function by a `with`-statement, to ensure the file is close when returning the data.
I also use this opportunity to remove some needlessly imported symbols in the data modules.

Ensure files are not left open, mostly in the  data sets

---

README.rst

It's also a convenient link to the build logs

add Travis CI status icon

---

statsmodels/stats/multitest.py
statsmodels/stats/tests/test_multi.py

This PR implements two techniques from the paper:
B Efron (2008).  Microarrays, Empirical Bayes, and the Two-Groups Model.  Statistical Science 23:1, 1-22.                                                                               
The ``local_fdr`` function calculates local False Discovery rates from Z-scores.  We could possibly implement this as an option within ``multipletests``, but it's nice to have the option to operate on z-scores rather than p-values, which ``mutlipletests`` does not allow.
The  ``empirical_null`` function estimates a non-standard normal distribution based on a set of Z-scores that consists of an unknown mixture of null and non-null hypotheses.  It uses a likelihood-based version of the "central matching" idea.
See also #1371.

Local FDR, estimation of null Z-score distribution

---

statsmodels/tsa/statespace/_statespace.pyx.in
statsmodels/tsa/statespace/tests/test_representation.py

Fixes #2732 by correctly indexing in the case of missing data (so the `kfilter.e_endog` variable will be different than the dimensions of the `kfilter.forecast_error_fac` array in memory).

BUG: Statespace: Error in determinant calculation with certain patterns of missing data

---

statsmodels/duration/hazard_regression.py
statsmodels/duration/tests/test_phreg.py

Miscellaneous minor improvements to PHReg:
* attach `df_resid` and `df_model` attributes (otherwise can't be used with `predict_functional` and perhaps other places)
* better handling of variable names passed as auxiliary variables (e.g. `entry`)
* provide additional information about dropped strata and entry times in summary output

Missing attributes and improved summary for Cox models

---

statsmodels/stats/tests/test_weightstats.py
statsmodels/stats/weightstats.py

I added weighted quantiles to the`DescrStatsW` class.  The calculation is straightforward, right out of the SAS docs:
https://support.sas.com/documentation/cdl/en/procstat/63104/HTML/default/viewer.htm#procstat_univariate_sect028.htm
I couldn't find a good way to integrate tests into the existing test code, so I started an independent testing mixin class.  This provides some additional test coverage for other statistics (mean, var, sum, sem, etc).

Weighted quantiles

---

statsmodels/discrete/discrete_model.py
statsmodels/iolib/tests/test_foreign.py
statsmodels/stats/mediation.py

Pandas 0.17.0 [deprecated](https://github.com/pydata/pandas/pull/11173) `DataFrame.convert_objects` in favor of type specific converters. This was the only usage of `convert_objects` that I found.
Also found a couple uses of `irow` and `icol`, which I've fixed up.

COMPAT: for pandas deprecations

---

statsmodels/tsa/statespace/mlemodel.py

Fixes the issue in #2798 and #2800 by making sure `jarquebera` is not called with nan elements. Allows test results from `test_normality` and `test_heteroskedasticity` in the case of missing data. Puts a note in `test_serial_correlation` documentation about output (which is `nan`) in the case of missing data.

ENH: Statespace: Diagnostic tests in missing data case.

---

.travis.yml

Ok, I was curious about why 2 of the builds weren't working. I figured out how to make one of them work, but the other is kind of a pickle still. 
- It seems that I need to force conda to install the `libgfortran` package. I think this package probably used to be installed via a dependency in the past, but that is over. This prevents builds .2 and .4 from running. 
- On build .2, I think we are trying to use mkl to do the test. I need to force conda to install mkl as well. 
Once I did those 2 things, this all ran. One weird thing... it appears that build .2 fails now only using the mkl drivers. Its a close fail--it may be related to some of the other changes we've made. But it only happening on build .2 is strange. I'm especially confused by the test …

FIX: Conda needs some more dependencies

---

statsmodels/regression/tests/test_lme.py

@josef-pkt noticed some warnings in MixedLM tests.
A few of these were due to incorrectly using stale starting values.  That is fixed.
Several others were due to fitting models where the MLE is on the boundary of the parameters space.  I have silenced these.
I also caught and fixed an error in `test_sparse`.
Everything should now run clean.
Finally, a bunch of pep8 fixes.

MixedLM test enhancements

---

statsmodels/base/tests/test_shrink_pickle.py
statsmodels/discrete/tests/test_sandwich_cov.py
statsmodels/genmod/families/family.py
statsmodels/genmod/generalized_linear_model.py
statsmodels/genmod/tests/test_glm.py
statsmodels/stats/sandwich_covariance.py

this is squashed and rebased version of #2805 
plus
- fixes GLM fit_gradient bug start
- add freq_weights correction in sandwich code (experimental, likely we stick with it)
- unit tests for GLM fit_gradient and with cov_type=HC0 for GLM with freq_weights

Glm weights rebased

---

statsmodels/tsa/statespace/structural.py

There's no 'resid' in plot_components function, I think it will be the endog length.

Fix plot_components issue if endog without dates

---

statsmodels/tsa/statespace/tests/test_dynamic_factor.py
statsmodels/tsa/statespace/tests/test_sarimax.py

A couple of statespace tests were failing when using one of the OpenBLAS
kernels (Sandybridge).  See #2876 for discussion.  Increase tolerance slightly
to allow tests to pass.
Closes gh-2876.

TST: relax test thresholds slightly for OpenBLAS

---

statsmodels/base/model.py
statsmodels/base/tests/test_generic_methods.py
statsmodels/base/tests/test_shrink_pickle.py
statsmodels/duration/tests/test_phreg.py
statsmodels/regression/linear_model.py
statsmodels/regression/tests/test_regression.py
statsmodels/sandbox/mice/mice.py

Modified the RegressionModel predict method to return a pandas DataFrame if the original model data was in the form of a DataFrame.
Fixes #1352

ENH: Allow predict to return a DataFrame

---

docs/source/plots/graphics_month_plot.py
statsmodels/graphics/tsaplots.py

isn't tested, plain substitution to reflect changes for which e.g. f1dc89 was the fix

BF: leftover pd.datetools.parse -> parse_time_string for compat with recent pandas

---

statsmodels/graphics/tests/test_mosaicplot.py

Closes #2910.
Adds `pylab.close('all')` to the end of mosaic plot tests which create figures.

TST: Explicitly close mosaic plot figures.

---

statsmodels/regression/tests/test_lme.py

The vcomp tests fail on old scipy, for some unkown reason.
Also, change test docstrings to regular comments to simplify reading travis output.

Skip a mixedlm test on old scipy

---

statsmodels/tsa/base/tests/test_base.py
statsmodels/tsa/base/tsa_model.py

Fixes #1180
TimeSeriesModel tries to coerce pandas index to datetime before throwing an error.

BUG: Try to coerce index into datetime before failing

---

statsmodels/tsa/statespace/sarimax.py
statsmodels/tsa/statespace/tests/test_prediction.py

Fixes the problem with incorrect prediction index - and more generally with incorrect values in `self.data.dates` - when `simple_differencing=True`.
See #2939 for the bug report.

BUG: SARIMAX dates if simple_differencing=True

---

statsmodels/tsa/seasonal.py
statsmodels/tsa/tests/test_seasonal.py

Added nside=2 to the arg list of seasonal_decompose in tsa/seasonal.py, so users can choose the way to do filter on the trend in STL decomposition.

expose nsides to the seasonal_decompose so users can choose their favorite filter method for the resulting trend and residual.

---

statsmodels/tsa/stattools.py

When raising an exception in `coint`, the passing of inputs into a formatted string is out of place.
`raise ValueError("regression option %s not understood") % regression`
instead of
`raise ValueError("regression option %s not understood" % regression)`

Typo in exception, premature closing of ValueError

---

statsmodels/stats/proportion.py

Adjusted upper and lower bounds to the optimizer when using the 'binom_test' method for `proportion_confint` to solve the `brentq fails ValueError: f(a) and f(b) must have different signs` error.  Also, enforced bounds out to 0.0 or 1.0 in the case where that's the ML estimate.

Fix conversion error in proportion_confint

---

statsmodels/sandbox/stats/multicomp.py

The intent seems to be to call ones with a specific shape, which requires a sequence or integer, but the parameters aren't a tuple and it throws a data type error.

Fix ones() call

---

statsmodels/regression/mixed_linear_model.py
statsmodels/regression/tests/test_lme.py

This came up in discussion of #2961.
What I have here fixes the issue and adds a test, but I want to change the names to be more consistent (sometimes they are Z1, Z2, etc. which is not very meaningful).

BUG: Fix name-related error in random_effects

---

statsmodels/discrete/tests/test_constrained.py
statsmodels/genmod/generalized_linear_model.py
statsmodels/genmod/tests/test_glm.py
statsmodels/stats/tests/test_mediation.py

Hello, 
I'd like to propose changing how you do convergence checking for GLM IRLS fits. 
A few notes:
1. Currently, I think the iteration check for IRLS has an off-by-1 error. The 1st run check's the 0th iteration vs. the -1st iteration. The 2nd  iteration will check the 1st and 0th. The 3rd with check the 1st and the 2nd, and so on. 
2.  I've been playing with statsmodels on some insurance datasets. I typically get really large datasets (hundreds of thousands of observations). I'm having difficulty getting convergence in reasonable times because the convergence tolerance is an absolute `1e-8`. I think this makes more sense because deviance increases as you add more observations. On a large dataset, waiting for deviance changes as small as 1e-8 requires many (essentially useless) …

ENH: Relative tolerance for GLM convergence

---

statsmodels/tsa/tests/test_tsa_tools.py
statsmodels/tsa/tsatools.py

Allows lagmat to return pandas DataFrames when calling lagmat with Series or
DataFrame inputs, without changing default behavior of reurning ndarrays.

ENH: Improve lagmat to understand pandas

---

statsmodels/base/wrapper.py
statsmodels/compat/python.py

Python 3 has deprecated getargspec in favor of signature.
getargspec has been removed in Python 3.6.

COMPAT: Remove dependence on getargspec in Python 3

---

statsmodels/base/elastic_net.py
statsmodels/base/model.py

Avoid using SVD to check for constant and exog rank in internal elastic net iterations where this is not needed.
Cuts run time in half for larger problems.
Also minor refactor in base.model to avoid needlessly calculating the rank of the same matrix twice.
See issue #2971

PERF: Speed improvements for elastic net

---

statsmodels/graphics/tests/test_tsaplots.py
statsmodels/graphics/tsaplots.py

Enable array input to show only specific lags
Change CI behavior to not include 0
Refactor both plots to exploit common structure
Add new kwarg, zero, to include/remove lag 0 from plot
closes #2430
closes #1658

ENH: Enable ACF and PACF plots to accept array inputs

---

statsmodels/duration/survfunc.py
statsmodels/duration/tests/test_survfunc.py

This is a relatively simple extension to support frequency weights in Kaplan Meier estimation of survival curves.
Some relevant background:
http://www.inside-r.org/r-doc/survival/survfit.formula
http://www.ssc.ca/survey/documents/SSC2003_J_Lawless.pdf

ENH: Add freq_weights to Kaplan Meier estimation

---

appveyor.yml
statsmodels/multivariate/tests/test_pca.py

Add support for running on appveyor
If this is still interesting, passes with one `skipif` needed for 32 bit Windows (a non-failure but tiny difference).
https://ci.appveyor.com/project/bashtage/statsmodels/build/1.0.2
closes #1799
closes #1800

TST: Add appveyor support

---

statsmodels/tsa/filters/hp_filter.py
statsmodels/tsa/filters/tests/test_filters.py

The issue with relative import of test results is that it breaks running the tests in that file (with ``nose.runmodule``). This pattern is used in lots of places in the test suite. I can fix them all up if you agree with the change.
Other fixes are pyflakes/pep8.

MAINT: fix some test and style issues with tsa.filters.hp_filter.

---

docs/source/conf.py
docs/source/imputation.rst
statsmodels/base/elastic_net.py
statsmodels/base/model.py
statsmodels/duration/survfunc.py
statsmodels/emplike/originregress.py
statsmodels/imputation/mice.py
statsmodels/sandbox/formula.py
statsmodels/stats/contingency_tables.py
statsmodels/stats/mediation.py
statsmodels/stats/multitest.py
statsmodels/tsa/vector_ar/var_model.py

Fixes a number of small documentation errors such as
wrong descriptions (Arguments vs Parameters) and typos.
Also fixes wrong module locations for moved modiel

DOC: Fix small documentation errors

---

examples/notebooks/tsa_arma_1.ipynb

`maparams` was missing `s`. This creates ARMA(2,1) process instead of ARMA(2,2) as originally intended.

Fixing a typo

---

statsmodels/tools/data.py
statsmodels/tools/tests/test_tools.py
statsmodels/tools/tools.py
statsmodels/tsa/tests/test_tsa_tools.py
statsmodels/tsa/tsatools.py

Simplified these two functions to handle NumPy arrays and recarrays as
well as pandas Series and DataFrames.  Removed bugs in add_trend.
Added complete test coverage for both functions.

CLN: Simplify add_constant and add_trend

---

appveyor.yml
statsmodels/datasets/utils.py
statsmodels/graphics/utils.py
statsmodels/iolib/table.py
statsmodels/sandbox/nonparametric/smoothers.py
statsmodels/sandbox/regression/try_treewalker.py
statsmodels/sandbox/stats/diagnostic.py
statsmodels/tools/tools.py
statsmodels/tsa/ar_model.py
statsmodels/tsa/arima_model.py
statsmodels/tsa/base/tsa_model.py
statsmodels/tsa/statespace/mlemodel.py
statsmodels/tsa/statespace/sarimax.py
statsmodels/tsa/statespace/tests/test_mlemodel.py
statsmodels/tsa/statespace/tests/test_structural.py
statsmodels/tsa/stattools.py
statsmodels/tsa/tsatools.py
statsmodels/tsa/vector_ar/util.py

Switched Python 2.7 to 64 bit which mostly elimiates noise which seems to be driven by small integer types.  
@ChadFulton Also found an incorrect practice of using `isinstance(*, int)` which should usually be `isinstance(*, (int, long))` for older Python.  Fixed all instances where I though it could be hit, even it accidentally.

TST: Switch appveyor 64bit

---

statsmodels/imputation/ros.py
statsmodels/imputation/tests/test_ros.py

Supercedes #2021 
In the environment, we can nearly never say that a certain parameter doesn't exist. Instead, we say that it was not detected, and as a result report a detection limit that corresponds to the lowest possible quantifiable value of the instrument and/or measurement method. You can think about this as measuring the diameter of hair with a ruler. You know the hairs have diameters, and you know they're <1 mm, but that's about all you can say.
So trying to compute basic stats about these data sets can be tricky. Luckily Dr. Helsel wrote a couple of text books about how to deal with this. [Here is the one I used to write this code](http://www.amazon.com/Nondetects-Data-Analysis-Statistics-Environmental/dp/0471671738).
Also [here's a overview …

ENH: add function ROS implementation to imputation module

---

statsmodels/nonparametric/kdetools.py

Numpy in master now raises exceptions for array indices that are not integers.

Cast array indices to integers in kdetools

---

statsmodels/tools/numdiff.py
statsmodels/tools/tests/test_numdiff.py

`approx_fprime` does not allow complex dtype input parameters because the gradient vector is hardcoded to float. This just changes the type of the gradient vector to that of the input parameter vector.

ENH: approx_fprime with complex parameters.

---

statsmodels/imputation/tests/test_ros.py

try to temporarily disable test for imputation.ros

TST: disable imputation ros tests, incompatible with older pandas

---

statsmodels/base/covtype.py
statsmodels/discrete/tests/test_sandwich_cov.py
statsmodels/regression/linear_model.py
statsmodels/regression/tests/test_robustcov.py

closes #2864 and related
1.
hac-panel versus nw-panel
hac-groupsum versus nw-groupsum
got mixed up between docstring and code.
Note: I prefer hac instead of nw, this PR allows both, but we will eventually deprecate nw
2.
name conflict doc - code for `"kernel"` in docstring versus `"weights_func"` in code.
this PR allows both
3.
add kernel option to HAC
with consistency checks in unit tests

REF/BUG/DOC Fix robustcov names of cov_types

---

docs/source/release/version0.8.rst

I think I stop with this.
I didn't go carefully through the list of bug fixes to see if something should be mentioned.
and I don't remember backwards incompatible changes. 
(I think there are no intentional backwards incompatible changes, except bugfixes, and predict return should be backwards compatible)

REL: release notes update, add names

---

statsmodels/tsa/ar_model.py
statsmodels/tsa/tests/test_ar.py

Fix select_order to allow 0 lag length selection when all coefficients
are insignificant
closes #2658

BUG: All t-stat lag length selection when nothing significant

---

docs/source/release/version0.8.rst

Added more detailed release notes for the added state space models and the Markov switching models

REL/DOC: Statespace, markov-switching 0.8 release notes

---

tools/nbgenerate.py

Closes https://github.com/statsmodels/statsmodels/issues/3047
Should work when you have the default `python2` or `python3` names. Otherwise you'll need to specify it with the `--kernel_name` command line option (which isn't available for make files). I'm still trying to find a canonical way of "get the default kernel for this environment", but this should do for now.

DOC/BUILD: Look for kernel name

---

docs/source/release/index.rst

this add the release notes to the index
but is missing the github-stats that I don't have

DOC: add 0.7 and 0.8 to release notes/what's new index

---

docs/source/_static/examples.css
docs/source/index.rst
docs/themes/statsmodels/indexsidebar.html

cc @josef-pkt 
Also removed the suggestion to use the `--upgrade` flag, since that can cause all sorts of trouble by updating not just statsmodels.
looks like

DOC: change doc link and remove easy_install

---

.travis_coveragerc

Exclude compat code
Exclude print_version
Exclude code after __name__ == '__main__'
Exclude other unrunnable code from coverage

COV: Improve accuracy of coverage

---

statsmodels/tsa/statespace/tests/test_mlemodel.py
statsmodels/tsa/statespace/tests/test_sarimax.py

Precision errors with 32-bit manylinux wheels.
See: https://github.com/statsmodels/statsmodels/issues/3067

BF: relax test precision for 32-bit failures

---

statsmodels/tsa/arima_model.py
statsmodels/tsa/tests/test_arima.py

Added ability to use the long AR method in fitting ARIMA start_params
Improved tests. Fixed case where longar_maxlag is greater than length of
series
Changed longar_start_params variable name to start_ar_lags
closes #2550

ENH: Add new method to generate starting params

---

statsmodels/base/model.py
statsmodels/duration/hazard_regression.py
statsmodels/duration/tests/test_phreg.py
statsmodels/genmod/generalized_estimating_equations.py

This PR is intended to solve a longstanding problem with Cox models, which must not have an intercept (either explicit, or hidden in the columnspan of the design matrix).
When the formula has no categoricals, it is sufficient to use "0 + " or "- 1" in the formula.  But with categoricals, having "0 +" just means that the intercept is hidden as a linear combination of columns.  
The solution we have found is to allow Patsy to put the intercept in, then remove it.  It works with everything we have tried including some fairly complex things (e.g. high order interactions of multi-level categoricals mixed with non-categoricals).
Unfortunately, there is no easy way to implement this purely inside the PHReg class  -- you need to get in between where the formula is processed and where the model is …

BUG/ENH: Intercept handling for PHReg

---

statsmodels/tsa/regime_switching/markov_switching.py

Closes #3092 
@josef-pkt I guess this should be backported. Do I just make a new PR against the tag?

BUG: Numpy deprecation warnings due to non-integer index array created from np.r_[ ]

---

statsmodels/base/data.py
statsmodels/tsa/statespace/dynamic_factor.py
statsmodels/tsa/statespace/mlemodel.py
statsmodels/tsa/statespace/sarimax.py
statsmodels/tsa/statespace/structural.py
statsmodels/tsa/statespace/tests/test_sarimax.py
statsmodels/tsa/statespace/tests/test_structural.py
statsmodels/tsa/statespace/tests/test_varmax.py
statsmodels/tsa/statespace/varmax.py

Closes #3108.
@josef-pkt I change the order of keyword arguments in this PR to make the SARIMAX methods match with the generic mlemodel method order. Is that considered a backwards incompatible change that I should avoid?

BUG: Statespace: get_prediction/get_forecast with exog

---

statsmodels/tsa/statespace/sarimax.py

Nothing big, this exact key is defined about ten lines down in the same dict.
Noticed this while browsing for a good place to insert the BoxCox mixin.

Key defined twice

---

statsmodels/base/tests/test_generic_methods.py
statsmodels/stats/contrast.py

closes #3116 
fix alpha to be used in t_test summary headers
summary frame does not specify alpha in column headers
add unit tests to test_generic_methods

BUG: t_test fix alpha in summary column header 

---

statsmodels/graphics/mosaicplot.py
statsmodels/graphics/regressionplots.py
statsmodels/graphics/tests/test_dotplot.py
statsmodels/graphics/tests/test_factorplots.py
statsmodels/graphics/tests/test_gofplots.py
statsmodels/graphics/tests/test_mosaicplot.py
statsmodels/graphics/tests/test_regressionplots.py
statsmodels/graphics/tests/test_tsaplots.py
statsmodels/stats/tests/test_power.py
statsmodels/tsa/vector_ar/tests/test_var.py

closes #3103
I added a unit test to compare the sizes used in the plot, but it uses a matplotlib figure private attribute `_sizes`.  This is most likely not robust, and might need to be `try except AttributeError` protected
I used matplotlib '1.5.1', and tests pass on my computer (only for the test method, I still get segfaults running the test class)
Detail (as explanation to test code): the plotted sizes are a affine transformation of the influence criterion, so I check that the residuals of the linear regression are close to zero.

BUG graphics influence plot, switched criterion

---

statsmodels/base/model.py
statsmodels/base/tests/test_generic_methods.py

closes #3087
solution: reindex to original exog after patsy has removed rows with missing
Considered as a bugfix, with backwards incompatibility in the formula-missing case.
needs update of release notes.

BUG: base.Results.predict, handle nan index with formula

---

docs/source/stats.rst
statsmodels/stats/proportion.py
statsmodels/stats/tests/results/results_multinomial_proportions.py
statsmodels/stats/tests/test_proportion.py

This should (at least partially) close #2895 (thanks for the help in that discussion!), implementing the "Goodman" and "Sison & Glaz" methods. No existing code was used for the implementation (aside from the MultinomialCI R package for generating test values and finding bugs by comparing intermediate values).
A few notes:
* I just found out about the [informal commit format standard](http://statsmodels.sourceforge.net/devel/dev/maintainer_notes.html#commit-comments), so commit messages don't all follow it; sorry about that (although rebasing+squashing could solve this I believe). I also tried to follow the general code style, but there might be fixes to do (e.g. I define several local functions for `sison_glaz`).
* I didn't include this addition in `docs/source/release/versionX.X.rst`, …

ENH: simultaneous confidence intervals for multinomial proportions (rebased)

---

statsmodels/base/covtype.py
statsmodels/discrete/tests/test_sandwich_cov.py
statsmodels/regression/linear_model.py
statsmodels/regression/tests/test_robustcov.py

closes #3155
`cov_type='hac_panel'` allow groups instead of time to specify panel units
adds also case insensitivity to cov_type keyword
I didn't check if `hac-groupsum' can be similarly changed. Without checking the details again, I think it's not possible because we need the time index to aggregate for contemporaneous correlation.

Covtype hacpanel groups

---

statsmodels/genmod/generalized_linear_model.py
statsmodels/genmod/tests/test_glm.py
statsmodels/genmod/tests/test_glm_weights.py

closes #2891
GLM resid_working is calculated incorrectly
I didn't try to run the test examples in Stata. (that's a lot of work without ready made `do` files)
I corrected the reference numbers, and activated the tests that has correct Stata numbers in test_glm_weights.
(One-character bug fix with several hours of figuring out the unit tests.)

BUG: fix GLM resid_working

---

statsmodels/duration/hazard_regression.py
statsmodels/duration/tests/test_phreg.py

The broadcasting approach creates all the outer products first then reduces them by summation.  For large datasets we encountered memory errors when there wasn't enough room to store the broadcasted matrix.
The einsum approach resolves the memory problem, but I expected it to be slower for small data sets.  But actually it seems to be about 2x faster, so win-win, at least in the checking I have done.
There is possible further improvement using the `out` parameter of einsum, but I will not get to that now.
(edited for clarity)

PERF: Use einsum instead of broadcasting in PHReg hessian calculations

---

statsmodels/discrete/discrete_model.py
statsmodels/discrete/tests/test_discrete.py

should close #2968 
in discrete binary pred_table uses incorrect bins if a column is zero
I just saw that MNLogit has the same problem if a boundary column is zero
not yet fixed or looked into, unit test commented out
Note: 
There is a backwards incompatible change in behavior if a probability is exactly at the threshold. 
Before, the ties are treated as 0 event, now as 1 event, which is the default
After thinking, I will change this again to be consistent with MNLogit, which inherits argmax behavior which chooses the first occurrence if there is not only one max.
**update**
switched back to ties go to lower index
fixed MNLogit.pred_table

BUG: fix binary pred_table for zeros see #2968

---

statsmodels/tsa/statespace/mlemodel.py
statsmodels/tsa/statespace/tests/test_mlemodel.py

Currently if a diagnostic test fails during a `summary` call, the exception is passed through. This PR catches the exception and displays the summary, where the failing test statistics are replaced by `nan`.

BUG: Statespace: Summary fails if diagnostic tests fail

---

statsmodels/tsa/base/tests/test_base.py
statsmodels/tsa/base/tsa_model.py

Closes #3068.
Puts a shim in to allow correctly creating the `DatetimeIndex` in the nanosecond case.

BUG: TSA models if date index without known frequency

---

statsmodels/tsa/seasonal.py

The old error message claims the timeseries index is not valid, even tough it could happen that this message is produced by a valid timeseries index with a timeseries frequency set to None.

DOC enhance misleading error message

---

docs/source/statespace.rst

Fixes the documentation problem related to the introduction of `complex_step` keyword argument to `update`, `filter`, and `smooth`. See e.g. #2970

DOC/BUG: Statespace custom model documentation

---

statsmodels/tsa/statespace/sarimax.py
statsmodels/tsa/statespace/tests/test_sarimax.py

Fails due to attempted in-place subtraction of float array from integer array.

BUG: SARIMAX start_params when endog is integer

---

statsmodels/tsa/statespace/sarimax.py

BUG: Backport: SARIMAX start_params when endog is integer

---

statsmodels/tsa/statespace/dynamic_factor.py
statsmodels/tsa/statespace/kalman_filter.py
statsmodels/tsa/statespace/mlemodel.py
statsmodels/tsa/statespace/representation.py
statsmodels/tsa/statespace/sarimax.py
statsmodels/tsa/statespace/simulation_smoother.py
statsmodels/tsa/statespace/structural.py
statsmodels/tsa/statespace/tests/test_impulse_responses.py
statsmodels/tsa/statespace/tests/test_representation.py
statsmodels/tsa/statespace/tests/test_simulate.py
statsmodels/tsa/statespace/tests/test_structural.py
statsmodels/tsa/statespace/tests/test_varmax.py
statsmodels/tsa/statespace/varmax.py

Primarily a PR to improve test coverage on `simulate` and `impulse_responses` methods. Also:
- Produces a backwards incompatible change in `simulate` and `impulse_responses`, where the returned dimensions did not match the documentation in the case of multivariate models
- Fixes a bug when simulation was run twice and the second simulation had fewer `nobs` than the first.
- Introduces a flag (`_time_invariant`) for state space models to explicitly flag they are time invariant (rather than having to detect based on system matrix shapes)

BUG/ENH/TST: State space: Simulate / Impulse Responses

---

statsmodels/regression/linear_model.py
statsmodels/regression/mixed_linear_model.py
statsmodels/regression/recursive_ls.py

This PR fixes a number of typos in docstrings and comments inside `statsmodels.regression`.

DOC: Fix typos in statsmodels.regression

---

statsmodels/tsa/statespace/_kalman_smoother.pyx.in

A non-ASCII character (a dash) was present in `_kalman_smoother.pyx.in`.
Closes #3286.

COMPAT: UTF-8 dash to ASCII

---

statsmodels/tsa/statespace/_simulation_smoother.pyx.in
statsmodels/tsa/statespace/tests/test_simulation_smoothing.py

This problem was caused due to using a short-cut for simulation smoothing where we filter the difference y_t - y_t^+ rather than separately filtering y_t and y_t^+ (see Durbin and Koopman, 2002). When filtering each separately, the `obs_intercept` should be kept as in the usual model, but when filtering the difference, the `obs_intercept` must be set to zero.
Durbin, J., and S. J. Koopman. 2002. “A Simple and Efficient Simulation Smoother for State Space Time Series Analysis.” Biometrika
Closes #3304

BUG: State space: Simulation smoothing with observation intercept.

---

statsmodels/discrete/discrete_margins.py
statsmodels/discrete/tests/test_discrete.py

closes #3309 
margins for MNLogit:
- summary() lost one of the conf_int columns in refactoring for conf_int header column titles
- summary_frame: make it work with MNLogit, 2d/multivariate endog was not supported

BUG: MNLogit margins fix summary and summary_frame

---

statsmodels/regression/quantile_regression.py

For now convergence cycle warning in quantile regression is printed every 100 iterations after 300, even if there were no real cycle detected which may be pretty annoying when training with more iterations.
In this patch I move warning to print it only if convergence cycle was really detected.

Fix false convergence cycle warning

---

statsmodels/tools/grouputils.py

I fixed some failing tests. 
Seems to be 2 things...
1. I _think_ pandas `read_table` in 0.19 closes a `StringIO` automatically somehow in python 2.7. (Not exactly sure why...) So I just went around that. 
2. `sort` is deprecated on an index... its now `sort_values`
I can squash this all this if desired. I was trying to figure out the fails and kept making new unnecessary commits.

TST: Fixed failing tests

---

statsmodels/stats/tests/test_anova.py

In test_anova.py, `read_table` will be run globally at the module level which should account for the fact that read_table now closes `StringIO`
I ran this locally on my windows anaconda with python 3.5 and pandas 0.19.0. 
Follow-up to #3239 
Closes #3228

TST: Fix pandas 0.19.0

---

statsmodels/genmod/generalized_estimating_equations.py

This fixes the numpy compatibility error when running the test suite with numpy 1.12
see #3332
This does not address the FutureWarnings

MAINT/REF: use integer division in NominalGEEResults see #3332

---

statsmodels/graphics/tests/test_tsaplots.py

Closes #3283 
- Fix tests to correctly use `'MS'` frequency.
- Replace deprecated `pd.datetools.parse_time_string` with `pd.tseries.tools.parse_time_string`.

TST/COMPAT: Compatibility with newer Pandas

---

statsmodels/imputation/mice.py

Resolves #3177 by raising if the column names are integer type.

ENH: Raise if MICEData dataframe has integer column names

---

statsmodels/tsa/statespace/structural.py
statsmodels/tsa/statespace/tests/test_structural.py

Seasonal and AR piece of _init_kwds incorrectly set (b/c the class level attributes don't correspond exactly to the kwargs parameters).
Updates a test, and fixes the problem.

BUG: Incorrect init kwds for UnobservedComponents

---

examples/incomplete/arma2.py
examples/incomplete/dates.py
examples/python/tsa_arma_1.py
examples/python/tsa_dates.py

Remove ``pd.TimeSeries`` which has been alias of ``Series`` for a while, and dropped in 0.20.

REF: Replace pd.TimeSeries to Series

---

statsmodels/genmod/families/family.py
statsmodels/genmod/families/links.py

* We use power with exponent=1 for the identity link, but especially in the derivatives this creates problems when evaluating at 0.  So I split these out as special cases.  
* I rearranged some terms in the Gamma log likelihood to eliminate some numerical warnings.  
* Small flake8 edits

ENH/BUG: GLM link/family misc numerical improvements

---

statsmodels/tsa/statespace/sarimax.py
statsmodels/tsa/statespace/tests/test_sarimax.py

This is just a corner case, which may be useful e.g. when doing some automatic model selection things.
Basically this just allows e.g. using SARIMAX to fit regression models.

ENH: Allow SARIMAX models with no AR or MA parts

---

statsmodels/tsa/regime_switching/markov_switching.py
statsmodels/tsa/regime_switching/tests/test_markov_autoregression.py

Bug in attaching pandas indexes to data in results object.
(Ideally this would be done in a wrapper, but the data is such that the wrapper system isn't well setup to handle it).

BUG: Pandas date indexes in MarkovAutoregression

---

statsmodels/genmod/_prediction.py
statsmodels/regression/_prediction.py
statsmodels/regression/tests/tests_predict.py

The problem was, a weights value of `None` slipped through
to an arithmetic calculation, which lead to a `TypeError`.
With this patch, the code below does not raise an error
```python
n = 100
x = np.arange(n)
y = x + 2*np.random.randn(n)
X = sm.add_constant(x)
model = sm.GLM(y, X)
results = model.fit()
pred = results.get_prediction(X)
```

Fix GLM prediction with an exog and no weights

---

statsmodels/base/model.py
statsmodels/formula/tests/test_formula.py

patsy is expecting a DataFrame, but users may pass
a Series if their model has a single predictor.
Closes #3409
Closes #3182
should be back ported to 0.8.x

BUG: Cast Series to DataFrame before predicting

---

statsmodels/nonparametric/kernel_density.py

Correct error in KDE doc for conditional distribution
Unify math notation for densities
closes #3118
[skip ci]

DOC: Fix KDE docs

---

statsmodels/tools/sm_exceptions.py
statsmodels/tsa/stattools.py
statsmodels/tsa/tests/test_stattools.py

Special case perfect colinearity since ADF is not reliable
when residual variance is very small
closes #3190

BUG: Ensure coint works for perfectly colinearity

---

statsmodels/tsa/base/datetools.py

This is related to #3349, but as it applies to the pre-0.9 date handling code.
I can't replicate the failure on my machine with pandas 0.19.2, but hopefully this fixes it.

BUG: pandas 0.19.2 compatibility - long versus integer in timestamp (0.8 version)

---

statsmodels/regression/tests/test_lme.py

exception with float instead of integer in numpy 1.12 see test run in #3427
(not locally tested because I don't have numpy 1.12 yet)

MAINT numy 1.12 compatibility integer division

---

statsmodels/compat/pandas.py

This addresses the Pandas deprecation in #3427.

COMPAT: is_numeric_dtype deprecation in Pandas

---

statsmodels/tsa/base/tests/test_base.py
statsmodels/tsa/base/tsa_model.py

Closes #2553
Shim in 0.8 for accepting `datetime.datetime` objects in `TimeSeriesModel._get_predict_end`. The strategy is the same as in `_get_predict_start` (i.e. convert to string, then use `_str_to_date`).
It \*appears\* to fix the issue (in the sense that I can use datetime objects in start and end of `predict` calls), and it seems very straightforward, but I don't know whether or not to merge it because:
1. it's pretty late in the process now, and
2. since I've already refactored the dates for 0.9 I don't want to spend a lot of time making sure it doesn't break corner cases or something
@josef-pkt what are your thoughts?

BUG: _get_predict_end did not accept datetime (0.8 shim)

---

statsmodels/tsa/base/tests/test_base.py

This is the master counterpart of #3430, where I just add a unit test to make sure that the effect of that PR (to allow `datetime` objects as predict endpoints) is still valid in 0.9.

TST: Test types accepted by predict start / end

---

statsmodels/tsa/statespace/sarimax.py
statsmodels/tsa/statespace/structural.py
statsmodels/tsa/statespace/tests/test_tools.py
statsmodels/tsa/statespace/tools.py

Makes naming consistent for seasonal periods in SARIMAX and UnobservedComponents models, as discussed in #3381.
Just want to get this in before we release these models in 0.8.

REF: State space: Consistent naming of seasonal_periods

---

statsmodels/tsa/statespace/sarimax.py
statsmodels/tsa/statespace/structural.py
statsmodels/tsa/statespace/tests/test_tools.py
statsmodels/tsa/statespace/tools.py

REF: State space: Backport: Consistent naming of seasonal_periods.

---

statsmodels/multivariate/pca.py
statsmodels/multivariate/tests/test_pca.py

Fix PCA to correctly handle missing values when input is pandas
Add tests for alternative drop methods
closes #3347

BUG: Correct handling of missing in PCA

---

statsmodels/tsa/vector_ar/tests/test_svar.py
statsmodels/tsa/vector_ar/tests/test_var.py

CLN: Remote FutureWarning

---

MANIFEST.in

I don't know if this is relevant or not, but [this travis build](https://travis-ci.org/MacPython/statsmodels-wheels/jobs/199070534#L337) failed on the `python setup.py egg_info` step. Not 100% sure why it failed on that one, and not others, but I don't think removing this line should cause any issues.

PKG: Remove directory from manifest

---

.travis.yml
statsmodels/tools/print_version.py
statsmodels/tsa/statespace/tests/test_save.py
statsmodels/tsa/tests/test_ar.py
statsmodels/tsa/tests/test_arima.py
statsmodels/tsa/tests/test_stattools.py
tools/matplotlibrc.qt4
tools/matplotlibrc.qt5

Suggested new testing defaults for Travis using a rule to test things back at least 2 years. Dates below.
Update travis config to test releases at least 2 years old:
NumPy 1.8+ (Oct 2013)
SciPy: 0.15+ (May 3, 2014)
Pandas: 0.14+ (May 30, 2014)
Matplotlib: 1.3+ (July 31, 2013)

TST: Update travis

---

statsmodels/tsa/statespace/_kalman_filter.pxd
statsmodels/tsa/statespace/_kalman_filter.pyx.in
statsmodels/tsa/statespace/_kalman_smoother.pxd
statsmodels/tsa/statespace/_kalman_smoother.pyx.in
statsmodels/tsa/statespace/_representation.pyx.in
statsmodels/tsa/statespace/_simulation_smoother.pxd
statsmodels/tsa/statespace/_simulation_smoother.pyx.in
statsmodels/tsa/statespace/_statespace.pyx.in
statsmodels/tsa/statespace/kalman_filter.py
statsmodels/tsa/statespace/tests/test_kalman.py
statsmodels/tsa/statespace/tests/test_pickle.py
statsmodels/tsa/statespace/tests/test_save.py

Minimal patch to allow pickling.
Likely is not correct in the sense that the pickled objects would
not behave the same after pickling.

FIX: Allow statespace models to be pickled in Python 3.6

---

statsmodels/tsa/base/tsa_model.py

Fix bug in location finding where only scalars can be
used for indexing in NumPy 1.12
closes #3474

BUG: Fix bus in location finding

---

statsmodels/tsa/statespace/tests/test_sarimax.py

Fix test order dependence in test_sarimax.Test_ar_no_enforce
where changing order of tests could result in unexpected failure

TST: Fix issue with test order dependence

---

appveyor.yml

Add SciPy 0.14 to Appveyor to catch any Windows-specific issues

TST: Add older scipy to Appveyor

---

setup.py

Closes #3499
Makes sure the exclusions file has the appropriate separator for comparison in `cythonize.py`. Tested on my Windows machine and works there.

BLD/BUG: Exclusions path separator for Windows

---

statsmodels/tsa/statespace/mlemodel.py

#3423 mistakenly changed some defaults for `loglike`, `score`, and `hessian`. They were pretty benign changes, but this reverts them back to the originals.

REF: Revert default params: loglike score hessian

---

statsmodels/tsa/statespace/sarimax.py
statsmodels/tsa/statespace/tests/test_sarimax.py
statsmodels/tsa/statespace/tools.py

Previous code used a transformation for MA parameters that was incorrect near the lag polynomial invertibility boundary. This fixes it.
Also sets the threshold for "invertible" lag polynomial to `1. - 1e-10` rather than `1.`, which was causing issues (although different ones from the above MA transformation) very (very) close to the invertibility boundary, where the root was not close enough to 1 to trigger `is_invertible() == False` but was too close for the transformation to work.

BUG: Error in MA params transformation near invertibility boundary

---

statsmodels/duration/hazard_regression.py

`params` erroneously appeared in the docstring for `PHRegResults.predict`.

Fix PHRegResults.predict docstring

---

statsmodels/base/model.py
statsmodels/base/optimizer.py
statsmodels/discrete/tests/test_discrete.py

Initial implementation for #2629.
Right now I've used it to add a proof-of-concept access to `dogleg` optimization method. 
As a next step I see a lot of room for refactoring of existing internal `_fit_*` methods to make use of the added `_fit_minimize`, rather than accessing `scipy`'s methods directly. @josef-pkt would that fit in with what you've envisioned for #2629?

ENH: add scipy's minimize to optimizer

---

statsmodels/regression/linear_model.py
statsmodels/regression/tests/test_regression.py

The ridge regression shortcut we used before was not correct when alpha is a non-constant vector.  This fixes that problem.
#3624

Ridge regression fix  (closes #3624 first part)

---

.coveragerc
.gitignore

Recent versions of coverage [require](http://stackoverflow.com/a/37746141/2957943) the show_missing setting to be made explicit.  Apparently it was accidentally the default for a while.
Added to .gitignore the coverage report information.

Settings for coverage reports

---

statsmodels/sandbox/regression/gmm.py

Docstring says the name of argument is `instruments`, when in code it is `instrument`.

Make docstring consistent with argument name

---

statsmodels/discrete/discrete_model.py
statsmodels/discrete/tests/test_discrete.py

See #3565 
discrete Countmodel: fix offset is ignored in predict if both offset and exposure are not None
Adds a test that fails under the status quo.

BUG: fix in countmodel predict with exposure and offset

---

.travis.yml

see #3658  error in test cases with one numpy/pandas combination
This is a, at least temporary, work-around to get TravisCI green again.
I didn't look at the actual errors, and whether there is a proper fix for them.

MAINT: travisci fix pandas version

---

statsmodels/base/model.py
statsmodels/genmod/generalized_linear_model.py
statsmodels/genmod/tests/test_glm.py

Hello, 
In a GLM if you are using one of the scipy optimizer and the Hessian inversion fails (i.e., it is not positive definite), `None` is returned. When running `res.summary()` later, a matrix is divided by `None` which causes a crash. 
This fixes the problem by returning a matrix of `nan` of the same shape as `H`. 
Example fail:
```python
data = sm.datasets.cpunish.load_pandas()
data.endog[:] = 1
mod = sm.GLM(data.endog, data.exog, family=sm.families.Gamma())
res = mod.fit(maxiter=1, method='bfgs', max_start_irls=0)
res.summary()
```

BUG: Handle non-invertible hessian from GLM scipy optimizers

---

appveyor.yml

see #3658 
avoid pandas-numpy version combination that causes test errors
make change to appveyor same as travisci

MAINT: appveyor pin pandas version 

---

statsmodels/iolib/summary.py
statsmodels/regression/tests/test_regression.py

Ensure extra text is written to html for use in IPython

ENH: Add extra lines to summary HTML output

---

statsmodels/discrete/discrete_margins.py
statsmodels/discrete/tests/test_discrete.py

should close #3695 
I didn't go through the full code path, checking if unit tests are fine on all machines.
does not include yet a possibly similar problem for `_get_count_index`
subclassing CheckMargEff in unit tests adds tests for count_index which fails for prepend=True case
using the same removal of the index adjustment fixes issues on my testing python
unit tests in CheckMargEff look pretty comprehensive, so I think it will be good to merge.

BUG: margins dummy incorrect if prepended constant

---

statsmodels/base/model.py
statsmodels/base/tests/test_generic_methods.py

closes #2682
we moved/copied design_info to model.data, adjust code in wald_test_terms
I checked that a unit test fails before change if `orig_exog.design_info` is deleted

MAINT/REF: wald_test_term, use data.design_info

---

statsmodels/base/covtype.py
statsmodels/discrete/tests/test_sandwich_cov.py
statsmodels/regression/linear_model.py

closes #3606 
add asarray to hac_panel group and time  
adjust one test for this case (fails before, succeeds after change)

BUG/ENH: cov_type hac_panel missing asarray

---

statsmodels/regression/linear_model.py
statsmodels/regression/tests/test_regression.py

closes #3642
if constant is the only regressor, than fvalue has no slope parameters to check. constraint is empty. (*)
return nan for fvalue, 
avoids exception in summary
similar to #2444
(*) this is for fvalue base on wald_null if covtype is robust
with nonrobust cov_type, the behavior is  
(I never checked whether that makes sense, needs maybe a new issue)
```
>>> res_diff.fvalue
inf
>>> res_diff.f_pvalue
nan
```

BUG: nan fvalue for constant-only regression with robust cov_type

---

statsmodels/tsa/arima_process.py
statsmodels/tsa/tests/test_arima_process.py

Addresses comments in #3666
The only material difference between this and the previous is the removal of assertions about the length of `res`.  That assertion is implicitly tested in `assert_allclose`. 
closes #3666

BUG: Highly persistent test case for arma_acovf

---

statsmodels/compat/pandas.py
statsmodels/discrete/discrete_model.py
statsmodels/graphics/tests/test_tsaplots.py
statsmodels/tools/grouputils.py
statsmodels/tsa/base/datetools.py
statsmodels/tsa/vector_ar/util.py

Pandas 0.20 deprecated some modules. This imports them from the new locations.
Closes https://github.com/statsmodels/statsmodels/issues/3617

Compat for pandas 0.20.x

---

statsmodels/discrete/discrete_model.py

in `MNLogit.hessian`.
Relates to #3725.  While not an actual bug, the current behavior is definitely misleading.  The code currently defines `J` in a way that equals `self.J - 1`.  The variable name is sufficiently distinctive that a reader (i.e. me an hour ago) can easily make the incorrect inference that `J == self.J`.  This PR just fixes that.

Use `self.J-1` instead of defining `J`

---

statsmodels/base/model.py
statsmodels/genmod/generalized_linear_model.py
statsmodels/genmod/tests/test_glm.py

Hello,
I think this is a rather simple approach to exposing the expected Hessian for scipy optimizer fits. 
I thought about using functools `partial` but ran into some obstacles. The real issue is that context matters and not all the `hessian` methods have an `observed` parameter. So this was as simple as I could make it without much effort. 
xref #3257

ENH: Allow expected hessian in scipy optimizer fits

---

statsmodels/tsa/arima_model.py
statsmodels/tsa/tests/test_arima.py

closes #3733 
`__getnewargs__`
use defaults if attributes are not available for ARIMA pickling
changed unit test fails without and passes with changes

BUG Fix ARIMA pickling for ndarrays (no dates, freq) 

---

examples/notebooks/robust_models_1.ipynb
statsmodels/graphics/regressionplots.py
statsmodels/graphics/tests/test_regressionplots.py

Prevent abline form updating non-existant line
Fixes a bug that appears in robust_models_1 notebook

BUG: Prevent abline from updating non-existent line

---

statsmodels/tsa/regime_switching/markov_regression.py
statsmodels/tsa/regime_switching/markov_switching.py
statsmodels/tsa/statespace/dynamic_factor.py
statsmodels/tsa/statespace/sarimax.py
statsmodels/tsa/statespace/structural.py
statsmodels/tsa/statespace/tools.py
statsmodels/tsa/statespace/varmax.py

`tsa.regime_switching.markov_switching._prepare_exog` is repeated verbatim in each of four `statespace` models.  This PR moves that function to `statespace.tools.prepare_exog` and calls it from each of those models.
`statespace.tools.set_mode` declares `global foo` for a handful of module-level dictionaries.  The "global" is perfunctory.
`var_model` imports some names that do not match the conventions used elsewhere.  The last commit here cleans that up.

REF: MLEModel De-duplication

---

statsmodels/stats/contingency_tables.py
statsmodels/stats/tests/test_contingency_tables.py

* Add `__str__` methods so that the table objects and results returned as bunches are informative when printed.
* Fix problems with `make_df_square` (it wasn't tested and was not working with current Pandas)
* Allow nested lists, e.g. [[3, 5], [2, 1]] to be passed to the Table2x2 initializer.
* Fix issues with the two `from_data` methods
* flake8 edits

ENH/BUG Contingency table improvements

---

statsmodels/tsa/vector_ar/tests/test_vecm.py
statsmodels/tsa/vector_ar/var_model.py
statsmodels/tsa/vector_ar/vecm.py

fixes two bug in forecasting, see #3775
- hardcoded number of terms in ma-rep limited forecast horizon
- seasonal indices in VECM deterministic did not adjust season_start for trimming initial observations in arrays
vecm.py has also a function _deterministic_to_exog that creates seasonal dummies. The first_season argument will need to be adjusted if there is trimming of initial observations. I didn't check this function
It's only in the causality tests to create the VAR model which I guess uses the full arrays without trimming of initial observations.

BUG: VAR, VECM forecast horizon, season dummies

---

statsmodels/__init__.py

Adding an absolute import here solves an [error](https://github.com/pyinstaller/pyinstaller/issues/2183) when compiling apps with [pyinstaller](https://github.com/pyinstaller/pyinstaller) that use statsmodels.

Add absolute import for pyinstaller compatibility

---

statsmodels/regression/linear_model.py

Line 1321: "Model degress of freedom" -> "Model degrees of freedom"

Correct spelling error in linearl_model.py

---

statsmodels/discrete/discrete_margins.py
statsmodels/discrete/discrete_model.py
statsmodels/discrete/tests/results/results_count_margins.py
statsmodels/discrete/tests/test_margins.py

closes #3809
this is a quickly done fix based on the exceptions.
no unit tests yet, but results for default margeff of poisson, generalized poisson and negative binomial are in the same neighborhood in datasets.randhie example.
```
>>> np.column_stack((margin_poi.margeff, margin_nb1.margeff, margin_gp1.margeff))
array([[-0.15027281, -0.16679301, -0.20048418],
[-0.70677348, -0.77079325, -0.91461298],
[ 0.10094501,  0.11860651,  0.12731912],
[-0.0989064 , -0.10977451, -0.10183608],
[ 0.77721772,  0.77404021,  0.59241921],
[ 0.09708707,  0.10984954,  0.09931454],
[-0.03614158, -0.12703383, -0.10461374],
[ 0.15462413,  0.04965824, -0.13230278],
[ 0.58957703,  0.51223776,  0.32332714]])
```
and similar for standard errors

BUG/ENH: discrete margins, handle extra param (e.g. NegativeBinomial)

---

statsmodels/tsa/tests/test_arima.py

just trying out a fit option. I cannot replicate the error locally.
appveyor errors with SVD not converge in arima test on 2 out of 3 test environments

TST: arima test_start_params, add large start_ar_lags

---

docs/source/_static/facebox.js
docs/themes/statsmodels/layout.html

Hello,
In the official http://www.statsmodels.org docs, there is a missing "close" x whenever you open "View Code" facebox. 
I think the problem lies with this javascript.
(Fair warning... I don't understand all the intricacies of sphinx, so this may not be the best approach.)

DOC: Missing icons

---

statsmodels/discrete/discrete_model.py
statsmodels/discrete/tests/test_discrete.py

This PR refactors llnull to use start_params provide by `model._get_start_params_null`.
The start_params for the null model can be obtained by moment estimators, which should make it more robust.
closes related issues: 
#3533 second part is for llnull, first part is convergence failure with defaults (where users can work around)
#3476 Poisson llnull, mailing list thread has also discussion on MNLogit
#3572 NB2 llnull
related issue #3751 (is more general, e.g. penalization, constraints. I don't know yet what should/needs to be done)
This also includes now refactoring and fixes that I ran into:
#3919 avoid integer overflow in GP hessian, REF set endog, exog dtypes to at least float64
#3918 start_params needed to to provide transformed params if transformparams is used internally
`closes …

ENH/REF/BUG Discrete models llnull improvements

---

examples/notebooks/statespace_dfm_coincident.ipynb

I believe that this is a typo - since this part of the equation is handling the autoregression for the constant `u_t`

DOC: Equation typo in DFM notebook

---

statsmodels/tsa/statespace/mlemodel.py

by calling hessian with kwargs instead of calling _hessian_xyz.
In the existing code, `cov_params_xyz` checks `approx_complex_step` and based on that calls the correct `model._hessian_abc`.  That dispatch is already built in to `model.hessian` if the `approx_complex_step` kwarg is passed.
In `model.hessian` there are two cases with `method == 'approx'` that are not currently covered.  By redirecting cov_params calls through `hessian`, this PR gets those covered.
There are a couple of cases in the cov_params_xyz that are a) not currently covered and b) removed by this PR.  Comments indicate where those used to be.
There are two changes that are *not* in this PR but that merit discussion.
1) Small functions that could go somewhere like (the unfortunately-neglected) `base.cov_types`:
```
def …
```

Simplify MLEResults.cov_params_xyz methods

---

statsmodels/discrete/tests/test_discrete.py

not a full pep-8 cleaning, just some fixes that I had started in another PR
lline length, empty lines, use `#` instead of docstrings in test classes

CLN: test_discrete: manual cleanup

---

setup.py

Used in some of the statespace examples.
Closes https://github.com/statsmodels/statsmodels/issues/3517
[ci skip]

DOC: Add pandas-datareader to doc setup requires

---

statsmodels/sandbox/regression/gmm.py
statsmodels/sandbox/regression/tests/test_gmm.py

IV2SLS set fvalue to nan if const_idx is None, fix is similar to #2477 for RegressionResults
this allows summary to work instead of causing an exception
closes #3544

BUG: IV2SLS set fvalue to nan if const_idx is None

---

statsmodels/discrete/discrete_model.py

Remove deprecated chisqprob in favor of stats.distributions.chi2.sf
closes #3931

BUG: Remove deprecated scipy function

---

statsmodels/stats/sandwich_covariance.py

Also added label formatting to references and a comment about the HCCM acronym.
Closes #3680

Update broken link in docstring

---

statsmodels/compat/pandas.py
statsmodels/tools/data.py

There are a couple stray WidePanel uses in sandbox, but I wasn't able to run those anyway since my matplotlib is too new
```bash
statsmodels/compat/pandas.py:34:    data_klasses = (pandas.Series, pandas.DataFrame, pandas.WidePanel,
statsmodels/sandbox/examples/thirdparty/findow_0.py:11:uses DataFrame and WidePanel to hold data downloaded from yahoo using matplotlib.
statsmodels/sandbox/examples/thirdparty/findow_0.py:57:# combine into WidePanel
statsmodels/sandbox/examples/thirdparty/findow_0.py:58:pawp = pa.WidePanel.fromDict(dmall)
statsmodels/sandbox/examples/thirdparty/findow_1.py:11:uses DataFrame and WidePanel to hold data downloaded from yahoo using matplotlib.
statsmodels/sandbox/examples/thirdparty/findow_1.py:61:# combine into WidePanel …
```

COMPAT/CI: remove Widepanel and pandas dev

---

.travis.yml

Skip conda update to avoid errors in recent minicondas

BLD: Update travis for miniconda errors

---

statsmodels/genmod/generalized_estimating_equations.py

The definitions of `resid_working` in [GEE](https://github.com/statsmodels/statsmodels/blob/master/statsmodels/genmod/generalized_estimating_equations.py#L1472) and [GLM](https://github.com/statsmodels/statsmodels/blob/master/statsmodels/genmod/generalized_linear_model.py#L1318) are _almost_ identical.
#3164 changed the version in GLM from division to multiplication.  This PR just applies the exact same change to the GEE version.
Note that at the moment, the GEE version is not getting hit in tests.

GLM vs GEE resid_working mismatch?

---

statsmodels/tsa/tests/test_arima.py

closes #3950
this should remove a test failure that shows up now in one environment on appveyor, no problems in other cases and I don't have a fail locally with the versions in my dev environment
required atol was 1e-6, actual error according to test log is 3e-6

TST: test_arima111_predict_exog_2127 increase tolerance

---

pyproject.toml

Add pyproject.toml to simplify installation into empty environments
xref #3195

BLD: Add pyproject

---

statsmodels/discrete/discrete_model.py
statsmodels/discrete/tests/test_discrete.py

closes #3958 
simple fix mentioned in #3958 comments
adds unit tests to compare params and predict with pandas and with formulas
better fix might be to call super. I think that would be more robust but currently not needed

BUG: fix MNLogit does not store design_info

---

statsmodels/compat/scipy.py
statsmodels/discrete/discrete_model.py

Use loggamma for complex inputs and gammaln for non-complex
xref #3926

REF: Use dtype to select log gamma implementation

---

statsmodels/iolib/summary2.py
statsmodels/iolib/tests/test_summary2.py

#3707 rebased, squashed and edited 
the edit is to change to plain test classes and numpy asserts instead of using python unittest
the tests emit one irrelevant warning that should be silenced
`closes #3707, closes #3701, closes #3700`

REF: remove duplicate tabular objects in summary_col latex

---

statsmodels/compat/collections.py

Require absolute imports in the compat.collections module.

---

statsmodels/tsa/statespace/_kalman_smoother.pyx.in
statsmodels/tsa/statespace/_representation.pyx.in
statsmodels/tsa/statespace/_simulation_smoother.pyx.in
statsmodels/tsa/statespace/representation.py
statsmodels/tsa/statespace/tests/test_models.py

Closes #3833
Fixes an intermittent issue resulting in a segfault if k_posdef > k_states. Adds a test case.

BUG: State space: memory error if k_posdef > k_states

---

statsmodels/base/optimizer.py
statsmodels/tsa/arima_model.py
statsmodels/tsa/tests/test_arima.py

closes #3980  test_arima111_predict_exog_2127 test fails again in some test environments
first try: Tighten pgtol for lbfgs optimization in test - pgtol was already at the tighter level
relevant change: increase maxiter in ARMA/ARIMA
bonus: add `iterations` to lbfgs mle_retvals
Note point of test was not precision issues, just that exog is transmitted properly.
If this doesn't work, then we just increase test tolerance again.
As check: gopt in mle_retvals is much smaller than the explicitly computed score with lbfgs.
However, the predictions agree with solver='newton' at an atol around 5e-7,  
solver='newton' works well starting from the lbfgs params and has very small score at optimum, in contrast to lbfgs. 
The newton predicts also agree with those used in the unit test at around atol …

REF/BUG: ARMA/ARIMA increase default maxiter in fit

---

statsmodels/tsa/filters/_utils.py
statsmodels/tsa/seasonal.py
statsmodels/tsa/tests/test_seasonal.py

closes #3503
solution is about as discussed in #3503 avoiding freq check early in the function if freq is given
The two `_maybe_get_pandas_wrapper` functions overlap in code but I didn't merge them here.
```
+    if freq is None:
+        _pandas_wrapper, pfreq = _maybe_get_pandas_wrapper_freq(x)
+    else:
+        _pandas_wrapper = _maybe_get_pandas_wrapper(x)
+        pfreq = None
```

BUG: seasonal_decompose, don't check inferred_freq if freq given, 

---

docs/source/install.rst

Nightly builds are not updated and so should not be referenced
[skip ci]

DOC: Remove reference to nightly build

---

examples/notebooks/markov_autoregression.ipynb

Closes #3761.
One possibility for fixing this issue is to download the (identical) dataset from Stata for this notebook, Instead of getting the data from the unit test folder. This PR makes that change.

DOC/REF: Markov Autoregression notebook: use Stata dataset rather than from tests

---

docs/source/stats.rst

Move documentation for promoted functions to point to correct location
closes #3442

DOC: Move reference to non-sandbox modules

---

statsmodels/stats/_lilliefors.py
statsmodels/stats/diagnostic.py
statsmodels/stats/tests/test_diagnostic.py
statsmodels/stats/tests/test_lilliefors.py

first try on rebase of #3837
commits from master were automatically ignored
duplicate commits in PR needed manual conflict resolution
I changed same empty lines and needed to manually resolve a conflict in a commit that became essentially empty, i.e. later commits only add or delete empty lines.
some commits are redundant and I think the best would be to completely squash this before merging, or at least squash the set of commits towards the end
(there is one commit that changed author because I hit accidentally the commit button in git gui)

ENH: Lilliefors exp rebased

---

statsmodels/genmod/generalized_linear_model.py
statsmodels/genmod/tests/test_glm.py

closes #4001
add `wls_method` fit option
adds `mle_settings` to results in fit_irls  see comments in #2401
(started out to investigate differences across linear algebra functions, but should be good to merge)
extra keyword introduced for testing
`attach_wls` to attach the final WLS results to the GLMResults instance.
not included in docstring
(used in unit tests, and will be useful for future development, e.g. for diagnostics. 
It is doubtful whether this will be in the final API, e.g. WLS results are not available with fit_gradient.)

ENH: add wls_method option, mle_settings to GLM fit IRLS

---

statsmodels/graphics/tests/test_tsaplots.py
statsmodels/graphics/tsaplots.py

Separate keywords for vlines from general keyword arguments
Improve docstrings with details
closes #2369

BUG: Fix keyword arguments to plot_acf/pacf

---

statsmodels/base/data.py
statsmodels/base/tests/test_data.py
statsmodels/discrete/tests/test_discrete.py
statsmodels/genmod/tests/test_glm.py

related to #3483 
this raises before we hit the linear algebra and might hang.
the check and raise is in has constant handling of the data. It can still be worked around or does not apply if the keyword is explicitly specified.
I want to merge this into master to see what is going on and prevent nans or infs that might be accidentally created in the internal code.
Will need review before next release, e.g. 
- should we make it in general code even if has_const is specified
- are there use cases where we don't want to raise? 
We need to raise before we hit BLAS/LAPACK. But generic data handling might not be the right point, if we allow for imputation of missing values in exog in a model.
Note: this is more basic and cheaper than the `missing='raise'` keyword
- we use just ptp which is …

REF: raise in has constant check if exog is not finite.

---

statsmodels/tsa/regime_switching/markov_autoregression.py
statsmodels/tsa/regime_switching/markov_regression.py
statsmodels/tsa/regime_switching/markov_switching.py
statsmodels/tsa/statespace/dynamic_factor.py
statsmodels/tsa/statespace/mlemodel.py
statsmodels/tsa/statespace/sarimax.py
statsmodels/tsa/statespace/structural.py
statsmodels/tsa/statespace/varmax.py

@ChadFulton When it rains it pours.
This PR implements a `_res_classes` property in `statespace` and `regime_switching` models.  Analogous to pandas' `_constructor` properties, these are used to describe the Results and Wrapper classes a Model should use.
As you can see, implementing this allows us to get rid of _a lot_ of boilerplate.  (This reduction is even more dramatic outside of tsa).
The `_wrap_results` methods defined in `markov_switching` and `mlemodel` are identical, should eventually be moved into a shared parent class (along with a bunch of other stuff).
`_res_classes` returns a dictionary because in e.g. discrete_model, `fit_regularized` or `fit_constrained` will have different Results/Wrapper classes.

ENH: Implement _res_classes in statespace+regime_switching

---

statsmodels/stats/power.py
statsmodels/stats/tests/test_power.py

Warn the user that no amount of power can detect an effect size of 0
First time contributor, open to suggestions! Also I had a lot of trouble with local installation and wasn't able to get tests to run locally. Seeing what happens with Travis....

Improved handling of power calculations when effect-size = 0

---

statsmodels/genmod/tests/test_glm_weights.py

Remove pending deprecation yield tests for GLM weights
xref #4000

TST: Remove yield tests from GLM weights

---

statsmodels/tsa/vector_ar/var_model.py

Move links out of first line of docstring to avoid broken links

DOC: Fix broken links in VARResults

---

statsmodels/discrete/discrete_model.py

Can we please fix this small fraction of flake errors (565 remaining!)?  The indentation crud in the docstrings is really annoying.

remove unused imports; fix gratuitous flake8 errors

---

statsmodels/tsa/arima_model.py

Under the status quo there is a typo in ARMA.predict.__doc__, specifically an extra newline before "params : array-like".  This PR fixes that, and then cut/pastes two other large strings that are repeated in the docstring sections of the file.

DOC: Cleanup arima docstrings

---

statsmodels/tools/sequences.py
statsmodels/tools/tests/test_sequences.py

If `bounds` is not set, it raises an issue as the tuple does not have `min` nor `max` method from numpy.

FIX: discrepancy without bounds

---

statsmodels/tsa/seasonal.py

This turns "timeseries index witha freq" into "timeseries index with a freq".

DOC: Fix a typo in an error message

---

.travis.yml

As the CI takes quite a long time, this is an experiment to try make start-to-finish times quicker by having slower jobs run first, to make full use of the five available parallel jobs, so we don't need to wait for them to run at the end.
Looking at the seven jobs, and representing them in roughly five minute blocks, based on some recent master builds:
```
xxxxx
xxx
xxx
xxxx
xxxxx
xxxxxx
xxxx
--------- 9*5=45
```
If we put the slower ones first, in theory we should be waiting less time for the last to finish:
```
xxxxx
xxxxx
xxxxx
xxxx
xxxx
xxx
xxx
------- 7*5=35
```

Build slower jobs first to speed up build

---

statsmodels/tsa/vector_ar/tests/test_var_jmulti.py
statsmodels/tsa/vector_ar/vecm.py

Replace recarray with pandas for testing
Remove 0 imag components where they should be 0

CLN: Remove test noise from vecm

---

statsmodels/iolib/summary2.py
statsmodels/multivariate/factor.py
statsmodels/multivariate/tests/test_factor.py
statsmodels/multivariate/tests/test_ml_factor.py

This is an implementation of maximum likelihood factor analysis.  It probably would need to be integrated with #3294.  
The main reference for me was Bai and Li:
https://arxiv.org/pdf/1205.6617.pdf
They focus more on estimation in high dimensions, less on issues relating to model assessment which are very important in psychometrics.  Specialized methods for the latter are not included here.
This uses direct numerical optimization of the log-likelihood.  The gradient is not provided but scipy minimize seems to do OK without it here.  EM is also common and we could provide that as an optional algorithm.

Maximum likelihood factor analysis

---

docs/source/example_formulas.rst
examples/notebooks/formulas.ipynb

Use return_type='matrix' instead of return_type='dataframe'.
Document that the former returns patsy.DesignMatrix, which is a
sub-class of np.ndarray.

DOC: fix patsy.dmatrices np array example

---

statsmodels/base/_constraints.py
statsmodels/base/covtype.py
statsmodels/discrete/discrete_model.py
statsmodels/discrete/tests/test_constrained.py
statsmodels/genmod/generalized_linear_model.py
statsmodels/genmod/tests/test_constrained.py

issue #4193
This currently adds unit tests for Gaussian compared to OLS for a single parameter constraint, inlcudes cov_type='HC0' test.
There is one test failure with master, bug not yet fixed.
The work around is to assign cov_params_default which doesn't fail the unit tests.
cov_type='HC0' looks correct with `fit_constrained`, tests don't fail
bug fix which most likely works is
to assign directly to cov_params_default in fit_regularized
side issue: OLS and GLM don't agree on scale with master (in this branch), difference in example is around 1%
I got agreement between OLS and GLM-Gaussian for scale when I worked on top of #3856 which looks like fixes the scale difference.
Aside: fit_constrained never got a follow-up #1749, see comments in original PR #1714

BUG: GLM-Gaussian fit_constrained, wrong bse

---

statsmodels/genmod/families/family.py
statsmodels/genmod/generalized_linear_model.py
statsmodels/genmod/tests/test_constrained.py
statsmodels/genmod/tests/test_glm.py
statsmodels/genmod/tests/test_glm_weights.py

xref #3773 
I apologize for this taking longer than had hoped, but my busy period was exacerbated by some unforeseen events. But I'm somewhat back now.
This is the first step to solving the above issue. 
Still a lot is missing... I've only really gotten `loglike` to work for all the families except `Gamma`, `Binomial`, `Gaussian`, and `Tweedie` (which has never had `loglike`). I also need to re-work the docstrings. I'm thinking its more logical to have a `loglike_obs` function called in each family and then have a `loglike` function in the `Family` class so that `loglike` will simply be inherited. I think you the doctrings could be elegantly written to handle this too. 
I'm thinking I will work on deviance next and then ciricle back to `loglike`... I feel like R takes some computational …

ENH: Revise loglike/deviance to correctly handle scale

---

statsmodels/genmod/tests/test_glm_weights.py

So I noticed that on the `statsmodels.genmod.tests.test_glm_weights` there is an `@pytest.mark.xfail` decorator before a class. While I think the point of that is to mark for xfail just that class, it seems to mark xfail that class and all succeeding classes. 
Here, I'm explicitly labeling the classes for xfail. 
@bashtage You are much better than me at this whole pytest thing (and the whole python thing in general!). I think pytest is your area of expertise, so if you have a better way, let me know.

TST: pytest.mark.xfail seems to xfail all succeeding tests in module

---

statsmodels/formula/tests/test_formula.py
statsmodels/genmod/tests/results/results_glm.py
statsmodels/stats/tests/test_contingency_tables.py
statsmodels/tsa/tests/test_stattools.py

I think bumpy's WarningManager has gone the way of the Monty Python parrot. 
This is causing AppVeyor to not run.

MAINT: Replace WarningManager with catch_warnings and other numpy 1.14.0 issues

---

statsmodels/genmod/families/family.py
statsmodels/genmod/generalized_linear_model.py
statsmodels/genmod/tests/test_glm_weights.py

We are currently not weighting `resid_anscombe` in GLM. This will enable that. Adjusted unit test vs stata to match. 
xref #3856 comment about `resid_anscombe`. 
[Gist showing match](https://gist.github.com/thequackdaddy/c03ea9b293760175024267e6e686067c)

BUG/REF: Weight anscombe residuals

---

statsmodels/genmod/families/family.py
statsmodels/genmod/generalized_linear_model.py
statsmodels/genmod/tests/test_gee_glm.py

Here's an attempt to close #4209 
This should make it so resid_dev in GLM and GEE will give the same answer. 
Probably need a unit test or two... any ideas?

BUG: Rework resid_dev for each family

---

statsmodels/nonparametric/bandwidths.py
statsmodels/nonparametric/kde.py
statsmodels/nonparametric/kdetools.py

I read through some files in ``statsmodels/nonparametric`` and found some pep8 violations which I fixed. Very small stufff, mostly spaces. Remoted a few unused imports. Made one change to the code: using ``arr.size`` is faster than ``len(arr)``.
Comments very welcome.

DOC: Fixed some pep8 violations, arr.size instead of len(arr)

---

statsmodels/tsa/kalmanf/kalmanfilter.py

This fixes the FutureWarnings from #4228 related to `issubdtype`.

REF: use full dtype in issubdtype call

---

statsmodels/regression/mixed_linear_model.py
statsmodels/regression/tests/test_lme.py

Attempt to fix #2961.
The results class cached attributes are documented through their docstrings, and in the class docstring.  If we can delete one or the other, it will be easier to maintain.

DOC: MixedLM documentation issue

---

.travis.yml
examples/notebooks/distributed_estimation.ipynb
statsmodels/tsa/vector_ar/util.py

Hello,
I'm noting that travis fails on the docbuild. 
I think running `conda update conda` fixes it. It looks like there are some new dependencies that `conda` that is shipped with miniconda can't seem to handle.

MAINT: Use more recent miniconda for travis, numpy 1.14 has broken genfromtext

---

statsmodels/tsa/vector_ar/data/e6.dat

One of the files had a non-utf8 character that under Python 3.6 was causing a Python error
> UnicodeDecodeError: 'utf-8' codec can't decode byte 0xfc in position 143: invalid start byte
I just replaced the character for its utf8-equivalent.

Fixed non-utf8 character in data.

---

statsmodels/iolib/summary2.py
statsmodels/iolib/tests/test_summary2.py

Keep regressors aligned with coefficients in summary_col by using pandas.unique (retains order) instead of numpy.unique (sorts alphabetically).
Also modify applicable test so that it catches the issue.
See: https://github.com/statsmodels/statsmodels/issues/3767

Fix summary col 3767

---

statsmodels/tsa/arima_model.py

I think the default `maxiter` in `ARIMA` and `ARMA` is 500.
https://github.com/statsmodels/statsmodels/blob/cd48743a8d721dc5e53b3b72db659da6fa779a33/statsmodels/tsa/arima_model.py#L818-L854
https://github.com/statsmodels/statsmodels/blob/cd48743a8d721dc5e53b3b72db659da6fa779a33/statsmodels/tsa/arima_model.py#L1071-L1107

DOC: maxiter in ARIMA is 500

---

statsmodels/tsa/tests/test_arima.py

this should avoid the current test failure in one of the travis versions
closes #4294
I will completely replace the example test case next time we have problems with this test, to see if there is some more serious problem or if it's just a messy example.

TST: test_arima111_predict_exog_2127 skip for scipy < 0.16

---

statsmodels/tsa/statespace/sarimax.py
statsmodels/tsa/statespace/tests/test_sarimax.py

Closes #4289 
Fixes `SARIMAXResults.arparams`, `SARIMAXResults.maparams` when there are nonconsecutive lags.
Also adds properties `SARIMAXResults.seasonalarparams` and `SARIMAXResults.seasonalmaparams` which give the corresponding results for the seasonal parts of the AR and MA polynomials.
Adds a unit test.

BUG: Results arparams, etc. w/ nonconsecutive lags

---

statsmodels/base/model.py
statsmodels/base/tests/test_generic_methods.py
statsmodels/stats/contrast.py
statsmodels/stats/tests/test_anova.py
statsmodels/stats/tests/test_contrast.py

this is related to #4361, and #4323 as a model analogue of tukeyhsd (with general multipletesting p-value correction)
pairwise comparison for the main effect of a categorical exog.
Also, this should be similar to Stata pairwise option, but I haven't compared yet.
This uses now the encoding contrast matrix from design_info. Therefore it should be independent of the contrast/categorical encoding.
I checked Treatment encoding with and without reference in my examples and it looks good.
Only one minimal unit test comparing t_test_pairwise with t_test with explicitly provided constraints.
`t_test_pairwise` is added as a method of LikelihoodModelResults, but actual function is in stats.contrasts.py
todo for now
- check api, maybe privatize some method
- more unit tests, (I have more examples in …

ENH: add t_test_pairwise to LikelihoodModelResults

---

statsmodels/imputation/mice.py
statsmodels/imputation/tests/test_mice.py

fix MICEData if column with only one missing value, adding atleast_1d
closes #4375

BUG: fix MICEData if column with one missing value closes #4375

---

statsmodels/tools/numdiff.py

If the function being differentiated by `sm.tools.numdiff.approx_hess3()` returns a `numpy.float64`, the function works fine, but if it returns, e.g., a `float`, there is a `TypeError: unsupported operand type(s) for -: 'float' and 'tuple'`. This is because there is an extra comma in the lines calculating the entries of the Hessian, resulting in the unintended creation of a tuple. Because of operator overloading of some Numpy types, this is not a problem in many contexts, but if the function being differentiated returns a `float`, this bug rears its head.
I fixed the bug by deleting the comma.
Here is a code snippet to reproduce the bug.
```python
import statsmodels as sm
import statsmodels.tools.numdiff
print('statsmodels version:', sm.version.full_version)
def f(x): …
```

Fixed bug in approx_hess3 related to floats and tuples.

---

statsmodels/nonparametric/smoothers_lowess_old.py
statsmodels/regression/_tools.py
statsmodels/sandbox/nonparametric/smoothers.py
statsmodels/sandbox/panel/mixed.py
statsmodels/sandbox/stats/contrast_tools.py
statsmodels/sandbox/tsa/diffusion.py
statsmodels/tsa/seasonal.py
statsmodels/tsa/varma_process.py
statsmodels/tsa/vector_ar/svar_model.py
statsmodels/tsa/vector_ar/var_model.py

see #3994 numpy changes default rcond in lstsq
we get many warnings in the unit tests with recent numpy
"To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`."
This PR adds `rcond=-1` to maintain the old behavior.
More generally, we might want to switch to a different behavior with rcond proportional to sqrt(nobs)
but this PR is just maintenance.
aside: There is a copy of a lstsq function in statsmodels.tools.linalg based on scipy linalg, which I guess is currently not in use. uses cond instead of rcond. I didn't make any changes there.

MAINT: numpy compat, keep old rcond in lstsq

---

statsmodels/regression/linear_model.py
statsmodels/stats/outliers_influence.py
statsmodels/stats/tests/test_diagnostic.py

closes #3971
pandas index is not sorted if order is true
This just moves the label access to the model row_labels to the beginning of the function before sorting occurs.

BUG: outlier_test fix index with order 

---

statsmodels/discrete/count_model.py
statsmodels/discrete/tests/test_count_model.py
statsmodels/discrete/tests/test_discrete.py
statsmodels/genmod/generalized_linear_model.py
statsmodels/genmod/tests/test_gee_glm.py
statsmodels/genmod/tests/test_glm.py
statsmodels/genmod/tests/test_glm_weights.py
statsmodels/tools/sm_exceptions.py
statsmodels/tsa/vector_ar/tests/JMulTi_results/parse_jmulti_var_output.py
statsmodels/tsa/vector_ar/tests/test_coint.py
statsmodels/tsa/vector_ar/tests/test_var.py
statsmodels/tsa/vector_ar/tests/test_vecm.py

This changes resid_anscombe UserWarning to FutureWarning, and reduces the test noise from warnings in glm
see #4229 for expected warnings, DomainWarnings, SpecificationWarnings, FutureWarnings
#3845 other warnings convergence, runtime
see #4231 for catching a specific warning category
in test_glm: completely silence one test that is expected to have problems
in test_glm_weights:
- change link to logit in binomial test (I think log was used because of an experiment with exposure that is not included)
- cheating in test_compare_optimizers. I didn't try to check the failing cases. I use now the reference params as start_params. Note, start_params = 0.9 * params or 1.1 * params resulted in test failures (params went far away), There are several division by zero and invalid value in log cases. …

TST: remove some warnings in unit tests

---

statsmodels/stats/inter_rater.py
statsmodels/stats/tests/test_inter_rater.py

see #4387 especially https://github.com/statsmodels/statsmodels/issues/4387#issuecomment-375893090
adds a method argument to get randolph's kappa
is backwards compatible
handles degenerate case without special code
unit tests against http://justusrandolph.net/kappa/#dInfo

ENH: inter_rater add randolph's kappa to fleiss_kappa

---

statsmodels/iolib/summary.py
statsmodels/sandbox/regression/gmm.py
statsmodels/sandbox/regression/tests/test_gmm.py
statsmodels/sandbox/regression/tests/test_gmm_poisson.py

closes #4340 
bug fix with a bit of refactoring/enhancements
- fixes the exog_names in GMM, use generic names if xnames from data too short
- also adds a new method `set_param_names` for users to override the default names.  
currently only in GMM class, but we might want to have something like this more generally.
- also summary `summary_params` raises now an exception if params and exog_names have a length mismatch, instead of silently truncating the params tabel
I opened #4426 for more general param_names/xnames/exog_names inconsistencies

BUG/REF: GMM fix exog_names, summary

---

statsmodels/tsa/stattools.py
statsmodels/tsa/tests/test_stattools.py

closes #4237
sets test statistic to -inf instead of 0, which will result in p-value = 0.
loosens the threshold for near collinearity a bit. #4222

BUG: tsa coint, nearly perfect colinearity, return (-inf, 0, ...)

---

statsmodels/genmod/tests/results/results_glm.py
statsmodels/graphics/boxplots.py
statsmodels/imputation/tests/test_ros.py
statsmodels/regression/tests/test_theil.py
statsmodels/tsa/statespace/mlemodel.py

this fixes or silences almost all deprecation warnings
several of the changes will need a follow-up when more recent changes make old code obsolete, or needs a proper solutions
- histogram normed -> density  
weignore deprecation warning histogram `normed`
https://github.com/statsmodels/statsmodels/issues/4228#issuecomment-379075961
We need to switch to `density` keyword in hist when matplotlib minimum is >= 2.1.x (I think)
- dataset genfromtxt and similar: see #4435
- this PR includes genfromtxt usage in test_glm conditional on numpy and python version

MAINT: deprecation warnings

---

statsmodels/discrete/discrete_model.py

The NegBin and GeneralizedPoisson likelihood/score/hessians are big hotspots for profiling.  They are _also_ complicated spots of algebra that are difficult to read/inspect.
This cleans them up a little bit and does a _few_ substitutions to reduce redundant calculations.  There are several more steps worth of algebraic simplification available, but this is a place where its easy to make mistakes, so let's do this in bite-size pieces.

small steps of algebra simplification

---

statsmodels/tsa/statespace/_simulation_smoother.pyx.in
statsmodels/tsa/statespace/tests/test_simulation_smoothing.py

This fixes a bug with simulation smoothing when there is a state intercept. It's basically the same underlying issue as was in #3305, but now in the state intercept case.
This issue and the fix is discussed in https://www.ecb.europa.eu/pub/pdf/scpwps/ecbwp1867.en.pdf

 BUG: Fix simulation smoothing with state intercept

---

statsmodels/tsa/base/tsa_model.py
statsmodels/tsa/tests/test_tsa_indexes.py

As of Pandas 0.18, the default index is `RangeIndex` rather than `Int64Index`. We only directly supported `Int64Index` (along with date indexes) so a warning would be issued by tsa models that the index would be ignored.
This adds direct support for `RangeIndex`es of all types.

ENH: Add support for RangeIndexes

---

statsmodels/genmod/_prediction.py
statsmodels/regression/_prediction.py
statsmodels/regression/tests/test_predict.py

the `index` check is inappropriate for Python lists.
check whether index is callable
fix for regression and GLM
closes #4437

BUG: allow list exog in get_prediction

---

statsmodels/tsa/stattools.py
statsmodels/tsa/tests/test_stattools.py

closes #4490
don't ignore autolag keyword in `coint`
Note, this changes the default autolag to the same as the adfuller default, aic instead of None used in statsmodels 0.8

BUG: coint use autolag in adfuller call

---

statsmodels/tsa/arima_model.py
statsmodels/tsa/tests/test_arima.py

closes #2982
this fixes an exception for insample dynamic predict when no exog is needed
`exog=None` raised exception in np.vstack

BUG: fix ARMA exog dynamic in-sample predict

---

statsmodels/datasets/tests/test_utils.py
statsmodels/datasets/utils.py

closes #3831
rdataset does not write-read roundtrip using cache on python 3.
The change here is to store the cache as strings (encoded in utf-8) instead of bytes in Python 3. 
A new unit test uses cache temporarily, instead of reusing already cached files.

BUG: fix rdataset cache writing on py3

---

statsmodels/tsa/ar_model.py
statsmodels/tsa/tests/test_ar.py

closes #3945
this uses the fix proposed in 3945
`UnboundLocalError: local variable 'mu' referenced before assignment`
unit tests against ARMA(9, 0) at optimization precision

BUG: AR undefined mu if trend='nc'

---

statsmodels/datasets/utils.py

this is just a guess.
travis in master is often hanging now with no response received.
AFAICS, the default timeout for urlopen is None, so urlopen might wait forever if there are problems.
```
>>> repr(urllib.request.socket.getdefaulttimeout())
'None'
```
This PR just add a timeout of 3 seconds.
The usage of rdataset in the unit test is protected by a hasinternet check, so this is not a problem if no internet at all is available.

MAINT: at timeout to urlopen rdatasets

---

statsmodels/sandbox/nonparametric/densityorthopoly.py

Reading all .py file broke on a file with windows encoding  (old sandbox file)
change encoding to utf-8

MAINT: sandbox change file encoding to utf-8

---

statsmodels/tsa/regime_switching/_hamilton_filter.pyx.in
statsmodels/tsa/regime_switching/markov_switching.py
statsmodels/tsa/regime_switching/tests/test_markov_regression.py

This pull request makes some improvements to the Hamilton filter functionality and docs (both the Python and Cython versions).
* Handles the order=0 case.
* Documents the sizes of the arguments correctly.
* Checks that the argument sizes satisfy the documented sizes.

BUG/ENH: Fix Hamilton filter docstrings and handle order=0, closes #4248

---

statsmodels/nonparametric/_kernel_base.py
statsmodels/nonparametric/tests/test_kernel_density.py

closes #3125
if 'bw' argument is None, then _bw_method was not set
unit test that bw=None defaults to "normal_reference" in KDEMultivariateConditional which has same problem as KDEMultivariate

BUG: KDEMultivariate, fix undefined _bw_method 

---

statsmodels/iolib/summary2.py
statsmodels/regression/tests/test_lme.py

closes #3324
This is trying a quickfix for summary2 to use param_names. It's similar to #3324 except for a try except protection.
summary_col doesn't work with MixedLM which uses summary2 for `summary()`
Note: `summary` also only uses model.exog_names, which I don't change here.
Bigger issue (not now) settle the param_names/exog_names pattern, #4426

BUG/ENH: summary2, try param_names before exog_names

---

statsmodels/graphics/gofplots.py
statsmodels/graphics/tests/test_gofplots.py

I added plotkwargs as an input to the top level version of qqplot from statsmodel.api which did not accept additional matplotlib arguments. I also added a test for this and enabled Travis CI on my fork. Seems to build fine.

ENH: Added plotkwargs to top level version of qqplot in statsmodels.graphics.gofplots

---

statsmodels/tsa/arima_model.py
statsmodels/tsa/tests/test_arima.py

closes #3504
This makes now a float64 copy in `_fit_start_params_hr` for inplace modification.
ARMA now uses OLS instead of GLS.
This does not change the dtype of the model.endog attribute, i.e. is still int (int32 in test case).
However, I added unit tests that params and bse are the same with int and float endog (at atol=1e-6 in case that is the optimization tolerance, actual difference is zero, not sure why there is no numerical noise)

BUG: allow ARMA/ARIMA with int endog, fix in _fit_start_params_hr 

---

docs/source/release/version0.9.rst
statsmodels/regression/mixed_linear_model.py
statsmodels/regression/tests/test_lme.py

This fixes a bug that prevented prediction covariances of BLUP's from being extracted from models having variance components.  
I also changed the name index for the variance component BLUP's from being the position to being the actual name (otherwise it is sometimes impossible to know which BLUP corresponds to which actual group in the data).  This could produce backwards incompatibilities so I will add a note to the release notes.  People who were relying on the previous names lining up with the actual group labels may not have been getting what they though they were getting, so I think this is an appropriate change to make despite the compatibility break.

BUG: MixedLM random effects BLUPs with variance components

---

examples/notebooks/statespace_seasonal.ipynb
statsmodels/tsa/statespace/structural.py
statsmodels/tsa/statespace/tests/results/results_structural.py
statsmodels/tsa/statespace/tests/results/test_ucm.R
statsmodels/tsa/statespace/tests/test_structural.py

Previously, we had implemented the main time domain seasonal component, which
is restrictive when the periodicity is very high or the seasonality can be
more parsimoniously represented by trigonometric terms.  Also, we were only
able to use a single seasonal component.  This commit allows for multiple
seasonal components in the frequency domain and for mixing of the two types.
Finally, we added an ipython notebook as an example showcasing the new
functionality.
Also
- Change offset for regression coefficients when cycle is included.
Cycle is two states regardless of if it is stochastic.  Therefore,
the offset should always be 2 instead of possibly 1 for a deterministic
cycle.
Signed-off-by: Jordan Yoder <jordan.yoder@gmail.com>
---- Additional commentary outside of commit message ------- …

ENH: Add frequency domain seasonal components to UnobservedComponents

---

statsmodels/base/model.py
statsmodels/base/tests/test_predict.py
statsmodels/formula/tests/test_formula.py

#3611 partially squashed, rebased, 2 changed and more unit tests
main change is that a pd.Series is interpreted as a row when converting to DataFrame instead of as a column, changed to check Series name to decide row versus column
closes #3611

REF: predict exog and return types, allow custom dict

---

statsmodels/multivariate/tests/test_factor.py
statsmodels/tsa/statespace/tests/test_simulate.py

some final fixes for 0.9rc1
see comments in #3386
- test_simulate still sometimes segfaults in a non-replicable way on Windows
I skip two of the tests that AFAIR showed up sometimes on appveyor
- pandas compat in test, import path for `formats` changed across pandas version
AFAICS it only affects the unit test, not the method the Factor class

TST pandas compat, skip test_simulate on WIN

---

statsmodels/tsa/statespace/tests/test_simulate.py

this time I'm skipping all tests in statespace test_simulate on Windows to avoid occasional segfault
https://github.com/statsmodels/statsmodels/pull/3791#issuecomment-385275048

TST: skip all statespace test_simulate on Windows

---

setup.py

increase version number to 0.10 dev
no changes to setup.py minimum version, or CI test matrix yet

MAINT: increase version number to 0.10 dev

---

statsmodels/iolib/tests/test_summary2.py
statsmodels/regression/mixed_linear_model.py
statsmodels/regression/tests/test_lme.py

The function `MixedLM.summary()` featured two arguments `xname_fe` and `xname_re` (respectively to change the display names of fixed effects and random effects), but the function did not use those values. As a consequence, those keywords did not have any impact.
This pull request implements those keywords. It tests that the length of the lists specified in `xname_fe` and `xname_re` match the number of fixed/random parameters, and insert them as index in the DataFrame used to summarize the results.

Implement "xname_fe" and "xname_re" arguments in MixedLM.summary()

---

statsmodels/tsa/statespace/_simulation_smoother.pyx.in
statsmodels/tsa/statespace/tests/test_simulate.py

This fixes a segmentation fault (illegal memory access) when simulating time series from a time-invariant state space model, where the number of simulations exceeds the number of observations in the base model.
(It is possible that #3386 is closed by this PR, but since I can't replicate those test failures *per se*, I guess we'll have to wait and see).

BUG: State space: Eliminate sometimes invalid copy operation in simulation.

---

statsmodels/genmod/generalized_linear_model.py
statsmodels/genmod/tests/test_glm.py

closes #4597
this fixes GLM.null and consequently null_deviance, llnull if exposure is used independent of family, and if offset is used in the binomial count case.
There are some unit tests for null_deviance, More unit test in my penalized #4576 where I initially ran into this bug.
more general: 
see #4599
fixes recreating models for Binomial count, by addin `n_trials` to `__init__` kwargs and init keys
This will fix most likely other bugs, or adds support for cases that are not supported yet, 
e.g. fit_constrained and fit_regularized for Binomial counts #4600
but I didn't check and test those cases yet.
If current unit tests work with these changes, then I might add some more unit tests.

BUG/REF: fix GLM `null`, init keywords 

---

statsmodels/tsa/vector_ar/var_model.py

closes #4584
In python 2.7 with numpy 1.14.2 an indexing error shows up,
most likely because of float, in Python 2.7 Python's round returns a float, in python 3 an int.
(tested on travis in #4576 which has the failing numpy python combination)
this just adds int to python round and is not necessary on python 3, i.e. could be removed again when we drop python 2 support

MAINT: numpy python 2.7 compat in VARProcess irf_errband_mc

---

statsmodels/genmod/generalized_linear_model.py

See #4622 and https://github.com/statsmodels/statsmodels/issues/1720#issuecomment-335657719
This removes `pinv` from the initialize step, which saves time on large(ish) exogs.

PERF: GLM - don't use pinv in initialize

---

statsmodels/base/elastic_net.py
statsmodels/genmod/tests/test_glm.py

closes #4605 
when recreating the model we need to work around that log exposure is currently attached
also does a bit of refactoring
- use `_get_init_kwds`
- avoid offset attribute lookup inside loop

BUG/REF: fix exposure transformation in elasticnet

---

statsmodels/genmod/generalized_linear_model.py

This addresses part of #4625 that simplifies the use of IRLS in coming up with `start_params` for `fit_gradient` for GLM.

Simplify start_params generation for gradient optimization in GLM #4625

---

statsmodels/tsa/arima_process.py

Fixed typo for variable name in the documentation example for ArimaProcess class.

DOC:ArmaProcess class documentation typo fix

---

statsmodels/tsa/kalmanf/kalman_loglike.pyx
statsmodels/tsa/kalmanf/kalmanfilter.py
statsmodels/tsa/statespace/_tools.pyx.in

@ChadFulton It took me a while to figure out what parts of kalman_loglike were doing, so I went ahead and wrote up comments to clarify it for the next reader.  In many cases the existing comments appear to be doing something similar, but I find this much clearer.
There is some remaining commented-out code that I'd like to document/clean up in a similar way, some of which I can do after looking up blas functions; other parts would require your input.
While I was at it I deleted a commented-out implementation of solve_discrete_lyapunov, since it has been replaced by a version immediately below it.

Document and cleanup bits of cython code

---

statsmodels/datasets/co2/data.py
statsmodels/genmod/tests/test_glm.py
statsmodels/tsa/statespace/tests/test_mlemodel.py
statsmodels/tsa/tests/test_tsa_indexes.py

https://github.com/pandas-dev/pandas/commit/537c06d150d0942454494b08773567eb245dd200
removed the to_datetime method from DateTimeIndex.  Use pd.to_datetime
instead.
This leads to
```
E   AttributeError: 'DatetimeIndex' object has no attribute 'to_datetime'
```
on test collection.

BF: DataTimeIndex.to_datetime removed in pandas

---

.travis.yml
INSTALL.txt
appveyor.yml
docs/source/install.rst
setup.py

This  PR updates the minimum versions (in `setup.py`) to:
```python
min_versions = {
'numpy' : '1.12',   # released January 2017
'scipy' : '0.19',   # released March 2017
'pandas' : '0.20',  # released May 2017
'patsy' : '0.4.0',  # released July 2015
}
```
and changes the Travis build strategy to roughly incorporate:
- Baseline (on Python 2.7, 3.3, and 3.5, with the package versions above)
- Partially updated (on Python 2.7 and Python 3.5 with incrementally updated packages)
- Cutting edge (Python 3.6 + latest packages)
along with one documentation build and one build with no Matplotlib at all.
```yml
- python: 2.7
env:
- PYTHON=3.6
- COVERAGE=true
- python: 2.7
env:
- PYTHON=2.7
- NUMPY=1.13
- MATPLOTLIB=2.1
- COVERAGE=true
- python: 2.7
env:
- PYTHON=3.5
- NUMPY=1.13
- SCIPY=1.0
- …
```

DISCUSS/BLD: Update minimum versions.

---

.travis.yml

Temporary fix since pandas=0.23 is incompatible with pandas-datareader=0.6. We can remove this line once pandas-datareader is next released (0.6.1 or 0.7.0).

BLD: Use older version of Pandas for docbuild

---

statsmodels/base/_penalized.py
statsmodels/base/_penalties.py
statsmodels/base/_screening.py
statsmodels/base/tests/test_screening.py
statsmodels/discrete/discrete_model.py

selecting variables for k_vars >> nobs
This is a generic function that takes a model or model class as argument to find and estimate the final model with selected exog.
requires a model with PenalizedMixing merged in #4576
Currently checked for Poisson and GLM-Poisson. 
example (used for test case)
https://gist.github.com/josef-pkt/a90eb8be076276874a0d026ad6c7efa0
and GLM version
https://gist.github.com/josef-pkt/df6ef0dcf42d99dee4afeb968f4f4c94
unit tests will most likely be: "it works" and not verified against other packages
TODOs and limitations in class docstring.
API not clear yet
I'm not sure whether I want to merge a basic version or add more options.

ENH: add ultra-high screening with SCAD

---

statsmodels/regression/mixed_linear_model.py
statsmodels/regression/tests/test_lme.py

@jbrockmendel if you have other suggestions for naming, documentation, and testing of the two SMW routines let me know, we can add them here.  So far, I don't see any indication that there is anything materially wrong with this code.

TEST: Docstring edits and variable name changes for clarity

---

statsmodels/regression/recursive_ls.py
statsmodels/regression/tests/test_recursive_ls.py

Uses the new exact diffuse filtering for `RecursiveLS`. The main benefit is much smaller tolerances in the unit tests.
Also switches to using univariate filtering method by default. This is not a big deal here since of course `endog` is actually univariate here, but it can help with numerical issues since there is no error term in the transition equation. Furthermore, it is necessary to support #4133, since the linear restrictions cause non-positive definite forecast error covariance matices.

ENH: Exact diffuse filtering for RecursiveLS

---

statsmodels/tsa/vector_ar/hypothesis_test_results.py
statsmodels/tsa/vector_ar/var_model.py

I noticed that some tests are failing.
Here's an attempt to fix a couple issues.
I changed a comparison of floats to `np.allclose` because on a Windows setup I have with the pypi numpy/scipy, it fails. I saw this under [Matthew Brett's appveyor](https://ci.appveyor.com/project/matthew-brett/statsmodels-wheels/build/job/4pnmaa46p34sb1ju) (see `test_granger_causality` and `test_inst_causality`
Also in `var_model` during `test_lag_order_selection` under certain scenarios the parameters coming out of `lstsq` are huge. I think there is a near-zero problem.

TST: allclose instead of exact match for floats and use machine precision

---

statsmodels/tsa/vector_ar/irf.py
statsmodels/tsa/vector_ar/var_model.py

The first half of `irf_errband_mc` is copy/paste identical to `irf_resim`, so let's go ahead and use that instead.
Also make a helper method for a commonly-used expression in irf.
This does _not_:
- clean up any formatting
- fix the `AttributeError` that `irf_errband_mc` or `irf_resim` would raise if it were ever called.
- fix the `TypeError` that `irf_errband_mc` would raise if it that `AttributeError` were fixed.

De-duplicate a bunch of identical code

---

statsmodels/tsa/statespace/sarimax.py

Previously, if non-stationary (or non-invertible) starting parameters were found (e.g. computed via least squares on lags), the `start_params` computation raised an exception. This seems unnecessary, so this PR replaces it with a warning, and sets the starting parameters for the non-stationary or non-invertible components to zero.
Example:
```python
mod = sm.tsa.SARIMAX(dta['cpi'], order=(1, 0, 0))
res = mod.fit()
print(res.params[0])
print(res.summary())
```
yields a:
```
/Users/fulton/projects/statsmodels/statsmodels/tsa/statespace/sarimax.py:914:
UserWarning: Non-stationary starting autoregressive parameters found. Using zeros as starting parameters.
warn('Non-stationary starting autoregressive parameters'
```
and returns output suggesting as close to a non-stationary model as the …

REF: SARIMAX: only warn for non stationary starting params

---

examples/notebooks/recursive_ls.ipynb
statsmodels/regression/recursive_ls.py
statsmodels/regression/tests/results/test_rls.do
statsmodels/regression/tests/test_recursive_ls.py
statsmodels/tsa/statespace/_filters/_univariate.pyx.in
statsmodels/tsa/statespace/_filters/_univariate_diffuse.pyx.in
statsmodels/tsa/statespace/kalman_filter.py

Allow linear restrictions on the (recursively estimated) least squares parameter estimates.
Needs unit tests.

ENH: Add linear restrictions to RecursiveLS

---

statsmodels/tsa/statespace/_filters/_univariate_diffuse.pyx.in

Bug causes the exact diffuse filter to never transition to the usual Kalman filter.

BUG: state space: exact diffuse filtering in complex data type case

---

docs/source/example_formulas.rst

Because of the function definition, the line where the custom function
was actually applied was gobbled up and did not show up in the
documentation. Adding a newline solved the problem.

DOC: Make custom function take effect

---

statsmodels/regression/recursive_ls.py
statsmodels/tsa/statespace/_filters/_conventional.pxd
statsmodels/tsa/statespace/_filters/_conventional.pyx.in
statsmodels/tsa/statespace/_filters/_univariate.pxd
statsmodels/tsa/statespace/_filters/_univariate.pyx.in
statsmodels/tsa/statespace/_filters/_univariate_diffuse.pyx.in
statsmodels/tsa/statespace/_kalman_filter.pxd
statsmodels/tsa/statespace/_kalman_filter.pyx.in
statsmodels/tsa/statespace/kalman_filter.py
statsmodels/tsa/statespace/kalman_smoother.py
statsmodels/tsa/statespace/mlemodel.py
statsmodels/tsa/statespace/sarimax.py
statsmodels/tsa/statespace/tests/test_concentrated.py
statsmodels/tsa/statespace/tests/test_dynamic_factor.py
statsmodels/tsa/statespace/tests/test_options.py
statsmodels/tsa/statespace/tests/test_sarimax.py

Adds the ability to perform filtering where the scale is concentrated out of the log-likelihood function, but is computed along with the filtering recursions.
Also adds an argument `concentrate_scale` to SARIMAX to allow estimating the model with the scale concentrated out. From very quick tests, it appears that we can get a higher optimized log-likelihood if there are a lot of parameters.
The filter output between the concentrated and non-concentrated models is the same, since they just need to be rescaled (and I do the relevant rescaling when constructing the filter results).
Not really an "essential" feature, but may be useful.

ENH: State space: allow concentrating scale out of log-likelihood

---

statsmodels/regression/mixed_linear_model.py
statsmodels/regression/tests/test_lme.py

This should fix #4413.  The bug was not detected by the tests because the group labels and the integer indices of the groups were the same.  So I changed the group labels from  ### to strings of the form g###.  The old code would have failed under the new tests.
Thanks @danlewis85

BUG Fix random effects covariance getter for MixedLM

---

statsmodels/imputation/bayes_mi.py
statsmodels/imputation/tests/test_bayes_mi.py

1. Allow MI to work with formulas
2. If BayesMI is given a DataFrame, it saves the column names and returns the imputed results as a DataFrame (previously it always returned an ndarray).
3. Docstring fixes and improvements

ENH: Add formula support to MI multiple imputation

---

statsmodels/tsa/vector_ar/vecm.py

Also can we _please_ get rid of the new `y_all` attribute before the upcoming release?  There's too many non-standard naming schemes as it is, and experience suggests they're impossible to get rid of.

Fix imports math.foo -->np.foo in vecm

---

.gitignore

Closes #4765 
Adds the tempita compiled intermediate files `_univariate_diffuse.pyx` under `_filters` and `_smoothers` to .gitignore.

MAINT: gitignore univariate_diffuse pyx files.

---

statsmodels/tsa/statespace/_filters/_inversions.pyx.in

Computing the standardized forecast error within the Cython iterations would silently fail when using the Cholesky methods.
This didn't actually have much of an effect since the multivariate state space models use the LU factorization by default (so that the Cholesky part was done correctly in the Python construction of the results object), and since the univariate method isn't affected, but it's still good to have it fixed.

BUG: State space: standardized forecast error when using Cholesky methods with partial missing data

---

statsmodels/tsa/vector_ar/tests/test_var.py

There are a whole mess of tests that are commented-out or mangled instead of being xfailed.  This makes it unnecessarily difficult to find tests that need attention.
(And uh, BTW, FEVD tests are 100% smoke tests)

xfail test instead of commenting it out

---

statsmodels/tsa/vector_ar/var_model.py

Closes #4784
See also https://github.com/statsmodels/statsmodels/commit/6c1f892c6032ea0e3422534e4bc83d6a7735af21#diff-e2d6024b9d0ed6c0410bf2fffc1f1254R342

BUG: Get prediction index in VAR predict.

---

statsmodels/tsa/statespace/sarimax.py

BUG: k_params if seasonal MA

---

statsmodels/discrete/discrete_model.py

I was confused about why a script was taking >20% of total running
time inside DiscreteModel.initialize. It turns out that computing the
rank of exog can be pretty slow! It does seem vary a lot depending on
BLAS and threading settings, e.g. I get wildly different results for
OpenBLAS vs. MKL and OMP_NUM_THREADS=1 versus not. So part of the
issue is probably hitting pathological edge cases in BLAS libraries.
But there's definitely no reason to compute the rank *twice* in the
same function.

Only compute matrix_rank(exog) once in DiscreteModel.initialize

---

statsmodels/tsa/statespace/_simulation_smoother.pyx.in
statsmodels/tsa/statespace/simulation_smoother.py
statsmodels/tsa/statespace/tests/test_collapsed.py

Closes #4800.
The problem here was that FILTER_COLLAPSED makes the effective number of endogenous variables smaller than the actual size of the observation array, but the simulation smoother wasn't taking this into account. This PR:
- Makes the simulation smoother behave appropriately with FILTER_COLLAPSED
- Adds a test for the smoothed measurement disturbance and the simulation smoothed measurement disturbance.

BUG: simulation smoothed measurement disturbance with FILTER_COLLAPSED

---

statsmodels/tsa/statespace/sarimax.py

This fixes some issues that can arise for close to non-stationary time series. Previously these models weren't even considered, but with e.g. #4739 these models may crop up more often. This:
- Fixes a problem with the `self.polynomial_*` variables got filled with exactly zeros (for example when non-stationary starting parameters were replaced with zeros)
- Bounds the initial variance estimate away from zero (again, can happen when non-stationary starting parameters were replaced with zeros)

ENH/BUG: Improve SARIMAX for time series close to non-stationary

---

statsmodels/base/data.py

Fixes this: https://github.com/statsmodels/statsmodels/issues/4118

CLEAN: Removed unnecessary and non-informative print

---

statsmodels/regression/recursive_ls.py
statsmodels/regression/tests/test_recursive_ls.py
statsmodels/tsa/statespace/mlemodel.py

See the title. The main impetus for the PR was a bug that raised an exception if multiple constraints were used. This also improves the display of endog names in the case of constraints.

BUG/ENH: Recursive LS: fix bug w/ multiple constraints

---

statsmodels/regression/mixed_linear_model.py
statsmodels/regression/tests/test_lme.py

We previously tried the same optimizer 5 times (picking up each time where the previous attempt stopped).  But this rarely if ever seems to help with problems where convergence is an issue.  Usually it just wastes a lot of time waiting for the same failure to happen 5 times.
This new approach has a series of optimizers that are cycled through.  The default is ['bfgs', 'lbfgs'].  lbfgs works sometimes when bfgs does not.

ENH: Allow several optimizers to be tried in sequence for MixedLM

---

docs/source/contingency_tables.rst

The formulas were not displaying correctly, because of missing
indentation. Moreover, the mosaic code is adapted a little so it could
be actually used to obtain a figure.

DOC: Fix indentation of math formulas

---

statsmodels/regression/tests/test_lme.py

Skip-if condition was not correct, resulting in test being skipped
on modern SciPy

TST: Restore incorrectly disabled test

---

.travis.yml
lint.sh

Ensure linting only runs when asked for (shaves ~1 minute from most builds)
Move coverage to Python 3.7 to reduce risks of timing out

BLD: Fix linting and move coverage

---

examples/notebooks/tsa_arma_0.ipynb

Fix typo about null of adfuller
closes #4764
[skip ci]

DOC: Fix small typo in unit root testing example

---

lint.sh
statsmodels/tools/decorators.py
statsmodels/tools/tests/test_decorators.py

Add both the decorators module and the test module to the lint-fully list.

[TST/CLN] Turn decorators __main__ section into tests

---

statsmodels/stats/sandwich_covariance.py
statsmodels/tools/grouputils.py
statsmodels/tools/tests/test_transform_model.py
statsmodels/tools/transform_model.py

Add a few files to the strict-linting list

[CLN/TST] Follow instructions to remove function

---

statsmodels/tsa/statespace/kalman_filter.py
statsmodels/tsa/statespace/tests/test_simulate.py

With the introduction of the new `Initialization` objects for state space initialization, the `simulate` method was never updated to initialize simulations appropriately.
(No backport required, since the new `Initialization` objects were introduced after v0.9 and haven't yet been in a release).

BUG: Initialization when simulating

---

statsmodels/regression/recursive_ls.py
statsmodels/tsa/statespace/mlemodel.py

Another issue with `RecursiveLS` in the constraints case. One or more "faux" `endog` are added to enforce the constraints, and these should not be returned in the results object, for `resid`, `fittedvalues`, or filter results.

BUG: remove faux endog from results if constraints

---

lint.sh
statsmodels/iolib/smpickle.py
statsmodels/iolib/tests/test_pickle.py

asserts `assert_equal(a,b)` twice, where the second assertion should be `assert_equal(a, c)`

TST: Fix incorrect assertion

---

statsmodels/genmod/generalized_estimating_equations.py

There was never a need to limit QIC to independence correlation structures.  That was my misreading of the literature.

ENH remove unneeded restriction on QIC (GEE)

---

statsmodels/tsa/statespace/kalman_filter.py

Closes #3610
Corrects documentation to note that k_posdef is the dimension of the state innovation.

BUG/DOC: Description of k_posdef

---

statsmodels/discrete/discrete_model.py

docstring says to look at summary.Summary, should say to look at summary2.Summary
small cleanups in the vicinity

MAINT: fix incorrect docstring summary-->summary2

---

statsmodels/stats/_adnorm.py
statsmodels/stats/proportion.py

hasattr '__call__' is not a reliable method to detect callable code

BUG: Correct check for callable

---

statsmodels/graphics/tests/test_mosaicplot.py
statsmodels/imputation/tests/test_mice.py
statsmodels/iolib/tests/test_foreign.py
statsmodels/sandbox/tests/test_predict_functional.py
statsmodels/stats/tests/test_power.py

`np.testing.dec` is imported in 5 places, never used, and requires `nose`, which we're trying to move away from.  This just deletes those imports.
Broken off from #4875

[MAINT/TST] remove np.testing.dec unused imports (nose dependency)

---

statsmodels/iolib/summary2.py
statsmodels/iolib/tests/test_summary2.py
statsmodels/regression/linear_model.py

Add "(uncentered)" after rsquared label in .summary, .summary2 when appropriate
Related to https://github.com/statsmodels/statsmodels/issues/5078 
I didn't find any Unit Test related to the formatting/labeling of the .summary{2} functions.  
The following script
```
import statsmodels.formula.api as smf
dat = sm.datasets.get_rdataset("Guerry", "HistData").data
results = smf.ols('Lottery ~ Literacy + Pop1831', data=dat).fit()
print('#################################################')
print('#########   CENTERED      #######################')
print('#################################################')
print('')
print(results.summary())
print(results.summary2())
print('#################################################')
print('#########   UNCENTERED …
```

Add "(uncentered)" after rsquared label in .summary, .summary2 when appropriate

---

.travis.yml
appveyor.yml

Show CPU type in CI to help understand random failures

BLD: Add line displaying CPU info to CI

---

statsmodels/imputation/bayes_mi.py
statsmodels/imputation/tests/test_bayes_mi.py

This PR allows optional storage of results generated during multiple imputation by passing each results instance through a callback function.  It needs to be optional and customizable since results contains a reference to the data, and there may not be room to store all imputed data in memory at once.
This also changes the default model_args_fn behavior since the existing approach did not work with models where the data parameter does not appear in the first position of the model initializer.  This is a new class from <6 months ago so minor compatibility break should be acceptable.

Allow results to be stored for multiple imputation

---

docs/themes/statsmodels/sidelinks.html

When using chrome, you get a warning that the docs aren't secure because every link needs to be to a secure resource. This fixes that. 
Before:
After:

MAINT: Chrome doesn't like having a secure link with an unsecure image

---

lint.sh
statsmodels/graphics/tsaplots.py

Set a sensible default value for acf and pacf plot lags when not provided
using a method common to R based on the log of the number of observations.
closes #4663

BUG: Set default lags for acf/pacf plots

---

statsmodels/base/tests/test_generic_methods.py

Test failing on macOS.  Discussion at gh-5158.

BF: drop tolerance of a zero_constrained test

---

.travis.yml
appveyor.yml
lint.sh
statsmodels/graphics/functional.py
statsmodels/graphics/tests/test_functional.py
statsmodels/tsa/stattools.py
statsmodels/tsa/tests/test_stattools.py

Use random order to avoid intertest dependency
Tests show there are some problems with order affecting test success.

REF/TST: add seed to hdrboxplot, Use random order in pytest

---

setup.cfg
statsmodels/base/tests/test_shrink_pickle.py
statsmodels/stats/mediation.py
statsmodels/tsa/base/tests/test_tsa_indexes.py
statsmodels/tsa/tests/test_ar.py
statsmodels/tsa/tests/test_arima.py
statsmodels/tsa/vector_ar/tests/test_var.py

Use isinstance instead of comparing types

CLN: Enforce E721, use isinstance

---

statsmodels/base/model.py

If we called `score`, it would be calling approx_fprime(params), which is the wrong signature for approx_fprime

BUG: incorrect self.score in GenericLikelihoodModel; closes #4453

---

statsmodels/conftest.py
statsmodels/discrete/tests/test_count_model.py
statsmodels/discrete/tests/test_discrete.py
statsmodels/tsa/tests/test_holtwinters.py

Basin hopping uses the global RandomState by default.  Add a fixture
to set the global state to a fixed and then restore it to its original
value after the test has completed.
Fixes random failures in TestZeroInflatedGeneralizedPoisson.test_minimize
xref #4230

TST: Set seed when using basin hopping

---

statsmodels/tsa/statespace/tests/test_sarimax.py

Atol isn't meaningful when scale differs substantially.  Use ratio
to avoid issue
xref #5197

TST: Alter test condition due to parameter scale

---

statsmodels/sandbox/distributions/multivariate.py
statsmodels/sandbox/distributions/tests/test_multivariate.py

Tighten integration tol to avoid spurious fail on Win32
Clean up related functions
xref #5197 
See https://ci.appveyor.com/project/bashtage/statsmodels/build/1.0.1019/job/gbmi5g4cwbfbqclp

TST/CLN: Tighten tol to reduce spurious test failure

---

lint.sh

Travis only clones a single branch by default. Manually clone master

BLD: Ensure master is available when linting

---

statsmodels/stats/contingency_tables.py

Add an alternative, more proper name for the pooled risk ratio in a collection of stratified contingency tables.  The original name can remain for compatability.

CLN: Provide better name for pooled risk ratio

---

statsmodels/tsa/statespace/mlemodel.py

Since `filter_results` is deleted during `save`, the check for `self.filter_results.filter_concentrated` would fail if `summary` was called.

BUG: Allow `summary` even if filter_results=None (e.g. after `save`, `load`)

---

statsmodels/tsa/base/tests/test_tsa_indexes.py
statsmodels/tsa/base/tsa_model.py

The bug causes problems with `predict`. For example:
```python
import pandas as pd
endog = pd.Series([1, 2, 3, 4], index=['a', 'b', 'c', 'd'])
mod = sm.tsa.SARIMAX(endog)
res = mod.filter([0., 1])
res.predict(end='c')
```
would yield a:
```
KeyError: 'The `end` argument could not be matched to a
location related to the index of the data.'
```

BUG/TST: TSA models: _get_index_label_loc failed when using row labels.

---

statsmodels/tsa/statespace/simulation_smoother.py
statsmodels/tsa/statespace/tests/test_simulate.py

`SimulationSmoother` objects store a Cython  `_{{prefix}}SimulationSmoother` object that is reused each time `simulate` is called.
Unfortunately, `simulate` wasn't properly updating the Cython objects' `state_intercept` in the case of multiple simulate calls, so for example the following:
```python
mod = sm.tsa.SARIMAX([1], order=(0, 0, 0), trend='c')
print(mod.simulate([1, 0], 5))
print(mod.simulate([10, 0], 5))
```
was giving:
```
[1. 1. 1. 1. 1.]
[10. 1. 1. 1. 1.]
```
instead of
```
[1. 1. 1. 1. 1.]
[10. 10. 10. 10. 10.]
```
This PR adds a unit test and corrects the issue.

BUG: Sequential simulation in models with state_intercept

---

statsmodels/genmod/generalized_estimating_equations.py
statsmodels/genmod/generalized_linear_model.py

Scale parameter for negative binomial in GLM fitting is fixed at 1.

DOC: Clarify/fix docs on GLM scale estimation for negative binomial

---

statsmodels/imputation/mice.py
statsmodels/imputation/tests/test_mice.py

Previous code only imputed value as the distance from the mean for the closest observed value, and not actually the observed value when MICEData is initialized.
closes #5254

BUG: MICEData sets initial imputation incorrectly

---

statsmodels/stats/stattools.py

Indentation error caused another bullet point in the return, when only dw statistic is returned.

DOC: minor fix on documentation on Durbin Watson test

---

statsmodels/tsa/stattools.py
statsmodels/tsa/tests/test_stattools.py

This fixes two bugs in `tsa.stattools.innovation_filter` and adds a more comprehensive unit test versus Kalman filter output.
@bashtage would be happy for your thoughts.

BUG/TST: Fix innovations_filter, add test vs Kalman filter

---

statsmodels/stats/_lilliefors.py
statsmodels/stats/anova.py

CLN: Fix F901 and E306 mixups

---

statsmodels/miscmodels/nonlinls.py
statsmodels/stats/power.py

In one case just reader-confusion caused by obscure namespace behavior

[BUG/MAINT] Fix NameErrors caused by missing kwargs

---

.travis.yml
lint.sh
setup.cfg
statsmodels/base/data.py
statsmodels/sandbox/distributions/tests/test_multivariate.py
statsmodels/stats/_lilliefors.py
statsmodels/stats/tests/test_corrpsd.py
tools/ci/travis_conda.sh
tools/ci/travis_pip.sh

Closes #5329
I also added a `-nv` option on the `wget miniconda.sh` because it shrinks the log file a bunch, and that should make it so that the docbuild will take under 10,000 lines, so you can see the entire log on travis without going to the raw log.

MAINT: eliminate some pytest warnings

---

statsmodels/genmod/cov_struct.py
statsmodels/genmod/generalized_estimating_equations.py
statsmodels/genmod/tests/test_gee.py

Better formula support for `dep_data`.
This is mainly to make it easier to use `cov_struct.Nested`, but could help with other cov_structs as well.

ENH: Allow dep_data to be specified using formula or names

---

statsmodels/genmod/cov_struct.py

Eliminates two warnings in tests.  Also a bit of docstring cleanup.

ENH/BUG Modify GEE indexing to remove numpy warnings

---

statsmodels/tsa/statespace/_simulation_smoother.pyx.in
statsmodels/tsa/statespace/tests/test_simulation_smoothing.py

The "faux" Kalman filter used in simulation smoothing wasn't being set correctly in the exact diffuse initialization case - the `initial_diffuse_state_cov` matrix wasn't being copied as it should have been.
Adds a test, fixes the problem.

BUG: Initialization of simulation smoother with exact diffuse initialization

---

statsmodels/stats/stattools.py
statsmodels/stats/tests/test_statstools.py

Fix medcouple behaviour when there is an even number of ties
closes #5395

BUG: Fix medcouple with ties

---

tools/dataset_rst.py
tools/examples_rst.py
tools/fold_toc.py
tools/nbgenerate.py

The scripts require python3 so the interpreter should use that.
python does not point to python3 on most distributions.

Set python3 as interpreter for doc tools

---

statsmodels/discrete/count_model.py
statsmodels/discrete/discrete_model.py
statsmodels/discrete/tests/test_count_model.py
statsmodels/discrete/tests/test_discrete.py

Check for a valid "method" argument before doing anything else, avoiding potentially-expensive calls.
Flesh out a more helpful error message.

REF: raise early on invalid method

---

statsmodels/tsa/vector_ar/var_model.py

Could easily be rolled in to #5220.

DEPR: warn that VARResults.cov_params will become method

---

.travis.yml
tools/ci/travis_conda.sh
tools/ci/travis_pip.sh

Here's an attempt to get travis to run on Mac. 2 more scenarios, so even slower than before. 
There are 2 runs. The first will use pyenv to download/install python 3.6.6 and I basically just use our pip install with a few modifications. 
The second run uses python 3.7 and uses pretty much our conda install. 
xref #2069 
xref #5154

TST: Add mac testing

---

examples/notebooks/regression_diagnostics.ipynb
examples/python/regression_diagnostics.py
statsmodels/base/data.py
statsmodels/base/model.py
statsmodels/discrete/discrete_model.py
statsmodels/duration/hazard_regression.py
statsmodels/genmod/generalized_linear_model.py
statsmodels/regression/linear_model.py
statsmodels/regression/mixed_linear_model.py
statsmodels/regression/quantile_regression.py
statsmodels/regression/tests/test_regression.py
statsmodels/robust/robust_linear_model.py
statsmodels/sandbox/regression/gmm.py
statsmodels/sandbox/stats/diagnostic.py
statsmodels/sandbox/sysreg.py
statsmodels/stats/_lilliefors.py
statsmodels/stats/api.py
statsmodels/stats/contrast.py
statsmodels/stats/diagnostic.py
statsmodels/tools/catadd.py
statsmodels/tools/tools.py
statsmodels/tsa/vector_ar/svar_model.py
statsmodels/tsa/vector_ar/util.py

Ref #5092.
Also usages of `np_matrix_rank`, which is no longer necessary.

DEPR: Remove items deprecated in previous versions

---

statsmodels/stats/proportion.py

Simple fix to the documentation to render the correct variable name.
Not a big issue, more quality of life for documentation users.

Misspelling in the documentation proportions_ztest

---

docs/source/gettingstarted.rst

Fixes #5458 . Updates the broken link to the new link.

Fixed broken link for Guerry Dataset

---

statsmodels/genmod/generalized_estimating_equations.py
statsmodels/genmod/tests/test_gee.py

Allow the submodel to be provided as a fitted GEEResults object, instead of via a system of linear constraints.

ENH Score test enhancements for GEE

---

statsmodels/tsa/vector_ar/tests/test_var.py
statsmodels/tsa/vector_ar/var_model.py

VAR ACF misses a transpose and produces incorrect values when number
of values if larger than model order

BUG: Correct error in VAR ACF

---

statsmodels/genmod/families/family.py
statsmodels/genmod/generalized_linear_model.py
statsmodels/genmod/tests/test_glm.py

The quasi-likelihood allows fit_regularized to be used with Tweedie family GLM's.
Also bypasses coordinate-descent when calling fit_regularized on a GLM with L1_wt=0.  This is ridge regression and can be fit more efficiently and accurately using gradients optimization.
#3670

ENH: Tweedie log-likelihood (+ridge regression by gradient for all GLM)

---

statsmodels/genmod/families/family.py
statsmodels/genmod/tests/test_glm.py

@thequackdaddy , @ludviclaberge
The EQL formula from the SAS docs seems to have multiple issues (not just the 1-p factor in the denominator).  I believe that the correct formula is here:
https://www.jstor.org/stable/2336136?seq=4#metadata_info_tab_contents
This PR fixes these errors.  The results have changed, so what we were returning before was (presumably) wrong.

BUG: Tweedie EQL quasi-likelihood

---

lint.sh
statsmodels/multivariate/pca.py

Couple of typos in a docstring and in a warning.  After that, the file is only a few long-lines away from being fully-lintable, so went for it.

MAINT: fix typos in pca, wrap long lines

---

.travis.yml
docs/source/contrasts.rst
docs/source/datasets/index.rst
docs/source/vector_ar.rst
docs/sphinxext/github.py
examples/notebooks/discrete_choice_example.ipynb
examples/notebooks/glm.ipynb
examples/notebooks/interactions_anova.ipynb
examples/notebooks/ols.ipynb
examples/notebooks/plots_boxplots.ipynb
examples/notebooks/predict.ipynb
examples/notebooks/quantile_regression.ipynb
examples/notebooks/regression_diagnostics.ipynb
examples/notebooks/regression_plots.ipynb
examples/notebooks/robust_models_0.ipynb
examples/notebooks/robust_models_1.ipynb
examples/notebooks/tsa_arma_0.ipynb
examples/notebooks/tsa_arma_1.ipynb
examples/notebooks/tsa_filters.ipynb
examples/notebooks/wls.ipynb
statsmodels/regression/mixed_linear_model.py
statsmodels/tools/linalg.py
statsmodels/tsa/innovations/tests/test_arma_innovations.py
tools/ci/docbuild_install.sh
tools/ci/travis_pip.sh

I think we can revert #5306 now. However, the magic in the jupyter notebooks need to be moved to a separate cell because that now counts against `from __future__` being at the "top" of a file.

DOC: Move magic

---

statsmodels/genmod/families/family.py

A simple documentation update, adding additional information about the valid formats for specifying endogenous values for the binomial GLM. 
Thanks to @josef-pkt for guidance on the three ways of passing in endogenous variables. 
Closes #5519.

DOC: Describe binomial endog formats

---

setup.cfg
statsmodels/discrete/tests/test_discrete.py
statsmodels/gam/generalized_additive_model.py
statsmodels/nonparametric/tests/test_lowess.py
statsmodels/sandbox/panel/correlation_structures.py
statsmodels/sandbox/predict_functional.py
statsmodels/stats/tests/test_nonparametric.py
statsmodels/stats/tests/test_pairwise.py
statsmodels/tools/grouputils.py

Silence ptp deprecation warning
Silence internal deprecations
Correctly access codes for categorical
Use contengency tables not sandbox
Pass correct tolerance args to scipy optimizers
Import Iterable from correct location
Remove unnecessary patsy call

MAINT: Resolve additional deprecations

---

statsmodels/iolib/table.py
statsmodels/regression/tests/test_regression.py

Replace $$ with a space to avoid compilation errors, and to
prevent munging of latex words during math mode

BUG: Replace $$ in generated LaTeX

---

.travis.yml

Reorder so that the oldest Python runs first, since
these are more likely to fail
closes #5286

MAINT: Reorder travis so that legacy fails early

---

statsmodels/base/tests/test_optimize.py
statsmodels/compat/scipy.py
statsmodels/discrete/tests/test_count_model.py

Set seed in basinhopping optimizers to improve reproducibility

TST: Explicitly set seed in basinhopping

---

statsmodels/iolib/table.py

Noticed in test logs:
```
iolib/table.py:639: FutureWarning: Index.data is deprecated and will be removed in a future version
self.data = data.data
iolib/table.py:639: FutureWarning: Float64Index.data is deprecated and will be removed in a future version
self.data = data.data
```
`Cell.__init__` currently uses a try/except to duck-type the check for another `Cell` object being passed as `data`.  In the case where a pandas Index is passed, the try/except works correctly, but not before issuing a warning.
This PR changes the try/except check to a specific check for the relevant case, avoiding the FutureWarning.

MAINT: avoid pandas FutureWarning by checking specific condition

---

statsmodels/genmod/families/family.py
statsmodels/genmod/tests/results/results_glm.py
statsmodels/genmod/tests/test_gee_glm.py
statsmodels/genmod/tests/test_glm.py

`Family.__init__` warns if the `link` given is a class instead of an instance.  That warning showed up in the CI, but did not have a useful line number attached to it to tell me where it came from.  To fix that going forward, this sets the appropriate `stacklevel` in the issued warning.
Then tracks down the couple of places where the tests used the deprecated call and updates them.
Then I went to de-duplicate an import of `cpunish` in the vicinity of that last fixup, which ended up touching a bunch of `test_glm`.  Here's hoping the fixes here earn enough leeway...

TST: apply stacklevel to warning in Family.__init__

---

statsmodels/sandbox/archive/linalg_covmat.py
statsmodels/sandbox/archive/linalg_decomp_1.py
statsmodels/sandbox/tsa/fftarma.py
statsmodels/stats/weightstats.py
statsmodels/tools/decorators.py

fix usage of OneTimeProperty that would be incorrect, specifically one that had more than just `self` as an argument.

CLN: Use cache_readonly instead of OneTimeProperty

---

statsmodels/sandbox/utils_old.py

Particularly the tools.tools functions are strictly better maintained in the non-sandbox versions.
Of the three remaining functions, `rank`, `fullrank`, `ECDF`, there are _almost_ identical non-sandbox versions, and I think it very likely that the differences are unintentional.  But until that is confirmed, leaving those in place.

MAINT: Import instead of copy/pasting utils

---

statsmodels/regression/_prediction.py

Broken off from #5132.
The part remaining over there is internal use of apparently-deprecated statsmodels API.  First pass at updating that usage broke a bunch of tests.  This part should be pretty easy.

MAINT: Avoid/Fix FutureWarnings

---

statsmodels/discrete/tests/test_count_model.py

Relax tolerance for platforms that use OpenBlas on a global optimizer

TST: Relax tolerance for OpenBlas issue

---

statsmodels/imputation/mice.py
statsmodels/imputation/tests/test_mice.py

Mattwigway mice setting with copy warning

---

statsmodels/base/data.py
statsmodels/base/model.py
statsmodels/discrete/count_model.py
statsmodels/discrete/discrete_margins.py
statsmodels/discrete/discrete_model.py
statsmodels/genmod/generalized_estimating_equations.py
statsmodels/genmod/generalized_linear_model.py
statsmodels/graphics/gofplots.py
statsmodels/nonparametric/kde.py
statsmodels/regression/linear_model.py
statsmodels/robust/robust_linear_model.py
statsmodels/sandbox/regression/gmm.py
statsmodels/stats/contingency_tables.py
statsmodels/tools/decorators.py
statsmodels/tools/tests/test_decorators.py
statsmodels/tsa/ar_model.py
statsmodels/tsa/arima_model.py
statsmodels/tsa/regime_switching/markov_switching.py
statsmodels/tsa/statespace/mlemodel.py

The "resettable" part of ResettableCache is never actually used.  By removing it we make it easier to reason about the behavior of the code.

remove unused resetlist

---

statsmodels/tsa/api.py
statsmodels/tsa/ar_model.py
statsmodels/tsa/filters/api.py
statsmodels/tsa/interp/__init__.py
statsmodels/tsa/tests/test_arima.py
statsmodels/tsa/tests/test_arima_process.py
statsmodels/tsa/vector_ar/api.py
statsmodels/tsa/vector_ar/irf.py
statsmodels/tsa/vector_ar/output.py
statsmodels/tsa/vector_ar/tests/results/results_svar.py
statsmodels/tsa/vector_ar/tests/test_svar.py
statsmodels/tsa/vector_ar/util.py
tools/code_maintenance.py
tools/examples_rst.py
tools/github_stats.py

Avoids results files that _might_ be auto-generated pending longer-term solution.
Avoids statespace which has other outstanding PRs.
Avoids a couple other files that need more in-depth excavation.

CLN: remove unused imports in tools, sm.tsa

---

statsmodels/iolib/foreign.py
statsmodels/iolib/tests/test_foreign.py

Cast before packing when required

MAINT: Ensure no warnings are produced by foreign

---

statsmodels/base/model.py
statsmodels/graphics/_regressionplots_doc.py
statsmodels/iolib/summary.py
statsmodels/miscmodels/tests/test_generic_mle.py
statsmodels/regression/quantile_regression.py
statsmodels/regression/tests/test_quantile_regression.py
statsmodels/sandbox/regression/gmm.py
statsmodels/sandbox/regression/tests/test_gmm.py

Remove hardcoded alpha and use_t
closes #5270

BUG: Stop hardcoding parameters in results

---

statsmodels/base/model.py
statsmodels/regression/mixed_linear_model.py

Deprecate unused scale parameter is test functions
closes #4598

MAINT: Deprecate scale in test function

---

setup.cfg
statsmodels/sandbox/panel/panel_short.py
statsmodels/stats/sandwich_covariance.py
statsmodels/stats/tests/test_groups_sw.py
statsmodels/tools/grouputils.py
statsmodels/tools/tests/test_grouputils.py

Fixes a lurking `NameError` in grouputils, closes #3558
Takes the `__main__` section of this file and turns it into tests, including one that hits the previously-failing path.
Updates imports, removing unused imports of grouputils.Group
sandwich_covariance uses `Group` but only actually needs `combine_indices`.  By using only the needed code, we make it easier to tell which parts of grouputils are actually used.

BUG: Fix NameError in grouputils, make __main__ into tests

---

statsmodels/stats/weightstats.py

Use a bulleted list for the possible hypotheses in the documentation of `ttest_ind`. Fix a couple of minor typos.

Bulleted list and minor typos in ttest_ind

---

statsmodels/iolib/summary.py

Remove a bunch of commented-out code in cases where a superior alternative was implemented adjacent to the commented-out version.
Subsequent cleanups of comments in cases where the meaning of comments is clear.  Comments that need maintainer attention are left "messy".

MAINT: De-duplicate code in iolib.summary

---

appveyor.yml
azure-pipelines.yml
requirements-dev.txt
tools/ci/azure_template.yml

Alternative to (builds on) #5609 enabling Windows builds in addition to Linux builds.  Mac builds are easy to enable, but are currently failing.

CI: Implement azure-pipelines with multi-platform support

---

setup.cfg
statsmodels/examples/example_enhanced_boxplots.py
statsmodels/iolib/foreign.py
statsmodels/iolib/table.py
statsmodels/multivariate/cancorr.py
statsmodels/sandbox/contrast_old.py
statsmodels/sandbox/formula.py
statsmodels/sandbox/tsa/diffusion.py
statsmodels/stats/contrast.py
statsmodels/tsa/vector_ar/svar_model.py

Adds a couple of lint checks that are passing but not currently specified.
Collects lint checks to be less verbose.
AFAICT the vast majority of remaining invalid escapes are caused by windows paths in docstring'd-out code (usually tracebacks) that needs to be either made into documentation or removed.

CLN: simplify lint configuration, fix some invalid escapes

---

statsmodels/graphics/factorplots.py
statsmodels/graphics/tests/test_factorplots.py

`interaction_plot` tries to recode a 'list' of string to 'list' of integers: https://github.com/statsmodels/statsmodels/blob/0c3f6ce6096f88a23d78e90eec68a89d4afa2412/statsmodels/graphics/factorplots.py#L106
This causes problems when the input is a pandas Series which has indices which are not `range(length)` (in my case the series had not contiguous indices). After recording, `interaction_plot` tries to combine the two independent variables and dependent variable with pandas:
https://github.com/statsmodels/statsmodels/blob/0c3f6ce6096f88a23d78e90eec68a89d4afa2412/statsmodels/graphics/factorplots.py#L108
Pandas notices it should create a DataFrame from several Series which have (through the recoding) potentially different indices, so it adds NAN for the non-overlapping values. This leads …

keep index of series when recoding a series

---

statsmodels/genmod/generalized_linear_model.py

So taking this code:
```python
%matplotlib inline
from __future__ import print_function
import scipy as sp
from scipy.stats.distributions import poisson
p = 25
n = 5000000
np.random.seed(43)
exog = np.random.rand(n, p - 1)
exog = np.hstack((np.ones((n, 1)), exog))
beta = np.concatenate(([-100], np.random.randint(-100, 100, p - 1))) / 100
eta = np.dot(exog, beta)
mu = np.exp(eta)
endog = poisson.rvs(mu)
model = sm.GLM(endog, exog, sm.families.Poisson(sm.families.links.log()))
```
And the money line...
`res = model.fit(method='newton', max_start_irls=0)`
On this simulated data, this PR is about 22 seconds vs. 24 seconds without. (Did a few `%%timeits`). 
Not sure if this is worth it...

PERF: Declare temporary output for hessian

---

.travis.yml

Remove one redundant travis build

BLD: Remove redundant travis config

---

statsmodels/base/model.py
statsmodels/formula/tests/test_formula.py

Improve error message shown for incorrect use of predict after formula
closes #3987

MAINT: Improve user-facing error message

---

azure-pipelines.yml
statsmodels/base/tests/test_generic_methods.py
statsmodels/compat/platform.py
statsmodels/regression/tests/test_lme.py

Relax tolerance on test that randomly fails on OpenBlas/OSX

MAINT: Relax tolerance on OSX only

---

tools/ci/azure_template.yml

MAINT: Enable xdist on azure

---

statsmodels/datasets/tests/test_utils.py

Webuse randomly fails with HTTPError
closes #2233
closes #4928

MAINT: Allow webuse fail

---

statsmodels/regression/tests/test_lme.py
statsmodels/tsa/tests/test_holtwinters.py

OpenBlas produces larger errors than MKL on OSX

TST: Relax tolerance on OSX for OpenBlas issues

---

statsmodels/tsa/arima_model.py
statsmodels/tsa/tests/test_arima.py

Improve explanation when passing an array that is not 1d or 1 column, 2d
closes #2575

ENH: Improve error when ARMA endog is not 1d

---

docs/source/dev/test_notes.rst
statsmodels/discrete/tests/results/results_discrete.py
statsmodels/discrete/tests/test_count_model.py
statsmodels/discrete/tests/test_discrete.py

It is _really_ tough to figure out what is tested where, what has externally-confirmed tests vs internal-consistency tests vs smoketests.  This peels back one entirely unnecessarily layer of that.

Make DiscreteResults Unchanging

---

statsmodels/tsa/tests/test_tsa_tools.py
statsmodels/tsa/tsatools.py

(1 - e^-x)/(1 + e^-x) = tanh(x/2) 
I modified the code to use numpy's tanh since it doesn't have the issue with large scale numbers.

ENH: Improve numerical stability of _ar_transparams, _ar_invtransparams

---

statsmodels/base/model.py
statsmodels/discrete/discrete_margins.py
statsmodels/discrete/discrete_model.py
statsmodels/duration/hazard_regression.py
statsmodels/genmod/generalized_estimating_equations.py
statsmodels/genmod/generalized_linear_model.py
statsmodels/iolib/summary.py
statsmodels/iolib/summary2.py
statsmodels/regression/linear_model.py
statsmodels/regression/mixed_linear_model.py
statsmodels/regression/quantile_regression.py
statsmodels/robust/robust_linear_model.py
statsmodels/stats/anova.py
statsmodels/stats/contingency_tables.py
statsmodels/stats/mediation.py

In a few cases this has unambiguous fixes, e.g. where a docstring incorrectly references summary.Summary instead of summary2.Summary.  In most cases there is just a ton of commented-out code in summary methods and I'd like to start the process of identifying what can be made useful and what should be removed.

WIP/MAINT: Identify defunct code in summary methods

---

lint.sh
statsmodels/datasets/tests/test_utils.py

Allow passing when network fails on tests that read files on the internet

TST: Allow network failure in web tests

---

statsmodels/multivariate/manova.py
statsmodels/multivariate/tests/test_manova.py

Fix mv_test so that it works when not using formulas
Improve MANOVA docstring to help users
closes #4903
closes #5578

BUG: Fix MANOVA when not using formulas

---

statsmodels/base/tests/test_penalized.py
statsmodels/iolib/summary2.py
statsmodels/iolib/tests/test_summary2.py

midrule is placed twice in a row which is incorrect
closes #5454

BUG: Replace midrule with hline

---

statsmodels/tsa/vector_ar/tests/test_svar.py

Adjust atol to allow Windows to pass

TST: Adjust test_irf atol

---

statsmodels/stats/tests/test_corrpsd.py
statsmodels/stats/tests/test_moment_helpers.py
statsmodels/stats/tests/test_multi.py
statsmodels/stats/tests/test_proportion.py
statsmodels/stats/tests/test_qsturng.py
statsmodels/tools/tests/test_eval_measures.py
statsmodels/tsa/tests/test_arima_process.py
statsmodels/tsa/tests/test_stattools.py

For any skeptics, recall the advantage of parametrizing is that if a particular case fails, a) the parameter value that fails is included in the test output and b) subsequent tests are still run, so we get information on all failing cases.

TST: parametrize tests instead of using for loops

---

statsmodels/base/tests/test_generic_methods.py
statsmodels/tsa/tests/test_arima.py

Relax tolerance of test that frequently fails by a small margin on OSX

TST: Relax test tolerance on OSX

---

statsmodels/tsa/vector_ar/tests/test_svar.py

Relax tolerance on windows to avoid failure noise

TST: Relax tolerance for irf test on windows

---

statsmodels/tsa/tests/test_ar.py
statsmodels/tsa/tests/test_seasonal.py
statsmodels/tsa/tests/test_stattools.py
statsmodels/tsa/tests/test_tsa_tools.py

Adjust tolerance on test that randomly fails on Windows
Reset randomstate to ensure that the test is identical in repeated runs

TST: Adjust tol and reset random state

---

statsmodels/tsa/tests/test_arima.py

Relax tolerance for test that frequently fails by a small margin on Windows
Add starting values for optimization to encourage accurate estimation

TST: Adjust tolerance for test on windows

---

statsmodels/discrete/discrete_model.py
statsmodels/discrete/tests/test_sandwich_cov.py

ATM the `get_robust_clu` classmethod calculates a correction factor and then a bunch of classes have that code copy/pasted into their `setup_class`.  A bunch of _other_ classes have a slightly-changed variant of that calculation, with no documentation as to why the slight change was made (IIRC the answer is "to make it match Stata/R").
This de-duplicates all that code by implementing `get_correction_factor`.

[TST/MAINT] de-duplicate get_correction_factor code

---

statsmodels/discrete/discrete_model.py
statsmodels/discrete/tests/test_count_model.py
statsmodels/genmod/generalized_linear_model.py

Show cov type for discrete models
closes #4581

ENH: Add cov type to summary for discrete models

---

statsmodels/base/model.py

Clarify docs so that predict gets dicts that return arrays, not lists.
closes #5557

DOC: Clarify that predict expects arrays in dicts [skip ci]

---

statsmodels/base/model.py
statsmodels/tsa/tests/test_arima.py

Ensure this is always set, even if it could be none
closes #2752

BUG: Always set mle_retvals

---

statsmodels/iolib/table.py
statsmodels/iolib/tests/test_summary.py

Escale string when output is LaTeX
closes #5297

BUG: Escape strings for latex output

---

statsmodels/stats/weightstats.py

As suggested in https://github.com/statsmodels/statsmodels/issues/5618#issuecomment-489373679. This PR will close #5618.
x1 and x2 are in separate lines now, and keep original descriptions.

DOC: Fix parameter description in weightstats

---

statsmodels/base/data.py
statsmodels/base/tests/test_data.py
statsmodels/iolib/tests/test_summary2.py
statsmodels/regression/tests/test_regression.py

Check const_idx when has_const is set to True

ENH: Allow const idx to be found

---

statsmodels/examples/ex_generic_mle.py
statsmodels/examples/ex_generic_mle_t.py
statsmodels/examples/ex_generic_mle_tdist.py
statsmodels/examples/try_gee.py
statsmodels/sandbox/distributions/genpareto.py
statsmodels/sandbox/regression/onewaygls.py
statsmodels/sandbox/tsa/diffusion.py
statsmodels/sandbox/tsa/diffusion2.py

One case is TeX that can be fixed with another backslash.  One case is fixed by updating the reference to the no-longer-existent pd.examples.finance.
Several cases are fixed by removing warning output from the py25 era.
The cases in try_gee are removed because the docstring'd-out code no longer raises.
The remaining cases _not_ addressed by this PR are in sandbox formula examples (#5692) or in other example files that no longer behave the way they did at the time of the docstring'd-out code (#5690), need input from @josef-pkt.
cc @bashtage

CLN: Fix invalid escapes where possible

---

statsmodels/base/data.py

Avoid implicit check since it does not help the situation
Always set k_constant=1 if hasconst even if not found

PERF: Avoid impplicit check when hasconst

---

statsmodels/sandbox/tsa/garch.py
statsmodels/sandbox/tsa/try_var_convolve.py
statsmodels/tsa/filters/filtertools.py

Functions from garch have been copied to non-sandbox modules, then better-maintained there.  This imports the non-sandbox versions and removes the old ones.
Really, I'd be OK with replacing the entire contents of that module with a message pointing users to `arch`, but that's for another day.

CLN: remove identical functions from garch

---

lint.sh
statsmodels/sandbox/distributions/try_pot.py

`try_pot`'s `__main__` block has docstring'd-out code with a traceback that I expect was meant to work.  It contains two calls to `mean_residual_life` that pass a `frac` kwarg, one of which raises.
This updates the docstring for `mean_residual_life` to clarify that the non-raising usage is the correct one, making the traceback unnecessary.  Adds the non-raising call to the end of the `__main__` block.
Followed by whitespace fixups.

MAINT: clean up docstring'd-out failure in __main__ block

---

.coveragerc
statsmodels/compat/python.py
statsmodels/datasets/tests/test_utils.py

Change location of import to reflect actual error
Broaden acepted errors types for network access

MAINT: Update import of URLError

---

statsmodels/tsa/innovations/_arma_innovations.pyx.in
statsmodels/tsa/innovations/api.py
statsmodels/tsa/innovations/arma_innovations.py
statsmodels/tsa/innovations/tests/test_cython_arma_innovations_fast.py

This exposes the "innovations filter", which is used for computing the one-step-ahead prediction errors for one more multiple series, assuming a given ARMA process, via the innovations algorithm.
In particular, this can be useful for generalized least squares estimation of regression with ARMA errors, since it can compute the transformed variables on which regression can be run (like the Prais–Winsten approach but for arbitrary ARMA processes).

ENH: expose innovations computation method to API.

---

statsmodels/stats/tests/test_multi.py

**Notes**:
See https://github.com/MacPython/statsmodels-wheels/pull/2
I think we just need to sort these. Seems like if this passing/failing is just luck if you are using xdist.

WIP: TST: Sort dicts in test_multi

---

statsmodels/tsa/stattools.py
statsmodels/tsa/tests/test_stattools.py

Limit lag length for very short series
closes #5432
closes #3330

BUG: Limit lag length in adf

---

statsmodels/tsa/stattools.py
statsmodels/tsa/tests/test_stattools.py

I don't believe there are open issues for this, but the enhancement is related to #5432 & #3330, only for the KPSS test. Adds a clear error message when the lags parameter exceeds the number of observations.

ENH: KPSS - detailed error message when lags > nobs

---

statsmodels/sandbox/distributions/estimators.py

Manually confirmed that the docstring'd-out code (from the py25 era) with the copy/pasted traceback no longer raises.  Removed the docstring'd-out code.  Small cleanups in the vicinity.
Removed a hessian function that used numdifftools.

MAINT: confirm that docstring'd-out traceback no longer raises; remove

---

statsmodels/tsa/tests/test_stattools.py

We're close to having all the invalid escapes gone (at which point we can add them to lint.sh and never worry about them again).  This fixes a handful that were recently introduced; all remaining cases are in either examples or sandbox

CLN: fix invalid escapes in test_stattools introduced in #5707

---

statsmodels/examples/ex_pandas.py

A couple of usages were out of date:
- an incorrect frequency passed to `VAR` raised, so this now passes the correct frequency.  
- `order` was passed to ARMA.fit instead of to the ARMA constructor, which raises, so this passes it in the up-to-date signature.
A couple of things were commented out, and one docstring'd-out traceback for things that used to fail or not exist.  These are now printed like everything else as they now work.

MAINT: fix non-working example ex_pandas

---

statsmodels/examples/ex_generic_mle_t.py

The docstring'd-out output there is apparently very out-of-date; the _shapes_ of several of the inspected outputs have changed.  I have no idea how the results on 106 and 112 would have been found.  (Re-running the code now, `tmp` produced on line 103 is a scalar, and tmp in line 111 has shape `(1000,)`)
Considered updating all the debugging output (the LinAlgError no longer occurs), but thats just trading one wall of text for another.

CLN: ellipses-out invalid escapes traceback

---

statsmodels/examples/ex_generic_mle_tdist.py
statsmodels/sandbox/distributions/sppatch.py

The affected code looks like it was copy/pasted (twice?) from a debugging terminal session.  To make it easier to work through and troubleshoot, this removes all of the copy/pasted code that are just typos, e.g. 375-378.
A few calls to `np.source` that just print the source code (of other statsmodels functions) are removed.  This removes the windows paths (and invalid escapes) that are printed with them.  e.g. 491
One error coming from numdiff (999-1005) has been fixed and the traceback is replaced with the expected output.  Along with it, two SingularMatrix errors no longer occur, so those tracebacks are removed.
The actual debugging here is in the fixed `stats.pareto.fit_fr` calls, where the underlying issues were/are in `sandbox.distributions.sppatch`.  The edits in that file are to …

CLN/EX: Troubleshoot broken example, clean up now-working scratch paper

---

statsmodels/sandbox/stats/multicomp.py

`scipy.stats` is missing, which would cause NameErrors if the relevant code paths were ever hit.
numpy as imported both as `numpy` and a `np`.  Standardize on `np`.
Move all module-level imports to the top of the file.

MAINT: fix missing or redundant imports

---

statsmodels/tsa/stattools.py

PERF: use np.sum(...) instead of sum(...)

---

statsmodels/iolib/foreign.py
statsmodels/iolib/tests/test_foreign.py

DEPR: deprecate StataReader, StataWriter, genfromdta

---

.coveragerc
statsmodels/datasets/tests/test_utils.py
tools/coveragerc/.coveragerc_travis

Protect CI from SSLError failures in web-based tests

TST: Protext against SSLError

---

statsmodels/tsa/vector_ar/tests/test_coint.py
statsmodels/tsa/vector_ar/vecm.py

Fix bug created using [:-0]
closes #5731

BUG: Ensure coint_johansen runs with 0 lags

---

lint.sh
statsmodels/tsa/statespace/tests/test_collapsed.py
statsmodels/tsa/statespace/tests/test_concentrated.py
statsmodels/tsa/statespace/tests/test_dynamic_factor.py
statsmodels/tsa/statespace/tests/test_exact_diffuse_filtering.py
statsmodels/tsa/statespace/tests/test_kalman.py
statsmodels/tsa/statespace/tests/test_mlemodel.py
statsmodels/tsa/statespace/tests/test_options.py
statsmodels/tsa/statespace/tests/test_pickle.py
statsmodels/tsa/statespace/tests/test_representation.py
statsmodels/tsa/statespace/tests/test_sarimax.py
statsmodels/tsa/statespace/tests/test_save.py

@ChadFulton the bare minimum to get linter to pass on statespace/tests.  There were a few places where changing assert_raises to pytest.raises was the best way to fix a linting complaint, but I didn't make that change in any _other_ places, so the usage is still plenty mixed.

CLN: Replace #5779

---

statsmodels/emplike/tests/test_regression.py
statsmodels/examples/tests/test_notebooks.py
statsmodels/graphics/tests/test_functional.py
statsmodels/imputation/tests/test_mice.py
statsmodels/multivariate/tests/test_pca.py
statsmodels/nonparametric/tests/test_kernel_density.py
statsmodels/nonparametric/tests/test_kernel_regression.py
statsmodels/regression/tests/test_lme.py
statsmodels/regression/tests/test_processreg.py
statsmodels/stats/tests/test_mediation.py

Adjust test tolerance after seeing a random OSX fail
Update slow markers

MAINT: Adjust tolerance for random fail on OSX

---

statsmodels/examples/ex_kde_confint.py
statsmodels/examples/ex_kde_normalreference.py
statsmodels/tsa/statespace/mlemodel.py

Looks like matplotlib has changed the kwarg from `normed` to `density`. 
This is causing a fail in the pip_pre travis, and will likely cause fails elsewhere as time passes.

MAINT: matplotlib normed -> density

---

statsmodels/genmod/generalized_estimating_equations.py
statsmodels/genmod/tests/test_gee.py
statsmodels/genmod/tests/test_glm.py

We can't delete fit_history after fitting the model (while transferring it to the results), because we may need to call update_params or other methods on the parent model that write to the fit history.
Also add some warnings.

BUG: GEE fit_history

---

statsmodels/base/model.py

----
This was a typo: `'normalized_cov_param'` does not appear anywhere else in the repo. Only difference this should make is no longer unnecessarily re-allocating the params matrix.

MAINT: use correct key name to check cov params presence

---

statsmodels/tsa/ar_model.py
statsmodels/tsa/tests/test_ar.py
statsmodels/tsa/tsatools.py

BUG: avoid silently dropping const column

---

tools/ci/docbuild.sh

I've noticed that we get occasional fails of the docbuild for random reasons on commits to master. The result is that doctr pushes an empty devel doc. Here's an example commit to master today where that happened:
https://travis-ci.org/statsmodels/statsmodels/jobs/538617713
This checks if `index.html` was created, which basically means the docbuild succeeded. If so, it aborts the commit. 
https://travis-ci.org/thequackdaddy/statsmodels/jobs/539032795

BLD: Check if docbuild succeeded before doctr

---

statsmodels/tsa/base/tsa_model.py

MAINT: RangeIndex._start deprecated in pandas 0.25

---

statsmodels/regression/linear_model.py

These must have been introduced recently, since at the time #5692 was made that fixed all remaining invalid escapes.  These will keep slipping through the cracks.

CLN: invalid escapes in linear_model
