statsmodels/statsmodels

- statsmodels/tools/linalg.py
closes https://github.com/statsmodels/statsmodels/issues/2159
> MAINT: remove calc_lwork

- statsmodels/genmod/generalized_estimating_equations.py
- statsmodels/genmod/generalized_linear_model.py
- statsmodels/genmod/tests/test_gee.py
- statsmodels/genmod/tests/test_glm.py
- statsmodels/graphics/_regressionplots_doc.py
- statsmodels/graphics/regressionplots.py
- statsmodels/graphics/tests/test_regressionplots.py
squashed and rebased version of #2018 
no other changes
> add GEE/GLM regression plots  rebase of #2018

- statsmodels/compat/python.py
Use explicit importing rather than try/except in python compatibility
> CLN: Explicit import for compatibility

- statsmodels/graphics/mosaicplot.py
- statsmodels/graphics/tests/test_mosaicplot.py
> ENH: Fail gracefully if no index given for DataFrame in MosaicPlot

- statsmodels/duration/hazard_regression.py
- statsmodels/duration/tests/test_phreg.py
> Initial commit to fix issue 2178

- statsmodels/genmod/cov_struct.py
- statsmodels/genmod/generalized_estimating_equations.py
- statsmodels/genmod/tests/test_gee.py
This PR adds weights to GEE.  The implementation follows what is done in Stata, as described here:
http://www.stata.com/support/faqs/statistics/weighted-estimation-and-xtgee/
> Add weights to GEE

- .travis.yml
Change package defaults to ensure that the most recently released packages
are tested
> TST: Update travis to newer packages

- statsmodels/base/model.py
- statsmodels/discrete/tests/test_sandwich_cov.py
- statsmodels/tools/_testing.py
closes #2209
add another condition to checks for available cov
I'll look for adjusting a unit test to cover this case. If there is none, then this will also be tested through it's use in SARIMAX #1698
> BUG: t_test, wald_test with only cov_params_default

- .travis.yml
add label='full' to test run on TravisCI
closes #2189
> TST: run also slow tests on TravisCI

- statsmodels/genmod/families/family.py
- statsmodels/genmod/generalized_estimating_equations.py
- statsmodels/genmod/generalized_linear_model.py
Partially (fully?) addresses #2208.
If we go ahead with this, we should add it to GEE too before merging.
> ENH: Emit warning in GLM if link does not respect family domain (#2208)

- statsmodels/sandbox/predict_functional.py
- statsmodels/sandbox/tests/test_predict_functional.py
This is a prediction method tailored to functional regression models in which one or more variables is modeled using b-splines.
The code doesn't produce any graphs of its own, but one natural thing to do with the predictions is to plot them, producing plots like this:
https://umich.box.com/shared/static/g2jx0wi5lo2r8liknpib.pdf
This is implemented as functions that are currently in the sandbox, but could be moved to become a method of the base results class (with the glm version attached to glm results class).
Related to #2151, but tailored to the functional case.
It would be nice to have an option for the pointwise confidence band to be a simultaneous confidence band.
> Prediction for functional regression

- docs/source/release/version0.7.rst
Added announcement for class-based PCA implementation with a listing
of new features.
> DOC: Added announcement for PCA

- statsmodels/datasets/tests/test_utils.py
- statsmodels/datasets/utils.py
rebased #2134 plus unit tests
downloading our datasets macrodata.dta
let's see what travis-ci says
> Fix webuse py3 rebased

- statsmodels/datasets/utils.py
make datasets webuse python3 compatible
Needs a test.
> COMPAT: webuse Python 3. Closes #2131.

- statsmodels/tsa/tests/test_tsa_tools.py
- statsmodels/tsa/tsatools.py
PR for fix for #2214 and new unit test for detrend
> Detrend bug#2214

- statsmodels/sandbox/tests/test_predict_functional.py
I think this should resolve the issue.  If not let me know.
> Check for matplotlib in tests (partially addresses #2227)

- statsmodels/api.py
Add PCA class to api to simplify access and enhance discoverability
> API: Add PCA to api

- statsmodels/datasets/tests/test_utils.py
see #2233
Travis-CI had now also some errors on this without internet
> TST disable test_webuse for now

- statsmodels/base/data.py
- statsmodels/base/model.py
- statsmodels/base/tests/test_data.py
- statsmodels/base/tests/test_shrink_pickle.py
- statsmodels/duration/tests/test_phreg.py
- statsmodels/formula/formulatools.py
- statsmodels/genmod/_prediction.py
- statsmodels/regression/_prediction.py
- statsmodels/regression/tests/test_regression.py
- statsmodels/sandbox/predict_functional.py
- statsmodels/stats/anova.py
rebased #2173
plus
- change to using new `data.desing_info` at several places
- style changes
> formula enhancements, rebased #2173

- statsmodels/regression/linear_model.py
Explain options in fit, and fix locations where detailed explainations
are located
> DOC: Improve OLS.fit docstring

- statsmodels/genmod/tests/test_gee.py
- statsmodels/tools/grouputils.py
- statsmodels/tools/pca.py
Small refactor to avoid pandas and numpy warnings
closes #2224
> CLN: Remove pandas and numpy warnings

- statsmodels/sandbox/regression/try_catdata.py
Replace deprecated calls to unique1d
closes #1378
> CLN: Remove unique1d

- statsmodels/datasets/tests/test_utils.py
see #2233
one file is being downloaded from sourceforge which has frequent connection problems
the download from our source on github worked without problems
But I want to get 0.7 out instead of being distracted by network problems
> TST disable test_webuse again

- setup.py
closes #2243
dev0+hash
see scipy and numpy (5556) issues
> MAINT: change dev version number for pep440 

- statsmodels/tsa/statespace/tests/test_sarimax.py
Proposed fix for #2267. At least it works on my 32 bit test system.
> BUG: Fix scaling issue on 32 bit systems in test.

- statsmodels/tsa/vector_ar/tests/test_var.py
- statsmodels/tsa/vector_ar/var_model.py
> FIX: Check for trend type in VAR models

- statsmodels/tsa/statespace/sarimax.py
> BUG: Fixed SARIMAX exog names when exog is pandas.

- statsmodels/tsa/statespace/mlemodel.py
> BUG: Fix ad-hoc models failing with no param_names

- docs/source/release/version0.7.rst
> DOC: Add state space and SARIMAX release notes.

- tools/notebook_output_template.py
> MAINT: update URL for mathjax om notebook_output_template.py

- docs/source/mixed_linear.rst
I started preparing my proposal for GSoC, and hence.
> DOC: Fix rst math for MixedLinear

- statsmodels/discrete/discrete_model.py
- statsmodels/discrete/tests/test_sandwich_cov.py
closes #2316
use offset and exposure in auxiliary model
use a k_params instead of possibly undefined len(start_params)
no extra unit tests yet, example for checking in #2316
> Bug count startparams NegativeBinomial

- statsmodels/graphics/regressionplots.py
this allows a newby to run this and focus on the cool stuff statsmodels offers.
thx
> sample code needs fully qualified path to run

- .gitignore
- statsmodels/genmod/families/family.py
- statsmodels/regression/linear_model.py
- statsmodels/sandbox/descstats.py
- statsmodels/sandbox/distributions/gof_new.py
- statsmodels/sandbox/tsa/garch.py
- statsmodels/stats/descriptivestats.py
- statsmodels/tsa/ar_model.py
Closes gh-2424
Also some other minor cleanups and an addition to .gitignore that was needed.
> MAINT: remove use of deprecated scipy.stats.ss helper function.

- statsmodels/base/data.py
- statsmodels/base/tests/test_shrink_pickle.py
see reopened #1263 
use original data `frame` to rebuild formula after unpickle
I will add unit tests before merging
> BUG: pickling with formulas - use original dataframe

- statsmodels/genmod/tests/test_glm.py
just add a smoke test for summary and summary2
this was my `glm_llnull` branch, see #2350 
gaussian loglike issue is #2351
> TST smoke test for GLM summary and summary2

- statsmodels/tsa/arima_model.py
- statsmodels/tsa/tests/test_arima.py
rebased version of #2457 plus unit tests
> BUG Arima forecast rebased

- statsmodels/tsa/statespace/sarimax.py
Simple commit to change it from a dict to a Bunch.
> ENH: Make SARIMAXResults.specification a Bunch

- docs/source/regression.rst
Some minor documentation cleanup for the regression module.
> Minor documentation update for regression.

- statsmodels/genmod/families/links.py
> fix docstring for Log.inverse_deriv

- statsmodels/genmod/cov_struct.py
- statsmodels/genmod/tests/test_gee.py
- statsmodels/tools/linalg.py
- statsmodels/tools/tests/test_linalg.py
This is a new covariance structure for GEE.  When grid=True it should be identical to the stationary covariance in Stata.  We also have grid=False, which allows unequal spacings of values.
> GEE stationary covariance structure

- statsmodels/tsa/arima_model.py
- statsmodels/tsa/kalmanf/kalmanfilter.py
I am assuming this is a typo since I could not find this abbreviation anywhere else in the project.
> DOC: arry -> array in ARIMA

- statsmodels/stats/weightstats.py
> DOC: fix CompareMeans.ztest_ind docstring

- statsmodels/graphics/correlation.py
Small fixes for #2510 and #2511
> Gh2510+2511

- statsmodels/tsa/statespace/mlemodel.py
Unfortunately, a couple of regressions occurred in #2473 after I rebased following #2356.
> REF: Fix regressions introduced in #2473.

- docs/source/release/version0.7.rst
- docs/source/statespace.rst
- examples/notebooks/statespace_local_linear_trend.ipynb
- examples/notebooks/statespace_sarimax_internet.ipynb
- examples/notebooks/statespace_sarimax_stata.ipynb
Updates the release notes and documentation to make it consistent with the recent changes.
> DOC: State space: release notes and documentation.

- examples/notebooks/tsa_arma_0.ipynb
- examples/python/tsa_arma_0.py
> EX: Update tsa example refactoring victims.

- statsmodels/graphics/regressionplots.py
- statsmodels/graphics/tests/test_regressionplots.py
> FIX: Allow 1 column exog plots

- examples/notebooks/interactions_anova.ipynb
- examples/python/interactions_anova.py
Fix a stale URL for data table in anova notebook. We should probably host this data somewhere.
closes #2320 for the missing data file, but we are still planning on `smdatasets`
> EX: Fix URL

- README.rst
xref https://github.com/statsmodels/statsmodels/issues/2544#issuecomment-123774737
> DOC: add section for github docs

- statsmodels/graphics/tests/test_tsaplots.py
- statsmodels/graphics/tsaplots.py
See Issue #2366. At least this fixes the existing bug.
> Handle alpha=None case for plot_acf

- docs/source/vector_ar.rst
Fixes #2272
- Update Pandas output to a recent version (0.16.2)
- Add context to `data` var in the example
> Update DynamicVAR docs

- statsmodels/iolib/table.py
I believe this should either be a local logger or removed as it is not terribly informative to users.
> removed root logger calls

- statsmodels/distributions/empirical_distribution.py
- statsmodels/sandbox/utils_old.py
> monotone_fn_inverter: fixed docstring

- examples/notebooks/statespace_arma_0.ipynb
- examples/notebooks/statespace_local_linear_trend.ipynb
- examples/notebooks/statespace_sarimax_internet.ipynb
- examples/notebooks/statespace_sarimax_stata.ipynb
- statsmodels/base/data.py
- statsmodels/base/wrapper.py
- statsmodels/tsa/statespace/_statespace.pyx.in
- statsmodels/tsa/statespace/kalman_filter.py
- statsmodels/tsa/statespace/mlemodel.py
- statsmodels/tsa/statespace/tests/test_mlemodel.py
- statsmodels/tsa/statespace/tests/test_representation.py
- statsmodels/tsa/statespace/tests/test_sarimax.py
A PR corresponding to #2564. Would like to add support for (at least):
- Full prediction / forecast interface (e.g. with confidence intervals, etc).
- Add impulse response functions, FEVDs, etc., and confidence intervals (at least asymptotic, possibly bootstrapped as well).
Possibly will also address (but may punt for later):
- Figure out how to better implement a wide range of diagnostic tests
> ENH: Statespace: Postestimation

- statsmodels/tsa/statespace/tests/test_smoothing.py
> BUG: Fix predict test due to new return value.

- statsmodels/tsa/statespace/structural.py
- statsmodels/tsa/statespace/tests/results/results_structural.py
- statsmodels/tsa/statespace/tests/test_structural.py
> BUG: Statespace: Error in UnobservedComponents start_params if endog is not Pandas.

- .travis.yml
try to fix travis error "conda not found"
> MAINT: try miniconda2 on path

- docs/source/missing.rst
- statsmodels/sandbox/mice/mice.py
- statsmodels/sandbox/mice/tests/test_mice.py
Frank and I decided that I should resubmit a MICE PR from my account due to time limitations on his side.
This PR supercedes #1757.  It is a substantial overhaul of the code, but still contains all the main elements as designed and implemented by Frank in his GSOC project.
Here are two notebooks that illustrate how it can be used:
[Dead links, see below for updated working links]
http://nbviewer.ipython.org/urls/umich.box.com/shared/static/dkinhqyyz374k37tdwdi.ipynb
http://nbviewer.ipython.org/urls/umich.box.com/shared/static/pt8p8tctkl10t32xo97v.ipynb
Feedback welcome and encouraged.
> New PR for MICE

- .travis.yml
> DEV: Use ubuntu image for CI build env.

- statsmodels/sandbox/mice/tests/test_mice.py
@josef-pkt @kshedden Check for matplotlib before calling it.
> MAINT: Check for matplotlib before use.

- statsmodels/stats/tests/test_weightstats.py
- statsmodels/stats/weightstats.py
@josef-pkt, take a look, please.
> Added from_data and summary methods in weightstats CompareMeans

- docs/source/tsa.rst
- statsmodels/tsa/stattools.py
- statsmodels/tsa/tests/test_stattools.py
Full implementation of the KPSS test; with unit tests and description in the
docs. See #2749 for a lengthy discussion on the design choices.
> Added KPSS test (1)

- statsmodels/tsa/stattools.py
> DOC: Remove non-ASCII character in KPSS docstring

- statsmodels/tsa/statespace/tests/test_dynamic_factor.py
- statsmodels/tsa/statespace/tests/test_kalman.py
- statsmodels/tsa/statespace/tests/test_options.py
- statsmodels/tsa/statespace/tests/test_representation.py
- statsmodels/tsa/statespace/tests/test_sarimax.py
- statsmodels/tsa/statespace/tests/test_smoothing.py
- statsmodels/tsa/statespace/tests/test_varmax.py
From #2694, replace __init__ with setup_class in statespace test classes.
> TST: Statespace: Replace __init__ with setup_class

- statsmodels/duration/tests/test_survfunc.py
- statsmodels/sandbox/mice/tests/test_mice.py
> TST: Avoid pandas SettingWithCopy Warning

- statsmodels/base/data.py
- statsmodels/tsa/ar_model.py
- statsmodels/tsa/arima_model.py
- statsmodels/tsa/base/tests/test_base.py
- statsmodels/tsa/base/tsa_model.py
- statsmodels/tsa/statespace/sarimax.py
- statsmodels/tsa/statespace/tests/test_mlemodel.py
- statsmodels/tsa/tests/test_ar.py
- statsmodels/tsa/tests/test_arima.py
- statsmodels/tsa/x13.py
Fixes issues described in #2769.
> REF: Statespace: Fix recent deprecation / future warning issues

- .travis.yml
try to fix #2836 
the testrun in master uses libgfortran 3.0
the initial PR used 1.0
try with specifying a version number
> Maint: pin libgfortran version

- statsmodels/tsa/statespace/_statespace.pyx.in
- statsmodels/tsa/statespace/dynamic_factor.py
- statsmodels/tsa/statespace/kalman_filter.py
- statsmodels/tsa/statespace/kalman_smoother.py
- statsmodels/tsa/statespace/mlemodel.py
- statsmodels/tsa/statespace/representation.py
- statsmodels/tsa/statespace/sarimax.py
- statsmodels/tsa/statespace/structural.py
- statsmodels/tsa/statespace/tests/test_dynamic_factor.py
- statsmodels/tsa/statespace/tests/test_mlemodel.py
- statsmodels/tsa/statespace/tests/test_sarimax.py
- statsmodels/tsa/statespace/tests/test_tools.py
- statsmodels/tsa/statespace/tests/test_varmax.py
- statsmodels/tsa/statespace/tools.py
- statsmodels/tsa/statespace/varmax.py
> BUG: Fix complex step score, Hessian calculations

- statsmodels/genmod/families/family.py
- statsmodels/genmod/generalized_linear_model.py
#2849, #2848, and others...
Let's remove `freq_weights` from the calculation of deviance.
> ENH/BUG: Removing weights from residuals.

- .travis.yml
similar to #2904 but using python 3.5
includes latest matplotlib
> MAINT: TravisCI add python 3.5 with latest dependencies

- statsmodels/regression/mixed_linear_model.py
- statsmodels/regression/tests/test_lme.py
This should close #2901 
@bburan thanks for the report
> Bug MixedLMResults.resid for vc fix #2901

- docs/source/dev/naming_conventions.rst
Fixed a little typo. I hope that I will be able to help out with more important tasks soon ;)
> DOC: Typo fix

- docs/source/conf.py
- setup.py
- tools/nbgenerate.py
Closes https://github.com/statsmodels/statsmodels/issues/2952
cc @wehlutyk this should fix things for you hopefully.
@josef-pkt I'll send along a PR to the statsmodels website repo with the updated HTML, with correct numpydoc sections.
> DOC/BLD: Fixed doc build process

- statsmodels/genmod/cov_struct.py
- statsmodels/genmod/generalized_estimating_equations.py
- statsmodels/genmod/tests/test_gee.py
This PR addresses comments about const_idx handling made in #2817.
Also, pep8 fixes to GEE code and tests.
> const_idx handling in GEE margins and pep8

- statsmodels/tsa/seasonal.py
- statsmodels/tsa/tests/test_seasonal.py
- statsmodels/tsa/tests/test_tsa_tools.py
- statsmodels/tsa/tsatools.py
Same as PR #2934 
Squashed all commits into one...
> ENH: seasonal_decompose override for periodicity as well as freq_to_period 'D' and 'H' support

- statsmodels/regression/tests/test_lme.py
- statsmodels/sandbox/stats/multicomp.py
- statsmodels/tools/grouputils.py
- statsmodels/tools/transform_model.py
- statsmodels/tsa/statespace/tests/test_varmax.py
- statsmodels/tsa/stattools.py
- statsmodels/tsa/tests/test_arima.py
Use sort_values for pandas dataframes
Enforce correct boolean index size for NumPy arrays
Avoid unintended comparisons of NumPy arrays
Close data files read during tests
Ensure division produces integers when used in array creation
Remove depricated exception use
> TST: Remove external warnings for deprecations and behavior changes

- statsmodels/sandbox/panel/panelmod.py
No idea what's the plan, if any, with this code/functionality... but updating it to work with recent pandas shouldn't do any harm ;-)
> COMPAT: update calls to pandas objects/methods

- statsmodels/datasets/china_smoking/china_smoking.csv
Missing data file, closes #2995
> Added China smoking data

- docs/make.bat
- docs/source/conf.py
- docs/source/contingency_tables.rst
- docs/source/dev/git_notes.rst
- docs/source/diagnostic.rst
- docs/source/distributions.rst
- docs/source/duration.rst
- docs/source/examples/index.rst
- docs/source/glm.rst
- docs/source/plots/graphics_month_plot.py
- docs/source/release/version0.6.rst
- docs/source/release/version0.7.rst
- docs/source/stats.rst
- docs/source/tools.rst
- docs/source/vector_ar.rst
- docs/sphinxext/numpy_ext/docscrape.py
- docs/sphinxext/numpy_ext/plot_directive.py
- statsmodels/api.py
- statsmodels/datasets/fair/data.py
- statsmodels/duration/__init__.py
- statsmodels/genmod/families/family.py
- statsmodels/graphics/tsaplots.py
- statsmodels/sandbox/stats/diagnostic.py
- statsmodels/stats/contingency_tables.py
- statsmodels/stats/weightstats.py
- statsmodels/tools/data.py
- statsmodels/tsa/arima_process.py
- statsmodels/tsa/statespace/kalman_filter.py
- statsmodels/tsa/statespace/mlemodel.py
- statsmodels/tsa/vector_ar/dynamic.py
Large scale fix up of small issues so that sphinx will build
the documentation correctly.
> DOC: Fix sphinx errors and warnings

- statsmodels/sandbox/stats/multicomp.py
- statsmodels/stats/tests/test_pairwise.py
Catch intentional warning in MultiComp
> TST: Catch intentional warning

- statsmodels/regression/tests/test_lme.py
> Skip slow MixedLM test on some setups

- statsmodels/iolib/table.py
- statsmodels/iolib/tests/test_table.py
Rebase patch so that it can make master
closes #2862 
closes #2868
> REBASE: Tvanessa's latex patch rebased

- statsmodels/tsa/stattools.py
- statsmodels/tsa/tests/test_stattools.py
Add string to results store
closes #2321
> FIX: Add _str to adfuller ResultsStore

- statsmodels/stats/anova.py
- statsmodels/stats/contrast.py
- statsmodels/stats/correlation_tools.py
- statsmodels/stats/gof.py
- statsmodels/stats/mediation.py
- statsmodels/stats/multitest.py
- statsmodels/stats/proportion.py
- statsmodels/stats/weightstats.py
Use doctest to find obvious errors in examples
> DOC: Improve doc examples

- statsmodels/base/model.py
- statsmodels/discrete/discrete_margins.py
- statsmodels/distributions/edgeworth.py
- statsmodels/distributions/mixture_rvs.py
- statsmodels/duration/survfunc.py
- statsmodels/emplike/aft_el.py
- statsmodels/emplike/descriptive.py
- statsmodels/emplike/originregress.py
- statsmodels/genmod/generalized_estimating_equations.py
Verify doc tests execute.  Final result is not verified due to
precision issues across platforms/BLAS implementation
> DOC: Verify doctests

- statsmodels/tsa/statespace/tests/test_sarimax.py
Adjust rtol to allow looser comparison on Windows
> TST: Adjust tolerance for Appveyor/Windows

- statsmodels/base/model.py
- statsmodels/base/tests/test_shrink_pickle.py
- statsmodels/distributions/edgeworth.py
- statsmodels/distributions/tests/test_edgeworth.py
- statsmodels/genmod/cov_struct.py
- statsmodels/genmod/generalized_estimating_equations.py
- statsmodels/genmod/generalized_linear_model.py
- statsmodels/miscmodels/tests/test_poisson.py
- statsmodels/multivariate/pca.py
- statsmodels/sandbox/predict_functional.py
- statsmodels/sandbox/stats/multicomp.py
- statsmodels/stats/contingency_tables.py
- statsmodels/stats/proportion.py
- statsmodels/stats/stattools.py
- statsmodels/stats/tests/test_proportion.py
- statsmodels/tools/sm_exceptions.py
- statsmodels/tsa/statespace/dynamic_factor.py
- statsmodels/tsa/statespace/kalman_filter.py
- statsmodels/tsa/statespace/kalman_smoother.py
- statsmodels/tsa/statespace/mlemodel.py
- statsmodels/tsa/statespace/sarimax.py
- statsmodels/tsa/statespace/structural.py
- statsmodels/tsa/statespace/varmax.py
- statsmodels/tsa/stattools.py
- statsmodels/tsa/tests/test_arima.py
- statsmodels/tsa/tests/test_stattools.py
- statsmodels/tsa/tsatools.py
Replace all UserWarnings with meaningful warnings
xref #2781
closes #2747
closes #2492
> CLN: Replace UserWarnings with meaningful warning

- statsmodels/duration/survfunc.py
- statsmodels/duration/tests/test_survfunc.py
Add a class for estimating cumulative incidence rates (used in competing risks modeling).  Some relevant references:
http://www.stata-journal.com/sjpdf.html?articlenum=st0059
http://www.ncbi.nlm.nih.gov/pmc/articles/PMC2760993/#!po=93.4783
http://data.princeton.edu/pop509/cumulativeIncidence.pdf
> ENH: Cumulative incidence rates

- statsmodels/tsa/stattools.py
- statsmodels/tsa/tests/test_arima.py
- statsmodels/tsa/tests/test_stattools.py
Rebase joesnacks/master which brings missing obs handling to acf
closes #1491
> ENH: add support for NaNs in acovf, acf, pacf (REBASE)

- statsmodels/duration/api.py
This should have been part of #3016
> BUG: Add CumIncidenceRight to the duration API

- docs/source/release/version0.8.rst
largely a stub to add the file
> REL/DOC:  start release notes for 0.8

- docs/source/release/version0.8.rst
I went through the list of merge commits and should have everything important for explicit mentioning
> DOC/REL: add more to release 0.8 notes

- statsmodels/genmod/families/family.py
- statsmodels/genmod/families/varfuncs.py
- statsmodels/genmod/generalized_linear_model.py
- statsmodels/iolib/foreign.py
- statsmodels/regression/linear_model.py
- statsmodels/robust/norms.py
- statsmodels/robust/robust_linear_model.py
- statsmodels/tsa/statespace/mlemodel.py
- statsmodels/tsa/tsatools.py
Clean-up incorrect See also references
closes #278
[skip ci]
> DOC: Verify See also

- statsmodels/graphics/tests/test_tsaplots.py
- statsmodels/graphics/tsaplots.py
Replace sort/sort_values with sort_index
Fix documentation
Change average line color to red by default to improve aesthetics
closes #2110
> FIX: Remove unnecessary sort in seasonal plot

- statsmodels/sandbox/regression/gmm.py
- statsmodels/sandbox/regression/tests/test_gmm.py
- statsmodels/tools/tests/test_tools.py
- statsmodels/tools/tools.py
Ensure IV2SLS works with 1d and 2d arrays
closes #2720
> FIX: Fix IV2SLS to handle data sizes

- docs/source/tsa.rst
- statsmodels/tsa/filters/bk_filter.py
- statsmodels/tsa/filters/cf_filter.py
- statsmodels/tsa/filters/hp_filter.py
- statsmodels/tsa/seasonal.py
Add seasonal_decompose to tsa.rst
Small improvements to seasonal_decompose docstring
See also links across filters
closes #2299
[skip ci]
> DOC: Add seasonal_decompose to docs

- statsmodels/tsa/tests/test_tsa_tools.py
- statsmodels/tsa/tsatools.py
Add support for Series and DataFrame in lagmat2ds
Add support for 1d arrays
xref #1306
> ENH: Add pandas support to lagmat2ds

- statsmodels/genmod/cov_struct.py
- statsmodels/tsa/vector_ar/util.py
- statsmodels/tsa/vector_ar/var_model.py
Use local RandomState when setting the seed instead of changing the
global RandomState
closes #306
> CLN: Change use of global NumPy RandomState

- docs/source/release/version0.7.rst
> REL/DOC add more to 0.7 release notes [ci skip]

- statsmodels/imputation/ros.py
- statsmodels/imputation/tests/test_ros.py
rebased #3034 plus 
try disable test_ros for pandas < 0.14
> Ros pandas compat rebased

- statsmodels/genmod/families/family.py
Fix resid_anscombe doc error
[skio ci]
> DOC: Fix small sphinx error in docs

- statsmodels/stats/proportion.py
- statsmodels/stats/tests/test_proportion.py
Fix incorrect value handling 
Add tests
closes #2779
closes #2969
> BUG: Fix incorrect value handling in stats.proportions 

- statsmodels/datasets/tests/test_utils.py
- statsmodels/datasets/utils.py
- statsmodels/sandbox/examples/ex_formula.py
- statsmodels/sandbox/formula.py
- statsmodels/sandbox/panel/panelmod.py
- statsmodels/sandbox/tests/test_formula.py
- statsmodels/stats/gof.py
- statsmodels/stats/tests/test_power.py
- statsmodels/tsa/filters/hp_filter.py
- statsmodels/tsa/statespace/tests/test_representation.py
Remove unreachable code for ancient versions of NumPy, etc.
Cleanup direct version tests to use compat
> CLN: Remove old unreachable code

- README.rst
Add additional badges and fix rst errors
[skip ci]
> DOC: Improve appearance of README

- tools/nbgenerate.py
> DOC/BUILD: Fix kernel name defaults

- statsmodels/imputation/ros.py
@josef-pkt 
Running the  CI build on this one, but passed locally without any pandas FutureWarnings.
> COMPAT: pandas.sort in ros.py

- docs/source/_static/examples.css
- docs/source/index.rst
- docs/themes/statsmodels/indexsidebar.html
- statsmodels/imputation/ros.py
- tools/nbgenerate.py
3 commits made to maintenance/0.8.x before rc1
> MAINT: Forward 3 merges from maintenance08

- appveyor.yml
> TST: Change appveyor clone depth

- statsmodels/datasets/anes96/data.py
- statsmodels/datasets/cancer/data.py
- statsmodels/datasets/ccard/data.py
- statsmodels/datasets/china_smoking/data.py
- statsmodels/datasets/co2/data.py
- statsmodels/datasets/committee/data.py
- statsmodels/datasets/copper/data.py
- statsmodels/datasets/cpunish/data.py
- statsmodels/datasets/elnino/data.py
- statsmodels/datasets/engel/data.py
- statsmodels/datasets/fair/data.py
- statsmodels/datasets/fertility/data.py
- statsmodels/datasets/grunfeld/data.py
- statsmodels/datasets/heart/data.py
- statsmodels/datasets/longley/data.py
- statsmodels/datasets/macrodata/data.py
- statsmodels/datasets/modechoice/data.py
- statsmodels/datasets/nile/data.py
- statsmodels/datasets/randhie/data.py
- statsmodels/datasets/scotland/data.py
- statsmodels/datasets/spector/data.py
- statsmodels/datasets/stackloss/data.py
- statsmodels/datasets/star98/data.py
- statsmodels/datasets/statecrime/data.py
- statsmodels/datasets/strikes/data.py
- statsmodels/datasets/tests/test_data.py
Add tests for data sets
Fix dataset type error in fertility data
> TST: Add tests for datasets

- setup.py
Update PyPI classifiers
Update PyPI website
Update Minimum version in setup dict
> DOC: Update PyPI classifiers

- README.rst
> Add missing methods to README

- statsmodels/stats/stattools.py
Improve Jarque-Bera documentation
closes #1579
[skip ci]
> DOC: Fix Jarque-Bera documentation

- statsmodels/tsa/regime_switching/markov_switching.py
> BUG: (Backport) Non-integer index array created from np.r_[ ]

- statsmodels/genmod/generalized_estimating_equations.py
- statsmodels/genmod/tests/test_gee.py
- statsmodels/graphics/factorplots.py
- statsmodels/graphics/regressionplots.py
- statsmodels/graphics/tests/test_boxplots.py
- statsmodels/graphics/tests/test_factorplots.py
- statsmodels/graphics/tests/test_regressionplots.py
Add missing tests for plotting functions
Fix small bugs in plotting functions
Refactor factorplots to remove bad practices
> TST/FIX/CLN: Add missing tests smoke for plotting functions

- statsmodels/base/data.py
- statsmodels/tsa/statespace/dynamic_factor.py
- statsmodels/tsa/statespace/mlemodel.py
- statsmodels/tsa/statespace/sarimax.py
- statsmodels/tsa/statespace/structural.py
- statsmodels/tsa/statespace/tests/test_sarimax.py
- statsmodels/tsa/statespace/tests/test_structural.py
- statsmodels/tsa/statespace/tests/test_varmax.py
- statsmodels/tsa/statespace/varmax.py
> BUG: (Backport) Statespace: get_prediction/get_forecast with exog

- statsmodels/miscmodels/tests/test_tmodel.py
- statsmodels/tools/tests/test_rootfinding.py
- statsmodels/tsa/vector_ar/tests/test_svar.py
see #3128 for new test failures with scipy 0.8.0
adjusting unit tests to avoid failures from changes in optimize behavior
> TST: fix tests for scipy 0.8.0

- statsmodels/tsa/stattools.py
Correct errors in docstrings
[skip ci]
closes #2937
> DOC: Fix adfuller docs and _autolag docs

- statsmodels/tsa/tests/test_x13.py
closes #3159 
see 3159 for change in resample behavior
> MAINT/TST: test_x13 resample pandas 0.18 compatibility

- docs/source/stats.rst
- statsmodels/stats/proportion.py
- statsmodels/stats/tests/results/results_multinomial_proportions.py
- statsmodels/stats/tests/test_proportion.py
this continues PR #2953 
remove exception for zero counts
allow counts to be zero or have decimals
speedup by avoiding calculating same value several times
> ENH: Multinomial confidence interval (cont. 2953)

- docs/source/dev/vbench.rst
- statsmodels/compat/pandas.py
- statsmodels/tsa/ar_model.py
- statsmodels/tsa/base/datetools.py
- statsmodels/tsa/base/tests/test_base.py
- statsmodels/tsa/base/tests/test_datetools.py
- statsmodels/tsa/base/tsa_model.py
- statsmodels/tsa/statespace/tests/test_mlemodel.py
- statsmodels/tsa/tests/test_ar.py
- statsmodels/tsa/tests/test_arima.py
- statsmodels/tsa/vector_ar/dynamic.py
- statsmodels/tsa/vector_ar/tests/example_svar.py
> CLN: Pandas deprecations rebased

- statsmodels/base/model.py
- statsmodels/tools/sm_exceptions.py
- statsmodels/tsa/kalmanf/kalman_loglike.pyx
Add test for PD hessian
Raise if not PD before inversion
closes #3098
closes #3094
> TST: Add test for PD hessian

- statsmodels/tsa/stattools.py
- statsmodels/tsa/tests/test_stattools.py
replace broken by new Engle Granger cointegration test
unit tested against Stata user contributed egranger
#1451 #3086
(This PR got some trailing white space cleanup)
> ENH/BUG Augmented Engle Granger cointegration test

- statsmodels/stats/proportion.py
STY: Small spacing cleanups
BUG: Fixed typo in option #3167
> Cleaned up some pep8 errors and fixes #3167 

- statsmodels/tsa/statespace/mlemodel.py
- statsmodels/tsa/statespace/tests/test_mlemodel.py
> BUG: Statespace: Backport: Summary fails if diagnostic tests fail

- statsmodels/tsa/statespace/mlemodel.py
- statsmodels/tsa/statespace/sarimax.py
- statsmodels/tsa/statespace/tests/test_save.py
- Improves `remove_data` by actually removing all of the data arrays.
- Adds unit tests for `save` and `load` for each of the 4 major models.
> ENH: Statespace: Improve/test remove_data, save, load

- statsmodels/tsa/base/tests/test_base.py
- statsmodels/tsa/base/tsa_model.py
> BUG: Backport: TSA models if date index without known frequency

- statsmodels/tsa/tsatools.py
Just that, nothing complicated.
> Fix small typo in error message

- statsmodels/tsa/statespace/structural.py
> DOC: Fix unobserved components seasonal docstring

- statsmodels/tsa/statespace/dynamic_factor.py
- statsmodels/tsa/statespace/kalman_filter.py
- statsmodels/tsa/statespace/mlemodel.py
- statsmodels/tsa/statespace/representation.py
- statsmodels/tsa/statespace/sarimax.py
- statsmodels/tsa/statespace/structural.py
- statsmodels/tsa/statespace/tests/test_impulse_responses.py
- statsmodels/tsa/statespace/tests/test_representation.py
- statsmodels/tsa/statespace/tests/test_simulate.py
- statsmodels/tsa/statespace/tests/test_structural.py
- statsmodels/tsa/statespace/tests/test_varmax.py
- statsmodels/tsa/statespace/varmax.py
> BUG/ENH/TST: Backport: State space: Simulate / Impulse Responses

- docs/source/about.rst
> DOC: fix small typo in about.rst

- statsmodels/api.py
- statsmodels/multivariate/cancorr.py
- statsmodels/multivariate/manova.py
- statsmodels/multivariate/multivariate_ols.py
- statsmodels/multivariate/tests/test_cancorr.py
- statsmodels/multivariate/tests/test_manova.py
- statsmodels/multivariate/tests/test_multivariate_ols.py
This is the squashed version of #3291
> (Squashed) Add MANOVA, CanCorr, _MultivariateOLS and the associated results class

- INSTALL.txt
- README.rst
but primarily to see if current maintenance/0.8.x builds/tests fine against current pandas etc since test build fails on debian :-/
> DOC: minor typos, trailing white spaces, etc

- statsmodels/graphics/tests/test_tsaplots.py
> TST/COMPAT: tsaplots test compatibility with newer Pandas - Backport

- statsmodels/tsa/base/tsa_model.py
Closes #3349 
Used the fix @jreback suggested (thanks!).
> BUG: Make sure int is passed to pandas date index

- statsmodels/base/elastic_net.py
- statsmodels/regression/linear_model.py
- statsmodels/regression/tests/test_regression.py
Ridge regression is a special case of the elastic net, and has a closed-form solution for OLS which is much faster than the elastic net iterations.  This PR shortcuts the elastic net in the special case of ridge regression.
> PERF: Ridge regression shortcut for OLS

- statsmodels/duration/survfunc.py
- statsmodels/duration/tests/test_survfunc.py
This PR adds entry times for `SurvfuncRight` (Kaplan-Meier estimation of the survival function).
Tests against R.
> ENH: entry times for Kaplan-Meier

- examples/python/glm.py
- statsmodels/discrete/tests/test_sandwich_cov.py
- statsmodels/genmod/families/family.py
- statsmodels/genmod/families/links.py
- statsmodels/genmod/tests/test_glm.py
- statsmodels/stats/mediation.py
- statsmodels/stats/tests/test_mediation.py
This should solve issue #2913.
> SUMM/REF: refactor link argument in family

- statsmodels/multivariate/cancorr.py
- statsmodels/multivariate/multivariate_ols.py
- statsmodels/multivariate/tests/test_cancorr.py
- statsmodels/multivariate/tests/test_manova.py
Fix incorrect pandas assignment for older pandas
Remove unnecessary unicode
> FIX: Fix broken Pandas/Python 2.6 usage

- statsmodels/compat/numpy.py
- statsmodels/compat/pandas.py
- statsmodels/datasets/utils.py
- statsmodels/examples/ex_pandas.py
- statsmodels/graphics/tests/test_tsaplots.py
- statsmodels/tsa/base/datetools.py
- statsmodels/tsa/tests/test_stattools.py
- statsmodels/tsa/tests/test_tsa_tools.py
- statsmodels/tsa/tsatools.py
- statsmodels/tsa/vector_ar/util.py
Refactor pandas to use a compat shim
xref #3332
> COMPAT: Avoid future warnings for pandas

- statsmodels/tsa/arima_model.py
- statsmodels/tsa/tests/test_arima.py
Rebase of #3217 and add test for pickling support
> Rebase getnewargs for ARIMA #3217

- statsmodels/stats/outliers_influence.py
- statsmodels/stats/tests/test_diagnostic.py
Rebase quackdaddy #3346 fix and add a test that would catch the error.
> Quackdaddy alpha fix

- statsmodels/tsa/statespace/_representation.pyx.in
- statsmodels/tsa/statespace/_simulation_smoother.pxd
- statsmodels/tsa/statespace/_simulation_smoother.pyx.in
- statsmodels/tsa/statespace/_statespace.pyx.in
- statsmodels/tsa/statespace/kalman_filter.py
- statsmodels/tsa/statespace/simulation_smoother.py
- statsmodels/tsa/statespace/tests/test_kalman.py
- statsmodels/tsa/statespace/tests/test_representation.py
- statsmodels/tsa/statespace/tests/test_simulate.py
- statsmodels/tsa/statespace/tools.py
> BUG: State space: incorrect ergodic mean if state intercept is non-zero

- statsmodels/tsa/statespace/_statespace.pyx.in
- statsmodels/tsa/statespace/tests/test_kalman.py
- statsmodels/tsa/statespace/tools.py
> BUG: Backport: State space: incorrect ergodic mean if state intercept is non-zero

- statsmodels/discrete/tests/test_constrained.py
- statsmodels/genmod/families/family.py
- statsmodels/genmod/tests/test_glm.py
> BUG: missing term in family Poisson deviance

- docs/source/conf.py
- docs/source/release/version0.7.rst
- statsmodels/base/model.py
- statsmodels/genmod/generalized_estimating_equations.py
- statsmodels/graphics/gofplots.py
- statsmodels/graphics/mosaicplot.py
- statsmodels/graphics/tsaplots.py
- statsmodels/imputation/mice.py
- statsmodels/multivariate/pca.py
- statsmodels/regression/linear_model.py
- statsmodels/regression/mixed_linear_model.py
- statsmodels/robust/robust_linear_model.py
- statsmodels/sandbox/distributions/extras.py
- statsmodels/tools/tools.py
- statsmodels/tsa/filters/bk_filter.py
- statsmodels/tsa/filters/cf_filter.py
- statsmodels/tsa/filters/hp_filter.py
- statsmodels/tsa/statespace/kalman_filter.py
- statsmodels/tsa/statespace/kalman_smoother.py
Fix a number of doctest errors
[skip ci]
> DOC: Fix doc test errors

- statsmodels/compat/numpy.py
- statsmodels/datasets/tests/test_data.py
- statsmodels/stats/tests/test_pairwise.py
- statsmodels/tsa/filters/tests/test_filters.py
Remove FutureWarnings from NumPy
Clean up test to remove docstrings
> CLN: Remove FutureWarnings

- docs/source/release/version0.8.rst
I moved one section and added some items that have been backported since 0.8rc1
> DOC update release notes for 0.8

- docs/source/stats.rst
- docs/source/tsa.rst
- statsmodels/stats/api.py
missing functions and class in api and doc rst files
closes #3226
I don't know if there are more
> ENH/DOC: add missing objects to stats.api stats.rst

- INSTALL.txt
- docs/source/install.rst
Update installation instruction with more accurate information about
requirements and instructions for more recent version of Python
closes #3328
[skip ci]
> DOC: Update installation instructions

- docs/source/stats.rst
- statsmodels/stats/api.py
- statsmodels/stats/multitest.py
Closes https://github.com/statsmodels/statsmodels/issues/3440
The description for Mediation came from Kirby's notebook [here](http://nbviewer.jupyter.org/urls/umich.box.com/shared/static/jpmd9y99259u6dv0rj6p46993981m7zm.ipynb)
Anything else to be added?
> Doc 08 mediation local fdr

- INSTALL.txt
- docs/source/install.rst
- setup.py
> REL: update setup.py for release

- docs/make.bat
- docs/source/conf.py
- docs/source/imputation.rst
- docs/source/iolib.rst
- docs/source/plots/graphics_month_plot.py
- docs/source/release/version0.7.rst
- docs/source/release/version0.8.rst
- docs/source/rlm.rst
- docs/source/statespace.rst
- docs/source/stats.rst
- docs/source/tsa.rst
- docs/themes/statsmodels/indexsidebar.html
- docs/themes/statsmodels/layout.html
- statsmodels/stats/correlation_tools.py
- statsmodels/stats/multitest.py
- statsmodels/tools/tools.py
Fix layout problem whihc excluded css
Fix broken URL
Remove missing todo document
[skip ci]
> DOC: Small doc fixes

- docs/source/conf.py
@TomAugspurger  @josef-pkt Final fix for docs.  Figures now render in correct location.
> DOC: Fix image build location

- docs/source/tools.rst
- statsmodels/base/model.py
- statsmodels/discrete/discrete_model.py
- statsmodels/robust/__init__.py
- statsmodels/robust/robust_linear_model.py
- statsmodels/robust/scale.py
- statsmodels/tools/tests/test_tools.py
- statsmodels/tools/tools.py
Remove all 0.7 scheduled deprecations
Rmove tests that use deprecated features
> CLN: Remove 0.7 deprecations

- statsmodels/datasets/tests/test_utils.py
- statsmodels/datasets/utils.py
Re-enable test with direct check for file availability.
closes #2278
> TST: Re-enable webuse test

- examples/notebooks/interactions_anova.ipynb
- examples/notebooks/statespace_arma_0.ipynb
- examples/notebooks/statespace_cycles.ipynb
- examples/notebooks/statespace_dfm_coincident.ipynb
- examples/notebooks/statespace_local_linear_trend.ipynb
- examples/notebooks/statespace_sarimax_internet.ipynb
- examples/notebooks/statespace_sarimax_stata.ipynb
- examples/notebooks/statespace_structural_harvey_jaeger.ipynb
- examples/notebooks/statespace_varmax.ipynb
- examples/notebooks/tsa_arma_0.ipynb
- examples/notebooks/tsa_arma_1.ipynb
Fix a range of small notebook errors
[skip ci]
> DOC: Fix notebook errors

- docs/source/conf.py
- docs/source/pitfalls.rst
- docs/source/rlm.rst
- examples/notebooks/interactions_anova.ipynb
- examples/notebooks/robust_models_1.ipynb
- examples/notebooks/statespace_arma_0.ipynb
- examples/notebooks/statespace_cycles.ipynb
- examples/notebooks/statespace_dfm_coincident.ipynb
- examples/notebooks/statespace_local_linear_trend.ipynb
- examples/notebooks/statespace_sarimax_internet.ipynb
- examples/notebooks/statespace_sarimax_stata.ipynb
- examples/notebooks/statespace_structural_harvey_jaeger.ipynb
- examples/notebooks/statespace_varmax.ipynb
- examples/notebooks/tsa_arma_0.ipynb
- examples/notebooks/tsa_arma_1.ipynb
Fixes for notebooks
Fixes for conf that allow module index to build
Small fixes to docs
> DOC: Doc fixes backport to 0.8.x

- docs/source/about.rst
- docs/source/anova.rst
- docs/source/conf.py
- docs/source/contingency_tables.rst
- docs/source/dev/internal.rst
- docs/source/discretemod.rst
- docs/source/distributions.rst
- docs/source/duration.rst
- docs/source/emplike.rst
- docs/source/gee.rst
- docs/source/glm.rst
- docs/source/gmm.rst
- docs/source/imputation.rst
- docs/source/iolib.rst
- docs/source/mixed_linear.rst
- docs/source/multivariate.rst
- docs/source/nonparametric.rst
- docs/source/regression.rst
- docs/source/rlm_techn1.rst
- docs/source/sandbox.rst
- docs/source/statespace.rst
- docs/source/stats.rst
- docs/source/tools.rst
- docs/source/tsa.rst
- docs/source/vector_ar.rst
Make changes that allow the py-modindex to correctly build
[skip ci]
> DOC: Add module synopsis

- statsmodels/datasets/utils.py
- statsmodels/discrete/discrete_margins.py
- statsmodels/discrete/discrete_model.py
- statsmodels/distributions/edgeworth.py
- statsmodels/distributions/empirical_distribution.py
- statsmodels/duration/hazard_regression.py
- statsmodels/examples/ex_generic_mle_t.py
- statsmodels/examples/ex_generic_mle_tdist.py
- statsmodels/genmod/families/family.py
- statsmodels/genmod/families/links.py
- statsmodels/genmod/generalized_linear_model.py
- statsmodels/imputation/ros.py
- statsmodels/miscmodels/count.py
- statsmodels/miscmodels/nonlinls.py
- statsmodels/miscmodels/tmodel.py
- statsmodels/nonparametric/_kernel_base.py
- statsmodels/nonparametric/kernel_density.py
- statsmodels/nonparametric/kernel_regression.py
- statsmodels/nonparametric/kernels.py
- statsmodels/regression/linear_model.py
- statsmodels/robust/norms.py
- statsmodels/stats/stattools.py
- statsmodels/tsa/statespace/tools.py
- statsmodels/tsa/vector_ar/svar_model.py
- statsmodels/tsa/vector_ar/var_model.py
Make sure escape characters are treated correctly
> DOC: Clean up escape characters

- .gitignore
- statsmodels/tsa/regime_switching/markov_switching.py
- statsmodels/tsa/statespace/dynamic_factor.py
- statsmodels/tsa/statespace/kalman_filter.py
- statsmodels/tsa/statespace/kalman_smoother.py
- statsmodels/tsa/statespace/mlemodel.py
- statsmodels/tsa/statespace/representation.py
- statsmodels/tsa/statespace/sarimax.py
- statsmodels/tsa/statespace/structural.py
- statsmodels/tsa/statespace/tests/test_dynamic_factor.py
- statsmodels/tsa/statespace/tests/test_mlemodel.py
- statsmodels/tsa/statespace/tests/test_prediction.py
- statsmodels/tsa/statespace/tests/test_sarimax.py
- statsmodels/tsa/statespace/tests/test_simulate.py
- statsmodels/tsa/statespace/tests/test_simulation_smoothing.py
- statsmodels/tsa/statespace/tests/test_smoothing.py
- statsmodels/tsa/statespace/tests/test_tools.py
- statsmodels/tsa/statespace/tools.py
- statsmodels/tsa/statespace/varmax.py
Just some basic cleanup tasks that have accrued over time. Most visible improvement is the suppression of irrelevant warnings that began in numpy 1.12.
> CLEAN: Clean up TSA (pep8, pyflakes, warnings)

- statsmodels/tsa/statespace/sarimax.py
Pull request #3405 was the general case fixing this bug when stationary initialization is handled through `self.ssm.initialize_stationary()`, but since SARIMAX does a manual stationary initialization (so that it can also accomodate non-stationary states, e.g. for differencing and for regression coefficients in the state vector), it was not fixed there.
(Practically the effects of this are pretty minor, but still obviously not good to be wrong :)
> BUG: SARIMAX initialization: ergodic mean with trend

- statsmodels/genmod/generalized_linear_model.py
- statsmodels/regression/_tools.py
- statsmodels/regression/linear_model.py
- statsmodels/regression/tests/test_tools.py
- statsmodels/robust/robust_linear_model.py
- statsmodels/stats/correlation_tools.py
- statsmodels/stats/multivariate_tools.py
- statsmodels/tools/tools.py
Implement minimal WLS that computes the bare minimum needed
for GLM and RLM model estimation.
closes #2287
> PERF: Implement a minimal WLS for use in iterative estimation

- .gitignore
- statsmodels/base/tests/test_transform.py
- statsmodels/base/transform.py
See #2925 for details. Older, and much more concise: #1309.
> BoxCox implementation and tests

- statsmodels/genmod/generalized_estimating_equations.py
> Fixing typo in GEE documentation

- statsmodels/regression/linear_model.py
- statsmodels/regression/tests/test_regression.py
> fit_regularized for WLS/GLS (closes #3559)

- statsmodels/stats/tests/test_weightstats.py
Make style changes only to adhere to pep8 style guide
> STY: Cleaned to conform to pep8

- statsmodels/sandbox/tsa/fftarma.py
- statsmodels/tsa/arima_model.py
- statsmodels/tsa/arima_process.py
- statsmodels/tsa/tests/test_arima_process.py
Clean and test arima process functions
> CLN/TST: Improve arima_process

- statsmodels/discrete/discrete_model.py
- statsmodels/discrete/tests/test_discrete.py
- statsmodels/iolib/summary2.py
fixes summary2 issue in #3651 
(I needed to get uncommitted changes out of the way)
> BUG: fix summary2 for MNLogit

- statsmodels/iolib/summary.py
- statsmodels/iolib/summary2.py
> Fix WLS Typo ("Weigthed" -> "Weighted")

- statsmodels/imputation/mice.py
Hello,
This closes #3754 (I think).
> MAINT/BUG: Closes #3754

- statsmodels/stats/tests/test_weightstats.py
- statsmodels/stats/weightstats.py
closes #3783
add missing atleast_1d
unit tests fail without and pass with change
> BUG: fix CompareMeans summary for 1-d arrays 

- docs/source/mixed_linear.rst
This documentation has not been updated since we added variance components.
> DOC Mixedlm

- docs/source/release/version0.9.rst
- statsmodels/regression/mixed_linear_model.py
- statsmodels/regression/tests/test_lme.py
> Missing data handling for mixedlm

- statsmodels/stats/contingency_tables.py
- statsmodels/stats/tests/test_contingency_tables.py
closes #3822 
wrong intervals were displayed in summary
> BUG: fix confidence interval in contingency table summary

- statsmodels/stats/anova.py
- statsmodels/stats/tests/test_anova_rm.py
If the data set contains more than one observation per subject and experimental condition, the current AnovaRM implementation will generate incorrect results.
This commit adds an extra aggregation step before performing the Anova and displays a warning. By default, the `np.mean` function will be used; but the user is free to specify a different function.
This functionality aims to resemble the behavior of the popular R package, afex, which features a `fun_aggregate` parameter. Quote from the [afex docs](https://cran.r-project.org/web/packages/afex/afex.pdf):
> fun_aggregate
> 
> The function for aggregating the data before running the ANOVA if
> there is more than one observation per individual and cell of the
> design. The default NULL issues a warning if aggregation is necessary
> and …
> BUG, ENH: Aggregate data set before performing RM-Anova if needed

- statsmodels/stats/multitest.py
NullDistribution description fix
> NullDistribution description fix

- statsmodels/api.py
- statsmodels/discrete/discrete_model.py
- statsmodels/discrete/tests/test_discrete.py
- statsmodels/discrete/tests/test_margins.py
this is currently just a rebase of #3832
> ENH: add NegativeBinomial-P rebased

- docs/Makefile
see #3875
this should avoid problems with latest sphinx in doc build
> MAINT: remove multiprocessing in doc build

- statsmodels/tsa/statespace/sarimax.py
> DOC: Typo in sarimax.py

- statsmodels/robust/tests/test_scale.py
- statsmodels/sandbox/examples/example_garch.py
- statsmodels/sandbox/examples/example_sysreg.py
- statsmodels/sandbox/examples/thirdparty/try_interchange.py
- statsmodels/sandbox/panel/sandwich_covariance.py
- statsmodels/sandbox/tests/test_formula.py
- statsmodels/sandbox/tests/test_pca.py
- statsmodels/sandbox/tsa/examples/ex_mle_garch.py
this is #3724 after rebase and resolving merge conflicts
> REF import cleanup 3724 rebased

- statsmodels/sandbox/nonparametric/densityorthopoly.py
fix python 3 compatibility and refactoring victim
just a fix when I was trying to run this the last time.
> BUG: densityorthopoly - fix bit rot

- statsmodels/base/tests/test_shrink_pickle.py
- statsmodels/discrete/discrete_model.py
#3678 interactively rebased with edit of changes
#2685 original bug report
#2686 unit test PR
`closes #2685, closes #2686, closes #3678`
> BUG fix pickling for discrete fit_regularized

- statsmodels/graphics/tsaplots.py
- statsmodels/tsa/stattools.py
Alter default value in plot_pacf to match documentation and pacf
closes #3827
> BUG: Correct default value in plot_pacf

- statsmodels/sandbox/regression/gmm.py
- statsmodels/sandbox/regression/tests/test_gmm.py
Remove model holding results for IV2SLS
closes #3849
> CLN: Remove circular reference

- tools/ci_docbuild.sh
Switch from nose to pytest for notebook test
> TST: Move docbuild test to pytest

- statsmodels/discrete/discrete_model.py
- statsmodels/discrete/tests/test_discrete.py
rebased version of #3735, squashed and slightly edited during merge conflict resolution
closes #3734, closes #3735
> BUG/REF Avoid changing model.df_model by results

- statsmodels/tsa/arima_model.py
- statsmodels/tsa/tests/test_arima.py
Bug fix: https://github.com/statsmodels/statsmodels/issues/3911
also : https://stackoverflow.com/questions/34005532/statsmodels-printing-summary-of-arma-fit-throws-error
> BUG Fix Arima summary()

- statsmodels/tsa/arima_model.py
- statsmodels/tsa/tests/test_arima.py
closes #2547 
I have made a new pull request as the older one (https://github.com/statsmodels/statsmodels/pull/4041) was a mess. Thank you for your understanding.
> BUG raise error for a not-implemented method

- statsmodels/genmod/families/family.py
- statsmodels/genmod/families/links.py
Clean up Notes sections in genmod
closes #3873
> DOC: Clean up Notes in genmod

- docs/source/glm.rst
- docs/source/regression.rst
- statsmodels/genmod/_prediction.py
- statsmodels/genmod/generalized_linear_model.py
- statsmodels/regression/_prediction.py
- statsmodels/regression/linear_model.py
Add PredictionResults to documentation
Import Results in parent class to all documentation from public mod
close #3753
> DOC: Add PredictionResults to documentation

- statsmodels/tsa/statespace/mlemodel.py
@ChadFulton The discussed fix for `MLEResults._get_robustcov_results`
> BUG: State space: Fix label cov_params_robust --> cov_params_robust_approx

- docs/source/release/version0.8.rst
- statsmodels/sandbox/stats/diagnostic.py
- statsmodels/stats/tests/test_diagnostic.py
Rebase of PR #3360 and small clean up
issue closes #3229
> Zveryansky iss3229

- statsmodels/iolib/summary2.py
- statsmodels/iolib/tests/test_summary2.py
> Natashawatkins add drop omitted summary2

- docs/source/graphics.rst
- docs/source/plots/graphics_functional_hdrboxplot.py
- statsmodels/graphics/api.py
- statsmodels/graphics/functional.py
- statsmodels/graphics/tests/test_functional.py
rebased and squashed version of #3876
> ENH: Add function HDR functional boxplot

- statsmodels/tsa/seasonal.py
- statsmodels/tsa/tests/test_seasonal.py
fixes https://github.com/statsmodels/statsmodels/issues/2820
closes https://github.com/statsmodels/statsmodels/pull/3684
Includes patch from https://github.com/statsmodels/statsmodels/pull/3684, with tests.
> ENH: 2-D tsa.seasonal_decompose with trend extrapolation

- statsmodels/graphics/functional.py
- statsmodels/stats/_lilliefors.py
- statsmodels/stats/diagnostic.py
Fix issue with kstest_normal so that it is included in docs
Fix issue with kstest_exponential so that it is included in docs
Fix typos and formatting in HDR box plot
closes #4086
> DOC: Fix recent documentaion issues

- statsmodels/datasets/tests/test_data.py
Remove yield which is pending deprecation in pytest
xref #4000
> TST: Remove yield from datasets tests

- statsmodels/nonparametric/tests/test_lowess.py
Remove pending deprecation yield tests from lowess
xref #4000
> TST: Remove yield from test_lowess

- statsmodels/duration/tests/test_phreg.py
Remove pending deprecation tests from phreg
xref #4000
> TST: Remove yield from test_phreg

- statsmodels/stats/multitest.py
Make shape of palues explicit
Clean multipletest doc string of small formatting errors
closes #3307
> DOC: Improve multipletest docstring

- examples/notebooks/wls.ipynb
Correct WLS example notebook so that teh correct weights are used
closes #3898
> DOC: Fix WLS example notebook

- statsmodels/tsa/vector_ar/tests/test_var_jmulti.py
- statsmodels/tsa/vector_ar/tests/test_vecm.py
Remove pending deprecation tests from vector ar tests
xref #4000
> TST: Remove yield tests from vector ar testing

- statsmodels/tools/sequences.py
- statsmodels/tools/tests/test_sequences.py
This is related to issue #4103 
It implements Halton sequence in a new module `statsmodels.tools.sequences`.
> ENH: add sequences module with Halton

- statsmodels/regression/tests/test_lme.py
This implements a small subset of #3847.
> remove yield tests from test_lme

- .travis.yml
- statsmodels/base/tests/test_shrink_pickle.py
- statsmodels/discrete/tests/test_discrete.py
- statsmodels/duration/survfunc.py
- statsmodels/nonparametric/tests/test_kernels.py
- statsmodels/stats/contrast.py
- statsmodels/stats/power.py
- statsmodels/stats/tests/test_pairwise.py
- statsmodels/stats/tests/test_tost.py
- statsmodels/tools/tools.py
- statsmodels/tsa/tests/test_arima.py
- statsmodels/tsa/tests/test_stattools.py
- statsmodels/tsa/vector_ar/tests/test_vecm.py
Clean up nans that are being passsed to NumPy and SciPy
Remove calls to print in tests
> CLN/TST: Remove nan issues with NumPy

- .travis.yml
Xdist now reports warnings and so can be enabled
> TST: Use xdist to speed up testing

- statsmodels/tsa/seasonal.py
- statsmodels/tsa/tests/test_seasonal.py
> BUG: seasonal_decompose, fix extrapolation with 1-D

- docs/source/graphics.rst
- docs/source/plots/graphics-mean_diff_plot.py
- statsmodels/graphics/agreement.py
- statsmodels/graphics/api.py
- statsmodels/graphics/tests/test_agreement.py
- statsmodels/graphics/tests/test_mean_diff_plot.py
this is a rebased version of #4112 with an import fix included
adds mean_diff_plot which is also know as bland-altman plot
> ENH: add bland altman tuckey mean-diff plot

- statsmodels/multivariate/factor.py
- statsmodels/multivariate/tests/test_ml_factor.py
This PR makes some changes to the linear algebra in the EM algorithm to avoid creating any `p x p` intermediate values (where `p` is the number of covariates).  Everything is either `p x k` or `k x k`, where `k` is the number of factors.
A few tests for EM are also added.
> ENH: Improvements to factor analysis (EM algorithm)

- statsmodels/stats/stattools.py
- statsmodels/stats/tests/test_statstools.py
Ensure input is double in medcouple
> BUG: Check dtype for medcouple

- .gitignore
These folders bug me... can we add them to `.gitignore`?
> Add pytest folders to .gitignore

- statsmodels/base/model.py
This is almost exclusively whitespace fixups.
I've reached a point where I need to make a bugfix fork for work, but very much want to make it easy to upstream any fixes that are made.  That process will be _much easier_ if code quality improvements like this are upstreamed in real-time.
> flake8 fixups in model.py

- statsmodels/datasets/template_data.py
- statsmodels/discrete/tests/test_discrete.py
- statsmodels/regression/tests/test_lme.py
- statsmodels/stats/tests/test_diagnostic.py
- statsmodels/tsa/tests/results/results_arma.py
- statsmodels/tsa/tests/test_arima.py
- statsmodels/tsa/vector_ar/tests/test_coint.py
@josef-pkt unlike other outstanding PRs, this one fixes a resource leak.
> REF: Fix unclosed files

- statsmodels/stats/anova.py
This prevents the scipy runtime warnings when calling anova_lm
> BUG: Prevent warnings from scipy.stats

- statsmodels/sandbox/stats/multicomp.py
- statsmodels/stats/tests/test_pairwise.py
just a unit test for now, this should fail on recent numpy
#3584 bug
#4290 fix
> TST/MAINT: tukeyhsd plot_simultaneous numpy compat

- docs/source/release/version0.9.rst
- statsmodels/imputation/mice.py
- statsmodels/imputation/tests/test_mice.py
This is relatively straightforward.  The first commit contains the substantive changes, second commit is pep8 fixes.
> ENH: Allow MICE to work with regularized fitting

- statsmodels/discrete/discrete_model.py
@ChadFulton this is the next step in the algebra simplication.  _should_ avoid overlaps/merge-conflicts with #4378.  Once both of these are in the following round will have a nice payoff.
> Easy substitutions in discrete_model

- statsmodels/graphics/boxplots.py
- statsmodels/graphics/tests/test_boxplots.py
rebase version of #3213
squashed and removed code comments during interactive rebase.
this adds bw_factor for gaussian_kde in violin plot.
It uses the existing `plot_opts`. It might be better to add it as main keyword argument, but I didn't change it.
closes #3213
> ENH: add bandwidth option to violinplot in boxplots

- docs/source/plots/graphics_plot_fit_ex.py
- docs/source/plots/hpf_plot.py
- docs/source/plots/var_plots.py
Use copies to avoid pandas noise
Fix ufunc error when constructing string dates
> DOC/CLN: Reduce doc build noise

- statsmodels/tsa/statespace/structural.py
See comments on #4250.
Will merge this tonight unless I hear from @Noobivsho.
> DOC: Minor fixes for frequency domain seasonal components docstring.

- statsmodels/genmod/bayes_mixed_glm.py
- statsmodels/genmod/tests/test_bayes_mixed_glm.py
Miscellaneous enhancements to BayesMixedLM, hope to get in to 0.9 but not essential.
The main thing here is to use the base classes for data processing.
> ENH: refactor BayesMixedLM to use base model data handling

- examples/notebooks/kernel_density.ipynb
adds more content to kde notebook
squashed and rebased version of #4207 with minor edit, typo and adding alpha to hist.
only includes the commits related to kernel density
The first 3 commits are for a typo fix in a statespace notebook (and broke rebase with "could not apply" commit), and are not included here.
closes #4207
> DOC Updated notebook on kernel density

- docs/source/release/version0.9.rst
I can expand on these if we prefer more verbose notes.
> DOC: 0.9 release notes for refactored state space models / tsa indexes / exponential smoothing

- docs/source/release/version0.9.rst
mostly complete
maybe a few more descriptions should be added
I didn't check rst formatting
> DOC: update release notes for 0.9  

- docs/source/release/version0.9.rst
- setup.py
small encoding fix in release notes, and
change version to 0.9 release
> REL/Maint: Release 09

- setup.py
> REL/MAINT add `rc' to version

- README.rst
- docs/source/release/index.rst
- setup.py
this should be the last merge before 0.9rc1 release, unless I forgot something else and I get a reminder.
this updated information in setup.py and README.rst will be on pypi
> MAINT: update setup.py and README.rst

- docs/source/release/version0.9.rst
- statsmodels/discrete/tests/test_sandwich_cov.py
- statsmodels/genmod/generalized_linear_model.py
- statsmodels/genmod/tests/test_constrained.py
- statsmodels/genmod/tests/test_glm.py
fix bugs in GLM score and hessian
first commit are only unit tests to see the results with current code
bugfixes will follow
closes #4616 closes #4614
> BUG: GLM score and hessian

- statsmodels/genmod/generalized_linear_model.py
> Use wls_method for irls, reverts 78dcce2

- README.rst
Remove spaces causing quited text
[skip ci]
> DOC: Reformat README

- statsmodels/genmod/generalized_linear_model.py
- statsmodels/genmod/tests/test_glm.py
> PERF: Use np.dot in GLM.score

- docs/source/release/version0.9.rst
one new contributor, 
line breaks
> DOC: update release notes 

- statsmodels/regression/mixed_linear_model.py
- statsmodels/regression/tests/test_lme.py
> TEST/DOC: SMW linalg routines documentation and test

- statsmodels/stats/anova.py
trying to fixes pandas 0.23 compatibility by avoiding dict to create data frame.
> REF/MAINT: avoid dict with pandas

- statsmodels/imputation/bayes_mi.py
This bug does not produce incorrect results, but does lead to testing errors.
#4645
> BUG/TEST: Make pattern order for multiple imputation deterministic

- statsmodels/tsa/adfvalues.py
> fix syntax-like error

- statsmodels/base/tests/test_generic_methods.py
- statsmodels/compat/scipy.py
- statsmodels/distributions/edgeworth.py
- statsmodels/distributions/tests/test_edgeworth.py
- statsmodels/graphics/functional.py
- statsmodels/miscmodels/count.py
- statsmodels/miscmodels/tests/test_poisson.py
- statsmodels/sandbox/nonparametric/densityorthopoly.py
- statsmodels/sandbox/nonparametric/kernels.py
- statsmodels/sandbox/regression/tests/test_gmm.py
- statsmodels/stats/tests/test_diagnostic.py
- statsmodels/tsa/statespace/tests/test_pickle.py
- statsmodels/tsa/tests/test_arima.py
Here's a more comprehensive PR that attempts to fix/deal with/cheat our way through the unittests that are failing. #4643 is still likely to fail as I have no clue. A few others might be problematic... I'm still testing.
> TST: Openblas appveyor fixes

- statsmodels/genmod/bayes_mixed_glm.py
- statsmodels/genmod/tests/test_bayes_mixed_glm.py
> BUG: Add missing predict and fit methods to BayesMixedGLM

- statsmodels/tools/sm_exceptions.py
> BUG: add ModelWarning base class to avoid warning filter on standard UserWarning. 

- statsmodels/stats/correlation_tools.py
- statsmodels/stats/tests/test_correlation.py
This implements a simple method of moments estimator of a spatial covariance function for multivariate data, using the approach discussed on page 7 of this paper:
Genton M, W Kleiber (2015).  Cross covariance functions for multivariate geostatics.  Statistical Science 30(2). https://arxiv.org/pdf/1507.08017.pdf
> ENH Kernel covariance 

- statsmodels/base/tests/test_data.py
> catch the correct exception, make assertions not-pointless

- statsmodels/sandbox/archive/linalg_decomp_1.py
This is the subset of #4526 that is _literally_ copy/pasted code.  @ChadFulton
> replace copy/pasted code with import

- statsmodels/tsa/vector_ar/vecm.py
Having to look these up just adds another layer for the reader to sort through.
> Get rid of non-standard imports and one-line functions

- .travis.yml
- statsmodels/tsa/statespace/tests/test_dynamic_factor.py
trying to fix conda problems with numpy-base
see #4776
> MAINT: conda specify numpy-base

- statsmodels/genmod/bayes_mixed_glm.py
- statsmodels/genmod/tests/test_bayes_mixed_glm.py
This PR fixes a few bugs relating to post-fit results in BayesMixedGLM:
* Ensure that column names are properly attached to the model
* Change `cov_params` to act more like it does in other models
> BUG: bayes mixed GLM maintenance

- statsmodels/genmod/bayes_mixed_glm.py
- statsmodels/genmod/tests/test_bayes_mixed_glm.py
This PR fixes a bug identified by @TheChymera in the Poisson version of BayesMixedLM.
> BUG: fix arguments in poisson mixed model

- .travis.yml
- lint.sh
- setup.cfg
- statsmodels/examples/ex_predict_results.py
- statsmodels/examples/try_fit_constrained.py
- tools/code_maintenance.py
- tools/examples_rst.py
- tools/generate_formula_api.py
- tools/migrate_issues_gh.py
Fixes the couple of py3-incompatible print statements, leaves unfixed the hundred+ lurking NameErrors discussed in #4768.
@ChadFulton please.  This shouldn't be like pulling teeth here.
> Implement basic linting for Travis

- lint.sh
- statsmodels/tsa/regime_switching/markov_switching.py
- statsmodels/tsa/regime_switching/tests/test_markov_autoregression.py
- statsmodels/tsa/regime_switching/tests/test_markov_regression.py
- statsmodels/tsa/regime_switching/tests/test_markov_switching.py
@ChadFulton this one was a breeze.  Only thing that could use your attention in a follow-up is an `except Exception:` that should probably be more specific.
> CLN: Fully lint regime_switching

- statsmodels/tsa/stattools.py
- statsmodels/tsa/tests/test_stattools.py
Correct documentation
Add minimal test
closes #2700
> CLN: Fix documentation for Levinson-Durbin

- lint.sh
- statsmodels/compat/python.py
- statsmodels/regression/recursive_ls.py
@ChadFulton I'm pretty sure this file is in your domain.
> CLN: Fully lint recursive_ls.py

- statsmodels/tools/sm_exceptions.py
- statsmodels/tsa/tests/test_stattools.py
Fix typo in warning name
closes #4671
> REF: Rename ColinearityWarning

- appveyor.yml
> BLD: Add pinned numpy on appveyor

- .travis.yml
- appveyor.yml
- statsmodels/compat/python.py
- statsmodels/tools/tests/test_grouputils.py
Slightly relax tolderance on failing test
> TST: Relax tolerance on failing test

- statsmodels/tsa/stattools.py
- statsmodels/tsa/tests/test_stattools.py
Add call to asarray to ensure data is a numpy array
closes #4727
> BUG: Add check to ensure array in arma order selection

- setup.cfg
- statsmodels/imputation/tests/test_mice.py
- statsmodels/iolib/tests/test_table.py
- statsmodels/sandbox/distributions/estimators.py
- statsmodels/sandbox/regression/anova_nistcertified.py
- statsmodels/sandbox/stats/multicomp.py
- statsmodels/sandbox/tests/test_formula.py
- statsmodels/stats/descriptivestats.py
- statsmodels/stats/power.py
Enfore 1 blank line before a nested function
> CLN: Enforce E306, blank lines in nested funcs

- statsmodels/genmod/generalized_estimating_equations.py
- statsmodels/stats/_knockoff.py
- statsmodels/stats/knockoff_regeffects.py
- statsmodels/stats/tests/test_knockoff.py
Bugs:
* Forgot to combine the real and knockoff features in init
* Modifying exog in-place leads to incorrect scaling
New tests
Enhancements
* Summary method
* Provide Knockoff+ (guaranteed to control FDR but slightly conservative) as well as Knockoff FDR
* New RegModelEffects allows the user to specify which model is used for parameter estimation
> BUG/ENH: Two bug fixes and several enhancements to knockoff filter (regression fdr)

- statsmodels/discrete/discrete_model.py
- statsmodels/sandbox/regression/penalized.py
- statsmodels/sandbox/stats/contrast_tools.py
> [MAINT] Fix typo Paramters-->Parameters

- docs/Makefile
- docs/make.bat
- docs/source/statespace.rst
- docs/source/tsa.rst
- docs/source/vector_ar.rst
Clean up TSA docs a bit
Add VECM
Update make.bat and Makefile to latest Sphinx standards
> DOC: Clean up tsa docs

- lint.sh
- statsmodels/tools/linalg.py
- statsmodels/tools/tests/test_linalg.py
Both the module and the test file are added to the fully-lint list.
> [TST] make tools.linalg __main__ section into tests

- statsmodels/sandbox/stats/diagnostic.py
- statsmodels/tsa/statespace/tests/test_tools.py
- statsmodels/tsa/stattools.py
- statsmodels/tsa/tests/test_stattools.py
- statsmodels/tsa/tests/test_tsa_tools.py
Add argument to limit computation and output
Propose settig fft=True in future version
closes #4135
> ENH: Add nlag argument to acovf

- .travis.yml
- docs/source/contingency_tables.rst
- docs/source/datasets/index.rst
- docs/source/discretemod.rst
- docs/source/glm.rst
- docs/source/missing.rst
- docs/source/plots/graphics_functional_fboxplot.py
- docs/source/plots/graphics_functional_hdrboxplot.py
- docs/source/plots/graphics_functional_rainbowplot.py
- docs/source/plots/graphics_gofplots_qqplot.py
- docs/source/regression.rst
- docs/source/rlm.rst
- docs/source/tsastats.rst.TXT
- examples/notebooks/regression_diagnostics.ipynb
- statsmodels/datasets/utils.py
- tools/ci/docbuild_install.sh
There are a few warnings in the docs. First, the Guerry dataset needs a `master` in the http string. Next, we added a warning to say that we are going to generally change `dataset.load()` to return a DataFrame, so I silenced as many as I could.
> MAINT: silenced as_pandas warnings in documentation

- statsmodels/sandbox/distributions/copula.py
resurrecting copulas see #4046
the first commit is from 2011 and was never included in the statsmodels.sandbox version
> ENH: more work on copula (deriv, classes)

- lint.sh
- statsmodels/tsa/statespace/tests/test_var.py
> MAINT: strict lint test_var.py

- statsmodels/regression/linear_model.py
- statsmodels/regression/tests/test_regression.py
- statsmodels/tsa/stattools.py
- statsmodels/tsa/tests/test_stattools.py
Add Burg's algorithm as an alternative to Yule-Walker for PACF, AR, and ACF estimation.
> ENH: Burgs algorithm

- lint.sh
- statsmodels/tsa/statespace/_pykalman_smoother.py
- statsmodels/tsa/statespace/api.py
- statsmodels/tsa/statespace/initialization.py
- statsmodels/tsa/statespace/kalman_filter.py
- statsmodels/tsa/statespace/mlemodel.py
- statsmodels/tsa/statespace/representation.py
- statsmodels/tsa/statespace/sarimax.py
- statsmodels/tsa/statespace/structural.py
- statsmodels/tsa/statespace/tools.py
- statsmodels/tsa/statespace/varmax.py
@ChadFulton The statespace files themselves are in pretty good shape, there are are a couple of points I'll comment on inline where your input will be needed in a follow-up.
After this `statespace/tests/results/*.py` will be an easy PR, then the test files will be split into a few steps because they're in less-good condition than the rest.
> CLN: Flake8 fixups and linting for statespace files (but not tests)

- statsmodels/sandbox/distributions/copula.py
> FIX failure caused by #5076

- setup.cfg
- statsmodels/base/_penalties.py
- statsmodels/graphics/factorplots.py
- statsmodels/iolib/tests/test_summary.py
- statsmodels/iolib/tests/test_summary_old.py
- statsmodels/sandbox/distributions/copula.py
- statsmodels/stats/tests/test_diagnostic_other.py
Remove multiple spaces before keyword
> CLN: Enforce E272, multiple spaces

- statsmodels/tsa/x13.py
> MAINT: clean up x13.py, delete main

- statsmodels/tsa/statespace/tests/test_simulation_smoothing.py
- statsmodels/tsa/statespace/tests/test_smoothing.py
- statsmodels/tsa/statespace/tests/test_structural.py
- statsmodels/tsa/statespace/tests/test_tools.py
@ChadFulton doing a few files instead of one at a time.
> MAINT: linting statespace tests

- tools/check_dirs.py
- tools/code_maintenance.py
- tools/hash_funcs.py
- tools/nbgenerate.py
- tools/notebook_output_template.py
- tools/update_web.py
Only usage of `upload_pdf` is commented out, but includes a `new_branch_dir` arg, which is missing from the actual signature of `upload_pdf`.  But `new_branch_dir` is needed in the function, and would raise `NameError` if hit.  So this fixes the signature.
And fixes up a bunch of other unused stuff.
> BUG: fix missing new_branch_dir arg in upload_pdf

- statsmodels/formula/api.py
Removes unused classes from the smf namespace, closes #4947 and #833.
> Clean up the smf namespace 

- docs/themes/statsmodels/layout.html
- docs/themes/statsmodels/static/nature.css_t
This is just some (not so) fancy javascript/sphinx/css that will add a dropdown so you can select older versions of the docs... Requires a file I called `versions.json` which is a json array of all the folders you want to add links to. 
See my gh-pages branch here:
https://thequackdaddy.github.io/statsmodels.github.io/devel/dev/index.html
https://github.com/thequackdaddy/statsmodels.github.io
> DOC: Add javascript to link to other doc versions

- appveyor.yml
- statsmodels/__init__.py
- statsmodels/tsa/statespace/tests/test_save.py
- tools/ci/run_test.bat
Ensure that the internal tester errors when an internal error was encountered
> BUG: Ensure internal tester exits with error if needed

- statsmodels/nonparametric/kernel_density.py
- statsmodels/nonparametric/kernel_regression.py
- statsmodels/robust/robust_linear_model.py
- statsmodels/robust/scale.py
Do not use mutable default values
> BUG: Don't use mutable default values

- statsmodels/regression/tests/test_theil.py
see #5148 
TestTheilPanel didn't specify random seed and breaks if not the entire module is run in sequence.
defining seed requires redoing regression test numbers
> TST: Theil test randomseed

- statsmodels/regression/linear_model.py
- statsmodels/regression/tests/test_regression.py
Fix definitin of GLS r2 for equivalence with WLS
closes #1252
closes #1171
> BUG: Fix definition of GLS r2

- statsmodels/nonparametric/kernel_regression.py
- statsmodels/nonparametric/tests/test_kernel_regression.py
Check inputs in KernelReg more carefully
closes #4873
> BUG: Check inputs in KernelReg

- statsmodels/tsa/arima_model.py
Replace the recursive cumsum_n function with an iterative function for readability.
> REF: Use iterative cumsum_n

- statsmodels/genmod/generalized_estimating_equations.py
> DOC: Fix section title in QIC

- statsmodels/tsa/tests/test_arima.py
Set seed so that results are identical across runs
See 
https://travis-ci.org/bashtage/statsmodels/jobs/427055102
>  TST: Fix random generation issue

- statsmodels/stats/correlation_tools.py
- statsmodels/stats/tests/test_corrpsd.py
Fix test that wasn't testing anything
Pass tuning parameters into optimization function
Increase max iterations
xref #5197
> TST/CLN/BUG: Fix corr nearest factor

- statsmodels/tsa/tests/test_arima.py
Rescale exog and endog to make parameters of similar orders of magnitude
xref #5197
> TST/CLN: Rescale data to avoid convergence issues

- statsmodels/graphics/tests/test_dotplot.py
- statsmodels/stats/libqsturng/tests/test_qsturng.py
- statsmodels/stats/tests/test_contrast.py
- statsmodels/stats/tests/test_corrpsd.py
- statsmodels/stats/tests/test_diagnostic.py
- statsmodels/stats/tests/test_nonparametric.py
- statsmodels/stats/tests/test_statstools.py
Add more random state resets to improve predictability
> TST: Ensure random numbers are reproducible

- statsmodels/tsa/holtwinters.py
Doc string improvements and formatting
[skip ci]
> DOC: Improve Holt Winters documentation

- statsmodels/graphics/functional.py
- statsmodels/multivariate/pca.py
- statsmodels/nonparametric/_kernel_base.py
- statsmodels/nonparametric/kernel_regression.py
Refactor PCA and Kernel methods to avoid instance methods
Remove buggy pickling method change in functional graphics
closes #4772
> BUG: Remove change of global pickle method

- statsmodels/base/model.py
- statsmodels/iolib/summary.py
- statsmodels/miscmodels/tests/test_generic_mle.py
this is a rebased version of #4676
> ENH/BUG Bootstrap clone rebased

- statsmodels/base/tests/test_generic_methods.py
- statsmodels/base/tests/test_predict.py
- statsmodels/compat/pandas.py
- statsmodels/stats/tests/test_influence.py
- statsmodels/tools/testing.py
- statsmodels/tsa/stattools.py
- statsmodels/tsa/tests/test_stattools.py
Add innovations algorithm to convert acov to MA
Add filter to filter innovations usign output of ia
> ENH: Add innovations algorithm

- lint.sh
- statsmodels/tools/web.py
> BUG: raise instead of return ValueError

- statsmodels/discrete/tests/test_count_model.py
- statsmodels/distributions/tests/test_discrete.py
- statsmodels/examples/es_misc_poisson2.py
- statsmodels/examples/ex_inter_rater.py
- statsmodels/regression/tests/test_glsar_gretl.py
- statsmodels/regression/tests/test_recursive_ls.py
- statsmodels/regression/tests/test_regression.py
- statsmodels/sandbox/datarich/factormodels.py
- statsmodels/sandbox/examples/example_pca_regression.py
- statsmodels/sandbox/nonparametric/tests/ex_smoothers.py
- statsmodels/sandbox/regression/tests/test_gmm.py
- statsmodels/sandbox/tsa/examples/ex_mle_arma.py
- statsmodels/sandbox/tsa/examples/ex_mle_garch.py
- statsmodels/sandbox/tsa/try_fi.py
- statsmodels/sandbox/tsa/varma.py
- statsmodels/stats/libqsturng/tests/test_qsturng.py
- statsmodels/stats/tests/test_diagnostic.py
- statsmodels/tsa/base/tests/test_tsa_indexes.py
- statsmodels/tsa/statespace/tests/test_dynamic_factor.py
- statsmodels/tsa/statespace/tests/test_impulse_responses.py
- statsmodels/tsa/statespace/tests/test_initialization.py
- statsmodels/tsa/statespace/tests/test_models.py
- statsmodels/tsa/statespace/tests/test_simulate.py
- statsmodels/tsa/statespace/tests/test_varmax.py
- statsmodels/tsa/tests/test_bds.py
remove unused imports
Replaces #5175.
> TST: Change assert_approx_equal to assert_allclose

- examples/python/robust_models_1.py
- statsmodels/compat/pandas.py
- statsmodels/graphics/tests/test_mosaicplot.py
- statsmodels/imputation/ros.py
- statsmodels/sandbox/multilinear.py
- statsmodels/tsa/base/tsa_model.py
> MAINT: Remove outdated pandas compat shims

- .travis.yml
- tools/ci/docbuild.sh
- tools/ci/docbuild_install.sh
Increase depth to ensure tag is in history
Simplify dependency install and remove echo flag
Ensure docs are not pushed to stable on dev tags
Build on tags
Install tzlocal for rpy2
> DOC: Fix small doc build errors

- .travis.yml
- appveyor.yml
Add the ability to manually skip each platform using the syntax below anywhere in the commit message
[skip appveyor]
[appveyor skip]
[skip travis]
[travis skip]
> BLD: Add platform-specific skips

- statsmodels/stats/anova.py
Docstring improvement for anova that clarifies the dataframes returned
rebased and squashed version of #5233
> DOC: Added documentation of elements in anova_lm

- statsmodels/tsa/statespace/structural.py
Very minor, will merge immediately.
> DOC: Use correct “autoregressive” in docstring

- .travis.yml
- statsmodels/base/wrapper.py
- statsmodels/compat/python.py
- statsmodels/graphics/factorplots.py
- statsmodels/sandbox/archive/linalg_decomp_1.py
- statsmodels/tools/decorators.py
Prefer modern method to get signature over deprecated method
> MAINT: Prefer signature over formatargspec

- statsmodels/genmod/tests/test_gee.py
Closes #5289 
Added random seed to statsmodels.genmod.tests.test_gee.TestGEE and verified the seeds all produce examples that reconcile as expected.
> TST: Added random seed to test_gee and verifed working

- statsmodels/genmod/bayes_mixed_glm.py
> Fix incorrect parameter name in docstring

- tools/ci/docbuild_install.sh
This is a workaround that will get docbuilds working again. Not sure if we want to merge or wait.
> DOC: Workarounds to fix docbuild

- lint.sh
- statsmodels/regression/tests/test_lme.py
@kshedden your domain
Relevant to #4396 since failing cases will all be displayed in test output.
> TST: parametrize tests in test_lme

- statsmodels/tsa/statespace/tools.py
> DOC: Revert incorrect docstring change [skip ci]

- statsmodels/tsa/statespace/mlemodel.py
> MAINT: remove self.table pinning

- statsmodels/stats/libqsturng/qsturng_.py
closes #5336 
@thequackdaddy @ChadFulton easy fix is easy.
> BUG: raise correct error

- statsmodels/tsa/vector_ar/tests/JMulTi_results/parse_jmulti_var_output.py
- statsmodels/tsa/vector_ar/tests/JMulTi_results/parse_jmulti_vecm_output.py
- statsmodels/tsa/vector_ar/util.py
- statsmodels/tsa/vector_ar/var_model.py
- statsmodels/tsa/vector_ar/vecm.py
There are a bunch more outside vector_ar, but no point doing it now since this is likely to be ignored for weeks on end.
Ref #5335.
> CLN: W605 fixups in vector_ar

- statsmodels/genmod/generalized_linear_model.py
- statsmodels/graphics/correlation.py
- statsmodels/iolib/table.py
- statsmodels/multivariate/factor_rotation/_gpa_rotation.py
- statsmodels/regression/mixed_linear_model.py
> CLN: Fix some invalid escapes

- CONTRIBUTING.rst
- It addresses issue #5447 
- Added instruction for both Linux and MacOS
> ENH/DOC: Added linting instruction in CONTRIBUTING.rst

- docs/source/gam.rst
- docs/source/glm.rst
- docs/source/tsa.rst
- statsmodels/gam/generalized_additive_model.py
- statsmodels/genmod/families/varfuncs.py
- statsmodels/stats/anova.py
fix path and wording in gam.rst
> DOC: fix gam.rst

- lint.sh
- statsmodels/compat/pandas.py
- statsmodels/gam/api.py
- statsmodels/gam/gam_cross_validation/gam_cross_validation.py
- statsmodels/gam/gam_penalties.py
- statsmodels/gam/generalized_additive_model.py
- statsmodels/gam/smooth_basis.py
- statsmodels/gam/tests/test_gam.py
- statsmodels/gam/tests/test_penalized.py
- statsmodels/regression/tests/test_regression.py
- statsmodels/tsa/base/tsa_model.py
- statsmodels/tsa/statespace/tests/test_pickle.py
- statsmodels/tsa/vector_ar/util.py
A little WIP here... some of this will fail. There's also some PEP8 issues I haven't thought fully through yet.
> MAINT: Travis fixes

- statsmodels/datasets/anes96/data.py
- statsmodels/datasets/spector/data.py
Just two minor tweaks to get rid of:
```
invalid escape sequence \s
```
> BUG: Bad escapes

- statsmodels/regression/mixed_linear_model.py
- statsmodels/regression/tests/test_lme.py
- statsmodels/stats/tests/test_mediation.py
This PR allows mediation to be used with MixedLM as a mediator and/or outcome model.
> ENH: Mediation for Mixedlm

- statsmodels/discrete/conditional_models.py
- statsmodels/discrete/tests/test_conditional.py
Equivalent to femlogit in Stata
> ENH Conditional multinomial logit

- statsmodels/genmod/generalized_estimating_equations.py
- statsmodels/genmod/tests/test_gee.py
Largely follows this reference:
http://users.stat.umn.edu/~wangx346/research/GEE_selection.pdf
> ENH: regularized GEE

- statsmodels/regression/linear_model.py
- statsmodels/regression/tests/test_regression.py
Another variation on the Lasso, doesn't require much tuning.
> ENH square root lasso

- examples/notebooks/recursive_ls.ipynb
construct and fir the model->construct and fit the model
> Correct a spell mistake

- docs/source/dev/maintainer_notes.rst
Update release instructions for versioneer
> DOC: Update release instructions [skip ci]

- docs/source/conf.py
- docs/source/discretemod.rst
- docs/source/vector_ar.rst
- statsmodels/gam/generalized_additive_model.py
- statsmodels/genmod/bayes_mixed_glm.py
- statsmodels/stats/contingency_tables.py
- statsmodels/tsa/holtwinters.py
- statsmodels/tsa/statespace/kalman_filter.py
- statsmodels/tsa/statespace/mlemodel.py
Fix issue with contextmanager appearing in docs
Remove double indexing for many entries due to
Attributes and cache_readonly interaction
Add a new required docbuild package to fix the contextmanager
and monkey patch in docbuild
Fix broken dataset names
> DOC: Fix nagging issues in docs

- lint.sh
Only run unshallow when required, which is usually on master
> BLD: Only unshallow when required

- docs/source/tsa.rst
- statsmodels/compat/numpy.py
- statsmodels/gam/generalized_additive_model.py
- statsmodels/tsa/stattools.py
- statsmodels/tsa/tests/test_stattools.py
Rebase #3862 and change to enhancement
Clean up docs for pacf functions
Add option to use through pacf()
> ENH: Add additional options for pacf ols

- examples/notebooks/exponential_smoothing.ipynb
- setup.py
- statsmodels/nonparametric/linbin.pyx
- statsmodels/tsa/kalmanf/kalman_loglike.pyx
Set language level to 3 since strings are not relevant
Fix pandas issue in notebook
> MAINT: Set language level for Cython

- statsmodels/regression/tests/test_regression.py
- statsmodels/tsa/base/datetools.py
- statsmodels/tsa/base/tests/test_base.py
- statsmodels/tsa/base/tests/test_tsa_indexes.py
- statsmodels/tsa/base/tsa_model.py
- statsmodels/tsa/filters/tests/test_filters.py
- statsmodels/tsa/holtwinters.py
- statsmodels/tsa/innovations/arma_innovations.py
- statsmodels/tsa/seasonal.py
- statsmodels/tsa/statespace/simulation_smoother.py
- statsmodels/tsa/statespace/tests/test_exact_diffuse_filtering.py
- statsmodels/tsa/statespace/tests/test_simulate.py
- statsmodels/tsa/statespace/tools.py
- statsmodels/tsa/tests/test_ar.py
- statsmodels/tsa/tests/test_arima.py
- statsmodels/tsa/tests/test_seasonal.py
- statsmodels/tsa/tests/test_stattools.py
- statsmodels/tsa/tests/test_x13.py
- statsmodels/tsa/vector_ar/tests/example_svar.py
- statsmodels/tsa/vector_ar/tests/test_var.py
- statsmodels/tsa/vector_ar/util.py
- statsmodels/tsa/vector_ar/var_model.py
Remove date and period-related issues
Escape strings
> MAINT: Remov deprecation issues

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/PULL_REQUEST_TEMPLATE.md
Add templates to improve PRs and issue reporting
[skip ci]
> DOC: Add issue and pr templates

- docs/source/contingency_tables.rst
> DOC: Updated the `for all i, j`

- statsmodels/compat/python.py
- statsmodels/discrete/discrete_margins.py
- statsmodels/robust/scale.py
- statsmodels/sandbox/distributions/gof_new.py
- statsmodels/sandbox/formula.py
- statsmodels/sandbox/nonparametric/kernels.py
- statsmodels/tsa/base/datetools.py
> MAINT: remove never-needed callable and never-used compat functions

- statsmodels/compat/numpy.py
- statsmodels/compat/pandas.py
- statsmodels/genmod/tests/results/results_glm.py
- statsmodels/graphics/tests/test_mosaicplot.py
- statsmodels/graphics/tests/test_tsaplots.py
- statsmodels/imputation/tests/test_ros.py
- statsmodels/multivariate/tests/test_factor.py
- statsmodels/stats/mediation.py
- statsmodels/stats/tests/test_power.py
- statsmodels/tsa/vector_ar/tests/test_dynamic.py
> Jbrockmendel pversion

- statsmodels/stats/libqsturng/tests/test_qsturng.py
Use a randomstate to ensure that the test is identical in all runs
Avoids random failures on travis
> TST: Ensure test is identical in all runs

- statsmodels/compat/__init__.py
Remove compat imports not used
> MAINT: Remove unavailable imports

- statsmodels/tsa/statespace/mlemodel.py
- statsmodels/tsa/stattools.py
Reference artical
Remove emphasis characters
> DOC: More emphasis and fix reference

- lint.sh
- statsmodels/formula/__init__.py
- statsmodels/formula/formulatools.py
- statsmodels/formula/tests/test_formula.py
> MAINT: fully lint formula

- .github/ISSUE_TEMPLATE/bug_report.md
> MAINT: Update template to encourage master check

- statsmodels/stats/proportion.py
> Guofei9987 modify comments proportion confint

- statsmodels/base/tests/test_generic_methods.py
- statsmodels/nonparametric/tests/test_kernel_regression.py
- statsmodels/tools/_testing.py
grepped for "FIXME" and started in on a couple of em.  The nonparametric one is an oddball, the others make for some nice de-duplication.
> TST: improve testing util functions; de-duplicate

- lint.sh
- statsmodels/compat/__init__.py
- statsmodels/compat/python.py
- statsmodels/compat/scipy.py
- statsmodels/compat/tests/test_itercompat.py
Broken off from #5181 (should be it for the time being)
> MAINT: fully lint compat

- docs/source/graphics.rst
- docs/source/plots/graphics_correlation_plot_corr.py
- docs/source/plots/graphics_correlation_plot_corr_grid.py
- docs/source/plots/graphics_gofplots_qqplot_2samples.py
- docs/source/plots/graphics_gofplots_qqplot_qqline.py
- docs/source/plots/graphics_mosaicplot_mosaic.py
- docs/source/plots/graphics_plot_grids_scatter_ellipse.py
- docs/source/plots/graphics_regression_abline.py
- docs/source/plots/graphics_regression_ccpr.py
- docs/source/plots/graphics_regression_ccpr_grid.py
- docs/source/plots/graphics_regression_ceres_residuals.py
- docs/source/plots/graphics_regression_influence.py
- docs/source/plots/graphics_regression_leverage_resid2.py
- docs/source/plots/graphics_regression_partregress.py
- docs/source/plots/graphics_regression_partregress_grid.py
- docs/source/plots/graphics_regression_regress_exog.py
- docs/source/plots/graphics_tsa_month_plot.py
- docs/source/plots/graphics_tsa_plot_acf.py
- docs/source/plots/graphics_tsa_plot_pacf.py
- docs/source/plots/graphics_tsa_quarter_plot.py
- statsmodels/graphics/_regressionplots_doc.py
- statsmodels/graphics/correlation.py
- statsmodels/graphics/gofplots.py
- statsmodels/graphics/mosaicplot.py
- statsmodels/graphics/plot_grids.py
- statsmodels/graphics/regressionplots.py
- statsmodels/graphics/tsaplots.py
> Jtweeder graphics addgraphics

- .github/PULL_REQUEST_TEMPLATE.md
> DOC: Improve PR template [skip ci]

- statsmodels/regression/mixed_linear_model.py
Try cg after bfgs and lbfgs fail
#5546
> ENH: extend mixedlm optimizer attempts

- statsmodels/base/tests/test_generic_methods.py
Also remove a bunch of unused imports in the affected file.
> [MAINT/Test] skip test instead of mangling name in test_generic_methods

- examples/notebooks/tsa_arma_0.ipynb
> DOC: Restore import

- statsmodels/genmod/generalized_linear_model.py
- statsmodels/regression/_tools.py
- statsmodels/regression/tests/test_tools.py
- statsmodels/robust/robust_linear_model.py
Add optional finite check for _MinimalWLS
closes #4566
> BUG: Add finite check for _MinimalWLS

- statsmodels/sandbox/stats/multicomp.py
- statsmodels/stats/multicomp.py
- statsmodels/stats/tests/test_multi.py
> Andrew d davis tukey pvals

- README.rst
> DOC: Update badges [skip ci]

- statsmodels/base/data.py
- statsmodels/base/tests/test_data.py
- statsmodels/iolib/tests/test_table.py
> Gabrielreid pandas multiindex handling bug

- .codecov.yml
Add a codecov config file to minimize false positives
> MAINT: Add a codecov config file

- lint.sh
- tools/backport_pr.py
- tools/code_maintenance.py
- tools/examples_rst.py
- tools/fold_toc.py
- tools/generate_formula_api.py
- tools/gh_api.py
- tools/github_stats.py
At some point we should figure out what parts of this directory are actually needed/used.
> CLN: strict linting for tools directory

- statsmodels/compat/platform.py
- statsmodels/multivariate/tests/test_pca.py
- statsmodels/tsa/statespace/tests/test_sarimax.py
Consolidate all platform checks in a single module
> MAINT: Consoliate platform checks

- statsmodels/tsa/vector_ar/svar_model.py
- statsmodels/tsa/vector_ar/tests/test_svar.py
> Josef pkt svar irf errband 5280

- lint.sh
> MAINT: Fix error in lint script

- lint.sh
- statsmodels/tools/sm_exceptions.py
> MAINT: Reformat exceptions

- azure-pipelines.yml
- tools/ci/azure_template.yml
> BLD: Add linting to azure

- statsmodels/tsa/statespace/varmax.py
Not adding a unit test for start params changes, since we don't really guarantee anything here.
> ENH/BUG: Use intercept form of trend / exog in VARMAX start params (not mean form)

- statsmodels/regression/tests/test_lme.py
> TST: change skip to xfail for test_compare_numdiff on OSX

- statsmodels/graphics/tests/test_functional.py
Protect against WindowsError when using a multiprocess Pool on Windows
which leads to permission denied errors
> TST: Protect multiprocess on windows

- statsmodels/genmod/generalized_linear_model.py
- statsmodels/sandbox/stats/multicomp.py
> MAINT: Remove unused code

- statsmodels/tsa/stattools.py
- statsmodels/tsa/tests/test_stattools.py
> Jim varanelli issue2781

- lint.sh
- statsmodels/stats/moment_helpers.py
- statsmodels/stats/tests/test_moment_helpers.py
Fix moment helpers so that they do not do inplace modification
Allow multidimensional input
closes #3362
closes #2928
> BUG: fix stats.moment_helpers inplace modification

- statsmodels/graphics/gofplots.py
- statsmodels/graphics/tests/test_gofplots.py
Allowpp and qq to use different size data sets
> ENH: Allow comparing two samples with different sizes

- lint.sh
- statsmodels/sandbox/panel/correlation_structures.py
See commit messages for details.
> MAINT: Fix NameErrors in correlation_structures

- examples/incomplete/arima.py
- examples/incomplete/arma2.py
- examples/incomplete/dates.py
- examples/incomplete/glsar.py
- examples/incomplete/ols_table.py
- examples/incomplete/ols_tftest.py
- examples/incomplete/wls_extended.py
- lint.sh
It's only the examples/unfinished directory that required any edits, everything else was already OK.
> CLN: strict linting for examples/

- .travis.yml
**Notes**:
So my bad push earlier had a couple bash errors I think that is going to prevent travis from running. Fixed them here.
> TST: Fix bad bash

- statsmodels/examples/ex_generic_mle.py
Replace no-longer-failing traceback for `res.conf_int()` with the array that is now produced.
I think there's only one more after this.
> MAINT: Fix incorrect specification of loglike arg

- lint.sh
- statsmodels/regression/dimred.py
- statsmodels/regression/process_regression.py
- statsmodels/regression/tests/test_dimred.py
- statsmodels/regression/tests/test_processreg.py
These files are newly introduced; should have been passing strict-linting already.  Not sure why they weren't.
> CLN: strict linting for dimred, processreg, and their tests.

- statsmodels/regression/linear_model.py
Spelling fix in ValueError message
> Spelling fix in ValueError message

- statsmodels/discrete/tests/test_discrete.py
- statsmodels/iolib/foreign.py
- statsmodels/sandbox/stats/diagnostic.py
- statsmodels/tools/decorators.py
- statsmodels/tools/grouputils.py
- statsmodels/tools/numdiff.py
- statsmodels/tools/tests/test_grouputils.py
- statsmodels/tools/tests/test_numdiff.py
- statsmodels/tools/tests/test_tools.py
- statsmodels/tsa/adfvalues.py
This is a hodge-podge.  I'll be happy to break it up into any requested subsets, but didn't want to make a bunch of tiny PRs right now.
> MAINT: close assorted small issues

- setup.cfg
- statsmodels/examples/try_polytrend.py
- statsmodels/examples/try_tukey_hsd.py
- statsmodels/genmod/families/family.py
- statsmodels/iolib/tests/test_summary2.py
- statsmodels/multivariate/manova.py
- statsmodels/sandbox/descstats.py
- statsmodels/sandbox/distributions/extras.py
- statsmodels/sandbox/examples/example_crossval.py
- statsmodels/sandbox/examples/example_pca_regression.py
- statsmodels/sandbox/nonparametric/densityorthopoly.py
- statsmodels/sandbox/regression/tools.py
- statsmodels/sandbox/stats/diagnostic.py
- statsmodels/sandbox/stats/stats_dhuard.py
- statsmodels/sandbox/tools/mctools.py
- statsmodels/sandbox/tsa/garch.py
- statsmodels/stats/descriptivestats.py
- statsmodels/stats/tests/test_corrpsd.py
- statsmodels/stats/tests/test_proportion.py
- statsmodels/tools/tests/test_numdiff.py
- statsmodels/tsa/base/tsa_model.py
- statsmodels/tsa/interp/denton.py
- statsmodels/tsa/statespace/tests/test_collapsed.py
- statsmodels/tsa/statespace/tests/test_exact_diffuse_filtering.py
- statsmodels/tsa/statespace/tests/test_representation.py
- statsmodels/tsa/vector_ar/tests/JMulTi_results/parse_jmulti_var_output.py
Each commit is for a separate code.
> CLN: codes with only a few violations apiece

- statsmodels/base/model.py
- statsmodels/base/tests/test_generic_methods.py
[NumPy's guide]
adds atleast_2d for single hypothesis, see #5475
adjust one unit test to also verify the single hypothesis
> BUG: fix df in summary for single constraint in wald_test_terms 

- statsmodels/base/_penalties.py
- statsmodels/base/tests/test_penalties.py
**Notes**:
```
```
using the Windows System for …
> BUG: rename wts to weights issue #4725

- statsmodels/genmod/generalized_estimating_equations.py
- statsmodels/genmod/tests/test_gee.py
This PR adds argument shape checking for GEE and allows GEE to be used with missing='drop' with formulas.
> ENH: improve missing data handling for GEE

- lint.sh
- statsmodels/tsa/statespace/tests/test_varmax.py
> CLN: strict linting for test_varmax

- lint.sh
- statsmodels/miscmodels/count.py
- statsmodels/miscmodels/tests/test_poisson.py
- statsmodels/miscmodels/try_mlecov.py
- statsmodels/sandbox/distributions/gof_new.py
- statsmodels/sandbox/distributions/tests/test_gof_new.py
- statsmodels/tools/tests/test_tools.py
Subset of #5757 for which tests are feasible.
> BUG/TST: Fix+test pieces of code that would raise NameError

- lint.sh
- setup.cfg
- statsmodels/base/l1_cvxopt.py
- statsmodels/base/l1_slsqp.py
- statsmodels/base/tests/test_shrink_pickle.py
- statsmodels/genmod/_tweedie_compound_poisson.py
- statsmodels/genmod/tests/test_glm.py
- statsmodels/nonparametric/kernel_regression.py
- statsmodels/nonparametric/tests/test_kernel_density.py
- statsmodels/nonparametric/tests/test_kernel_regression.py
- statsmodels/sandbox/bspline.py
- statsmodels/sandbox/formula.py
- statsmodels/sandbox/nonparametric/kernel_extras.py
- statsmodels/sandbox/stats/multicomp.py
- statsmodels/sandbox/tsa/diffusion2.py
- statsmodels/tsa/filters/hp_filter.py
- statsmodels/tsa/holtwinters.py
- statsmodels/tsa/interp/denton.py
- statsmodels/tsa/tests/test_holtwinters.py
- statsmodels/tsa/vector_ar/var_model.py
Comments addressed from #5751; force-pushed so can't re-open the old one.
> CLN: lint for ambiguous variable names

- statsmodels/gam/tests/test_gam.py
- statsmodels/regression/tests/test_recursive_ls.py
- statsmodels/tools/tests/test_grouputils.py
- statsmodels/tsa/base/tests/test_base.py
- statsmodels/tsa/statespace/tests/test_simulate.py
- statsmodels/tsa/statespace/tests/test_structural.py
- statsmodels/tsa/tests/test_arima.py
Selected by looking through Travis logs and picking out warnings produced internally.
> TST: test for intentionally emitted warnings, avoid some unintentional ones

- lint.sh
- statsmodels/base/tests/test_data.py
Getting this out of the way makes it easier to make progress on #5768.
> CLN: test_data.py

- setup.cfg
- statsmodels/sandbox/infotheo.py
- statsmodels/sandbox/regression/anova_nistcertified.py
- statsmodels/sandbox/regression/runmnl.py
- statsmodels/sandbox/stats/multicomp.py
- statsmodels/sandbox/tsa/garch.py
But at least enforce it elsewhere so we can prevent future bugs
Also a couple of typos in setup.cfg
> BUG: ignore bugs instead of fixing them

- lint.sh
- statsmodels/genmod/tests/test_gee.py
> CLN: test_gee.py

- statsmodels/regression/dimred.py
- statsmodels/regression/tests/test_dimred.py
> DOC: Add docstring for base class

- docs/source/release/version0.10.rst
- docs/themes/statsmodels/static/nature.css_t
- statsmodels/genmod/families/links.py
> DOC: Fix small errors in release notes

- setup.cfg
- statsmodels/base/tests/test_penalties.py
- statsmodels/datasets/tests/test_utils.py
- statsmodels/iolib/tests/test_foreign.py
- statsmodels/sandbox/regression/tests/test_gmm.py
- statsmodels/stats/tests/test_power.py
- statsmodels/tools/data.py
- statsmodels/tsa/statespace/tests/test_impulse_responses.py
- statsmodels/tsa/statespace/tests/test_simulate.py
- statsmodels/tsa/statespace/tests/test_structural.py
Catch expected warnings
**Notes**:
```
```
using …
> MAINT: Catch intentional warnings

- setup.py
[skip ci]
Update maintainer
xref #4573
> DOC: Update maintainer

- statsmodels/tsa/tests/test_ar.py
- statsmodels/tsa/tsatools.py
Improve error message to help users
closes #2202
[NumPy's guide]
> MAINT: Improve error message

- statsmodels/tools/tests/test_tools.py
- statsmodels/tools/tools.py
Add support for DataFrames and Series
closes #1342
> BUG: Allow categorical to accept pandas dtype

- statsmodels/graphics/gofplots.py
- statsmodels/graphics/tests/test_gofplots.py
> Cdown gofplot typerror

- statsmodels/tools/tools.py
There are a couple fails in the PIP_PRE build. I think this fixes it.
> MAINT: Use pd.Categorical() instead of .astype('categorical')

- statsmodels/tsa/holtwinters.py
[skip ci]
Clarify role of seasonal_periods
closes #5866
> DOC: Improve ExponentialSmoothing docstring

- lint.sh
- statsmodels/__init__.py
- statsmodels/gam/gam_cross_validation/gam_cross_validation.py
- statsmodels/gam/smooth_basis.py
- statsmodels/multivariate/factor.py
- statsmodels/tests/__init__.py
- statsmodels/tests/test_package.py
- statsmodels/tools/_testing.py
- statsmodels/tools/sm_exceptions.py
> PERF: Import speed

- statsmodels/graphics/regressionplots.py
- statsmodels/graphics/tests/test_regressionplots.py
Refactor so that he required keyword arguments are always available
closes #5873
<details>
**Notes**:
```
```
assuming …
> BUG: Ensure keywords exist in partial reg plot

- docs/source/release/version0.10.rst
Update release notes for 0.10.0 release
<details>
**Notes**:
```
``` …
> DOC: Update release notes

- statsmodels/compat/pandas.py
pandas is about to release 0.25.0, which will finally remove Panel.
> BUG: fix pandas compat

- tools/ci/appveyor_conda.bat
- tools/ci/travis_conda.sh
Update conda config to restore free
> MAINT: Update conda config

- tools/ci/azure_template.yml
> MAINT: Pin NumPy max on Azure

- .travis.yml
- appveyor.yml
- docs/source/install.rst
- requirements-dev.txt
- requirements.txt
- setup.py
- statsmodels/tsa/holtwinters.py
- tools/ci/azure_template.yml
Bump dependencies and update travis, appveyor and azure
Alternative to #5894 
> MAINT: Bump dependencies

- statsmodels/tsa/regime_switching/markov_switching.py
- statsmodels/tsa/regime_switching/tests/test_markov_regression.py
> BUG: TVTP for Markov regression

- statsmodels/regression/dimred.py
- statsmodels/regression/tests/test_dimred.py
This doesn't need to go in right away.
> ENH: Dimension reduction for covariance matrices

- statsmodels/regression/linear_model.py
> BUG: Fix kwargs update bug in linear model fit_regularized

- statsmodels/genmod/bayes_mixed_glm.py
- statsmodels/genmod/tests/test_bayes_mixed_glm.py
This addresses the issues raised in #5776
> DOC: improvements to BayesMixedGLM docs, argument checking

- docs/source/release/version0.10.1.rst
- statsmodels/genmod/bayes_mixed_glm.py
- statsmodels/genmod/tests/test_bayes_mixed_glm.py
- statsmodels/regression/linear_model.py
- [X ] properly formatted commit message. See 
<details>
**Notes**:
```
``` …
> Backport 5895 5903

- statsmodels/regression/mixed_linear_model.py
This may make it easier to understand how the variance components work.
It also may be slightly faster than the current dictionary-based approach.
Finally, this opens the door to some future extensions.
> ENH: use class to define MixedLM variance components structure

- docs/source/release/version0.10.1.rst
- statsmodels/compat/pandas.py
- statsmodels/tsa/holtwinters.py
- statsmodels/tsa/tests/test_holtwinters.py
> Backport 5921

- statsmodels/sandbox/regression/anova_nistcertified.py
Implements a test for anova_nistcertified, broken off from #5756.
> TST: test for anova_nistcertified

- azure-pipelines.yml
- docs/source/release/version0.10.1.rst
- statsmodels/sandbox/distributions/tests/test_multivariate.py
- statsmodels/tools/decorators.py
- statsmodels/tools/tests/test_decorators.py
- statsmodels/tsa/vector_ar/svar_model.py
- statsmodels/tsa/vector_ar/tests/test_var.py
- statsmodels/tsa/vector_ar/var_model.py
> Backport #5933 and #5784

- lint.sh
- statsmodels/discrete/tests/test_constrained.py
> CLN: test_constrained

- statsmodels/tsa/vector_ar/var_model.py
Fix linting failure
<details>
**Notes**:
```
``` …
> MAINT: Fix linting failures

- tools/ci/azure_template.yml
> MAINT: Test removal of numpy pin

- docs/source/release/version0.10.1.rst
- statsmodels/compat/pandas.py
- statsmodels/tsa/vector_ar/irf.py
- statsmodels/tsa/vector_ar/svar_model.py
- statsmodels/tsa/vector_ar/tests/test_svar.py
- statsmodels/tsa/vector_ar/util.py
- statsmodels/tsa/vector_ar/var_model.py
> MAINT: Port 5935

- statsmodels/stats/outliers_influence.py
Update references
closes #5427
<details>
**Notes**:
```
``` …
> DOC: Update references for Cook's distance

- statsmodels/regression/linear_model.py
Simplify definiition
closes #5373
<details>
**Notes**:
```
``` …
> DOC: Fix formula for log-like in WLS

- setup.py
- statsmodels/tsa/_innovations.pyx
- statsmodels/tsa/stattools.py
> PERF: Cythonize innovations algo and filter

- statsmodels/stats/outliers_influence.py
- statsmodels/stats/tests/test_outliers_influence.py
Improve stability by normalizing columns
Test against Stata
<details>
**Notes**:
```
``` …
> ENH: Improve RESET test stability

- tools/ci/docbuild_install.sh
Add seaborn to docbuild
<details>
**Notes**:
```
``` …
> MAINT: Ensure seaborn is available for docbuild

- statsmodels/base/model.py
- statsmodels/discrete/conditional_models.py
- statsmodels/discrete/discrete_model.py
- statsmodels/duration/hazard_regression.py
- statsmodels/genmod/generalized_estimating_equations.py
- statsmodels/genmod/generalized_linear_model.py
- statsmodels/genmod/qif.py
- statsmodels/imputation/bayes_mi.py
- statsmodels/imputation/mice.py
- statsmodels/iolib/summary.py
- statsmodels/iolib/summary2.py
- statsmodels/regression/linear_model.py
- statsmodels/regression/mixed_linear_model.py
- statsmodels/regression/quantile_regression.py
- statsmodels/robust/robust_linear_model.py
- statsmodels/sandbox/regression/gmm.py
- statsmodels/stats/contingency_tables.py
- statsmodels/stats/contrast.py
- statsmodels/tsa/arima_model.py
Clarify purpose to name x variables
closes #3122
<details>
**Notes**:
```
``` …
> DOC: Clarify xname length and purpose

- statsmodels/tsa/stattools.py
- statsmodels/tsa/tests/test_stattools.py
Deprecate in favor of tested version in scipy
closes #2592
<details>
**Notes**:
```
``` …
> MAINT: Deprecate periodogram

- docs/source/release/version0.10.1.rst
- statsmodels/compat/pandas.py
- statsmodels/graphics/mosaicplot.py
- statsmodels/graphics/tests/test_mosaicplot.py
> Backport 5951

- statsmodels/regression/_tools.py
- statsmodels/robust/robust_linear_model.py
- statsmodels/robust/tests/test_rlm.py
> ENH: Add start_params to RLM

- statsmodels/__init__.py
- statsmodels/compat/__init__.py
- statsmodels/compat/numpy.py
- statsmodels/compat/python.py
- statsmodels/datasets/tests/test_data.py
- statsmodels/datasets/utils.py
- statsmodels/discrete/tests/test_discrete.py
- statsmodels/formula/tests/test_formula.py
- statsmodels/genmod/tests/results/results_glm.py
- statsmodels/genmod/tests/test_glm_weights.py
- statsmodels/imputation/tests/test_mice.py
- statsmodels/iolib/foreign.py
- statsmodels/iolib/openfile.py
- statsmodels/iolib/tests/test_foreign.py
- statsmodels/regression/mixed_linear_model.py
- statsmodels/tests/test_package.py
- statsmodels/tools/tests/test_grouputils.py
- statsmodels/tsa/statespace/mlemodel.py
- statsmodels/tsa/statespace/tests/test_impulse_responses.py
- statsmodels/tsa/statespace/tests/test_simulate.py
- statsmodels/tsa/statespace/tests/test_structural.py
- statsmodels/tsa/tsatools.py
Remove PY3 and related shims
<details>
**Notes**:
```
``` …
> MAINT: Remove PY3

- docs/source/vector_ar.rst
- statsmodels/tsa/vector_ar/vecm.py
Add class to provide end user documentation
<details>
**Notes**:
```
``` …
> ENH: Add JohansenResults class

- statsmodels/tools/validation/__init__.py
- statsmodels/tools/validation/decorators.py
- statsmodels/tools/validation/tests/test_validation.py
- statsmodels/tools/validation/validation.py
- statsmodels/tsa/_bds.py
- statsmodels/tsa/_innovations.pyx
- statsmodels/tsa/arima_model.py
- statsmodels/tsa/arima_process.py
- statsmodels/tsa/filters/_utils.py
- statsmodels/tsa/filters/bk_filter.py
- statsmodels/tsa/filters/cf_filter.py
- statsmodels/tsa/filters/filtertools.py
- statsmodels/tsa/filters/hp_filter.py
- statsmodels/tsa/filters/tests/test_filters.py
- statsmodels/tsa/holtwinters.py
- statsmodels/tsa/seasonal.py
- statsmodels/tsa/stattools.py
- statsmodels/tsa/tests/test_arima.py
- statsmodels/tsa/tests/test_holtwinters.py
- statsmodels/tsa/tests/test_stattools.py
- statsmodels/tsa/tsatools.py
Add a lightweight array subclass to simplify input validation and
standardization
> ENH: Add array_like function to simplify input checking

- statsmodels/tools/validation/__init__.py
- statsmodels/tools/validation/tests/test_validation.py
- statsmodels/tools/validation/validation.py
- statsmodels/tsa/_innovations.pyx
- statsmodels/tsa/stattools.py
- statsmodels/tsa/tests/test_holtwinters.py
- statsmodels/tsa/tests/test_stattools.py
- statsmodels/tsa/tsatools.py
Add functions to simplify strict input checking
<details>
**Notes**:
```
``` …
> ENH: Add type checkers/converts for int, float and bool

- statsmodels/robust/scale.py
- statsmodels/robust/tests/test_scale.py
> Rlucas7 mad fun empty

- statsmodels/tsa/holtwinters.py
- statsmodels/tsa/tests/test_holtwinters.py
- statsmodels/tsa/tsatools.py
Ensure inputs are sanitized to prevent pandas Series from entering
<details>
**Notes**:
```
``` …
> BUG: Fix a future issue in ExpSmooth

- statsmodels/base/data.py
- statsmodels/discrete/discrete_model.py
- statsmodels/discrete/tests/test_discrete.py
- statsmodels/tsa/vector_ar/tests/test_var.py
- statsmodels/tsa/vector_ar/var_model.py
> BUG: Fix mutidimensional model cov_params when using pandas

- statsmodels/tsa/holtwinters.py
> MAINT: Backport 5971

- docs/source/release/version0.10.1.rst
> DOC: Release 0.10.1

- statsmodels/discrete/discrete_model.py
- statsmodels/discrete/tests/test_discrete.py
- statsmodels/tsa/vector_ar/tests/test_var.py
Discussed in comments in #5956
> CLN: follow-up to #5956

- statsmodels/sandbox/stats/diagnostic.py
- statsmodels/stats/tests/test_diagnostic.py
Add dimension check
closes #5886
<details>
**Notes**:
```
``` …
> MAINT: Clarify breusch_pagan is for scalars

- statsmodels/discrete/discrete_model.py
Complete predict docstring for CountModels
closes #1817
<details>
**Notes**:
```
``` …
> DOC: Add parameters for CountModel predict

- statsmodels/tsa/arima_model.py
Remvoe TODO that no longer applies
<details>
**Notes**:
```
``` …
> MAINT: Remove comment no longer relevant

- docs/source/faq.rst
- docs/source/tsa.rst
- statsmodels/genmod/generalized_linear_model.py
[skip ci]
Fix underline issues and alignment
<details>
**Notes**:
```
``` …
> DOC: Small fixups after teh spell check

- statsmodels/tsa/ar_model.py
- statsmodels/tsa/tests/test_ar.py
Add summary to AR
closes #2573
<details>
**Notes**:
```
``` …
> ENH: Add summary to AR

- statsmodels/tsa/tests/test_x13.py
Refactor to use pytest to split large test
closes #3452
<details>
**Notes**:
```
``` …
> MAINT: Refactor X13 testing

- docs/source/sandbox.rst
- lint.sh
- statsmodels/sandbox/tsa/garch.py
Clarify that this module is not going forward
<details>
**Notes**:
```
``` …
> DOC: Clarify that GARCH models are deprecated

- statsmodels/tsa/stattools.py
- statsmodels/tsa/tests/test_stattools.py
Use common definitions
closes #4154
<details>
**Notes**:
```
``` …
> MAINT: Standardized on nlags for acf/pacf

- statsmodels/graphics/gofplots.py
- statsmodels/graphics/tests/test_gofplots.py
Do not fit distribution if fit is False
closes #3547
closes #4255
<details>
**Notes**:
```
``` …
> BUG: Do not fit when fit=False

- statsmodels/base/tests/test_generic_methods.py
- statsmodels/compat/platform.py
> Ignore warns on 32 bit linux

- statsmodels/tsa/arima_model.py
- statsmodels/tsa/tests/test_arima.py
Check exog shape and adjust when possible to match expected size.
closes #2472
closes #2323
<details>
**Notes**:
```
``` …
> BUG/ENH: Check exog in ARMA and ARIMA predict

- lint.sh
- statsmodels/tools/validation/validation.py
- statsmodels/tsa/ar_model.py
- statsmodels/tsa/arima_model.py
- statsmodels/tsa/tests/test_ar.py
- statsmodels/tsa/tests/test_arima.py
Prevent refit except in cases where it does not break results instances
Complete testing of AR
Clean files
<details>
**Notes**:
``` …
```
> ENH/BUG: Add check to AR instance to prevent bugs

- statsmodels/tsa/x13.py
closes #3445
<details>
**Notes**:
```
```
using the …
> MAINT: Rename forecast years to forecast periods

- statsmodels/sandbox/stats/multicomp.py
https://github.com/statsmodels/statsmodels/issues/5974
**Notes**:
```
``` …
> Replace alpha=0.05 with alpha=alpha

- statsmodels/tsa/tests/test_arima.py
Improve test that is failing due ot precision issues on Win32
<details>
**Notes**:
```
``` …
> TST: Imrove test that is failing due to precision issues

- lint.sh
- statsmodels/tsa/seasonal.py
- statsmodels/tsa/tests/test_seasonal.py
Clarify minimum data length
Check multiple series are supported
Rename incorrectly named variable freq->period
<details>
**Notes**:
``` …
```
> MAINT/BUG/TST: Improve testing of seasonal decompose

- statsmodels/regression/tests/test_robustcov.py
Test is correct, notes are not
closes #1988
<details>
**Notes**:
```
``` …
> CLN: Remove notes about incorrect test

- statsmodels/genmod/tests/test_glm.py
closes #25
<details>
**Notes**:
```
```
using the …
> TST: Add check for dtyppes in Binomial

- statsmodels/tsa/arima_model.py
> Josef pkt arma startparams2

- statsmodels/tsa/ar_model.py
- statsmodels/tsa/arima_model.py
- statsmodels/tsa/tests/test_arima.py
Fix cov_params so that it works with standard methods
closes #947
<details>
**Notes**:
```
``` …
> BUG: Fix ARMA cov_params

- statsmodels/tsa/tests/test_arima.py
Verify missing raises
closes #2476
<details>
**Notes**:
```
``` …
> TST: Verify missing exog raises in ARIMA

- statsmodels/regression/dimred.py
- statsmodels/regression/tests/test_dimred.py
Fit SIR using L2 penalization.  This gives a "functional SIR" among other uses.
> ENH: Functional SIR

- .pep8speaks.yml
- docs/source/discretemod.rst
- docs/source/gam.rst
- docs/source/graphics.rst
- docs/source/nonparametric.rst
- docs/source/tsa.rst
- statsmodels/multivariate/pca.py
- statsmodels/regression/linear_model.py
- statsmodels/regression/quantile_regression.py
- statsmodels/stats/stattools.py
- statsmodels/tsa/_innovations.pyx
- statsmodels/tsa/_stl.pyx
- statsmodels/tsa/ar_model.py
- statsmodels/tsa/base/tsa_model.py
- statsmodels/tsa/seasonal.py
- statsmodels/tsa/stattools.py
- tools/ci/docbuild.sh
- tools/ci/docbuild_install.sh
- tools/validate_docstrings.py
Add check for doc string validity to doc build
Begin correcting some of the errors
<details>
**Notes**:
```
```
assuming …
> BLD/DOC: Add doc string check to doc build

- docs/source/names_wordlist.txt
- docs/source/spelling_wordlist.txt
- statsmodels/base/model.py
- statsmodels/regression/linear_model.py
- statsmodels/tsa/stattools.py
Fix spelling mistakes
<details>
**Notes**:
```
``` …
> DOC: Fix spelling

- examples/notebooks/statespace_seasonal.ipynb
Wrap RangeIndex with asarray to allow matplotlib integration
<details>
**Notes**:
```
``` …
> DOC: Fix notebook due to pandas index change

- docs/source/vector_ar.rst
Remove DynamicVAR which requires pd Panel
<details>
**Notes**:
```
``` …
> DOC: Remove DynamicVAR

- statsmodels/tsa/statespace/mlemodel.py
- statsmodels/tsa/statespace/tests/test_mlemodel.py
- statsmodels/tsa/statespace/tests/test_representation.py
> BUG: MLEModel now passes nobs to Representation

- docs/source/_static/overrides.css
- docs/themes/statsmodels/static/nature.css_t
[skip ci]
<details>
**Notes**:
```
```
using the Windows System for Linux once `flake8` is installed in the 
local Linux environment. While passing this test is not …
> DOC: More small doc fixes

- docs/source/_static/overrides.css
- statsmodels/tsa/_stl.pyx
[skip ci]
Small changes
<details>
**Notes**:
```
``` …
> DOC: Small changes to doc building

- docs/source/conf.py
- tools/ci/docbuild_install.sh
> DOC: Use the working branch of numpy doc

- docs/themes/statsmodels/static/nature.css_t
[skip ci]
<details>
**Notes**:
```
```
using the …
> DOC: Fix web font size

- statsmodels/tsa/statespace/kalman_filter.py
- statsmodels/tsa/statespace/tests/test_prediction.py
- statsmodels/tsa/statespace/varmax.py
Related to discussion in #5287.  Previously when using prediction or forecasting from state space models, we always ran the Kalman filter from the beginning of the dataset, which is unnecessary.
This PR can yield substantial performance gains when e.g. forecasting after a very long time series (e.g. hundreds of times faster), but in most cases the gains are only modest and probably not noticeable.
Also, this PR cleans up a weird bit of code from when I originally implemented this and didn't really realize what was going on with dynamic forecasts (they weren't wrong, but just computed in a convoluted unnecessary way).
Finally, for the pure forecasting case, this PR now allows using the `memory_no_predicted` optional along with pure out-of-sample forecast (still can't use that option when …
> ENH/PERF: Only perform required predict iterations in state space models

- statsmodels/compat/pandas.py
Fixes issue reimporting same class
<details>
**Notes**:
```
``` …
> MAINT: Fix small lint issue

- statsmodels/tsa/statespace/_tools.pxd
- statsmodels/tsa/statespace/_tools.pyx.in
@ChadFulton this is largely a proof of concept, since there is lots of room to continue down this path
> ENH: Use cython fused types to simplify statespace code

- docs/source/stats.rst
- lint.sh
- statsmodels/stats/api.py
- statsmodels/stats/oaxaca.py
- statsmodels/stats/tests/test_oaxaca.py
Hi everyone, 
I wanted to add some more econometrics to this package with the Oaxaca-Blinder decomposition. It is used to classify the differences between the means of two groups. It is commonly used in Labor and Health economics. I also would like to add some more of the ideas from the STATA library, but wanted to get feedback early.
I compared all the results to STATA and they are the exact same.
I am also sure there are better ways to code some of the things that I did, so I am looking forward to hearing your suggestions. Looking forward to learning, so that I can hopefully contribute some more econometrics methods.
> WIP: Added Oaxaca-Blinder Decomposition

- docs/source/names_wordlist.txt
- examples/notebooks/rolling_ls.ipynb
- statsmodels/base/model.py
- statsmodels/stats/oaxaca.py
- statsmodels/tsa/_bds.py
- statsmodels/tsa/stattools.py
Bring tsatools docs into standards compliance
<details>
**Notes**:
```
``` …
> DOC: Clean tsatools docs

- statsmodels/tsa/statespace/tests/test_conserve_memory.py
These were meant to have been included in #6071.
> TST: Add conserve memory tests.

- statsmodels/sandbox/stats/diagnostic.py
- statsmodels/stats/tests/test_diagnostic.py
Improve Ljung-Box to take an optional model_df parameter
Improve documentation
<details>
**Notes**:
```
``` …
> ENH/DOC: Improve Ljung-Box

- statsmodels/tools/tools.py
- statsmodels/tsa/ar_model.py
- statsmodels/tsa/base/tsa_model.py
- statsmodels/tsa/tsatools.py
[skip ci]
General doc string clean up
<details>
**Notes**:
```
``` …
> DOC: Improve docs in tools and ar_model

- statsmodels/tools/tools.py
Correct input check
<details>
**Notes**:
```
``` …
> BUG: Fix error introduced in isestimable

- docs/source/conf.py
- statsmodels/tsa/filters/bk_filter.py
- statsmodels/tsa/filters/cf_filter.py
- statsmodels/tsa/filters/filtertools.py
- statsmodels/tsa/filters/hp_filter.py
- statsmodels/tsa/seasonal.py
[skip ci]
Improve doc strings for filters
<details>
**Notes**:
```
``` …
> DOC: Improve filter docstrings

- docs/source/spelling_wordlist.txt
- examples/notebooks/formulas.ipynb
- statsmodels/sandbox/stats/diagnostic.py
[skip ci]
Correct spelling mistake and update notebook link
<details>
**Notes**:
```
``` …
> DOC: Spelling and motebook link

- docs/themes/statsmodels/static/nature.css_t
Remove function masking attribute
Small website fix
<details>
**Notes**:
```
``` …
> MAINT: Remvoe redundant code

- statsmodels/datasets/utils.py
- statsmodels/iolib/smpickle.py
Avoid pickle when unnecessary
Mitigates a potential security risk if the cached data directory is shared
<details>
**Notes**:
``` …
```
> MAINT/SEC: Remove unnecessary pickle use

- statsmodels/datasets/tests/test_utils.py
- statsmodels/datasets/utils.py
Fix new cache name to have a better appearance
<details>
**Notes**:
```
``` …
> MAINT: Fix new cache name

- statsmodels/tsa/statespace/dynamic_factor.py
- statsmodels/tsa/statespace/mlemodel.py
- statsmodels/tsa/statespace/sarimax.py
- statsmodels/tsa/statespace/structural.py
- statsmodels/tsa/statespace/tests/test_fixed_params.py
- statsmodels/tsa/statespace/varmax.py
> BUG: Fix score computation with fixed params

- CONTRIBUTING.rst
> DOC: Update CONTRIBUTING.rst "relase"-> "release"

- .github/PULL_REQUEST_TEMPLATE.md
> DOC: Update PR template Numpy guide link

- statsmodels/discrete/discrete_model.py
<details>
**Notes**:
```
```
using the …
> added interpretations to LogitResults.get_margeff

- statsmodels/miscmodels/tests/test_tarma.py
- statsmodels/tools/docstring.py
- statsmodels/tsa/arima_process.py
- statsmodels/tsa/innovations/arma_innovations.py
- statsmodels/tsa/tests/test_arima_process.py
- statsmodels/tsa/tsatools.py
- statsmodels/tsa/x13.py
Bring doc strings into line with standards
<details>
**Notes**:
```
``` …
> DOC: Improve docstrings

- setup.py
> BUG: Remove extra LICENSE.txt and setup.cfg

- docs/source/api.rst
- docs/source/index.rst
- statsmodels/api.py
- statsmodels/imputation/bayes_mi.py
- statsmodels/regression/rolling.py
Add documentation of official API
Fix some small doc issues identified
<details>
**Notes**:
```
``` …
> DOC: Add initial API doc

- docs/source/about.rst
- docs/source/api.rst
- docs/source/conf.py
- docs/source/dev/test_notes.rst
- docs/source/tsa.rst
- statsmodels/__init__.py
- statsmodels/discrete/count_model.py
- statsmodels/discrete/discrete_model.py
- statsmodels/duration/hazard_regression.py
- statsmodels/gam/generalized_additive_model.py
- statsmodels/genmod/bayes_mixed_glm.py
- statsmodels/genmod/generalized_linear_model.py
- statsmodels/graphics/gofplots.py
- statsmodels/multivariate/manova.py
- statsmodels/multivariate/pca.py
- statsmodels/regression/linear_model.py
- statsmodels/regression/mixed_linear_model.py
- statsmodels/regression/rolling.py
- statsmodels/robust/robust_linear_model.py
- statsmodels/tsa/_bds.py
- tools/ci/docbuild.sh
Add a few undocumented functions in the API
Shorten summary doc strings
<details>
**Notes**:
```
``` …
> DOC: Small improvements to docs

- docs/Makefile
- statsmodels/regression/rolling.py
- tools/ci/docbuild.sh
Fix issue in doc build
<details>
**Notes**:
```
``` …
> DOC: Fix doc build failure

- docs/source/_templates/autosummary/attribute.rst
- docs/source/_templates/autosummary/member.rst
- docs/source/_templates/autosummary/method.rst
- docs/source/gee.rst
- docs/source/gettingstarted.rst
- statsmodels/genmod/generalized_estimating_equations.py
- statsmodels/tools/tests/test_web.py
- statsmodels/tools/tools.py
- statsmodels/tools/web.py
Add and improve function in the API
Simplify templates
<details>
**Notes**:
```
``` …
> DOC: Update templates and add missing API functions

- statsmodels/tsa/statespace/tests/test_varmax.py
- statsmodels/tsa/statespace/varmax.py
Fixes the conditional statement and adds a test.
> BUG: start_params for VMA model with exog.

- docs/source/api.rst
- docs/source/importpaths.rst
- docs/source/imputation.rst
- docs/source/tsa.rst
- docs/source/vector_ar.rst
- statsmodels/tsa/api.py
Add functions that are not documented in the API
<details>
**Notes**:
```
``` …
> DOC: Add missing functions from the API

- tools/ci/docbuild.sh
- tools/validate_docstrings.py
Fix validator and avoid future stops
<details>
**Notes**:
```
``` …
> DOC: Fix validator so that it works

- docs/source/api.rst
- docs/source/conf.py
Add formula API to API page
<details>
**Notes**:
```
``` …
> DOC: Add formula API

- .travis.yml
<details>
**Notes**:
```
```
using the …
> Travis CI: The sudo: tag is deprecated in Travis

- docs/source/api.rst
- docs/source/names_wordlist.txt
- docs/source/spelling_wordlist.txt
- statsmodels/__init__.py
- statsmodels/base/model.py
- statsmodels/base/wrapper.py
- statsmodels/datasets/utils.py
- statsmodels/genmod/generalized_estimating_equations.py
- statsmodels/imputation/bayes_mi.py
- statsmodels/imputation/ros.py
- statsmodels/iolib/smpickle.py
- statsmodels/regression/process_regression.py
- statsmodels/regression/rolling.py
- statsmodels/sandbox/multilinear.py
- statsmodels/tsa/statespace/tests/test_tools.py
Use Python official language
Fix spelling
<details>
**Notes**:
```
``` …
> DOC: Update pickle warning

- docs/source/install.rst
- statsmodels/discrete/discrete_model.py
- statsmodels/regression/linear_model.py
Add cvxopt to documentation
closes #6169
<details>
**Notes**:
```
``` …
> DOC: Clarify req for cvxopt
