statsmodels/statsmodels

statsmodels/base/l1_solvers_common.py

Warn users abotu convergence rather than priting a message
closes #3794

BUG: Warn rather than print

---

statsmodels/tsa/statespace/initialization.py
statsmodels/tsa/statespace/tests/test_tools.py
statsmodels/tsa/statespace/tools.py

Allow NumPy ints in companion matrix and other tsa functions
closes #5570

BUG: Allow NumPy ints

---

statsmodels/tsa/arima_model.py
statsmodels/tsa/tests/test_arima.py

Refactor method used when generating variable names across multiple calls
closes #4870
[NumPy's guide]

BUG: Refactor method used to name variables

---

statsmodels/iolib/summary.py
statsmodels/iolib/tests/test_summary.py

Verify that xnames has the same number of elements as parameters

BUG: Add check for xnames length

---

statsmodels/tsa/ar_model.py

DOC: fix incorrect ARResults.predict docstring, closes #4498

---

statsmodels/iolib/table.py
statsmodels/iolib/tests/test_table.py

Switch to right for text align
closes #1477

BUG: Fix default alignment for SimpleTable

---

statsmodels/discrete/discrete_model.py
statsmodels/discrete/tests/test_discrete.py

Ensure MNLogit summary works with float values
closes #3960

BUG: Fix MNLogit summary with float values

---

statsmodels/tsa/arima_model.py
statsmodels/tsa/tests/test_arima.py

[NumPy's guide]
ARIMA analogue for #5802.

BUG: ARIMA fit with trend and constant exog

---

statsmodels/tsa/statespace/_smoothers/_univariate.pyx.in
statsmodels/tsa/statespace/tests/test_univariate.py

In a particular place, smoothing algorithm should use T_{t-1} and I had been using T_{t}.
I had a helpful TODO suggesting that I check it, but then apparently did not check it :(
Should be merged in before 0.10 release.

BUG: State space univariate smoothing w/ time-varying transition matrix: wrong transition matrix used

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/PULL_REQUEST_TEMPLATE.md

[skip ci]
Improve template to help users report better bugs

DOC: Improve bug report template

---

docs/themes/statsmodels/layout.html

So doctr by default prepends a "v" to the version number of the folders. Historically, we've  not had the "v" prefix. This changes the javascript that we use to handle drop the prefix.
See the finished product here...
https://thequackdaddy.github.io/statsmodels.github.io/devel/index.html
Before:
After:

DOC: Update version dropdown javascript

---

statsmodels/tsa/holtwinters.py
statsmodels/tsa/tests/test_holtwinters.py

Exponential smoothing with a damped trend gives the wrong result for `res.params['initial_slope']` and gives wrong predictions.
The problem is the initial trend is accidentally multiplied by the damping parameter before the results object is created. This means that when predictions are made later, they will be based on the wrong initial trend.
This PR also fixes the problem that `sm.tsa.Holt` silently ignores the `initial_level` and `initial_slope` arguments.

BUG: exponential smoothing - damped trend gives incorrect param, predictions

---

lint.sh
statsmodels/regression/tests/test_tools.py

<details>
It looks like pytest 5 changed the way some errors are reported. Small syntax change and I think this should fix most of the failing tests.
</details>

MAINT: Use pytest.raises to check error message

---

statsmodels/regression/linear_model.py
statsmodels/regression/tests/test_cov.py
statsmodels/sandbox/regression/penalized.py
statsmodels/stats/anova.py

This had already been done in the version of get_robustcov_results in base.covtype, which drifted away from the near-identical version in RegressionResults.get_robustcov_results.  Confusion over "is this still needed/intentional" can be avoided by avoiding duplicated code.

MAINT: remove no-longer-needed HC_se lookups

---

statsmodels/tsa/regime_switching/markov_switching.py
statsmodels/tsa/regime_switching/tests/test_markov_regression.py

Backport of #5917. Not as straightforward as cherry-picking, since we merged #5826 after releasing v0.10, and that changed some of the filtering code.

MAINT: Backport "BUG: TVTP for Markov regression"

---

statsmodels/tsa/holtwinters.py
statsmodels/tsa/tests/test_holtwinters.py

Ensure data is always C contiguous and double

BUG: Ensure exponential smoothers has continuous double data

---

statsmodels/compat/pandas.py
statsmodels/graphics/tests/test_tsaplots.py
statsmodels/tsa/vector_ar/tests/test_dynamic.py

Modernize pandas compat imports to reflect min version
<details>
**Notes**:
```
``` …

MAINT: Fix pandas imports

---

appveyor.yml

MAINT: Remove Python 2.7 from Appveyory

---

statsmodels/base/model.py
statsmodels/base/tests/test_shrink_pickle.py
statsmodels/compat/pandas.py
statsmodels/genmod/generalized_linear_model.py
statsmodels/tools/decorators.py

The existing approach to `remove_data` is haphazard, lets a lot of things fall through the cracks.  For the purpose of this Proof Of Concept, the things falling through the cracks are `GLMResults.resid_response`, `resid_deviance`, `resid_pearson`, ... Because these are not listed in `GLM.__init__` when extending `self._data_attr`, they do not get removed when `remove_data` is called.
On the flip side, there are a number of summary statistics that we would like to retain when pickling but will not if a `cache_readonly` attribute has not been evaluated.
The suggestion here is to add two variants of `cache_readonly`: `cached_value` and `cached_data`.  `cached_data` attributes are treated as data-like for the purposes of `remove_data`, so will be removed.  `cached_value` attributes on the …

implement cached_value, cached_data proof of concept

---

statsmodels/tsa/stattools.py
statsmodels/tsa/tests/test_stattools.py

Limit lags to nobs - 1 in KPSS
closes #5925

BUG: Limit lags in KPSS

---

statsmodels/tsa/tests/test_stattools.py

MAINT: Relax tol on test that randomly fails

---

lint.sh
statsmodels/sandbox/stats/ex_multicomp.py
statsmodels/sandbox/stats/multicomp.py
statsmodels/sandbox/stats/tests/test_multicomp.py

with test.
Separate the formerly-raising code out from `__main__` block into `example_fdr_bonferroni`, implement a smoketest to check it runs without raising.
The new function example_fdr_bonferroni is cleaned up, the rest left as is.

MAINT: Remove docstring'd-out traceback for code that no longer raises

---

statsmodels/sandbox/distributions/tests/test_multivariate.py

Fix test so that it is deterministic

MAINT: Fix test that fails with positive probability

---

.travis.yml

Remove Python 2.7 testing from master

MAINT: Remove Python 2.7 from travis

---

INSTALL.txt

Assuming that the more recently updated set is correct.
Given the amount of duplication with docs/install.rst, should INSTALL.txt instead be removed altogether?

DOC: Fix self-contradictory minimum dependency versions

---

statsmodels/tools/decorators.py

Restore ResettableCache so that 0.9 pickles can loaded
closes #5899

BUG: Restore ResettableCache

---

statsmodels/graphics/mosaicplot.py
statsmodels/graphics/tests/test_mosaicplot.py

Fix plot so that it work with dataframes that are missing categories
closes #5639
<details>
**Notes**:
```
```
assuming …

BUG: Fix mosaic plot with missing category

---

statsmodels/tsa/vector_ar/tests/test_coint.py
statsmodels/tsa/vector_ar/vecm.py

Normalize so that first non-zero element is always positive to prevent random sign
flips due to lienar algebra libraries
closes #5517
- [x ] closes #5517
<details>
**Notes**:
```
git diff …
```

ENH: Normalize eigenvectors from coint_johansen

---

statsmodels/graphics/tests/test_mosaicplot.py

Makr test as matplotlib to ensure it isn't run when MPL is
not available
<details>
**Notes**:
```
``` …

MAINT: Mark MPL test as MPL

---

.travis.yml

Drop configs that are run on appveyor

MAINT: Drop redendant travis configs

---

statsmodels/robust/norms.py
statsmodels/robust/robust_linear_model.py
statsmodels/robust/scale.py
statsmodels/robust/tests/test_rlm.py

Ensure RLM doesn't crash if perfect fit
Clean norms so that they don't crash either
Avoid calculations the load to nan
Improve testing of RLM
Replace fabs with abs
xref #55
<details>
**Notes**:
verify you changes are well formatted by …

BUG/ENH: Improve RLM in the case of perfect fit

---

statsmodels/nonparametric/_smoothers_lowess.pyx
statsmodels/tsa/_exponential_smoothers.pyx
statsmodels/tsa/_innovations.pyx
statsmodels/tsa/_stl.pyx
statsmodels/tsa/regime_switching/_hamilton_filter.pxd
statsmodels/tsa/regime_switching/_kim_smoother.pxd
statsmodels/tsa/regime_switching/_kim_smoother.pyx.in
statsmodels/tsa/statespace/_smoothers/_univariate_diffuse.pyx.in
statsmodels/tsa/statespace/_tools.pyx.in

trailing whitespace, `cimport numpy as cnp` instead of as `np` to disambiguate the namespaces

CLN: cython cleanups

---

statsmodels/regression/linear_model.py

RR str was missing the return keyword
closes #4618
<details>
**Notes**:
```
``` …

BUG: Fix return for RegressionResults

---

statsmodels/iolib/summary2.py
statsmodels/iolib/tests/test_summary2.py

ENH: Add R-squared and Adj. R_squared to summary_col

---

statsmodels/tsa/arima_model.py
statsmodels/tsa/tests/test_arima.py

Allow predict to swallow argument that is used in ARIMA forecasting
Needed since ARIMA can return ARMA when d=0
closes #2741
<details>
**Notes**:
``` …
```

ENH/BUG: Allow ARMA predict to swallow typ

---

statsmodels/tsa/stattools.py
statsmodels/tsa/tests/test_stattools.py

Allow test to be run for a specific lag
closes #2866
<details>
**Notes**:
```
``` …

ENH: Allow GC testing for specific lags

---

statsmodels/discrete/discrete_model.py
statsmodels/discrete/tests/test_discrete.py

Add test for categorical endog in MNLogit
closes #2601
<details>
**Notes**:
```
``` …

TST: Verify categorical is supported for MNLogit

---

.travis.yml
statsmodels/base/model.py
statsmodels/discrete/tests/test_discrete.py

Fix t-test and f-test to also work with multidimensional parameters
as in MNLogit or VAR
<details>
**Notes**:
```
```
assuming …

BUG: Fix t-test and f-test for multidim params

---

.pep8speaks.yml
statsmodels/base/model.py
statsmodels/genmod/families/family.py
statsmodels/genmod/generalized_linear_model.py
statsmodels/genmod/tests/test_glm.py
statsmodels/multivariate/manova.py
statsmodels/multivariate/multivariate_ols.py

Add a class variable that limits the number of endog variables
closes #2733
<details>
**Notes**:
```
``` …

ENH: Set limit for number of endog variables when using formulas

---

statsmodels/tsa/tests/test_arima.py

Correct ARIMA(1,1,1) to have a non-zero trend to avoid random test failures
<details>
**Notes**:
```
``` …

TST: Correct test to use trend not level

---

docs/source/vector_ar.rst

[skip ci]
Add documentation
closes #2869
<details>
**Notes**:
```
``` …

DOC: added content for two headings in VAR docs

---

statsmodels/__init__.py

Turn relative import into an absolute import to work around the issue with pyinstaller.

Turn relative import into an absolute import

---

statsmodels/iolib/tests/test_foreign.py

Change test to use python/pandas types to avoid NumPy casting
<details>
**Notes**:
```
``` …

MAINT: Change types for future changes in NumPy

---

statsmodels/datasets/utils.py

Remove code that produced a warning
<details>
**Notes**:
```
``` …

DOC/MAINT: Remove warning due to deprecated features

---

docs/source/_static/overrides.css
docs/source/_templates/autosummary/class.rst
docs/source/examples/index.rst
examples/notebooks/formulas.ipynb

Some small tweaks to catch missed elements
<details>
**Notes**:
```
``` …

DOC: Small fix ups for modernized size

---

docs/source/spelling_wordlist.txt
docs/themes/statsmodels/static/nature.css_t
examples/notebooks/statespace_arma_0.ipynb
examples/notebooks/statespace_dfm_coincident.ipynb
examples/notebooks/tsa_arma_0.ipynb
examples/python/statespace_arma_0.py
examples/python/statespace_dfm_coincident.py
examples/python/tsa_arma_0.py
statsmodels/base/elastic_net.py
statsmodels/base/model.py
statsmodels/base/wrapper.py
statsmodels/discrete/conditional_models.py
statsmodels/discrete/count_model.py
statsmodels/discrete/discrete_model.py
statsmodels/duration/hazard_regression.py
statsmodels/genmod/families/family.py
statsmodels/genmod/generalized_linear_model.py
statsmodels/graphics/factorplots.py
statsmodels/graphics/regressionplots.py
statsmodels/regression/linear_model.py
statsmodels/stats/contrast.py
statsmodels/tsa/_stl.pyx
statsmodels/tsa/arima_model.py
statsmodels/tsa/seasonal.py
statsmodels/tsa/statespace/mlemodel.py
statsmodels/tsa/statespace/varmax.py
statsmodels/tsa/stattools.py
statsmodels/tsa/vector_ar/var_model.py
tools/validate_docstrings.py

Fix more docstrings
<details>
**Notes**:
```
``` …

DOC: Continue fixing docstring formatting

---

docs/source/examples/index.rst
statsmodels/tsa/ar_model.py

Avoid repeat of docstring in ARResults.predict
Add missign notebook to build
<details>
**Notes**:
```
``` …

DOC: Fix doc errrors affecting build

---

MANIFEST.in
statsmodels/compat/scipy.py
statsmodels/tests/test_package.py

Prevent -OO test from running on buggy scipy
<details>
**Notes**:
```
``` …

MAINT: Stop testing on old, bugy SciPy

---

statsmodels/tsa/arima_model.py
statsmodels/tsa/tests/test_arima.py

Remove legacy hack that changed exog structure
<details>
**Notes**:
```
``` …

BUG: Fix ARMA so that it works with exog when trend=nc

---

statsmodels/tsa/statespace/_kalman_smoother.pyx.in
statsmodels/tsa/statespace/dynamic_factor.py
statsmodels/tsa/statespace/kalman_filter.py
statsmodels/tsa/statespace/mlemodel.py
statsmodels/tsa/statespace/sarimax.py
statsmodels/tsa/statespace/structural.py
statsmodels/tsa/statespace/tests/test_prediction.py
statsmodels/tsa/statespace/tests/test_representation.py
statsmodels/tsa/statespace/varmax.py

This PR improves the usability of memory conservation in state space models. In particular, we can now use maximum memory conservation in combination with `fit` and (since #6064 was merged) out-of-sample forecasting.

ENH: state space: Improve low memory usability; allow in fit, loglike

---

statsmodels/tsa/statespace/mlemodel.py
statsmodels/tsa/statespace/tests/test_fixed_params.py

This fixes a bug that raised an error when attempting parameter covariance matrix computation from a results object within the `fix_params` context.

BUG: state space: cov_params computation in fix_params context

---

statsmodels/tsa/statespace/mlemodel.py
statsmodels/tsa/statespace/tests/test_dynamic_factor.py
statsmodels/tsa/statespace/tests/test_mlemodel.py
statsmodels/tsa/statespace/tests/test_sarimax.py
statsmodels/tsa/statespace/tests/test_structural.py
statsmodels/tsa/statespace/tests/test_varmax.py

For `append`, `extend`, and `apply`, this passes the `cov_params` to the new results objects and adds a note to the bottom of summary output that parameters and cov_params were not estimated based on the current dataset.
Also makes available `fit_kwargs` to each of the methods.

ENH: Improve cov_params in append, extend, apply

---

docs/source/spelling_wordlist.txt
examples/notebooks/formulas.ipynb
statsmodels/base/model.py
statsmodels/base/wrapper.py
statsmodels/graphics/regressionplots.py
statsmodels/regression/_prediction.py
statsmodels/regression/linear_model.py
statsmodels/regression/rolling.py
statsmodels/stats/oaxaca.py
statsmodels/tsa/_stl.pyx
statsmodels/tsa/interp/denton.py
statsmodels/tsa/statespace/sarimax.py
statsmodels/tsa/stattools.py
tools/validate_docstrings.py

Improve regression doc strings
Fix small spelling errors
<details>
**Notes**:
```
``` …

DOC: Improve regression doc strings

---

lint.sh
statsmodels/tools/docstring.py
statsmodels/tools/tests/test_docstring.py

Add a simple tools that allows docstrings to be modified and rerendered
<details>
**Notes**:
```
``` …

ENH/DOC: Add tools for programatically manipulating docstrings

---

statsmodels/datasets/utils.py
statsmodels/tools/docstring.py

Use a new file name pattern to ensure cache is valid
Small improvement to docstring
<details>
**Notes**:
```
```
assuming …

MAINT: Ensure r download cache works

---

setup.cfg
statsmodels/stats/tests/test_diagnostic.py
statsmodels/stats/tests/test_oaxaca.py
statsmodels/tools/tests/test_docstring.py
statsmodels/tsa/tests/test_stattools.py

Correct wrong docstring test
Silence warnings during test run
<details>
**Notes**:
```
``` …

TST: Fix wrong test

---

statsmodels/tsa/statespace/sarimax.py
statsmodels/tsa/statespace/tests/test_sarimax.py

Fixes the uninformative `ValueError` ("maxlag should be < nobs") reported in e.g. #4465. Technically, the `ValueError` is being raised during computation of `start_params`, which is not really the place to raise an error about the number of observations. We should probably separately do something more in the `SARIMAX` constructor if given too few observations to estimate the model.
This PR changes the `start_params` behavior to issue a warning if there are not enough observations to compute starting parameters via CSS, and then sets the starting parameters for ar/ma/trend to zeros if they can't be computed.

ENH: Improve SARIMAX start_params if too few nobs

---

examples/notebooks/statespace_sarimax_stata.ipynb

changed `order=(1,1,1)` to `order=(1,1,(1,0,0,1))`
closes #6037

DOC: Seasonality in SARIMAX Notebook

---

statsmodels/iolib/summary2.py

The docstring now refers to regressor_order, not regressors_list, to match the variable name that the function asks for.

DOC: Changes summary_col's docstring to match variables

---

statsmodels/tsa/statespace/mlemodel.py
statsmodels/tsa/statespace/sarimax.py
statsmodels/tsa/statespace/structural.py
statsmodels/tsa/statespace/tests/results/results_structural.py
statsmodels/tsa/statespace/tests/results/test_ucm.R
statsmodels/tsa/statespace/tests/test_mlemodel.py
statsmodels/tsa/statespace/tests/test_representation.py
statsmodels/tsa/statespace/tests/test_structural.py

Both SARIMAX and UnobservedComponents have used approximate diffuse initialization to handle non-stationary states since they were introduced. We got exact diffuse initialization for custom state space models in v0.10, but there was no option to use it in SARIMAX or UnobservedComponents. This adds a keyword argument `use_exact_diffuse` (default is False, so that approximate diffuse initialization continues to be the default) to the constructor to allow specifying exact diffuse initialization.
(In a future version, we may want to switch the default to exact diffuse initialization.)

ENH: Add exact diffuse initialization as an option for SARIMAX, UnobservedComponents

---

statsmodels/tsa/base/tests/test_tsa_indexes.py
statsmodels/tsa/base/tsa_model.py

Fixes the behavior in `_get_index_loc` if Pandas returns a slice from the `get_loc` index method. This previously caused an extra element to sometimes get returned in `_get_prediction_index`.

 BUG: Incorrect TSA index if loc resolves to slice

---

statsmodels/tsa/statespace/_filters/_univariate_diffuse.pyx.in

We can compute the standardized forecast error even in periods for which diffuse initialization is still in effect in the case that the diffuse forecast error covariance matrix is equal to zero.
Previously, we just did not compute this quantity at all in diffuse periods.

ENH: Compute standardized forecast error in diffuse period if possible

---

statsmodels/duration/survfunc.py

When one runs:
```python
sf = sm.SurvfuncRight(df["futime"], df["death"])
sf.plot()
```
The survival function is being plotted along with **all** the censored points.
Some of them are identical points.
I find it unnecessary to plot the same points multiple times. Fixed that.

Plot only unique censored points

---

statsmodels/sandbox/stats/multicomp.py

The __init__ for MultiComparison defines self.data = np.asarray(data) where data is an input.
However on the line modified in this PR it calculates data.shape which fails for the case where data is, say, an array-like object without defined shape e.g. a list. 
The change is to use self.data.shape instead, which will  be defined.

BUG: use self.data consistently

---

docs/source/conf.py

The html sidebars need 'globaltoc.html' for the sidebar to work. Also, I think a toc depth of 3 makes sense...

DOC: fix sidebartoc

---

statsmodels/discrete/discrete_model.py

The source contains what is obviously intended to be an error message, but was never actually output.

Improve the cvxopt not found error

---

statsmodels/tests/test_package.py

On systems where 'python' is Python 2, test_docstring_optimization_compat tries to import statsmodels in Python 2, which does not work (currently with ImportError: No module named abc).

Don't assume that 'python' is Python 3

---

statsmodels/base/model.py
statsmodels/formula/tests/test_formula.py

According model.from_formula documentation, the `eval_env`
parameter can be a `patsy.EvalEnvironment` but this type was
not properly handled.

BUG: Fix accepting of eval environment for formula

---

statsmodels/base/model.py
statsmodels/base/wrapper.py
statsmodels/iolib/smpickle.py

The Python pickle format is intentionally a "can run arbitrary code" format:
https://docs.python.org/3/library/pickle.html#restricting-globals

DOC/SEC: Warn that only trusted files should be unpickled

---

statsmodels/base/model.py
statsmodels/base/wrapper.py

Remove extra space
<details>
**Notes**:
```
``` …

DOC: Fix warning format

---

statsmodels/tsa/statespace/dynamic_factor.py
statsmodels/tsa/statespace/mlemodel.py
statsmodels/tsa/statespace/sarimax.py
statsmodels/tsa/statespace/structural.py

Adds a more convenient results attributes, `states`, for accessing predicted, filtered, and smoothed states and covariances.
For example:
```python
mod = sm.tsa.UnobservedComponents(...)
res = mod.fit()
res.states.smoothed['level'].plot()
res.states.smoothed_cov.loc['level', 'level'].plot() . # see below for a question on this approach
```
These are useful for several reasons:
- The filter output (like `res.predicted_state`) are always numpy arrays, so the main goal was to get a new attribute that would wrap the array with a Pandas date index when that's available
- `res.predicted_state` includes an additional element, the "initial" state: unlike e.g. `res.filtered_state` which has length `nobs`, `res.predicted_state` has length `nobs + 1`. This can be a gotcha if you expect the arrays to …

ENH: state space: add wrapped states and, where possible, named states

---

statsmodels/regression/mixed_linear_model.py

Change header text in summary from "Likelihood" to "Log-Likelihood"
Thanks @stevenli-ds
<details>
**Notes**:
```
``` …

BUG: Fix summary table header for mixedlm

---

statsmodels/tsa/statespace/dynamic_factor.py
statsmodels/tsa/statespace/tests/test_dynamic_factor.py

BUG: allow dynamic factor starting parameters computation with NaNs values

---

statsmodels/tsa/statespace/sarimax.py
statsmodels/tsa/statespace/tests/test_sarimax.py

BUG: SARIMAX: basic validation for order, seasonal_order

---

statsmodels/tsa/statespace/dynamic_factor.py
statsmodels/tsa/statespace/tests/test_dynamic_factor.py
statsmodels/tsa/statespace/tests/test_fixed_params.py

BUG: parameter names in DynamicFactor for unstructured error covariance matrix

---

statsmodels/tsa/base/tests/test_tsa_indexes.py
statsmodels/tsa/base/tsa_model.py

Note: Although we could potentially make non-full `PeriodIndex`'s work, currently they produce weird behavior and should be disallowed.

BUG: Forecasts now ignore non-monotonic period index

---

statsmodels/tsa/arima/model.py
statsmodels/tsa/arima/specification.py
statsmodels/tsa/arima/tests/test_model.py
statsmodels/tsa/arima/tests/test_specification.py
statsmodels/tsa/arima/tests/test_tools.py
statsmodels/tsa/arima/tools.py
statsmodels/tsa/statespace/sarimax.py

In addition to handling the case of inputting a list of lags to include, this also adds some additional validation with better error messages (e.g. for the case that `endog` is not univariate, now there will be a clear message to that effect).

ENH: Update SARIMAX to use SARIMAXSpecification for more consistent input handling

---

statsmodels/tsa/arima/estimators/hannan_rissanen.py
statsmodels/tsa/arima/estimators/tests/test_hannan_rissanen.py
statsmodels/tsa/arima/tests/test_model.py

See #6238 for the report of the underling issue that this PR resolves, which is essentially an overflow error from generating an intermediate series for the unbiasing step if the estimated parameters are non-stationary / non-invertible.

BUG: Hannan-Rissanen third stage is invalid if non-stationary/invertible

---

statsmodels/tsa/statespace/mlemodel.py
statsmodels/tsa/statespace/tests/test_fixed_params.py

`extend`, `apply`, and `append` weren't properly passing the dictionary of which parameters had been fixed to the new results object when the model wasn't being re-fit.

BUG: state space: saving fixed params w/ extend, apply, append

---

.travis.yml
appveyor.yml
docs/source/release/index.rst
docs/source/release/version0.10.2.rst
docs/source/vector_ar.rst
examples/notebooks/statespace_seasonal.ipynb
requirements-dev.txt
setup.py
statsmodels/__init__.py
statsmodels/compat/pandas.py
statsmodels/datasets/tests/test_utils.py
statsmodels/datasets/utils.py
statsmodels/iolib/smpickle.py
statsmodels/sandbox/stats/multicomp.py
statsmodels/stats/correlation_tools.py
statsmodels/tools/docstring.py
statsmodels/tsa/statespace/mlemodel.py
statsmodels/tsa/statespace/tests/test_mlemodel.py
statsmodels/tsa/statespace/tests/test_representation.py
statsmodels/tsa/stattools.py
statsmodels/tsa/tests/test_stattools.py
tools/ci/azure_template.yml
tools/ci/docbuild.sh
tools/ci/travis_conda.sh
tools/ci/travis_pip.sh

<details>
**Notes**:
```
```
using the …

0.10.2 cherry

---

INSTALL.txt
docs/source/install.rst
requirements.txt

Clarify patsy requirement
closes #6267

MAINT/DOC: Clarify patsy 0.5.1 is required

---

examples/notebooks/statespace_sarimax_stata.ipynb

Fix SARIMAX stata notebook to have correct examples in correct cells
<details>
**Notes**:
```
``` …

DOC: Fix notebook

---

statsmodels/graphics/regressionplots.py

Plot leverage now passes axes through
closes #6264
<details>
**Notes**:
```
``` …

BUG: Pass arguments through in plot_leverage_resid2

---

statsmodels/tsa/vector_ar/tests/test_var.py
statsmodels/tsa/vector_ar/var_model.py

Raise when trying to test GC in a model with 0 lags
closes #6274
<details>
**Notes**:
```
``` …

BUG: Raise in GC test for VAR(0)

---

statsmodels/graphics/regressionplots.py

make vlines optional in regression plot
- [NA] closes #xxxx
- [see info below] tests added / passed. 
<details>
**Notes**:
``` …
```

ENH: and vlines option to plot_fit

---

statsmodels/tsa/vector_ar/output.py
statsmodels/tsa/vector_ar/tests/test_var.py
statsmodels/tsa/vector_ar/var_model.py

Ensure that dimension is correct when model contains exogenous variables
closes #6203
<details>
**Notes**:
```
``` …

BUG: Correct VAR sumary when model contains exog variables

---

statsmodels/api.py

Remove unsupported chm help opener
closes #5134
<details>
**Notes**:
```
``` …

MAINT: Remove open_help method

---

statsmodels/tsa/statespace/mlemodel.py
statsmodels/tsa/statespace/tests/test_exponential_smoothing.py

Fix confidence interval so that it works with MI series
closes #6296
<details>
**Notes**:
```
``` …

BUG: Fix conf interval with MI

---

statsmodels/base/tests/test_shrink_pickle.py

Reduce matrix size from 10000x10000 to avoid issues on 32 bit platforms
<details>
**Notes**:
```
``` …

TST: Reduce test size to prevent 32-bit crash

---

setup.cfg
statsmodels/base/data.py
statsmodels/base/tests/test_data.py
statsmodels/genmod/tests/results/results_glm.py
statsmodels/genmod/tests/test_glm.py
statsmodels/sandbox/descstats.py
statsmodels/tools/data.py
statsmodels/tools/sm_exceptions.py
statsmodels/tools/tests/test_data.py
statsmodels/tools/tests/test_tools.py
statsmodels/tools/tools.py
statsmodels/tsa/tests/test_tsa_tools.py
statsmodels/tsa/tsatools.py

Deprecate recarray support with aim to drop after 0.12
closes #1552
closes #2656
<details>
**Notes**:
```
```
assuming …

MAINT: Deprecate recarray support

---

statsmodels/nonparametric/kde.py
statsmodels/nonparametric/tests/test_kernel_density.py
statsmodels/sandbox/nonparametric/kde2.py

Ensure data is dould and contiguous
closes #1915
<details>
**Notes**:
```
``` …

BUG: Check dtype in KDEUnivariate

---

.codacy.yml
setup.cfg
statsmodels/base/tests/test_shrink_pickle.py
statsmodels/conftest.py
statsmodels/genmod/tests/test_glm.py
statsmodels/miscmodels/tests/test_tarma.py
statsmodels/regression/tests/test_dimred.py
statsmodels/regression/tests/test_lme.py
statsmodels/regression/tests/test_rolling.py
statsmodels/sandbox/tests/test_gam.py
statsmodels/tsa/tests/test_ar.py

Fix warnings when fix is available
Catch remaining sm-produced warnings
<details>
**Notes**:
```
``` …

MAINT: Catch and fix warnings

---

statsmodels/base/data.py
statsmodels/regression/tests/test_regression.py

Workaround for bool data when using ptp
Also silences pandas ptp warning in this location
xref numpy/numpy#15057
<details>
**Notes**:
```
git diff upstream/master -u -- "*.py" | flake8 …
```

MAINT: Workaround NumPy ptp issue

---

docs/source/dev/test_notes.rst

Restore accidentally deleted summary for test
<details>
**Notes**:
```
``` …

DOC: Restore test() autosummary

---

statsmodels/tsa/stattools.py
statsmodels/tsa/tests/test_stattools.py

Add a check for finite values
closes #2344
<details>
**Notes**:
```
``` …

BUG: Ensure inputs are finite in granger causalty test

---

statsmodels/tsa/statespace/dynamic_factor.py
statsmodels/tsa/statespace/kalman_filter.py
statsmodels/tsa/statespace/kalman_smoother.py
statsmodels/tsa/statespace/mlemodel.py
statsmodels/tsa/statespace/representation.py
statsmodels/tsa/statespace/sarimax.py
statsmodels/tsa/statespace/simulation_smoother.py
statsmodels/tsa/statespace/structural.py
statsmodels/tsa/statespace/tests/test_impulse_responses.py
statsmodels/tsa/statespace/tests/test_representation.py
statsmodels/tsa/statespace/tests/test_simulate.py
statsmodels/tsa/statespace/varmax.py

Still need to do:
There are two primary purposes for this PR:
1. After fitting a model, allow simulating datasets starting from just after the last observation (i.e. conditional on the predicted state distribution after running the Kalman filter over the entire sample) - or more generally simulating datasets starting after any particular observation. This is via a new `anchor` argument.
2. Improve `simulate` and `impulse_responses` in time-varying state space models.
It also has makes other improvements:
- Centralizes the machinery for dealing with out-of-sample `exog` and trends, and so removes a fair amount of boilerplate in `get_prediction` methods.
- Adds a `repetitions` argument for generating multiple simulations.
- Adds methods for cloning and extending the `Representation` class …

ENH: State space: Improve simulate, IRF, prediction

---

statsmodels/tsa/statespace/mlemodel.py
statsmodels/tsa/statespace/tests/test_mlemodel.py
statsmodels/tsa/statespace/tools.py

Closes #6301.
Raises an understandable exception when `append` or `extend` is called with data that has an index that does not appear to extend the model's index.
Tests added.

ENH: append, extend check that index matches model

---

statsmodels/tsa/base/tsa_model.py

See #6302 for discussion.
Future versions will raise an error when trying to perform out-of-sample operations (like forecasting) in state-space models that were instantiated with data that has an unsupported index (e.g. a date index with no associated frequency or a non-monotonic Int64Index).

DEPR: state space: deprecate out-of-sample w/ unsupported index

---

statsmodels/tsa/statespace/mlemodel.py
statsmodels/tsa/statespace/tests/test_mlemodel.py

Closes #6335
Just adds an explicit type cast when integer parameters are given to `filter`, etc.
Usually only happens in testing, since otherwise not all (or any) parameters will be integers.

BUG: state space: integer params can cause imaginary output

---

docs/source/release/version0.11.rst
docs/source/statespace.rst
docs/source/tsa.rst

This PR adds documentation and release notes for several important improvements, including:
- New AR model, AutoReg (#6087)
- New ARIMA model (#5827)
- More robust regime switching models (#5826)
- State space improvements:
- Linear exponential smoothing models (#6179)
- Apply fitted parameters to new data (#5915)
- Fixed parameters (#5735)
- Low memory options (#6071 and follow-ups)
- Improved access to state estimates (#6181)
- Improvements to simulate/IRF for time-varying models (#6280)
Any improvements or corrections would be greatly appreciated.
@bashtage this edits `version0.11.rst` directly: is this okay to do since we have the new script for generating this file?

DOC: Documentation for release v0.11

---

statsmodels/nonparametric/_kernel_base.py
statsmodels/nonparametric/kernel_regression.py
statsmodels/nonparametric/kernels.py
statsmodels/nonparametric/tests/test_kernel_regression.py
statsmodels/sandbox/nonparametric/kernel_extras.py

Currently, KernelRegression supports only the Gaussian kernel. By adding the kernel as a parameter to the class, we can support custom kernels for the local linear mode of kernel regression.
This is useful for performing other nonparametric regressions. For example, this would now support the LOESS regression, which can be achieved by specifying local linear mode, and a tricube kernel. 
This PR also adds the tricube kernel to statsmodels library of kernels.

ENH: Supporting custom kernel in local linear kernel regression

---

statsmodels/tsa/vector_ar/tests/test_var.py
statsmodels/tsa/vector_ar/util.py
statsmodels/tsa/vector_ar/var_model.py

Use user supplied exog names if available
closes #6376
<details>
**Notes**:
```
``` …

BUG: Use correct exog names

---

statsmodels/tools/eval_measures.py
statsmodels/tools/tests/test_eval_measures.py
statsmodels/tools/validation/validation.py

Correct axis bug in iqr
closes #6384
<details>
**Notes**:
```
``` …

BUG: Fix axis in irq

---

.travis.yml
appveyor.yml
requirements-dev.txt

Pin xdist to 1.29 to avoid random test discovery failures
<details>
**Notes**:
```
``` …

MAINT: Pin xdist

---

statsmodels/regression/recursive_ls.py
statsmodels/regression/tests/test_recursive_ls.py

`RecursiveLS` can only allow parameter constraints via the constructor (because the way it is implemented changes the dimensions of the state vector, which is set in the constructor).

BUG: RecursiveLS should not allow `fix_params` method.

---

lint.sh
statsmodels/base/data.py
statsmodels/base/tests/test_generic_methods.py
statsmodels/compat/scipy.py
statsmodels/graphics/regressionplots.py
statsmodels/graphics/tests/test_regressionplots.py
statsmodels/sandbox/predict_functional.py
statsmodels/tsa/holtwinters.py
statsmodels/tsa/tests/test_holtwinters.py

Silence new warnings produced by pandas 1.0+
Ensure starting values respect builds in HoltWinters
<details>
**Notes**:
``` …
```

CLN: Fixes for future SciPY and pandas

---

statsmodels/discrete/tests/test_count_model.py
statsmodels/tsa/holtwinters.py
statsmodels/tsa/tests/test_holtwinters.py

Skip test on Linux32 which is failing
Improve bounds check for future SciPy
<details>
**Notes**:
```
```
assuming …

MAINT: Fixes for rc2

---

statsmodels/regression/recursive_ls.py
statsmodels/regression/tests/test_recursive_ls.py

Follow-up to #6415 that just improves the error message so that users know how to impose valid constraints in `RecursiveLS` models even though `fix_params` doesn't work.

REF: More descriptive error message for recursive least squares parameter constraints.

---

statsmodels/tsa/tests/test_arima.py

Change test to reduce risk of failure
<details>
**Notes**:
```
``` …

TST: Improve test that randomly fails

---

statsmodels/genmod/generalized_linear_model.py
statsmodels/genmod/tests/test_glm.py

Fix issue when alpha is a vector
closes #6441
<details>
**Notes**:
```
``` …

BUG: Fix bug in ridge for vector alpha

---

docs/source/conf.py

Fix the version that appears in a release
<details>
**Notes**:
```
``` …

DOC: Fix the version that appears in the documentaion

---

tools/ci/docbuild.sh

Send doctr log to /dev/null/ to prevent travis from limiting out
<details>
**Notes**:
```
``` …

DOC: Send log to dev/null/

---

lint.sh
setup.cfg
statsmodels/graphics/boxplots.py
statsmodels/graphics/tests/test_boxplots.py
statsmodels/tsa/innovations/tests/test_cython_arma_innovations_fast.py
statsmodels/tsa/tests/test_arima.py

Fix future warnings from numpy about ragged arrays
<details>
**Notes**:
```
``` …

MAINT: Fix future warnings

---

statsmodels/graphics/boxplots.py
statsmodels/stats/libqsturng/qsturng_.py

Fix issue which creates ragged arracy.
<details>
**Notes**:
```
``` …

MAINT: Fix issue with ragged array

---

.travis.yml

Cache to reduce docbuild time
<details>
**Notes**:
```
``` …

BLD: Attempt to cache key docbuild files

---

statsmodels/genmod/generalized_estimating_equations.py
statsmodels/genmod/generalized_linear_model.py

WIP to address this bug.  Subclass GEE and GEEResults from GLM and GLMResults.
**Notes**:
```
``` …

BUG: Fix exposure/offset handling in GEEResults

---

docs/source/install.rst
requirements-dev.txt
setup.py

Remove 3.5 and add 3.8
<details>
**Notes**:
```
``` …

MAINT: Remove Python 3.5 references

---

statsmodels/stats/diagnostic.py
statsmodels/stats/tests/test_diagnostic.py

This adds as an option to run the original heteroscedasticity test described by Breusch-Pagan.
I recently spent a few hours researching why the results from `het_breuschpagan` did not match Stata's output, only to realize that the standard heteroscedasticity test used in Stata is not implemented in Statsmodels. Instead Statsmodels uses a modified version, described by Koenker (1981). The existing implementation is equivalent to the Stata commands `estat hettest, iid` and `estat hettest, fstat`. By setting the parameter `iid=False`, the first two return values are now identical to Stata's default (`estat hettest`).

ENH: Add option for original Breusch-Pagan heteroscedasticity test

---

statsmodels/base/_constraints.py
statsmodels/base/_parameter_inference.py
statsmodels/base/tests/test_shrink_pickle.py
statsmodels/discrete/discrete_model.py
statsmodels/discrete/tests/test_constrained.py
statsmodels/genmod/generalized_linear_model.py

see #6427 
attaches constraints `R, q` instead of patsy constraints instance.
not backwards compatible but in a minor code (mainly as user information so far)
`GLM.score_test` and unit tests needed adjustments

REF/BUG: don't attach patsy constraint instance 

---

statsmodels/genmod/generalized_linear_model.py
statsmodels/genmod/tests/test_glm.py

<details>
Currently fails on a Tweedie/EQL regression test, but there is no independent verification of the values used in the regression test
**Notes**:
```
git diff upstream/master …
```

BUG: Change default optimizer for glm/ridge and make it user-settable

---

statsmodels/tsa/statespace/tests/test_exact_diffuse_filtering.py

Relax tolerance to avoid noise failues
<details>
**Notes**:
```
``` …

MAINT: Relax tolerance on test that occasionally fails

---

statsmodels/nonparametric/kde.py
statsmodels/nonparametric/tests/test_kernel_density.py
statsmodels/sandbox/nonparametric/kernels.py

Fix domain check in density estimation
closes #6546
<details>
**Notes**:
```
``` …

BUG: Fix domain check

---

statsmodels/tsa/statespace/mlemodel.py
statsmodels/tsa/statespace/tests/test_mlemodel.py

The `states` attribute added in v0.11 allows accessing the predicted, filtered, and smoothed states (and covariance matrices) as Pandas objects with proper indexes / columns.
Unfortunately, I set the index for the predicted states as going from e.g. `-1, 0, ..., nobs` instead of `0, ..., nobs, nobs + 1`. This fixes the problem and adds unit test.
We may want to issue a bugfix release for this.

BUG: `MLEResults.states.predicted` has wrong index

---

azure-pipelines.yml

Our Azure CI currently runs against Mac OS X 10.13, which is [being removed](https://devblogs.microsoft.com/devops/removing-older-images-in-azure-pipelines-hosted-pools/) in favor of Mac OS X 10.14.
Currently, Azure is running hour-long "brownouts" every day, but 10.13 will be removed on March 23.
This PR (hopefully) updates our CI job to use Mac OS X 10.14.

BLD: Azure: Mac OSX 10.13 -> 10.14

---

statsmodels/tsa/statespace/tests/test_exact_diffuse_filtering.py

Relax tolerance to eliminate random failure
<details>
**Notes**:
```
``` …

MAINT: Relax tolerance on test that randomly fails

---

statsmodels/tsa/statespace/_kalman_smoother.pxd
statsmodels/tsa/statespace/_kalman_smoother.pyx.in
statsmodels/tsa/statespace/kalman_smoother.py
statsmodels/tsa/statespace/tests/test_impulse_responses.py
statsmodels/tsa/statespace/tests/test_smoothing.py

We already compute the `lag=1` smoothed autocovariance matrix for the state vector (i.e. Cov(t, t-1)) in the Cython recursions (because it is required for the EM algorithm applied to the transition equation, and so it's best if it's pretty fast).
This PR adds a new `smoothed_state_autocovariance` method to the `SmootherResults` class to allow computing autocovariances with any `lag = 0, +-1, +-2, ...`. One application of this is computing the "news" for nowcasting models, described in Banbura and Modugo (2014). Not in Cython since as far as I know, this is just for postestimation results, and won't be in an inner loop.

ENH: state space: compute smoothed state autocovariance matrices for arbitrary lags

---

docs/source/statespace.rst

Found an instance of `true` lowercase which is a bug and should be `True`.
<details>
**Notes**:
```
```
assuming …

Fix `true` type on statespace docs page

---

statsmodels/genmod/cov_struct.py
statsmodels/genmod/tests/test_gee.py

Provide a non-default option to calculate the AR parameters for GEE using gridded data.

ENH Calculate AR covariance parameters for gridded data

---

statsmodels/regression/linear_model.py
statsmodels/regression/tests/test_regression.py

<details>
**Notes**:
```
```
using the …

BUG: statsmodels.regression.linear_model.OLS.fit_regularized fails to generate correct answer (#6604)

---

statsmodels/tsa/stattools.py
statsmodels/tsa/tests/test_stattools.py

Ensure the lwoer case comparrisons use lower case
close #6624
<details>
**Notes**:
```
``` …

BUG: Ensure text comparrison is lower

---

statsmodels/tsa/holtwinters.py
statsmodels/tsa/tests/test_holtwinters.py

Just two very small additions to #6560:
- I fixed the alignment of equations in the docstring of simulate
- I saw that one of the new tests was failing. I added a seed to the RNG to prevent it from failing due to RNG randomness.

DOC/TST: minor fixes for holtwinters simulate

---

statsmodels/regression/linear_model.py

Update the example of OLS by using the dataset.
Rebuild html and the docstring renders properly.
This is my first pull request, please let me know if there is anything I can improve. Thanks!

DOC: change OLS example to use datasets

---

statsmodels/stats/base.py
statsmodels/stats/tests/test_base.py

see #6637
I used a version of this for constraints in PR #6521
A Holder class that allows indexing and unpacking, but would still fail if we want to use it as an array or list, e.g. to combine several of those into an array or dataframe.
intended use for returns of hypothesis tests and similar function.

ENH: stats.base, add HolderTuple, Holder class with indexing

---

statsmodels/tools/tools.py
statsmodels/tsa/statespace/mlemodel.py
statsmodels/tsa/statespace/tests/test_exponential_smoothing.py

Fix bug where empty arrays raised in linear algebra functions
closes #6687
<details>
**Notes**:
```
```
assuming …

BUG: Fix covariance estimation in parameterless models

---

statsmodels/stats/multivariate.py
statsmodels/stats/tests/test_multivariate.py

see e.g. #3208
I thought I already wrote something like this but don't find anything.
This is currently just a short exercise writing some basic multivariate mean tests to get started.
plans for implementation
There is a lot of repeated computation if we provide and use separate function that all start from data. Those standalone functions are good to get started but need better structure. 
Most likely the pattern will or should follow weightstats with a mixture of classes and standalone functions. One useful pattern is to have the functions based on summary statistics, so we have to compute those only once.
Reference for this time is Johnson and Wichern Applied Multivariate Statistical Analysis 6th edition. (I started to browse it by chance.)
Stata mvtests has good functions with almost …

ENH: multivariate mean tests and confint

---

statsmodels/stats/multitest.py

A very quick documentation PR, since I noticed argument description of `statsmodels.stats.multitest.fdrcorrection` was missing documentation for the `is_sorted` parameter. 
I copied the text from `statsmodels.stats.multitest.multipletests`.
<details>
**Notes**:
* New code additions must be well formatted. Changes should pass flake8. …

DOC: Fix `fdrcorrection` docstring missing `is_sorted` parameter

---

lint.sh
setup.cfg
statsmodels/genmod/tests/test_qif.py
statsmodels/multivariate/pca.py
statsmodels/multivariate/tests/test_pca.py
statsmodels/tools/validation/validation.py
statsmodels/tsa/arima/estimators/tests/test_gls.py
statsmodels/tsa/vector_ar/hypothesis_test_results.py

Improve missing value handling
Ensure a warning is correctly raised when using GLS weights if needed
closes #6483
<details>
**Notes**:
``` …
```

BUG\ENH: Improve missing value handeling in PCA

---

examples/notebooks/statespace_sarimax_stata.ipynb

closes #6683
<details>
**Notes**:
```
``` …

DOC: Fix number if notebook text

---

statsmodels/tsa/statespace/tests/test_exact_diffuse_filtering.py
statsmodels/tsa/stattools.py
statsmodels/tsa/tests/test_stattools.py

Improve warning message to be more exaplantory
Relax tolerance on randomly failing test
closes #6684
xref #6468
<details>
**Notes**:
```
git diff upstream/master -u -- "*.py" | flake8 …
```

ENH: Improve warning message in KPSS

---

statsmodels/tsa/_stl.pyx
statsmodels/tsa/tests/test_stl.py

Change initialization to match suggestion in STLEZ function
closes #6701
<details>
**Notes**:
```
``` …

BUG: Change trend initialization in STL

---

statsmodels/tsa/vector_ar/tests/test_var.py
statsmodels/tsa/vector_ar/var_model.py

Check that nlags is larger than the number of lags included
in the model
closes #6686
<details>
**Notes**:
```
``` …

ENH: Add check in test_whiteness

---

statsmodels/stats/diagnostic.py
statsmodels/stats/tests/test_diagnostic.py

Raise if the first model has a regressor matrix that is not positive definite
<details>
**Notes**:
```
```
assuming …

ENH: Raise exception when recursive residual is not well defined

---

statsmodels/genmod/bayes_mixed_glm.py

Replace with int64 which is the default on most systems
<details>
**Notes**:
```
``` …

MAINT: Remove dtype np.integer for avoid Dep Warning

---

statsmodels/tsa/vector_ar/tests/test_var.py
statsmodels/tsa/vector_ar/var_model.py

Raise ValueError when exog has incorrect size
closes #6636
<details>
**Notes**:
```
``` …

BUG: Raise on incorrectly sized exog

---

statsmodels/tsa/vector_ar/irf.py
statsmodels/tsa/vector_ar/tests/test_var.py

Include figsize as parameter for IRF-related plots, since it is available for [`irf_grid_plot`](https://github.com/statsmodels/statsmodels/blob/master/statsmodels/tsa/vector_ar/plotting.py#L188). Without this, it is still possible to change the figure size, but it has to be done afterwards through `fig.set_size_inches(x, y)`, so this PR brings ease to the customization of figure size.
<details>
**Notes**:
* When fixing a bug, you must add a test that would …

ENH: Include figsize as parameter for IRF plot

---

statsmodels/duration/survfunc.py
statsmodels/duration/tests/test_survfunc.py

`Survdiff` conducts logrank test on survival data. Before this PR it was only possible to test survival data with 2 groups, while now it is possible for any N groups.
Calculations based on: https://web.stanford.edu/~lutian/coursepdf/unit6.pdf
But variance taken from: https://web.stanford.edu/~lutian/coursepdf/survweek3.pdf
Tests pass!
(there is also a backport to v0.11.1: https://github.com/statsmodels/statsmodels/pull/6625)
<details>
**Notes**:
* When fixing …

ENH: allow more than 2 groups for survdiff in statmodels.duration

---

docs/source/dev/index.rst
docs/source/imputation.rst
docs/source/install.rst
docs/source/mixed_linear.rst
docs/source/sandbox.rst
statsmodels/nonparametric/_kernel_base.py

This PR updates links with 404 error. There are still links where the page exists, but not the anchor (mostly links to SAS documentation).

DOC: Fix broken links with 404 error

---

statsmodels/tsa/statespace/tests/test_forecasting.py
statsmodels/tsa/statespace/tools.py

Fixes the `statsmodels.tsa.statespace.tools.concat` when the objects have different dimensions.

BUG: dataframe/series concatenation in statespace results append

---

statsmodels/tsa/arima/model.py
statsmodels/tsa/arima/tests/test_model.py

These arguments were just not included in the `super()` call.

BUG: pass cov_type, cov_kwargs through ARIMA.fit

---

docs/source/_static/stylesheets/deprecation.css
docs/source/_templates/layout.html

Improve deprecation presentation in the docs
<details>
**Notes**:
```
``` …

DOC: Make deprecations more visible

---

statsmodels/tsa/statespace/_kalman_filter.pxd
statsmodels/tsa/statespace/_kalman_filter.pyx.in
statsmodels/tsa/statespace/_kalman_smoother.pyx.in
statsmodels/tsa/statespace/_representation.pxd
statsmodels/tsa/statespace/_representation.pyx.in
statsmodels/tsa/statespace/_simulation_smoother.pyx.in
statsmodels/tsa/statespace/_smoothers/_univariate.pyx.in
statsmodels/tsa/statespace/_smoothers/_univariate_diffuse.pyx.in
statsmodels/tsa/statespace/tests/test_multivariate_switch_univariate.py

This PR does the following:
1. Improves the performance of the univariate smoother about 4x in the case of a large state vector.
2. Allows the multivariate filter / smoother to fall back to the univariate filter / smoother when the multivariate filter would fail (i.e. when the forecast error covariance matrix is singular)
3. Fixes a bug in the computation of the "innovation transition" matrix in the diffuse initialization case
4. Fixes a bug with the multivariate smoother in diffuse periods when all observations are missing.
Note that in models with a large number of `endog` variables (e.g. 100+) that also have a large state vector, the univariate smoother can be much slower than the multivariate smoother (e.g. 10x slower), even given the improvements in (1). That's why (2) is useful: it …

ENH: improve univariate smoother performance

---

statsmodels/nonparametric/bandwidths.py
statsmodels/nonparametric/tests/test_bandwidths.py

kernel.normal_reference_constant is a property and it is only
accessible on an instantiated object. This commit enforces that
in the bw_normal_reference function.
<details>
**Notes**:
verify you changes are well formatted by running …

BUG: Fix access to normal_reference_constant

---

statsmodels/stats/diagnostic.py
statsmodels/stats/tests/test_diagnostic.py

With reference to issue [#6645](https://github.com/statsmodels/statsmodels/issues/6645)
Automatic lag selection according to the reference below for Box-Pierce, Ljung-Box. According to the reference at page8, it introduces a penalty term, which switches between AIC and BIC depending on the value of correlation. This penalty term penalises the test statistic and the optimal lag length is one which is able to maximise the test statistic after applying the penalty.
A q value of 2.4 is recommended in the reference for the penalty term according to other research results quoted.
[Reference](https://www.sciencedirect.com/science/article/abs/pii/S0304407609000773?via%3Dihub# …

ENH: automatic lag selection for Box-Pierce, Ljung-Box #6645

---

statsmodels/regression/linear_model.py
statsmodels/regression/tests/test_regression.py

Remove Warnings and lable them as notes
closes #6821
<details>
**Notes**:
```
``` …

MAINT: Replace Warnings with Notes in regression summary

---

statsmodels/tools/tools.py
statsmodels/tsa/tests/test_arima.py
statsmodels/tsa/tsatools.py

Return information about constant columns in add_constant
closes #6756
<details>
**Notes**:
```
``` …

ENH: Return column information in add_constant

---

statsmodels/stats/tests/test_moment_helpers.py

see https://github.com/statsmodels/statsmodels/issues/6796#issuecomment-641463139
unit test defines random state instance but doesn't use it

TST: stats moment_helpers use random state in unit test

---

statsmodels/regression/quantile_regression.py

When calling [`QuantReg.fit()`](https://www.statsmodels.org/devel/generated/statsmodels.regression.quantile_regression.QuantReg.fit.html#statsmodels.regression.quantile_regression.QuantReg.fit), the parameter `q` (indicating the quantile) is checked to be within the interval [0, 1] (lines [119-120](https://github.com/statsmodels/statsmodels/blob/d4d46c84bba5bfd58f94b6954046ff90fab84a6b/statsmodels/regression/quantile_regression.py#L119)). However, also values of q=0 or q=1 will cause the fit() method to crash (raising `numpy.linalg.LinAlgError: SVD did not converge`). The reason for this behavior is in the way the residuals are weighted in line …

BUG: Insufficient input checks in QuantReg

---

lint.sh
statsmodels/regression/rolling.py
statsmodels/regression/tests/test_rolling.py

Allow the rolling estimators to be used with an expanding initial window
until some number of observations have occurred.
closes #6717
<details>
**Notes**:
```
git diff upstream/master …
```

ENH: Add expanding initialization to RollingOLS/WLS

---

tools/ci/docbuild_install.sh

Looks like they've pushed the new numpydoc to pypi.
<details>
**Notes**:
```
``` …

MAINT: numpydoc should work now

---

statsmodels/regression/linear_model.py
statsmodels/regression/tests/test_regression.py

Add a not explaining when R2 is uncentered
closes #5550
<details>
**Notes**:
```
``` …

ENH: Add  a note when R2 is uncentered

---

statsmodels/tsa/stattools.py

Remove redundant definition of ResultsStore in favor of better implementation
<details>
**Notes**:
```
```
assuming …

MAINT: Remove redundant definition

---

statsmodels/formula/tests/test_formula.py
statsmodels/genmod/_prediction.py
statsmodels/regression/_prediction.py

ALlow Series to be used as exog in predict
closes #6509
<details>
**Notes**:
```
``` …

BUG: Allow Series as exog in predict

---

statsmodels/tsa/stattools.py
statsmodels/tsa/tests/test_stattools.py

Limit lag length to 50% of the same to ensure that the autocovariance
matrix may be positive definite
closes #4663
<details>
**Notes**:
``` …
```

BUG: Ensure PACF lag length is sensible

---

statsmodels/stats/stattools.py
statsmodels/stats/tests/test_statstools.py

Tests for the function durbin_watson function in stats/stattools.py already exist in the stats/tests folder, so I removed the TODO asking for this. Also added new tests which test the function when the input array is multi-dimensional. Also cleaned up the docstring of the function a little.
Note: when updating the docstring, e.g. when adding information on the 'axis' parameter (which was not previously there), I have chosen to be consistent with the jarque_bera function in the same module.
This is my first statsmodels PR. Please let me know if I need to edit anything :).
<details>
**Notes**:
* It is essential that you add a test when making code changes. Tests are …

Updated durbin_watson Docstring and Tests

---

statsmodels/stats/tests/test_corrpsd.py
statsmodels/tsa/arima/tests/test_model.py
statsmodels/tsa/tests/test_arima.py

Relax tolerance on test that occasionally fails
<details>
**Notes**:
```
``` …

TST: Relax tolerance on test that fils Win32

---

statsmodels/stats/tests/test_corrpsd.py

Correct debugging information on test factor
<details>
**Notes**:
```
``` …

MAINT: Correct debuggin info

---

statsmodels/regression/linear_model.py

Explain the low df in cluster
closes #6555
<details>
**Notes**:
```
``` …

DOC: Explain low df in cluster

---

statsmodels/tsa/statespace/tests/test_smoothing.py

Relax tolerance to avoid spurious failures
<details>
**Notes**:
```
``` …

MAINT: Relax test tolerance

---

statsmodels/tsa/arima/estimators/gls.py
statsmodels/tsa/arima/tests/test_model.py
statsmodels/tsa/arima_process.py
statsmodels/tsa/innovations/arma_innovations.py
statsmodels/tsa/innovations/tests/test_arma_innovations.py

closes #6540
<details>
**Notes**:
```
``` …

BUG: Raise on nonstationary parameters when attempting to use GLS

---

statsmodels/stats/tests/test_corrpsd.py

Refactor tests to prevent random failures
<details>
**Notes**:
```
``` …

TST: Refactor factor tests again

---

statsmodels/tsa/holtwinters.py
statsmodels/tsa/tests/test_holtwinters.py

Fix index when using int indices
closes #6549
<details>
**Notes**:
```
``` …

BUG: Fix indexing with HoltWinters's forecast

---

statsmodels/stats/tests/test_dist_dependant_measures.py

Allow test ot be skipped when data is not available
<details>
**Notes**:
```
``` …

MAINT: Allow skip if rdataset fails

---

statsmodels/tsa/stattools.py
statsmodels/tsa/tests/test_stattools.py

Issue #6876: Fix for the appropriate behavior when passing a list
containing a zero lag to `maxlag` (e.g. `[0, 1, 2]`), now it raises
`ValueError`
<details>
**Notes**:
```
git diff …
```

BUG: fix raise exception on granger causality test

---

.travis.yml
docs/source/install.rst
pyproject.toml
requirements.txt
statsmodels/base/model.py
statsmodels/genmod/generalized_linear_model.py
statsmodels/regression/_prediction.py
statsmodels/regression/linear_model.py
statsmodels/regression/rolling.py
statsmodels/regression/tests/test_predict.py
statsmodels/robust/robust_linear_model.py
statsmodels/stats/contingency_tables.py
statsmodels/tests/test_package.py
statsmodels/tsa/exponential_smoothing/initialization.py
statsmodels/tsa/statespace/mlemodel.py
statsmodels/tsa/statespace/tools.py

Correct exog dimension when data has been removed
closes #6887
<details>
**Notes**:
```
``` …

BUG: Correct dimension when data removed

---

statsmodels/tsa/ar_model.py
statsmodels/tsa/statespace/mlemodel.py
statsmodels/tsa/statespace/tests/test_conserve_memory.py
statsmodels/tsa/statespace/tests/test_fixed_params.py
statsmodels/tsa/statespace/tests/test_mlemodel.py
statsmodels/tsa/statespace/tests/test_sarimax.py
statsmodels/tsa/tests/test_ar.py

Change the default lag to use a smaller value in serial correlation tests
closes #3381
<details>
**Notes**:
```
``` …

MAINT: Change default lag in serial correlation tests

---

statsmodels/iolib/summary2.py
statsmodels/iolib/tests/test_summary2.py

Fix header alignment to prevent extra table
<details>
**Notes**:
```
``` …

ENH: Fixed the shifted column names in summary.to_latex()

---

statsmodels/tsa/holtwinters/model.py
statsmodels/tsa/holtwinters/results.py
statsmodels/tsa/holtwinters/tests/test_holtwinters.py

Stop transforming components in ExponentialSmoothing models
closes #6629
<details>
**Notes**:
```
``` …

BUG: Stop transforming ES components

---

statsmodels/graphics/gofplots.py
statsmodels/graphics/tests/test_gofplots.py
statsmodels/tsa/statespace/tests/test_exact_diffuse_filtering.py

Ensure that uneven samples are suppported irrespective of the input position
closes #677
<details>
**Notes**:
```
``` …

ENH: Enable qqplot_2sample to handle uneven samples

---

statsmodels/iolib/summary2.py

Proposing to remove the hline between the tabulars of the latex table created by the "to_latex()" function of the statsmodels.iolib.summary2.Summary class.
```
import pandas as pd
import statsmodels.formula.api as smf
df = pd.DataFrame(np.random.rand(10, 3), columns=['var1', 'var2', 'var3'])
dependent_variable = 'var1'
expression = 'var3'
formula = 'Q("{}") ~ {}'.format(dependent_variable, expression)
model = smf.mixedlm(formula, df, groups='var2')
fit = model.fit()
summary = fit.summary()
latex_summary = summary.as_latex()
print(latex_summary)
```

removed additional hline between tabulars

---

statsmodels/iolib/summary2.py
statsmodels/iolib/tests/test_summary2.py

Proposing a label option to the statsmodels.iolib.summary2.Summary class such that the resulting latex table can be referenced in a latex document.
Below a small example showing the latex table with label:
```
import pandas as pd
import statsmodels.formula.api as smf
df = pd.DataFrame(np.random.rand(10, 3), columns=['var1', 'var2', 'var3'])
dependent_variable = 'var1'
expression = 'var3'
formula = 'Q("{}") ~ {}'.format(dependent_variable, expression)
model = smf.mixedlm(formula, df, groups='var2')
fit = model.fit()
summary = fit.summary()
summary.label = 'MyLabel'
latex_summary = summary.as_latex()
print(latex_summary)
```
```
\begin{table}
\caption{Mixed Linear Model Regression Results}
\label{MyLabel}
\begin{center}
\begin{tabular}{llll}
\hline
Model:            & …
```

Added label option to summary.to_latex()

---

statsmodels/nonparametric/_smoothers_lowess.pyx
statsmodels/nonparametric/smoothers_lowess.py
statsmodels/nonparametric/tests/test_lowess.py

xvals allows evaluation of the lowess smoother at
x-values other than those used in the smoothing, for example
fitting from some points and using that to 'predict' others
<details>
**Notes**:
verify you changes are well formatted by …

ENH: Add xvals param to lowess smoother

---

setup.cfg
statsmodels/discrete/discrete_model.py
statsmodels/imputation/tests/test_ros.py
statsmodels/regression/_tools.py
statsmodels/tools/tests/test_tools.py
statsmodels/tsa/ar_model.py
statsmodels/tsa/deterministic.py
statsmodels/tsa/holtwinters/model.py
statsmodels/tsa/holtwinters/tests/test_holtwinters.py
statsmodels/tsa/tests/test_exponential_smoothing.py

Remove future warnings from pandas, NumPy and internal
<details>
**Notes**:
```
``` …

MAINT: Remove FutureWarnings

---

statsmodels/tsa/base/tsa_model.py
statsmodels/tsa/statespace/kalman_filter.py
statsmodels/tsa/statespace/mlemodel.py
statsmodels/tsa/statespace/tests/test_sarimax.py

@ChadFulton Seems to be a bug in get_prediction with dynamic not an int.  I also pulled some code to share with other forecasting methods.
<details>
**Notes**:
```
git diff …
```

BUG: dynamic is incorrect when not an int in statespace get_prediction

---

statsmodels/gam/smooth_basis.py
statsmodels/gam/tests/test_smooth_basis.py

The docstring for `BSplines` appears to have been copied from that of  `UnivariateCubicCyclicSplines`, as it specified the `df` and `degree` parameters to be integers, but in fact required them to be lists (raising a `TypeError: 'int' object is not subscriptable` if either was an integer)
- Fixed docstring to specify `{list[int], int}` instead
- Implemented support for integers by converting `df` and `degree` to lists if they aren't already
- Added `test_bsplines` parameterised test to test the creation of BSplines instances and the transformation of their original data
<details>
**Notes**:
* It is essential that you add a test when making code changes. Tests are not …

Fixed BSplines to match existing docs

---

statsmodels/duration/hazard_regression.py
statsmodels/regression/dimred.py
statsmodels/robust/robust_linear_model.py
statsmodels/tools/docstring.py
statsmodels/tsa/_stl.pyx
statsmodels/tsa/arima/model.py
statsmodels/tsa/arima/specification.py
statsmodels/tsa/statespace/mlemodel.py

Silence warning and fix documentation errors
<details>
**Notes**:
```
``` …

DOC/MAINT: Fix doc errors and silence warning

---

statsmodels/genmod/generalized_linear_model.py
statsmodels/genmod/tests/test_glm.py

<details>
**Notes**:
```
```
using the …

Make glm's predict function return numpy array even if exposure is a pandas series

---

statsmodels/tsa/statespace/mlemodel.py
statsmodels/tsa/statespace/tests/test_sarimax.py
statsmodels/tsa/stattools.py

<details>
**Notes**:
```
```
using the …

    BUG: SARIMAX throwing different errors when length of endogenous var is too low

---

statsmodels/tsa/statespace/sarimax.py
statsmodels/tsa/statespace/tests/test_sarimax.py

<details>
**Notes**:
```
```
using the …

BUG: Fix start params computation with few nobs

---

statsmodels/tsa/statespace/tests/test_dynamic_factor_mq.py

Relax tolerance on test that fails occasionally
<details>
**Notes**:
```
``` …

TST: Relax tolerance on random failure

---

statsmodels/tools/validation/validation.py

Add docstring to string_like method
<details>
**Notes**:
```
``` …

DOC: Add docstring to string_like method

---

statsmodels/robust/scale.py
statsmodels/robust/tests/test_scale.py

This is regarding the recently added robust.scale.iqr, which computes the normalized interquartile range. Since quantiles are translation equivariant, the interquartile range as an estimate of scale does not need centering. Centering, as implemented now, does not hurt either, it is inconsequential, but there is no need for it. This PR simply removes centering from robust.scale.iqr.
- [Y] tests added / passed. 
- [Y] code/documentation is well formatted.  
- [Y] properly formatted commit message. See 
<details>
**Notes**:
* When adding a new function, test values …

ENH/BUG: robust.scale.iqr does need centering, since quantiles are translation equivariant

---

statsmodels/nonparametric/kde.py
statsmodels/nonparametric/tests/test_kde.py

Return the fitted instance to simplify chaining
<details>
**Notes**:
```
``` …

ENH: Return self from KDEUnivariate fit

---

lint.sh
statsmodels/nonparametric/kde.py
statsmodels/nonparametric/tests/test_kde.py

<details>
**Notes**:
```
```
using the …

ENH: Allow custom bandwidth functions in KDEUnivariate fit

---

docs/source/stats.rst
statsmodels/stats/nonparametric.py
statsmodels/stats/tests/test_nonparametric.py
statsmodels/tools/testing.py

see #6960 stochastically larger, with notes and references leading to this PR
and #3575 brunner-munzel test
includes
- standard brunner munzel test
- brunner-munzel type test for non-zero (not equal 0.5) null hypothesis for stochastically-larger probability, including one-sided
- equivalence test, tost version of above
- confidence interval for the probability
location: new module stats.nonparametric

ENH: add prob(x1 > x2) effect size measure, inference based on brunner munzel

---

statsmodels/tsa/statespace/tests/test_varmax.py
statsmodels/tsa/statespace/varmax.py

Fixes incorrect ordering of drift / higher order trend terms in the parameter names list for VARMAX.

BUG: param names with higher order trend in VARMAX

---

statsmodels/tsa/arima/model.py
statsmodels/tsa/arima/specification.py
statsmodels/tsa/statespace/sarimax.py
statsmodels/tsa/statespace/tests/test_sarimax.py

REF: Don't validate specification in SARIMAX when cloning to get extended time varying matrices

---

statsmodels/tsa/stattools.py
statsmodels/tsa/tests/test_stattools.py

Ensure that it is always defined even when all t-stats are small
closes #7014
<details>
**Notes**:
```
```
assuming …

BUG: Ensure bestlag is defined in autolag

---

statsmodels/tsa/statespace/dynamic_factor.py

Fixes small typo in description of error order in a dynamic factor model. Link to doc page for convenience: https://www.statsmodels.org/stable/generated/statsmodels.tsa.statespace.dynamic_factor.DynamicFactor.html#statsmodels.tsa.statespace.dynamic_factor.DynamicFactor

DOC: Fix typo in error order of Dynamic Factor model docs

---

statsmodels/tsa/exponential_smoothing/ets.py
statsmodels/tsa/tests/test_exponential_smoothing.py

- [x ] closes #7018 
- [x ] tests added / passed. 
- [x ] code/documentation is well formatted.  
- [x ] properly formatted commit message. See 
<details>
Fixed the issue where the ETSModel get_prediction method fails when start is greater than the last index. Modified test case to reflect this use case, which would fail on master and would pass once this branch is merged.
**Notes**:
* When fixing a bug, you must add a test that would produce the bug in …

Bug fix ets get prediction

---

statsmodels/regression/process_regression.py
statsmodels/regression/tests/test_processreg.py

The process noise is white noise that is added to the process realization.  This PR allows that form of variance to be switched off, so that the process is observed directly instead of with additive noise.

ENH: Make additive noise optional for ProcessReg

---

statsmodels/tsa/holtwinters/results.py
statsmodels/tsa/holtwinters/tests/test_holtwinters.py

Avoid oversqueezing the array
closes #7053
<details>
**Notes**:
```
``` …

BUG: Fix squeeze when nsimulation is 1

---

examples/notebooks/stationarity_detrending_adf_kpss.ipynb

<details>
**Notes**:
```
```
using the …

DOC: Fix contradicting KPSS-statistics interpretations in stationarity_detrending_adf_kpss.ipynb

---

statsmodels/stats/oneway.py
statsmodels/stats/rates.py
statsmodels/stats/robust_compare.py

Fixes most of the issues raised in #7032, along with some other minor stuff that I found. The only thing I couldn't figure out how to solve is the duplicate methods entry in the TrimmedMean docs.
<details>
**Notes**:
```
``` …

DOC: fix several doc issues in stats functions

---

statsmodels/base/optimizer.py

- [ N/A] closes #xxxx
- [ N/A] tests added / passed. 
- [ x] code/documentation is well formatted.  
- [ x] properly formatted commit message. See 
<details>
Added docstrings for statsmodels.base.optimizer as first contribution.
**Notes**:
* New code additions must be well formatted. Changes should pass flake8. If on Linux or OSX, …

DOC: augmented docstrings from statsmodels.base.optimizer

---

statsmodels/tsa/forecasting/tests/test_theta.py
statsmodels/tsa/forecasting/theta.py

Prediction intervals are using the wrong expression
<details>
**Notes**:
```
``` …

BUG: Correct prediction intervals for ThetaModel

---

statsmodels/tsa/statespace/news.py

Fixes an issue where impacts tables raise an error if there is no news, rather than simply producing an empty table.

BUG: don't raise error in impacts table if no news.

---

statsmodels/tsa/holtwinters/tests/test_holtwinters.py

I see the following on s390x architecture in Ubuntu 21.04 development:
Arrays are not almost equal to 1 decimals
ACTUAL: 6082.159328812731
DESIRED: 6082.0

Loosen tolerance in TestHoltWinters.test_holt_damp_fit

---

statsmodels/gam/generalized_additive_model.py

Fixing a small typo in plot_partial function's docstring.

A small typo in GAM

---

statsmodels/tsa/exponential_smoothing/base.py
statsmodels/tsa/tests/test_exponential_smoothing.py

Just removed an unnecessary `squeeze`.

BUG: Remove unnecessary squeeze in ETS

---

statsmodels/tsa/tests/test_exponential_smoothing.py

Skip tests on Linux 32 that repeatedly fail.  Test is not well defined and already
has a very large tolerance
<details>
**Notes**:
```
git diff upstream/master -u -- "*.py" | flake8 …
```

MAINT: Skip test on Linux 32

---

tools/ci/travis_pip.sh

This doesn't necessarily needs to be merged, but I wanted to check that statsmodels' CI is passing with pandas' latest version, and currently that build is not running because of https://github.com/scipy/scipy/issues/13196

CI: use legacy pip solver to trigger a build with --pre packages

---

tools/ci/azure/azure_template_posix.yml

Limit linting to one per distinct version
<details>
**Notes**:
```
``` …

MAINT: Limit linting

---

docs/source/spelling_wordlist.txt
statsmodels/tsa/ar_model.py
statsmodels/tsa/stattools.py

Improve bic docstring in ar models
Improve explaination of maxlag in adfuller
closes #7238
closes #7143
<details>
**Notes**:
``` …
```

DOC: Improve doc strings

---

statsmodels/discrete/discrete_model.py
statsmodels/discrete/tests/test_discrete.py

see #7210  Probit does not support continuous interval data
this PR adds the binary check to Probit and raises for non 0-1 endog.
I didn't change loglike of Logit which is incorrect for continuous data, everything else in Logit seems fine
(changing loglike in Logit will add possible problems with 0 log 0, so refactoring needs to be more careful)

BUG: raise if non-binary endog in Probit

---

docs/source/discretemod.rst
statsmodels/base/covtype.py
statsmodels/regression/linear_model.py

Fix wrong indentation
<details>
**Notes**:
```
``` …

DOC: Improve docstring formatting

---

statsmodels/tsa/_stl.pyx
statsmodels/tsa/tests/test_stl.py

Add reduce so STL can be pickled
closes #7248
<details>
**Notes**:
```
``` …

BUG: Enable pickling of STL object

---

statsmodels/tsa/arima/model.py
statsmodels/tsa/arima/tests/test_model.py
statsmodels/tsa/statespace/sarimax.py

New behavior is:
1. Raises a `ValueError` if you try to specify a trend term that is not identified given the model's order of integration
2. Fixes a bug when forecasting with a time trend (not a constant, but t, t^2, etc.)

ENH/BUG: update ARIMA models trend term handling

---

statsmodels/tsa/statespace/mlemodel.py
statsmodels/tsa/statespace/tests/test_mlemodel.py

The sample code below demonstrates the discrepancy of statsmodels output of Ljung-Box serial correlation test p-value due to faulty degrees of freedom used in the test. The correct version should include subtraction of estimated model's degrees of freedom. This change will significantly align the output with R's Arima() output given by checkresiduals(). The remaining differences are probably due to different state space representation used and other minor technical differences.
**Statsmodels version**: 0.12.1
```
import pandas as pd
import statsmodels.tsa.api as tsa
import rpy2
import warnings
from scipy.stats import boxcox
from statsmodels.tsa.arima.model import ARIMA
warnings.filterwarnings("ignore")
%load_ext rpy2.ipython
passengers = …
```

ENH: Add small sample df adjustment option to test_serial_correlation

---

statsmodels/tsa/statespace/structural.py

I fixed some small errors and typos in [docs of UnobservedComponents](https://www.statsmodels.org/dev/generated/statsmodels.tsa.statespace.structural.UnobservedComponents.html#statsmodels.tsa.statespace.structural.UnobservedComponents).

DOC: Fixed LaTeX errors and a markdown typo in UnobservedComponents

---

statsmodels/discrete/tests/test_discrete.py

adjust unit test so expected tail observations are not left out
tail probability is very small but too large for latest scipy which added a requirement in chisquare test

TST/MAINT: make chisquare test for genpoisson more accurate

---

statsmodels/discrete/discrete_model.py
statsmodels/discrete/tests/test_count_model.py

closes #7015 closes #7127
this is a rebased and a bit cleaned up version of #7127
- remove pep-8 reformatting of entire module
- adjust test case so we don't get warnings

BUG/ENH: Poisson offset rebased

---

statsmodels/distributions/discrete.py
statsmodels/distributions/tests/test_discrete.py

- see #7161
This removes the extra `.mean()` in the `_var` methods of zero inflated distributions in distributions.discrete.
Now they can be called with vectorized mean parameter.
Unit tests only verify the Poisson special case, but now vectorized.
However,
The scipy distribution framework does **not** use `_mean` and `_var`, so calling `mean` and `var` still goes through the generic path.
In the scipy version that I use, moments, stats, mean, var are not vectorized.
AFAICS, in scipy master they should be vectorized, at least mean, var and stats.
This will need a proper solution, either we define `mean` and `var` without going through scipy, or we define  mean and var in `_stats` which might be vectorized for some recent scipy.
Changing this will need checking with different scipy …

BUG/TST: fix _mean, _var in distributions ZI count models

---

statsmodels/discrete/tests/test_sandwich_cov.py
statsmodels/genmod/families/family.py
statsmodels/genmod/families/links.py
statsmodels/genmod/families/tests/test_link.py

this is #7226 but without the changes to the CDFLink class, i.e. fully backwards compatible
adds explicit deriv2 to probit and cauchy link
I included the changes for zero division in binomial corner cases

BUG/PERF: Improve probit and cauchy link

---

statsmodels/graphics/gofplots.py
statsmodels/graphics/tsaplots.py
statsmodels/tsa/statespace/mlemodel.py
statsmodels/tsa/stattools.py

Although the current implementation of time series diagnostic plots provided by `plot_diagnostics()` method is quite solid, I've identified several aspects that could make the output more visually attractive, giving users more customization options during their analysis of the model's residuals and, most importantly, fixed currently not optimal selection of Bartlett's standard error for ACF values. 
I've been inspired by the well-designed diagnostic plot available in R's `checkresiduals()` and found that statsmodels uses confidence intervals employing Bartlett's formula even for model's residuals, when, according to the theory, the constant s.e. of 1/sqrt(N) should be used instead. This can be confirmed even by looking directly to the code …

ENH/BUG: Add flexibility options to plot_diagnostics output. 

---

statsmodels/stats/diagnostic.py

Replace vector of 1s with vector of 0s in acorr lm
<details>
**Notes**:
```
``` …

BUG: Correct LM Test

---

statsmodels/tsa/statespace/structural.py

I added description of `observed` parameter to [docs of UnobservedComponentsResults.plot_components()](https://www.statsmodels.org/stable/generated/statsmodels.tsa.statespace.structural.UnobservedComponentsResults.plot_components.html#statsmodels.tsa.statespace.structural.UnobservedComponentsResults.plot_components) because it is missing.

DOC: add a missing parameter description in UnobservedComponentsResults

---

statsmodels/tsa/statespace/mlemodel.py
statsmodels/tsa/statespace/structural.py

I added links to the doc of [UnobservedComponentsResult](https://www.statsmodels.org/stable/generated/statsmodels.tsa.statespace.structural.UnobservedComponentsResults.html#statsmodels.tsa.statespace.structural.UnobservedComponentsResults) in docs of [MLEModel.fit](https://www.statsmodels.org/stable/generated/statsmodels.tsa.statespace.mlemodel.MLEModel.fit.html#statsmodels.tsa.statespace.mlemodel.MLEModel.fit) and [UnobservedComponents](https://www.statsmodels.org/stable/generated/statsmodels.tsa.statespace.structural.UnobservedComponents.html#statsmodels.tsa.statespace.structural.UnobservedComponents).
The purpose of this PR is that users will be able to find the page of UnobservedComponentsResults more easily.
In the current documentation, users cannot find the doc of …

DOC/ENH: make it easier to find the page of UnobservedComponentsResults

---

statsmodels/stats/diagnostic.py
statsmodels/stats/tests/test_diagnostic.py

In ARMA models without constant (or ARMAX without constant and without exogs) the acorr_breusch_godfrey method don't check if res.model.exog is None.
If it's None then where is a ValueError. I add a check before use exog, if is None, then we use only the lags terms.

BUG: acorr_breusch_godfrey, problem with regressions without const or exogs

---

statsmodels/tsa/statespace/structural.py

I found the description of two parameters (`endog` and `mle_regression`) missing in the docstring of UnobservedComponents.

DOC: add missing parameters to docs of UnobservedComponents

---

statsmodels/tsa/forecasting/stl.py
statsmodels/tsa/forecasting/tests/test_stl.py

Ensure that start is correctly defined when None
xref #7309
<details>
**Notes**:
```
``` …

BUG: Fix STLForecast when start is None

---

examples/notebooks/ets.ipynb

DOC: fix misleading ETSModel example

---

docs/source/nonparametric.rst
statsmodels/nonparametric/kernels_asymmetric.py
statsmodels/nonparametric/tests/test_asymmetric.py

see #7346
nonparametric kernel estimation for density and cdf based on asymmetric kernels
kernels are based on the corresponding scipy distribution
for unit interval:
- beta, beta2
for R+:
- gamma, gamma2
- invgamma
- invgauss
- recipinvgauss
- bs (Birnbaum-Saunders)
- log-normal
- weibull  (weibull_min for y>0 )
Status:
currently only checked visually using kde plots for gamma random sample (nobs=1000), plots look good, 
(invgauss is not so good, also weak performance in some references)
I followed parameterization of original articles, but I might want to make them more consistent between them.
no extras, especially no bandwidth defaults or selection

WIP ENH: add asymmetric kernels for kde and cdf, for unit interval and R+

---

statsmodels/genmod/generalized_estimating_equations.py

…ting du
<details>
**Notes**:
* Replaced `self.endog` with `np.concatenate(self.endog_li)` to make sure means are subtracted from the corresponding endogenous variable value

BUG: `du` calculation in `qic` should have both means and endog sorted in the same order

---

statsmodels/tsa/exponential_smoothing/base.py
statsmodels/tsa/exponential_smoothing/ets.py
statsmodels/tsa/forecasting/stl.py
statsmodels/tsa/forecasting/tests/test_stl.py

Fix bugs in ETS simulation and forecast error variance calculation
closes #7309
<details>
**Notes**:
```
```
assuming …

BUG: Correct ETS simulation and forecast error variance

---

statsmodels/tsa/holtwinters/results.py
statsmodels/tsa/holtwinters/tests/test_holtwinters.py

Prevent Nans from breaking the summary
<details>
**Notes**:
```
``` …

BUG: Ensure summary can print with NaNs

---

statsmodels/graphics/gofplots.py

Matplotlib version: **3.4.1** (released 31.03.2021)
Code to reproduce:
```
from statsmodels.graphics.gofplots import qqplot
qqplot(np.random.randn(5))
```
<details>
**Notes**:
verify you changes are well formatted by …

MAINT: Fix UserWarning: marker is redundantly defined (Matplotlib v 3.4.1) 

---

README.rst

DOC: Don't point to release version

---

statsmodels/graphics/tests/test_tsaplots.py
statsmodels/graphics/tsaplots.py

ENH: changed month abbreviations with localization

---

statsmodels/graphics/gofplots.py
statsmodels/graphics/tests/test_gofplots.py

BUG: Fix axis labels in qqplots

---

statsmodels/sandbox/stats/runs.py
statsmodels/sandbox/stats/tests/test_runs.py

When you try to execute the `runstest_1samp` with the parameter `cutoff` set as a number, it raises a `TypeError`:
> TypeError: '>=' not supported between instances of 'list' and 'int'
I added a conversion to `np.float64` when the `cutoff` is a number.
Here is a snippet that shows the problem:
```{python}
from statsmodels.sandbox.stats.runs import runstest_1samp
import numpy as np
x = [1] * 5 + [2] * 6 + [3] * 8
cutoff = 2
runstest_1samp(x, cutoff=cutoff, correction=False)
```
I didn't add the bugfix correction in the **release notes** because I didn't find a file for `statsmodels==0.12.2`.
**Notes**:
* It is essential that you add a test when making code changes. …

BUG: Runs test numeric cutoff error

---

statsmodels/multivariate/pca.py

These are simple fixes in the PCA docstring, removing duplicated "of"s and spaces.

DOC/MAINT: Remove redundant words in PCA docstring

---

statsmodels/base/optimizer.py

Greetings, I just found this line in the implementation of the Newton-Raphson Algorithm (statsmodels/base/optimizer.py:421):
`newparams = oldparams - np.dot(np.linalg.inv(H),
score(oldparams))`
The issue here is that it uses `np.linalg.inv` to solve a linear equation system which is slower and less accurate than the alternative method `np.linalg.solve`.
This is why in this PR I suggest to change the line as follows:
`newparams = oldparams - np.linalg.solve(H, score(oldparams))`
To back up my claim that this will increase accuracy and performance, you can find a related post on stackoverflow here:
[Why does numpy.linalg.solve() offer more precise matrix inversions than numpy.linalg.inv()?](https://stackoverflow.com/questions/31256252/why-does-numpy-linalg-solve-offer-more-precise-matrix-inv …

Use np.linalg.solve() instead of np.linalg.inv() in Newton-Raphson Algorithm

---

examples/notebooks/exponential_smoothing.ipynb
tools/ci/azure/azure_template_posix.yml
tools/ci/run_test.bat

Use --dist loadscope to avoid rerunning setup when running tests
<details>
**Notes**:
```
``` …

MAINT: Use loadscope to avoid rerunning setup

---

statsmodels/tsa/exponential_smoothing/ets.py

Small typo fix for the error raised when endog is not strictly positive and multiplicative components are chosen.
from: 
```python
ValueError: endog must be strictly positive when usingmultiplicative error, trend or seasonal components.
```
to:
```python
ValueError: endog must be strictly positive when using multiplicative error, trend or seasonal components.
```

fix typo in ets error

---

statsmodels/tsa/vector_ar/irf.py
statsmodels/tsa/vector_ar/tests/test_var.py

Looking over #6769 I noticed that the IRF error bands don't run with default arguments because using floats as indices is an error now. Added smoke tests for this part of the code at least...

BUG: Fix float index usage in IRF error bands

---

statsmodels/stats/multitest.py

Here I fix the docstr of `statsmodels.stats.multitest.fdrcorrection`. Prior to this PR, the help would skip the parameter documentation after `method`, because its description was not fully populated, see this screenshot.
This is now fixed.
Furthermore I added to the documentation that `pvals` is expected to be a 1D array (or array_like), and added an assert line in the beginning of the function to warn users if they pass something else.
- ~~[ ] closes #xxxx~~
<details>
**Notes**:
* When adding a new function, test values should usually be verified in another …

DOC: misc fixes in docstr of fdrcorrection

---

examples/notebooks/theta-model.ipynb

This is just a small typo correction on a notebook example. No code component was modified.

Correct small typo in Theta model Notebook

---

examples/notebooks/statespace_varmax.ipynb

The usage of the impulse response function is different between `vector_ar` and `statespace`.
When it comes to `vector_ar`, all directions of impulses can be calculated all at once, but in `statespace`, a shock should be put as an argument of `impulse_responses`. Otherwise, it is implicitly given to a first column.
I feel that to prevent confusion, showing how to give a shock is beneficial to users.
<details>
**Notes**:
* When fixing a bug, you must add a …

Specify impulse to impulse_responses in VARMAX notebook

---

docs/source/distributions.rst
statsmodels/base/model.py
statsmodels/distributions/discrete.py
statsmodels/distributions/tests/test_discrete.py

see #7479 count models based on discretizing a continuous distribution
**update:**
this now also includes two fixes for base GenericLikelihood Mixin
- fix aic of k_constant=0
- fix bootstrap when recreating model with `init_keys`
open decision: do we use scale keyword of underlying  distribution, or do we handle scale explicitly instead of delegating?
**update:** decided: explicit scale internally, 
currently: parameter, args handling is inconistent in scale, it's a shape parameter for the discrete discretized distribution.
if we use scale keyword, then it will not work if the underlying distribution is discrete, which doesn't allow `scale`

ENH: add discretized count distribution

---

statsmodels/tsa/statespace/mlemodel.py
statsmodels/tsa/statespace/tests/test_impulse_responses.py

By this PR, when endog is `pd.DataFrame`,
the column name can be passed as an argument in `impulse_responses` in `VARMAX`.
I believe if users choose to use `pd.DataFrame` as `endog`, they should like to specify the index of the column by column name.
<details>
</details>

ENH: Column name can be passed as an argument in `impulse_responses` in `VARMAX`

---

docs/source/release/version0.13.rst
statsmodels/tsa/exponential_smoothing/base.py
statsmodels/tsa/statespace/mlemodel.py
statsmodels/tsa/statespace/tests/test_fixed_params.py

BUG: statespace MLEModel false validation error with nested fix_params (GH7507)

---

statsmodels/graphics/tsaplots.py

example contained "sm.graphics.tsa.plot_acf", should be 'sm.graphics.tsa.plot_pacf'. (According 'plots/graphics_tsa_plot_pacf.py' already looks fine.)

Remove typo in plot_pacf example

---

tools/ci/azure/azure_template_windows.yml
tools/nbgenerate.py

Remove 32-bit testing
Small fix to nbgenerate
<details>
**Notes**:
```
``` …

MAINT: Remove 32-bit testing

---

statsmodels/genmod/families/family.py
statsmodels/genmod/generalized_linear_model.py
statsmodels/genmod/tests/test_glm.py

see #106, and fixes bug in Gamma parameterization closes #6650
binomial is missing, still to do, design/usage of n_trials?
tweedie is missing but we don't have a distribution for it.
for rvs we could use compound poisson if  `1  < p  < 2` which is the "mixed" range
WIP:
this adds get_distribution to families, 
GLM.get_distribution does not yet delegate to it.

BUG/ENH fix and enh GLM, family get_distribution

---

statsmodels/tsa/forecasting/tests/test_theta.py
statsmodels/tsa/forecasting/theta.py

Correct seasonal index location
<details>
**Notes**:
```
``` …

BUG: Correct index location of seasonal

---

examples/notebooks/contrasts.ipynb

Fix contrasts to always use an object array
<details>
**Notes**:
```
``` …

MAINT: Fix contrasts for Pandas changes

---

statsmodels/genmod/families/family.py
statsmodels/genmod/tests/test_glm.py

The weighted residual approach to calculating the score and Hessian is incorrect for Tweedie EQS models, because the likelihood is not based on a proper density.  This arose in discussions relating to #7476, but also has other implications (e.g. using gradient-based fitting and IRLS fitting for Tweedie models yields different results).
The propopsed solution is to calculate the score and Hessian directly for models that are not based on proper likelihoods.

BUG: score and Hessian for Tweedie models

---

statsmodels/base/model.py
statsmodels/iolib/openfile.py
statsmodels/iolib/smpickle.py
statsmodels/iolib/tests/test_pickle.py

Add support for objects supporting open
closes #7199
<details>
**Notes**:
```
``` …

ENH: Add support for pickling for generic path-like objects

---

setup.cfg
statsmodels/graphics/tests/test_tsaplots.py
statsmodels/graphics/tsaplots.py

Warn users about future changes
<details>
**Notes**:
```
``` …

ENH: Start process of changing default in plot-pacf

---

statsmodels/base/model.py
statsmodels/othermod/tests/test_beta.py

fixes bug with incorrect df constraints in llr_pvalue for beta regression
https://github.com/statsmodels/statsmodels/issues/7584#issuecomment-881689009
fix is to use the difference in df_resid following the pattern of `RegressionResults.compare_lr_test`
df_model is still ambiguous across models, and currently not counting number of slope parameters.
see https://github.com/statsmodels/statsmodels/issues/1723#issuecomment-881904749

REF/BUG generic likelihood LLRMixin use df_resid instead of df_model for llr_pvalue

---

statsmodels/tsa/exponential_smoothing/base.py
statsmodels/tsa/regime_switching/markov_switching.py
statsmodels/tsa/statespace/mlemodel.py
statsmodels/tsa/statespace/tools.py

Protect cond in case of nan or inf
<details>
**Notes**:
```
``` …

BUG: Ensure warning does not raise

---

statsmodels/base/tests/test_shrink_pickle.py
statsmodels/regression/linear_model.py
statsmodels/regression/tests/test_predict.py

This partially reverts changes in OLS for remove_data in #6888, now wendog, wexog and wresid are removed again
reported in https://github.com/statsmodels/statsmodels/issues/7494#issuecomment-878322999
unit test changed to call results `scale` before remove_data, so that get_prediction works #6887
This does not revert changes other than wendog, wexog and wresid
~e.g. RLM `sresid` is not removed after 6888, which I guess can also be reverted.~
**correction**, I read that part too fast, sresid is in cache list and is removed. 
(In unit test case, RLM size shrinks to less than 3% of original size)
open question: Why did unit tests not catch that remove_data didn't remove the `wxxx` arrays?

BUG: regression, allow remove_data to remove wendog, wexog, wresid

---

statsmodels/base/_penalized.py
statsmodels/base/model.py
statsmodels/base/optimizer.py
statsmodels/discrete/discrete_model.py
statsmodels/discrete/tests/test_count_model.py
statsmodels/discrete/tests/test_diagnostic.py
statsmodels/discrete/tests/test_discrete.py
statsmodels/gam/tests/test_gam.py
statsmodels/genmod/generalized_linear_model.py
statsmodels/othermod/betareg.py
statsmodels/tsa/arma_mle.py
statsmodels/tsa/statespace/dynamic_factor_mq.py
statsmodels/tsa/statespace/mlemodel.py
statsmodels/tsa/tests/test_exponential_smoothing.py
statsmodels/tsa/vector_ar/svar_model.py

xref #7030
<details>
**Notes**:
```
```
using …

ENH: Raise when invalid optimization options passed to optimizer

---

setup.cfg
statsmodels/base/optimizer.py
statsmodels/base/tests/test_generic_methods.py

Change exception to a warning and warn of future exception
<details>
**Notes**:
```
``` …

MAINT: Revert exception to warning

---

statsmodels/distributions/copula/archimedean.py
statsmodels/distributions/copula/copulas.py
statsmodels/distributions/copula/other_copulas.py
statsmodels/distributions/copula/tests/test_copula.py
statsmodels/tools/rng_qrng.py

This is another follow up of #7254 which adds a wrapper around `np.random.Generator` and alike.
It is similar to the one in SciPy for QMC, but it also allows to pass along an instance of `scipy.qmc.QMCEngine`. This way we can use QMC with copula.
c.f. discussion https://github.com/statsmodels/statsmodels/pull/7408#issuecomment-888266539
cc @josef-pkt

ENH: random number generation wrapper for rng, qrng

---

statsmodels/base/optimizer.py
statsmodels/tsa/tests/test_exponential_smoothing.py

Use correct name for kwarg
<details>
**Notes**:
```
``` …

MAINT: Avoid passing bad optimization param

---

docs/source/api-structure.rst
docs/source/api.rst
docs/source/tsa.rst
statsmodels/tsa/api.py
statsmodels/tsa/stattools.py
statsmodels/tsa/tests/test_stattools.py

The RUR test implementation comes from the paper  "Range Unit-Root tests" by Aparicio et Al. [2006]
The critical values table has been recalculate with more iterations than the paper.
<details>
**Notes**:
verify you changes are well …

ENH: Add RUR stationarity test to statsmodels.tsa.stattools

---

docs/source/dev/index.rst

Is there any reason we should have different flake8 commands (`--isolated`) on the [dev page](https://github.com/statsmodels/statsmodels/blob/main/docs/source/dev/index.rst) and on the [pull request template](https://github.com/statsmodels/statsmodels/blob/main/.github/PULL_REQUEST_TEMPLATE.md) (or just see details below)? e.g. slowdown from the additional rules?
Making this PR in case this was unintended. :)
<details>
**Notes**:
* New code additions must …

DOC: Update dev page flake8 command to follow PULL_REQUEST_TEMPLATE.md

---

statsmodels/stats/multitest.py
statsmodels/stats/tests/test_multi.py

see issue, closes #7465 closes #7466
updated PR #7466
corrects both cases of sidak "s" and "hs"

BUG: improve sidak multipletest precision close to zero

---

statsmodels/stats/proportion.py
statsmodels/stats/tests/test_proportion.py

closes #7603
use dtype at least float64 in _table_proportion
(aside: complex numbers will not work because, scipy distribution norm uses special function that doesn't support complex for cdf, ppf)

BUG: proportions_chisquare prevent integer overflow 

---

statsmodels/genmod/generalized_linear_model.py
statsmodels/genmod/tests/test_glm.py
statsmodels/regression/linear_model.py
statsmodels/regression/rolling.py
statsmodels/regression/tests/test_regression.py

closes #6577 aic
#1802 bic and FAQ
this adds dk_params to `GLMResults.info_criteria`
default is unchanged

ENH: add dk_params option to GLM info_criteria

---

statsmodels/regression/quantile_regression.py
statsmodels/regression/tests/test_quantile_regression.py

rebased version of #6397
minor merge conflict, removed note in release 0.11

ENH: quantile regression use dimension of x matrix rather than rank

---

statsmodels/regression/linear_model.py
statsmodels/regression/tests/test_regression.py

this adds `slim` option to regression results `summary`
closes #6880
rebased #6880 with interactive editing (preserved original author)
squashed commit, removed formatting changes, fix up pep 8
added a basic unit test that slim only has 2 tables and text length is smaller
```
(Pdb) print(summ)
OLS Regression Results
==============================================================================
Dep. Variable:                      y   R-squared:                       0.995
Model:                            OLS   Adj. R-squared:                  0.992
No. Observations:                  16   F-statistic:                     330.3
Covariance Type:            nonrobust   Prob (F-statistic):           4.98e-10
==============================================================================
coef …
```

ENH: add option for slim summary in OLS results

---

statsmodels/nonparametric/kde.py
statsmodels/nonparametric/tests/test_kernels.py
statsmodels/sandbox/nonparametric/kernels.py

closes #7671
closes #7663
rebase and squashed version of #7671 plus one simple unit test against R package kedd
other kernels are unit tested against Stata, and Stata doesn't have tricube (neither does base R stats)
R package kdensity has tricube, but doesn't have public function to evaluate kernel directly
distr6 package looks good, but I cannot install it on my slightly older R version.

ENH add  tricube kernel

---

statsmodels/stats/_lilliefors.py
statsmodels/stats/tests/test_lilliefors.py

The `lilliefors` function is broken on (single-column) DataFrames. The input gets coerced by `np.as_array()` into an array of shape `(N, 1)`, where it should be `(N,)`. This causes problems in the further calculations in the function, leading to incorrect results.
This PR adds a test that reproduces the problem, and fixes it by calling `np.squeeze()` on the array. It also adds raising a `ValueError` when the array cannot be squeezed to a 1d array.

ENH: Fix lilliefors results for single-column DataFrames

---

statsmodels/multivariate/factor.py
statsmodels/multivariate/tests/test_ml_factor.py

rebased version #7358   multivariate `Factor1 resets global numpy random state with seed
closes #7357 closes #7358
I edited the unit test during interactive rebase
convert docstring to code comment
remove unused variable
squashed 2 of the 3 commits
this is bug fix, not systematically adding random state

BUG: Factor fit ml em resets seed (rebased)

---

statsmodels/multivariate/multivariate_ols.py

Following discussion in #5487 , this adds `E` and `H` matrices to the `multivariate_ols._multivariate_test` return dictionary. This dictionary makes its way into the `MultivariateTestResults` returned by `MANOVA.mv_test()` so these matrices are made available to the user who can use them to calculate the discriminant function coefficients.

multivariate - Return E and H matrices in dict

---

statsmodels/tools/validation/validation.py
statsmodels/tsa/stattools.py
statsmodels/tsa/tests/test_stattools.py

I have changed `ccovf` to use `scipy.signal.correlate` instead of `np.correlate` which can use FFT. The way to enable FFT is chosen to be similar to how `acovf` does it and not as `scipy.signal.correlate`. 
A change is done to how the adjusted `d` is calculated  to speed up the calculation, an example is given here:  
``` python
nobs = 100
d1 = np.arange(nobs, 0, -1)
xi = np.ones(nobs)
d2 = np.correlate(xi, xi, "full")[nobs - 1 :]
np.allclose(d1, d2)
```
At last, I have updated some docstrings with minor corrections, an if statement, and added a FIXME comment, but I can remove them if you want to have it in a separate PR.
<details>
**Notes**:
* It is essential that …

ENH: Added fft to ccovf and ccf

---

statsmodels/genmod/generalized_linear_model.py
statsmodels/genmod/tests/test_glm.py

see #7741
this adds it to GLM
If it works, then we can add it as private helper method at a higher level.
A possible problem: we hardcode that the instance is not from a subclasse.g. `type(self) is GLM`

ENH: Warn kwargs glm

---

statsmodels/base/_penalized.py
statsmodels/base/model.py
statsmodels/discrete/discrete_model.py
statsmodels/discrete/tests/test_discrete.py
statsmodels/distributions/copula/archimedean.py
statsmodels/gam/tests/test_penalized.py
statsmodels/genmod/generalized_estimating_equations.py
statsmodels/genmod/generalized_linear_model.py
statsmodels/genmod/tests/test_gee.py
statsmodels/genmod/tests/test_glm.py
statsmodels/regression/linear_model.py
statsmodels/regression/quantile_regression.py
statsmodels/regression/tests/test_predict.py
statsmodels/regression/tests/test_regression.py
statsmodels/robust/robust_linear_model.py

replaces UserWarning by ValueWarning in GLM kwarg check
followup to #7741
this uses now base Model helper function check_kwargs
this  adds check_args to
GLM, GEE
discrete CountModel, BinaryModel
RLM
regression: OLS, WLS, GLS, QuantReg
also includes bug fix for #7755 GLS.fit_regularized

REF: GLM init invalid kwargs use ValueWarning

---

statsmodels/nonparametric/_smoothers_lowess.pyx
statsmodels/nonparametric/tests/test_lowess.py

Resolves two issues in `nonparametric.lowess` where zeros or near-zero values could cause unreliable results.
Tests are added for both of these cases.
<details>
**Notes**:
```
git diff …
```

BUG: fix lowess spikes/nans from epsilon values

---

statsmodels/base/_parameter_inference.py
statsmodels/discrete/discrete_model.py
statsmodels/discrete/tests/test_constrained.py
statsmodels/discrete/tests/test_discrete.py
statsmodels/discrete/tests/test_sandwich_cov.py
statsmodels/genmod/generalized_linear_model.py
statsmodels/stats/outliers_influence.py

rebased version of #5711
no code removed (like NB, GPP score factor in first commit)
Logit score_factor is already in main
possible problems
sign of hessian factor, not sure how GLM and discrete really compare
docstrings need review, Resolving merge conflicts might not have left good docstrings.
duplicate shortcut name for `base._parameter_inference `infer` and `pinf`
**included in PR:**
- offset in BinaryModel
- possible problem in MNLogit, not supported
- possible problem new code added to main after changes in this PR, needs checking
- fit_constrained in BinaryModel
- score_test in GLMResults
- score_test in Discretresults
- will likely not work in several models needs checking maybe inherited too high in class hierarchy 
- score_factor, hessian_factor in Probit
- score_factor, …

Discrete scorefactor offset rebased3

---

statsmodels/stats/weightstats.py

Some mentions to "Welch ttest" were written "Welsh ttest", this commit fixes it.
Minor typo change on Docstring, therefore no test was added.
No escape requirement due to the change (LaTeX).

DOC: Fixes typo "Welsh ttest" to "Welch ttest"

---

statsmodels/base/_parameter_inference.py
statsmodels/genmod/generalized_linear_model.py
statsmodels/genmod/tests/test_score_test.py

see #7840 only relevant if scale is estimated
The fix here temporarily resets `model.df_resid` inside `GLMResults.score_test`.
The standalone score_test function cannot be used in the res_constrained and res_full cases because it doesn't adjust the df_resid for the constrained scale estimation.
I also added `scale` as argument to `_parameter_inference.score_test` function, but it is currently not used.
aside: 
for GLM-Gaussian, the unit test for wooldridge fails. I didn't check whether that is an equivalent test in this case.
It looks like the score_test versions correspond to different wooldridge pvaluex version than in poisson case.
currently skipped

BUG: GLM score_test, use correct df_resid

---

statsmodels/compat/pandas.py
statsmodels/regression/rolling.py
statsmodels/tsa/ar_model.py
statsmodels/tsa/ardl/model.py

CachedProperty is not property-like and uses fget rather than func
<details>
**Notes**:
```
``` …

MAINT: Protect against future pandas changes

---

statsmodels/base/model.py

Deprecate a feature that does nto work with pandas and is
hard to get to work correctly
closes #1956
<details>
**Notes**:
```
git diff upstream/main -u -- "*.py" | flake8 --diff …
```

MAINT: Deprecate cols in conf_int

---

statsmodels/tsa/holtwinters/model.py
statsmodels/tsa/holtwinters/tests/test_holtwinters.py

BUG: incorrect HW predictions
<details>
**Notes**:
```
``` …

BACKPORT: Merge pull request #7791 from Wooqo/fix-hw

---

setup.cfg
statsmodels/base/model.py
statsmodels/base/tests/test_generic_methods.py
statsmodels/discrete/tests/test_discrete.py
statsmodels/gam/tests/test_penalized.py
statsmodels/genmod/tests/test_constrained.py
statsmodels/genmod/tests/test_score_test.py
statsmodels/sandbox/regression/tests/test_gmm.py
statsmodels/stats/diagnostic.py
statsmodels/stats/tests/test_diagnostic.py
statsmodels/stats/tests/test_oneway.py
statsmodels/stats/tests/test_outliers_influence.py
statsmodels/tools/_testing.py
statsmodels/tsa/tests/test_ar.py

Begin deprecation cycle to move to wards scalars in scalar test statistics
<details>
**Notes**:
```
``` …

ENH: Start move to scalar test statistics

---

statsmodels/base/model.py

MAINT: Deprecate cols in conf_int
<details>
**Notes**:
```
``` …

BACKPORT: Merge pull request #7842 from bashtage/deprecate-cols

---

statsmodels/stats/weightstats.py

DOC: Fixes typo "Welsh ttest" to "Welch ttest"
<details>
**Notes**:
```
``` …

BACKPORT: Merge pull request #7839 from guilhermesilveira/main

---

setup.cfg
statsmodels/regression/tests/test_regression.py
statsmodels/regression/tests/test_rolling.py

Silence warning about cols being deprecated
<details>
**Notes**:
```
``` …

MAINT: Silence warning

---

statsmodels/base/_prediction_inference.py
statsmodels/base/model.py
statsmodels/discrete/count_model.py
statsmodels/discrete/discrete_model.py
statsmodels/discrete/tests/test_predict.py
statsmodels/othermod/betareg.py
statsmodels/othermod/tests/test_beta.py

another round for get_predictions
- get_prediction which="linear" didn't work if there are extra_params
- add GenericLikelihoodModelResults.get_prediction
- minimal unit tests for BetaModel get_prediction inherited from GenericLikelihood, no verified se, conf_int
- ...
decision for now:
- get_prediction_linear is only used for first exog in multilink models
- all other linear predictions go through NonlinearDeltaCov. Results will be the same except for numerical derivative
- zero-inflated models have inflation params before main paramss, i.e. params for exog are not first segment of `params`.
I don't support (for now) using get_prediction_linear for ZI models.
- ...

ENH/BUG: get_prediction for more models and cases

---

statsmodels/tsa/exponential_smoothing/ets.py
statsmodels/tsa/statespace/exponential_smoothing.py
statsmodels/tsa/tests/test_exponential_smoothing.py

Reverse seasonal during model intialization
<details>
**Notes**:
```
``` …

BUG: Correct seasonal order

---

statsmodels/base/_parameter_inference.py
statsmodels/base/model.py
statsmodels/discrete/discrete_model.py
statsmodels/discrete/tests/test_discrete.py
statsmodels/discrete/tests/test_predict.py
statsmodels/othermod/betareg.py
statsmodels/othermod/tests/test_beta.py

starting to add score_test to multilink model
- score_factor: return tuple, backwards incompatible but internal and newish
- GenericLikelihoodModelResults BUG/ENH no cov_type attribute if nonrobust is not explicitly specified
score_test will be experimental, because I don't have a clear design about how to outsource the relevant multilink computations.
Also models with extra params (but not extra exog) like NBP or GPP will need a different solution than multi-exog models like BetaModel.

ENH/REF: Scoretest betareg

---

statsmodels/discrete/discrete_model.py
statsmodels/discrete/tests/test_predict.py
statsmodels/othermod/betareg.py
statsmodels/othermod/tests/test_beta.py
statsmodels/stats/outliers_influence.py

It works but I have not looked at the results numbers yet, only smoke test
uses numdiff for `_deriv_score_obs_dendog`, see #7891
`_deriv_score_obs_dendog` takes derivative w.r.t. endog
this might be a problem in discrete models
count models NBP, GPP should be ok
Probit will likely be a problem, and we cannot use complex step derivatives.
I'm not sure whether definitions used in MLEInfluence apply to Probit.
Standardized score residuals use sf[0] / hf[0]. Does this work in general? 
Do we need the same for the second score_factor?
Note, `_deriv_mean_dparams` needs to be w.r.t. full params even if mean only depends on mean params (for consistent shape with hessian)
R betareg has some of the influence outlier measures to test against.

ENH: MLEInfluence for two-part models, extra params, BetaModel

---

statsmodels/genmod/tests/test_glm_weights.py
statsmodels/regression/tests/test_regression.py
statsmodels/tsa/holtwinters/tests/test_holtwinters.py

Remove explicit use of None in pytest warns
<details>
**Notes**:
```
``` …

MAINT: Start removing pytest warns with None

---

statsmodels/base/model.py
statsmodels/discrete/count_model.py
statsmodels/discrete/discrete_model.py
statsmodels/discrete/tests/test_discrete.py
statsmodels/discrete/tests/test_predict.py
statsmodels/distributions/discrete.py
statsmodels/distributions/tests/test_discrete.py

more work on post-estimation for discrete
This also outsources the predict transform exog from base.model.Results.predict to a new private method `_transform_predict_exog`
This helper method is reused in `get_distribution` to avoid code duplication. `get_distribution` does not use the pandas index because return is a scipy frozen distribution instance.
see also #7928 class diagram of unit tests
no get_distribution for MNLogit. I never tried out the scipy multinomial distribution, and don't know if it will work for our case.
This PR has now 
- `get_distribution` for all discrete models except MNLogit. Currently only in model classes not in results classes.
- added predict `which="var"` for count models, not yet zi

ENH/REF: discrete add get_distribution, add which="var" for NBP, GPP

---

setup.cfg
statsmodels/base/tests/test_generic_methods.py
statsmodels/compat/pytest.py
statsmodels/distributions/copula/tests/test_copula.py
statsmodels/tsa/holtwinters/tests/test_holtwinters.py
statsmodels/tsa/tests/test_ar.py
statsmodels/tsa/tests/test_deterministic.py
statsmodels/tsa/vector_ar/tests/test_var_jmulti.py
statsmodels/tsa/vector_ar/tests/test_vecm.py

Avoid using None in pytest warns and explicitly check for no warning
<details>
**Notes**:
```
``` …

MAINT: Prevent future issues with pytest

---

docs/source/pitfalls.rst
statsmodels/discrete/count_model.py
statsmodels/discrete/discrete_model.py
statsmodels/discrete/tests/test_predict.py
statsmodels/genmod/generalized_linear_model.py
statsmodels/graphics/regressionplots.py
statsmodels/othermod/betareg.py
statsmodels/othermod/tests/test_beta.py
statsmodels/stats/outliers_influence.py
statsmodels/stats/tests/test_influence.py

WIP still in design/decision stage
MLEInfluence with resid_pearson default
works for
Logit,
Poisson,
NegativeBinomialP,
GeneralizedPoisson,
other models are missing derivatives.
currently test failures because definition of `MLEInfluence.resid_studentized` changed, in TestInfluenceGaussianGLMMLE.test_basics

ENH: add get_influence to DiscreteResults

---

pyproject.toml
statsmodels/base/_prediction_inference.py
statsmodels/discrete/count_model.py
statsmodels/genmod/generalized_linear_model.py
statsmodels/imputation/ros.py
statsmodels/stats/tests/test_anova_rm.py
statsmodels/tsa/vector_ar/tests/test_var.py

DataFrame append is deprecated in favor of concat(*,axis=0)
<details>
**Notes**:
```
``` …

MAINT: Remove DataFrame.append usage

---

statsmodels/tsa/vector_ar/tests/test_var.py

Relax tolerance to ensure test passes on recent NumPy
<details>
**Notes**:
```
``` …

MAINT: Relax tolerance on VAR test

---

pyproject.toml

Switch to oldest-supported-numpy to avoid build issues
<details>
**Notes**:
```
``` …

MAINT: Simplify pyproject using oldest supported numpy

---

statsmodels/tsa/statespace/exponential_smoothing.py
statsmodels/tsa/statespace/tests/test_exponential_smoothing.py

This PR:
1. Fixes the issue identified in #7893 for the `sm.tsa.statespace.ExponentialSmoothing` model for the heuristic and simple initialization methods
2. Improves the parameter / state names to make the order of the seasonal factors more clear
3. Adds documentation about this order, and adds comments in the code to explain why the array of seasonal factors returned by the heuristic and simple initializations needs to be reversed

BUG/DOC: Fix heuristic and simple initial seasonals in state space ExponentialSmoothing

---

statsmodels/stats/descriptivestats.py
statsmodels/stats/proportion.py
statsmodels/stats/tests/test_proportion.py

Update to non-deprecated binomtest from SciPy
<details>
**Notes**:
```
``` …

MAINT: Update binom_test to binomtest

---

statsmodels/tsa/exponential_smoothing/ets.py

Closes #7443 
Typo in the documentation of loglike method in ETSModel class is fixed. Refer to ticket 7443

DOC: ETS model loglike doc typo fix

---

statsmodels/regression/linear_model.py
statsmodels/regression/tests/test_regression.py

Add optional parameter slim to docstring of summary
<details>
**Notes**:
```
``` …

MAINT: Add slim to summary docstring

---

statsmodels/tsa/ar_model.py
statsmodels/tsa/deterministic.py
statsmodels/tsa/tests/test_ar.py
statsmodels/tsa/x13.py

Add append to AutoRegResults to correspond to other time-series models
<details>
**Notes**:
```
``` …

ENH: Add append method to AutoRegResults

---

statsmodels/genmod/generalized_estimating_equations.py
statsmodels/genmod/tests/test_gee.py

[GEE's documentation](https://www.statsmodels.org/dev/generated/statsmodels.genmod.generalized_estimating_equations.GEE.html) says that `endog`, `exog`, `groups`, `time`, and `offset` can all be array-like, which "includes lists ... and tuples".
However, lists and tuples are not currently supported. The `GEE` class inherits from `GLM` but uses its own function to check inputs, `_check_args` [here](https://github.com/statsmodels/statsmodels/blob/main/statsmodels/genmod/generalized_estimating_equations.py#L463-L479). That function assumes that each of the inputs has a `size` attribute, without first checking their types.
`GLM` seems to do type checking and conversion with the `handle_data` function, [here](https://github.com/statsmodels/statsmodels/blob/main/statsmodels/base/data.py#L665-L67 …

GEE inputs: handle lists and tuples

---

statsmodels/tsa/statespace/_tools.pyx.in
statsmodels/tsa/statespace/dynamic_factor_mq.py
statsmodels/tsa/statespace/initialization.py
statsmodels/tsa/statespace/kalman_smoother.py
statsmodels/tsa/statespace/mlemodel.py
statsmodels/tsa/statespace/news.py
statsmodels/tsa/statespace/representation.py
statsmodels/tsa/statespace/tests/test_decompose.py
statsmodels/tsa/statespace/tests/test_dynamic_factor_mq_frbny_nowcast.py
statsmodels/tsa/statespace/tests/test_news.py
statsmodels/tsa/statespace/tests/test_weights.py
statsmodels/tsa/statespace/tools.py
statsmodels/tsa/statespace/varmax.py

ENH: state space: add revisions to news, decomposition of smoothed states/signals

---

setup.cfg
statsmodels/tsa/stattools.py
statsmodels/tsa/tests/test_stattools.py
statsmodels/tsa/tests/test_tsa_tools.py

Improve testing
Deprecate verbose
<details>
**Notes**:
```
``` …

MAINT: Improve testing of grangercausality

---

statsmodels/nonparametric/smoothers_lowess.py
statsmodels/nonparametric/tests/test_lowess.py

Ensure data are converted to contiguous double
<details>
**Notes**:
```
``` …

BUG: Check dtype for xvals in lowess

---

statsmodels/sandbox/stats/multicomp.py
statsmodels/stats/tests/test_multi.py
statsmodels/stats/tests/test_pairwise.py

This PR replaces use of statsmodels' studentized range distribution functions (`statsmodels.stats.libqsturng.qsturng`, `statsmodels.stats.libqsturng.psturng`) with those from SciPy when `scipy.stats.studentized_range` is available (SciPy 1.7.0+).
Speed is maintained, and results are more accurate because SciPy's implementation evaluates the integral for the provided arguments rather than interpolating from tabulated results.
For example, this box and whiskey plot (from [here](https://zenodo.org/record/5151976#.YekY3_7MKUk)) compares the relative accuracy of the studentized range CDF in SciPy, statsmodels, and R (ptukey) across a wide range of inputs.
<details> …

ENH: use scipy.stats.studentized_range in tukey hsd when available

---

pyproject.toml

[maintenance/0.13.x] Merge pull request #7989 from bashtage/try-oldest-supported-numpy

---

statsmodels/sandbox/stats/multicomp.py
statsmodels/stats/tests/test_multi.py
statsmodels/stats/tests/test_pairwise.py

[maintenance/0.13.x] Merge pull request #8035 from swallan/scipy-studentized-range-qcrit-pvalue

---

statsmodels/tsa/stattools.py

[maintenance/0.13.x] Merge pull request #8023 from MichaelChirico/patch-1

---

statsmodels/tsa/stattools.py
statsmodels/tsa/tests/test_tsa_tools.py

[maintenance/0.13.x] Merge pull request #8026 from wirkuttis/bugfix_statstools

---

statsmodels/nonparametric/smoothers_lowess.py
statsmodels/nonparametric/tests/test_lowess.py

[maintenance/0.13.x] Merge pull request #8047 from bashtage/fix-lowess-8046

---

statsmodels/sandbox/distributions/multivariate.py

multivariate_t_rvs function currently seems to fail with "cannot apply subscript to float" in df==np.inf case
<details>
**Notes**:
```
git diff upstream/main -u -- "*.py" | flake8 --diff …
```

BUG: denominator needs to be a vector

---

statsmodels/stats/proportion.py
statsmodels/stats/tests/test_proportion.py

closes #8049
nobs ratio was not correctly used in power_proportions_2indep and samplesize_proportions_2indep_onetail

BUG: use nobs ratio in power and samplesize proportions_2indep

---

statsmodels/stats/proportion.py
statsmodels/stats/tests/test_proportion.py

[maintenance/0.13.x] Merge pull request #8093 from josef-pkt/bug_proportion_pwer_2indep

---

pyproject.toml
setup.py

The default is `build-backend = "setuptools.build_meta:__legacy__"`, which is not ideal. This field really shouldn't have been optional, but it was.
The legacy backend injects the local path - that has to be done by hand with the non-legacy backend, since packages are discouraged from importing in setup.py. If that makes a difference, that will also have to be added here.
Oops, didn't format the commit message. Can reformat after tests run.
<details>
**Notes**:
* When adding a new function, test values should usually be verified in another package (e.g., …

fix(setup): use correct setuptools backend

---

statsmodels/tsa/tsatools.py

Fixes the error message in `lagmat` when `trim="backward"` and `use_pandas=True`. The current error message incorrectly states that `trim="forward"` and `use_pandas=True` are incompatible.

BUG: Fix ValueError output in lagmat when using pandas

---

statsmodels/tsa/ardl/model.py

Fix spelling of a few words in ARDL
<details>
**Notes**:
```
``` …

DOC: Fix spelling in ARDL

---

statsmodels/tsa/stattools.py
statsmodels/tsa/tests/test_stattools.py

This PR adds `"burg"` as an option for the method argument in `pacf` which enables the option to use the already implemented `pacf_burg` function via `pacf(x, method="burg")`. Feedback would be appreciated in particular for the added test.
<details>
**Notes**:
* New code additions must be well formatted. Changes should pass flake8. If …

ENH: add burg as an option for method to pacf

---

statsmodels/stats/diagnostic.py
statsmodels/stats/tests/test_diagnostic.py

Require 2 columns including a constant
<details>
**Notes**:
```
``` …

BUG: Ensure exog is well specified

---

statsmodels/iolib/summary.py
statsmodels/iolib/summary2.py
statsmodels/iolib/table.py
statsmodels/iolib/tests/test_summary.py
statsmodels/iolib/tests/test_summary2.py
statsmodels/iolib/tests/test_table.py

PR adds `_repr_latex_` functionality, such that summary tables will be outputted in LaTeX format when converting Jupyter Notebooks to PDF via nbconvert.
**Notes**:
```
git diff …
```

ENH: Add _repr_latex_ methods to iolib tables

---

statsmodels/stats/rates.py
statsmodels/stats/tests/test_rates_poisson.py

Add y_grid as parameter and deprecate ygrid.
https://github.com/statsmodels/statsmodels/issues/8135

BUG: Make ygrid work for etest_poisson_2indep

---

lint.sh

Replace references to stl with new directory
<details>
**Notes**:
```
```
using the Windows System for Linux once `flake8` is installed in the 
local Linux environment. …

MAINT: Correct linting

---

examples/notebooks/mstl_decomposition.ipynb

This PR changes the heading levels of the MSTL notebook to correct an issue with the docs (described below). Typos are also corrected and some parts are re-phrased for clarity.
The issue: the [Examples section](https://www.statsmodels.org/devel/examples/index.html) in the docs is currently displaying multiple headings from the MSTL notebook (see image below).

DOC: Change heading levels in MSTL notebook to fix docs

---

statsmodels/regression/tests/test_recursive_ls.py
statsmodels/stats/diagnostic.py

Check res type
closes #8222
<details>
**Notes**:
```
``` …

BUG: Enforce type check in recursive_olsresiduals

---

statsmodels/stats/power.py

Very minor change fixing argument names in the documentation

Fix docs std_null twice instead of std_alternative

---

statsmodels/tsa/stl/tests/test_mstl.py

This PR removes a print statement in a fixture in the MSTL tests.

TST: Remove print statement in MSTL test fixture

---

statsmodels/iolib/table.py

Should be the length of each row in all rows (len(row)), but not the number of rows (nrow).
It's an obvious bug, and I don't have the time to actually setup a dev env and run tests. Feel free to close this and fix it yourself.

Bug when determine if all rows have same length

---

docs/source/duration.rst

duration.rst was using the "code-block" tag instead of the "ipython" tag used elsewhere in the documentation, causing the python output to not appear. I switched the "code-block" tags to "ipython" tags, added okwarning/okexcept flags so it would run, and savefig flags so the figures would be saved. The code itself had to be slightly modified so sphinx would run it as well.

DOC: Updated duration.rst to display output

---

setup.py

distutils is deprecated and is no longer needed
<details>
**Notes**:
```
``` …

MAINT: Remove distutils

---

statsmodels/stats/descriptivestats.py
statsmodels/stats/tests/test_descriptivestats.py

 BUG: fix #8227 wrong standard error of the mean 

---

statsmodels/tsa/statespace/representation.py

fix a typo in the documentation
<details>
**Notes**:
```
``` …

DOC: fix a typo in the documentation

---

examples/notebooks/ets.ipynb

Minor doc update to fix 404 error in the ETS example
- Before PR: link https://otexts.com/fpp3/7 leads to 404 error
- notice that the older link https://otexts.com/fpp/7 does work but gets redirected on the 2nd edition https://otexts.com/fpp2/expsmooth.html
- After PR: working link to Ch 8 "Exponential smoothing" is now https://otexts.com/fpp3/expsmooth.html
For completeness, the same book chapter is referenced in the [exponential_smoothing.ipynb](https://github.com/statsmodels/statsmodels/blob/main/examples/notebooks/exponential_smoothing.ipynb) notebook, but this is the older & safe link https://otexts.com/fpp/7 so it's OK.

Update book reference in ETS example

---

.github/workflows/backport.yml
.github/workflows/generate-documentation.yml

A bit of CI maintenance:
- Update to actions/checkout@v3, actions/setup-python@v3, r-lib/actions/setup-pandoc@v2 and ts-graphviz/setup-graphviz@v2
- Cache packages installed by pip
- Remove the `python -m` part, `pip` is directly callable
Checklist

CI: Update used actions, cache pip deps, Python 3.10

---

statsmodels/discrete/discrete_model.py

`method`
**Detail**:
This change is very minor. I let DiscreteModel be accessed with two attributes, which are `method` and `converged`. Actually, `converged` attribute can be found in `model.mle_retvals["converged"]`, but I think it is good to set this attribute for consistency with `genmod.generalized_linear_model` and user-friendliness. 
**Notes**:
Currently I can not pass tests after running `pytest statsmodels/discrete/` because of the following lines. When I just installed the current version of statsmodels without any changes, this test again can not be passed... I think my change does not affect the result fof fitting, and actually, other errors are not be …

ENH: Add method and converged attributes to DiscreteModel.

---

docs/source/stats.rst
statsmodels/stats/_inference_tools.py
statsmodels/stats/rates.py
statsmodels/stats/tests/test_rates_poisson.py

see #8138
collecting functions
It's not clear yet what will be in here and how it will be structured.
literature references are a bit all over the place.
It still open which options and methods will be available.
current plan
- 1 sample poisson
- test
- confint
- 2 sample poisson ratio
- confint to match part of current ratio hypothesis test 
- power, based on PASS, Zhu and Guo (equivalence, one-sided with a margin)
- 2 sample poisson diff, 
- confint, mainly mover
- test ???
- power ???, maybe only basic wald, equality hypothesis similar to power proportion 2indep
-  negbin  2indep
- power Zhu, analogy to Poisson
- test, confint, 1 sample ??? 
- generic power based on variance functions under null and alternative
also includes
confint for poisson quantile and tolerance interval  for …

ENH:  hypothesis tests,  confint, power for rates (poisson, negbin)

---

setup.cfg
statsmodels/stats/descriptivestats.py

MAINT: Remove pandas warning from pytest errors

---

statsmodels/stats/nonparametric.py
statsmodels/stats/proportion.py
statsmodels/stats/rates.py
statsmodels/stats/tests/test_nonparametric.py
statsmodels/stats/tests/test_proportion.py
statsmodels/stats/tests/test_rates_poisson.py

closes #8213
- fix max for tost_proportions_2indep, with vectorization
- vectorizes tost poisson 2indep
- better unit tests for nonparametric rankcompare tost
these are the only newer tost functions
old tost functions are in proportions for one sample and in weightstats
Those functions return simple tuple with numbers, not a HolderTuple or Holder instance.

BUG/ENH: fix max in tost_proportions_2indep, vectorize tost

---

statsmodels/discrete/tests/test_predict.py
statsmodels/stats/_adnorm.py
statsmodels/tests/test_x13.py
statsmodels/tsa/ar_model.py

Remove a few print statements in functions
closes #8345
<details>
**Notes**:
```
``` …

MAINT: Remove unintended print statements

---

statsmodels/stats/diagnostic.py
statsmodels/stats/tests/test_diagnostic.py

Corrected the implementation of optimal lag selection (Escanciano & Lobato, J. of Econometrics, 2009). `auto_lag = True` does not return a zero-size array ValueError when data is a non-autocorrelated series. Added test and corrected the previous test for this which did not flag `auto_lag = True` and therefore did not test this feature. Need additional test to compare to R results.
<details>
The `get_optimal_length` inner function of the `acorr_ljungbox` function calculated the optimal lag incorrectly. First, the optimal lag was initialized to `0`, which then caused an empty array to be initialized. The function barfed when the `max()` of this array was attempted, …

BUG: Fix auto lag selection in acorr_ljungbox #8338

---

statsmodels/tsa/statespace/_filters/_conventional.pyx.in
statsmodels/tsa/statespace/_representation.pxd
statsmodels/tsa/statespace/_simulation_smoother.pxd
statsmodels/tsa/statespace/_simulation_smoother.pyx.in
statsmodels/tsa/statespace/_smoothers/_conventional.pyx.in
statsmodels/tsa/statespace/kalman_filter.py
statsmodels/tsa/statespace/mlemodel.py
statsmodels/tsa/statespace/simulation_smoother.py
statsmodels/tsa/statespace/tests/test_collapsed.py
statsmodels/tsa/statespace/tests/test_multivariate_switch_univariate.py
statsmodels/tsa/statespace/tests/test_simulation_smoothing.py
statsmodels/tsa/statespace/tests/test_smoothing.py
statsmodels/tsa/statespace/tests/test_univariate.py

This improves the state space simulation smoother in a couple of ways:
**Bugs**
- Fixes a bug with incorrect simulation smoothing draws for periods with NaN `endog` values
- Fixes a bug that could occur if the dimensions of the state space system matrices changed between `simulate` calls (e.g. one example would be if a model with a time-invariant intercept switched to a time-varying intercept between `simulate` calls)
**Enhancements**
- Adds a `random_state` argument to all simulate / simulation smoother methods (implemented the same as in [scipy rvs](https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.rv_continuous.rvs.html))
- Improves the flexibility of specifying the shocks

BUG/ENH: Fix sim smoother nan, dims / add options

---

statsmodels/tsa/exponential_smoothing/ets.py

The issue is that the left-hand side uses a mask `y_hat <= 0` while the right-hand side uses a mask `y_hat < 0`. This is obviously a problem in the corner-case that some y_hat == 0.

BUG: ETS loglike indexing bug when y_hat == 0

---

statsmodels/tsa/statespace/tools.py

I've added a much more detailed `ValueError` to `prepare_trend_spec`. The original gave the user no help whatsoever if they passed anything incorrect. 
It's my first time contributing to a project of this size. I'm not sure what kind of change this is but seems to fit DOC more than anything else? I've checked it passes flake8, is there anything else I need to do?
<details>
**Notes**:
* New code additions must be well formatted. Changes should pass flake8. …

DOC: added detailed ValueError to prepare_trend_spec()

---

statsmodels/duration/survfunc.py
statsmodels/genmod/tests/test_gee.py
statsmodels/imputation/tests/test_bayes_mi.py
statsmodels/imputation/tests/test_mice.py
statsmodels/multivariate/factor_rotation/_gpa_rotation.py
statsmodels/multivariate/tests/test_ml_factor.py
statsmodels/sandbox/bspline.py
statsmodels/stats/mediation.py
statsmodels/stats/tests/test_effectsize.py
statsmodels/tsa/deterministic.py
statsmodels/tsa/regime_switching/markov_switching.py
statsmodels/tsa/vector_ar/tests/JMulTi_results/parse_jmulti_vecm_output.py

Fix issues due to SciPy boost integration
Fix lint issues in flake8 >= 5
<details>
**Notes**:
```
``` …

MAINT: Fix lint and upstream induced changes

---

statsmodels/tsa/statespace/_quarterly_ar1.py

Use hstack in place of calling array to avoid future NumPy breaking change
<details>
**Notes**:
```
``` …

MAINT: Remove inhonogenous array constructor

---

statsmodels/regression/tests/test_regression.py
statsmodels/tsa/tests/test_tsa_tools.py
statsmodels/tsa/tsatools.py

Ensure it is a list of columns
<details>
**Notes**:
```
``` …

BUG: Ensure x_columns is a list

---

.github/workflows/generate-documentation.yml

This PR adds explicit [permissions section](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions) to workflows. This is a security best practice because by default workflows run with [extended set of permissions](https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token) (except from `on: pull_request` [from external forks](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)). By specifying any permission explicitly all others are set to none. By using the principle of least privilege the damage a compromised workflow can do (because of an [injection](https://securitylab.github.com/research/github-actions-untrusted-input/) or compromised third party tool or …

GitHub Workflows security hardening

---

statsmodels/discrete/tests/test_discrete.py
statsmodels/genmod/families/family.py

`NegativeBinomial` now warns if default value used for alpha parameter
Tests added to check for warning and ensure that warning not generated if alpha=1.0 explicitly set

GLM negative binomial warns if default used for parameter alpha

---

statsmodels/stats/power.py

Corrected the docstring for the argument "power". Definition copied from `NormalIndPower.solve_power()`.

Corrected the docstring of normal_sample_size_one_tail()

---

azure-pipelines.yml

This PR adds a weekly scheduled run to the Azure pipelines CI. It runs each Monday at 06:00 UTC on the `main` and `maintenance/0.13.x` branches.
Periodically scheduled runs can detect errors and warnings appearing in changes in upstream dependencies or the build environment. By having a scheduled run they can be traced back easier to a dependency or environment change, then if they would pop up in a random PR.

CI: Add a weekly scheduled run to the Azure pipelines

---

docs/source/dev/test_notes.rst
setup.py

Fixes the develop installs by reading `requirements-dev.txt` into setup.py and adding it to `extras_require`'s develop.
<details>
**Notes**:
```
git diff upstream/main -u -- "*.py" | …
```

MAINT: fix develop installs

---

tools/ci/azure/azure_template_posix.yml
tools/ci/azure/azure_template_windows.yml

Add Python 3.11 jobs to the Azure pipelines CI.

CI: Add Python 3.11 jobs

---

tools/ci/azure/azure_template_posix.yml

Reverts commit 99428667f since the stable Python 3.11.0 has been added to the macOS runner images (see https://github.com/actions/setup-python/issues/531#issuecomment-1291855440).
Part of #8287, reverts the second commit of #8431.

CI: Use stable Python 3.11 on macOS

---

pyproject.toml
requirements.txt

MAINT: Refine pins

---

.github/workflows/generate-documentation.yml
docs/source/dev/test_notes.rst
docs/source/release/version0.13.3.rst

DOC: Final 0.13.3 docs

---

pyproject.toml

Remove the redundant `wheel` dependency, as it is added by the backend automatically.  Listing it explicitly in the documentation was a historical mistake and has been fixed since, see: https://github.com/pypa/setuptools/commit/f7d30a9529378cf69054b5176249e5457aaf640a

BLD: Remove redundant wheel dep from pyproject.toml

---

statsmodels/base/_prediction_inference.py
statsmodels/discrete/discrete_model.py
statsmodels/genmod/generalized_linear_model.py
statsmodels/genmod/tests/test_glm.py
statsmodels/genmod/tests/test_glm_weights.py

add "which" option to GLM predict
GLM get_prediction returns generic Prediction results classes if which is not None
This is currently backwards compatible, but we will remove the old version when "linear" keyword is removed.
Then only the `which is not None` path will remain, with default which="mean"

REF/ENH: GLM predict which and get_prediction

---

statsmodels/discrete/conditional_models.py
statsmodels/duration/hazard_regression.py
statsmodels/genmod/generalized_linear_model.py

Noticed a typo in a `ValueError` message when using L2 regularization in GLM. `fit_regularized` was misspelled as `fit_regularied`. Fixed three instances of this typo.

fix typo in fit_regularized

---

statsmodels/robust/norms.py
statsmodels/robust/tests/test_mquantiles.py

work in progress, I opened the PR so I don't loose track of this
This is currently just a RobustNorm class.
no unit tests yet, and might not have correct standard errors when used in RLM.
currently I only checked that the prediction is close to quantile regression with HuberT(t=small) e.g. small=1e-6.  It "works" for expectiles when t is set very large, i.e. all observations are in the quadratic least squares range.
The prediction when using splines seems to become wigly very soon as the number of knots increases (unpenalized, just plain patsy), even more so in quantile regression and its M-quantile approximation than in least-squares expectiles.
There are several R packages mentioned in some of the articles but I have not yet looked at any of them.
This should work as smooth alternative …

WIP ENH: robust add MQuantileNorm

---

statsmodels/distributions/copula/elliptical.py

add parameter allow_singular for gaussian copula

---

statsmodels/stats/power.py
statsmodels/stats/tests/test_power.py

closes #8507
this is an updated version of #8507, using original author
changes compared to previous PR, mainly that I keep power in [0,1] in docstring

BUG: normal_sample_size_one_tail, fix std_alt default, minimum nobs

---

statsmodels/nonparametric/kde.py

Small correction to the KDE docs such that they match the code (`*` should be `+`).

DOC: Correct description of `cut` parameter for `KDEUnivariate`

---

statsmodels/tsa/stattools.py
statsmodels/tsa/tests/test_stattools.py

<details>
**Notes**:
```
```
using the Windows System for Linux once `flake8` is installed in the 
local Linux environment. While passing this test is not required, it is …

BUG: Dickey Fuller constant values (issue #8471 )

---

statsmodels/discrete/discrete_model.py
statsmodels/discrete/tests/test_discrete.py
statsmodels/genmod/generalized_linear_model.py
statsmodels/genmod/tests/test_glm.py
statsmodels/tools/sm_exceptions.py

closes #2680
currently defaults to warning instead of raising exception
I didn't add `raise_on_perfect_prediction` attribute to GLM. It is in discrete but with raising exception as default
I'm not sure yet if I keep this default and implementation

REF: PerfectSeparation, warn by default instead of raise, GLM, discrete

---

docs/source/endog_exog.rst

<details>
Changes were made to the page [http://www.statsmodels.org/dev/endog_exog.html]
At the bottom, the sentence "if the error terms are autocorrelated, then OLS does not have good statistical properties (is inconsistent)' was modified to "However, if the error terms are autocorrelated in the presense of lagged dependent variables, then, OLS does not have good statistical properties (is inconsistent)"

Changes made in the documentation on endogeneity

---

statsmodels/discrete/discrete_model.py
statsmodels/discrete/tests/test_predict.py
statsmodels/discrete/tests/test_truncated_model.py
statsmodels/genmod/families/family.py
statsmodels/genmod/families/links.py
statsmodels/genmod/families/tests/test_family.py
statsmodels/genmod/families/tests/test_link.py
statsmodels/genmod/generalized_estimating_equations.py
statsmodels/genmod/tests/test_gee_glm.py
statsmodels/genmod/tests/test_glm.py
statsmodels/genmod/tests/test_glm_weights.py

first commit here is to silence the unit test warnings.
code and tests are adjusted to avoid deprecated link names
back to 3 warnings when running all genmod unit tests
1 negbin warning still to silence
includes option to turn of link check,  closes #1880 (previous PR)

REF/TST: glm links

---

statsmodels/stats/nonparametric.py

Type is "poolean" but probably should be "boolean".

DOC: fix docstring typo in rank_compare_2indep

---

README.rst

Add the [Statsmodels logo](https://www.statsmodels.org/stable/about.html#brand-marks) to the Readme to increase the brand recognizability of Statsmodels.

Add Statsmodels logo to Readme

---

statsmodels/miscmodels/tests/test_ordinal_model.py

MAINT/TST: Relax test tol for OSX fail

---

statsmodels/distributions/copula/_special.py
statsmodels/distributions/copula/archimedean.py
statsmodels/distributions/copula/copulas.py
statsmodels/distributions/copula/extreme_value.py
statsmodels/distributions/copula/other_copulas.py
statsmodels/distributions/copula/tests/test_copula.py
statsmodels/distributions/copula/transforms.py

see #8631
pr will close bug, but maybe not add full extension to k_dim > 3
I will not implement k_dim > 4 for Frank and Gumbel for 0.14. 
Main open question is how to vectorize the special functions. We need our own functions for polylog and sterling numbers and those are not vectorized.
Also, I'm not fixing other methods, e.g. `rvs` raises if k_dim != 2. I don't know how to do those.
This includes, or will include
- bugfixes in cdf for k_dim > 2 of Clayton, explicit formula
- generic pdf for k_dim=2 also uses deriv2_inverse instead of inverting from deriv, deriv2
- explicit 3rd and 4th derivative of generator inverse transforms, Clayton, Frank and Gumbel
- analytical kth derivative of generator inverse transforms for Clayton
- todo: pdf for k_dim > 2 will for now delegate to generic …

ENH/BUG: archimedean k_dim > 2, deriv inverse in generator transform

---

statsmodels/distributions/copula/archimedean.py
statsmodels/distributions/copula/copulas.py
statsmodels/distributions/copula/elliptical.py
statsmodels/distributions/copula/extreme_value.py
statsmodels/distributions/copula/tests/test_copula.py
statsmodels/distributions/tools.py

trying to extend archimedean rvs to general k_dim
It looks like the current formulas immediately extend to k_dim > 2.
However, I have problems creating unit tests for it.  We need some gof statistics to check whether the generated data has distribution close to the data generating distribution (rvs).
2-dim marginals of k_dim = 3 look good, graphically and with approximate gof test.
But it doesn't work for full  k_dim=3 copula.
Current helper function in test_copula was written for 2-d case and does not work for k_dim=3. When I fix it, it rejects the null for the archimedean. Limitation is that function uses approximation using pdf instead of cdf.
`check_cop_rvs(cop, rvs=None, nobs=2000, k=10, use_pdf=True)`
We need better helper tools for mv distribution approximation for k-dim>2.
eg. in …

ENH/TST: archimedean rvs for k_dim>2, test/gof tools

---

statsmodels/stats/oneway.py
statsmodels/stats/power.py
statsmodels/stats/tests/test_power.py

closes #8646
closes #8624
this adds a new class as replacement for the FTestPower class.
also adds the corresponding function ftest_power_f2
two differences
- corrected names df_num, df_denom
- effect size is `f2` instead of `f`
old class is not (yet) deprecated
unit test just uses a copy of the old unit tests with the new power class

ENH/BUG: add FTestPowerF2 as corrected version of FTestPower

---

statsmodels/iolib/summary2.py
statsmodels/iolib/tests/test_summary2.py

ENH/TST: Possibility of not printing r-squared in summary_col

---

statsmodels/stats/_knockoff.py
statsmodels/stats/tests/test_knockoff.py

(sorry, I seem to have submitted that unfinished by accident, the title is supposed to be "Fix test_knockoff.py::test_sim failures and link")
Ubuntu's statsmodels [failed test_knockoff.py::test_sim on some (unusual) hardware](https://launchpadlibrarian.net/650184054/buildlog_ubuntu-lunar-s390x.statsmodels_0.13.5+dfsg-6_BUILDING.txt.gz).
This is probably because a fixed random seed only gives fixed results within a hardware type, and the threshold is strict enough that random failures are expected.  (It [can](https://salsa.debian.org/science-team/statsmodels/-/jobs/3944557/raw) also [fail](
https://salsa.debian.org/science-team/statsmodels/-/jobs/3944556/raw) on x86 if the random seed is changed.)  A rough estimate is that it fails when negativebinomial(6\*10,p=0.5)>0.05\*30\*10, or ~10% …

Fix test_knockoff.py::test_sim failures and link

---

statsmodels/tests/test_package.py

closes #8692
unintentionally deleted test module
deleted in #8343
file at commit for history and blame https://github.com/statsmodels/statsmodels/blob/35b803767bd7803ca5f9fc35d4546aa8cb7be844/statsmodels/tests/test_package.py

TST: readd deleted test_package.py 

---

statsmodels/regression/linear_model.py
statsmodels/stats/proportion.py
statsmodels/stats/tests/test_proportion.py

- reenable floats in proportion_confint except for method="binom_test"
https://github.com/statsmodels/statsmodels/pull/7998#issuecomment-1438922706
- fix type in docstring closes #8698
- score_test_proportions_2indep hardcoded correction closes #8704

BUG/DOC: doc fixes, bugs in proportion

---

statsmodels/tsa/statespace/sarimax.py

**Issue**: `SARIMAX.initial_transition` method contains loop which body does not depends on loop variable `i` and can be replaced with `if` comparison (line 763).
https://github.com/statsmodels/statsmodels/blob/a948e8dee9e99a08f249f67ca2ac5df68fea835b/statsmodels/tsa/statespace/sarimax.py#L752-L767
The variable `d` in outer loop (line 755) ranges from `0` to `self._k_seasonal_diff` (not including). Inner loop (line 763) ranges from `d + 1` to `self._k_seasonal_diff` and repeats same operation `max(0, self._k_seasonal_diff - d - 1)` times. Which corresponds to condition `d < self._k_seasonal_diff - 1`.

BUG: loop instead of if in SARIMAX transition init

---

statsmodels/tsa/arima_process.py
statsmodels/tsa/tests/test_arima_process.py

**Issue**: `ArmaProcess` can be created without AR or MA coefficient with `__init__` and `from_coeffs`. It looks like `from_roots` should also support this feature. But actually, when the method is called with empty (`None` or `[]`) `arroots` or `maroots` it throws exceptions. This is because `np.polynomial.polynomial.Polynomial.fromroots` does not work with `None` or `[]`.
This PR solves the issue and makes possible to call:
- `ArmaProcess.from_roots(arroots=[...])`
- `ArmaProcess.from_roots(maroots=[...])`
- `ArmaProcess.from_roots()`

ENH/TST: AR/MA creation with ArmaProcess.from_roots

---

docs/source/dev/index.rst

**Issue**: [developer page](https://www.statsmodels.org/stable/dev/index.html) suggests using a non-existent flake8 flag `--diff`. 
> Follow [PEP8](https://www.python.org/dev/peps/pep-0008/) style guidelines wherever possible. Compare your code to what’s in main by running git diff upstream/main -u -- "*.py" | flake8 --diff --isolated prior to submitting.
The option `--diff` was removed in version 6.0.0 (https://flake8.pycqa.org/en/latest/release-notes/6.0.0.html#backwards-incompatible-changes).

DOC: fix developer page linting requirements

---

statsmodels/discrete/count_model.py
statsmodels/discrete/discrete_model.py
statsmodels/discrete/tests/test_conditional.py
statsmodels/discrete/tests/test_predict.py
statsmodels/discrete/truncated_model.py
statsmodels/genmod/generalized_linear_model.py
statsmodels/genmod/tests/test_glm.py
statsmodels/othermod/betareg.py
statsmodels/othermod/tests/test_beta.py
statsmodels/tools/numdiff.py

#8723
This also warns now on invalid `__init__` kwargs in BetaModel closes #8779
I changed the get_distribution in discrete to return 1-d instead of 2d.
~~Some unit tests might fail.~~ They didn't
Some parts don't fail because they are written to handle both 1-d or one 2-d column returns, they work around current inconsistency in return shape.
Not decided yet:
Do we add an option `as_column=False` to get_distribution?
Currently, I commented out the old column code, so I can reuse it if we add the option.
**update** not for now
Related missing:
GLM and OLS need results method (they only have model.get_distribution)

REF: get_distribution, return 1-d instead of column frozen distribution

---

statsmodels/compat/pandas.py
statsmodels/imputation/tests/test_mice.py
statsmodels/stats/descriptivestats.py

MAINT: Improve specificity of warning check

---

statsmodels/regression/recursive_ls.py
statsmodels/tsa/statespace/dynamic_factor_mq.py
statsmodels/tsa/statespace/exponential_smoothing.py
statsmodels/tsa/statespace/kalman_filter.py
statsmodels/tsa/statespace/kalman_smoother.py
statsmodels/tsa/statespace/mlemodel.py
statsmodels/tsa/statespace/representation.py
statsmodels/tsa/statespace/tests/test_fixed_params.py
statsmodels/tsa/statespace/tests/test_mlemodel.py

The base state space class (`Representation`) silent swallows invalid `kwargs`. This fixes that behavior and raises a `TypeError` as usual.

ENH/BUG: statespace: issue FutureWarning for unknown keyword args

---

statsmodels/distributions/bernstein.py
statsmodels/distributions/copula/archimedean.py
statsmodels/distributions/tests/test_tools.py
statsmodels/distributions/tools.py
statsmodels/robust/scale.py

closes #8821
handles numpy deprecation alltrue and product, 
(not the one-element-array versus scalar problem)

Maint: remove deprecated np.alltrue and np.product

---

docs/source/contingency_tables.rst
docs/source/plots/stl_plot.py
docs/source/treatment.rst
requirements-doc.txt
setup.cfg
statsmodels/datasets/danish_data/data.py
statsmodels/distributions/copula/archimedean.py
statsmodels/emplike/originregress.py
statsmodels/genmod/families/tests/test_family.py
statsmodels/sandbox/distributions/extras.py
statsmodels/sandbox/distributions/tests/test_transf.py

MAINT/DOC: Fix more deprecations and restore doc build

---

statsmodels/discrete/discrete_model.py
statsmodels/genmod/generalized_linear_model.py
statsmodels/genmod/tests/test_glm.py
statsmodels/sandbox/stats/runs.py
statsmodels/stats/_diagnostic_other.py
statsmodels/stats/outliers_influence.py
statsmodels/stats/rates.py
statsmodels/stats/tests/test_nonparametric.py
statsmodels/stats/tests/test_rates_poisson.py
statsmodels/tsa/base/tsa_model.py
statsmodels/tsa/statespace/simulation_smoother.py
statsmodels/tsa/statespace/tests/test_simulation_smoothing.py

Use FutureWarning for visibility
closes #8628
<details>
**Notes**:
```
``` …

MAINT: Switch DeprecationWarn to FutureWarn

---

statsmodels/graphics/regressionplots.py
statsmodels/graphics/tests/test_regressionplots.py

OLS results doesn't have (doesn't need) a converged attribute, so the added variable plot fails.

BUG: Fix added variable plots to work with OLS

---

statsmodels/discrete/tests/test_sandwich_cov.py
statsmodels/genmod/generalized_linear_model.py
statsmodels/stats/_delta_method.py

closes #4751
see also #7341 mentions weights which are not supported here in GLM
adding margeff to GLM is largely copy-paste-adjust
unit tests compare GLM with discrete Logit, Probit and Poisson in `discrete/tests/test_sandwich_cov`
those comparisons do not include Negbin NB2
(could possibly be backported even though it's an enhancement)

ENH: add get_margeff to GLM

---

statsmodels/gam/generalized_additive_model.py

Currently, when called with `cpr=True`, `GLMGamResults.plot_partial` will plot the scatter of residuals over the fitted curve:
The change plots the curve over the scatter and reduces the marker size:

ENH: plot prediction curve over scatter in GLMGamResults.plot_partial

---

statsmodels/regression/linear_model.py

Correct the sign of the last term of the log likelihood expression.
Clarify the meaning of the (not standard) vertical bars notation.
<details>
There was a mismatch between the docstring and the code, and the code seems to be correct.
It took me a while to understand what |W| meant, I finally figured out it's the determinant, which simplify to the product of the diagonal terms in this case. This notation is not standard across branches of maths, so I added a comment to clarify the meaning.
</details>

DOC: correct typo in WLS.loglike docstring

---

statsmodels/graphics/tests/test_tsaplots.py
statsmodels/graphics/tsaplots.py

- New function `plot_ccf` to plot cross-correlations by lag between two variables, analogous to `plot_acf`.
- New function `plot_accf` to plot a matrix of auto- and cross-correlation plots between several variables.

ENH: Plot cross-correlations and auto/cross-correlation matrix

---

statsmodels/multivariate/multivariate_ols.py

BUG: Writing read-only arry on pandas 2/CoW

---

statsmodels/tsa/statespace/_tools.pyx.in
statsmodels/tsa/statespace/dynamic_factor_mq.py
statsmodels/tsa/statespace/kalman_smoother.py
statsmodels/tsa/statespace/mlemodel.py
statsmodels/tsa/statespace/news.py
statsmodels/tsa/statespace/tests/test_news.py
statsmodels/tsa/statespace/tests/test_weights.py
statsmodels/tsa/statespace/tools.py
statsmodels/tsa/statespace/varmax.py

This PR primarily adds the ability to only compute detailed impacts for revisions to existing data starting at a certain period, but using the new `revisions_details_start` argument to the `news` method.
For all data revisions prior to that period, the total impact of revisions is still computed, but it is reported as a single grouped impact.
This can massively improve performance when a data series has minor revisions throughout its entire history that the user does not need to compute detailed impacts for.

ENH/PERF: faster computation of revision impacts

---

statsmodels/stats/tests/test_weightstats.py
statsmodels/stats/weightstats.py

Adds the case for unequal variances in the 2-sample z-test in `weightstats.py`.
Closes #8936 
@josef-pkt

ENH: 2-sample z-test unequal variances case

---

statsmodels/tsa/vector_ar/var_model.py

Fixes the return type inconsistency in `var_model.py`
@bashtage @ChadFulton

DOC: fix inconsistency in `var_model.py`

---

requirements.txt

Block pandas 2.1.0 due to bug in MultiIndex assignment
<details>
**Notes**:
```
``` …

MAINT: Block pandas 2.1.0

---

statsmodels/tsa/statespace/tests/results/results_structural.py
statsmodels/tsa/statespace/tests/test_structural.py
tools/ci/azure/azure_template_posix.yml

Use required freq names, A->Y
Remove unnecessary pytest help
<details>
**Notes**:
```
``` …

MAINT: Use modern freq names

---

statsmodels/graphics/tests/test_tsaplots.py
statsmodels/graphics/tsaplots.py
statsmodels/tsa/stattools.py
statsmodels/tsa/tests/test_stattools.py

Reduce default lag size when sample is small
closes #9015
<details>
**Notes**:
```
``` …

ENH: Improve lag selection in pacf

---

statsmodels/tsa/deterministic.py

This pull request refactors a function that drops all but the first constant column from `DeterministicProcess.in_sample` object. Previously, it was raising a FutureWarning due to development in the pandas library. The change removes the need to assign to a Series based on index altogether by creating a single mask that flags surplus constant columns. For example, if columns B, C, F were constant columns (in that order), the mask flags column B as False and flags C and F as True. Therefore, if we negate this  mask, we select the desired columns.
Given the example:
```python
terms = pd.DataFrame({'A': [1, 3, 1], 'B': 2, 'C': 1.1, 'D': 20, 'E': [10, 20, 20], 'F': 10}, index=range(3))
```
`B`, `C`, `F` are constant columns. Then 
```python
is_constant = terms.max(axis=0) == terms.min(axis=0) …
```

refactor code to drop constant columns

---

statsmodels/genmod/tests/test_glm.py
statsmodels/imputation/tests/test_mice.py
statsmodels/multivariate/factor_rotation/_wrappers.py
statsmodels/sandbox/panel/panelmod.py
statsmodels/sandbox/sysreg.py
statsmodels/tsa/statespace/structural.py
statsmodels/tsa/statespace/tests/results/results_structural.py
statsmodels/tsa/statespace/tools.py

Fix some linting errors found by `ruff`. 
Is it also a welcome change in `statsmodels` to add `ruff` as a linting tool to leverage its autofix feature? It can be added as either a GitHub Actions job, a `pre-commit` job, or part of the current `lint.sh` file
<details>
**Notes**:
* New code additions must be well formatted. Changes …

Fix linting error

---

statsmodels/graphics/gofplots.py
statsmodels/graphics/mosaicplot.py

Fix these string formatting errors
```bash
statsmodels/graphics/gofplots.py:263:19: F523 [*] `.format` call has unused arguments at position(s): 0
statsmodels/graphics/mosaicplot.py:43:26: F523 [*] `.format` call has unused arguments at position(s): 0
statsmodels/graphics/mosaicplot.py:63:26: F523 [*] `.format` call has unused arguments at position(s): 1
Found 3 errors.
```

Fix string formatting

---

statsmodels/tsa/arima/tests/test_model.py
statsmodels/tsa/statespace/mlemodel.py

Ensure rpoducability by creating random_state earlier and using consistently
<details>
**Notes**:
```
``` …

BUG: Ensure ARIMA simulation is reproducable

---

statsmodels/graphics/tests/test_tsaplots.py
statsmodels/tools/tests/test_grouputils.py

Fix dim change from NumPy
Switch freq string
<details>
**Notes**:
```
``` …

MAINT: Fixes for pre-release testing

---

examples/notebooks/gls.ipynb
examples/notebooks/influence_glm_logit.ipynb
examples/notebooks/ols.ipynb
examples/notebooks/regression_diagnostics.ipynb
examples/notebooks/robust_models_1.ipynb
examples/notebooks/wls.ipynb
statsmodels/stats/diagnostic.py
statsmodels/stats/tests/test_diagnostic.py
statsmodels/tsa/tests/test_seasonal.py

Consistently use cov_kwds
Fix bug that can occur in some tests due to wrong name passed to OLS.fit
closes #9121
<details>
**Notes**:
```
git diff upstream/main -u -- "*.py" | flake8 …
```

BUG: Correct cov_kwargs -> cov_kwds

---

examples/notebooks/autoregressions.ipynb
examples/notebooks/deterministics.ipynb
examples/notebooks/ets.ipynb
examples/notebooks/exponential_smoothing.ipynb
examples/notebooks/linear_regression_diagnostics_plots.ipynb
examples/notebooks/postestimation_poisson.ipynb
examples/notebooks/statespace_concentrated_scale.ipynb
examples/notebooks/statespace_local_linear_trend.ipynb
setup.cfg
statsmodels/base/tests/test_generic_methods.py
statsmodels/base/tests/test_shrink_pickle.py
statsmodels/discrete/tests/test_predict.py
statsmodels/graphics/gofplots.py
statsmodels/regression/linear_model.py
statsmodels/regression/tests/test_processreg.py
statsmodels/sandbox/predict_functional.py
statsmodels/tools/tests/test_tools.py
statsmodels/tsa/exponential_smoothing/ets.py
statsmodels/tsa/innovations/arma_innovations.py
statsmodels/tsa/statespace/mlemodel.py
statsmodels/tsa/statespace/tests/test_kalman.py
statsmodels/tsa/statespace/tests/test_mlemodel.py
statsmodels/tsa/tests/test_deterministic.py

Start to address issues with read-only arrays
Fix other warnings from pandas 3
<details>
**Notes**:
```
```
assuming …

MAINT: Fix issues with pandas 3

---

statsmodels/stats/weightstats.py

The pvalue description in the `weightstats.py` file has been updated from "pvalue of the t-test" to "pvalue of the z-test". This change ensures accurate documentation of the statistical test being performed.
<details>
**Notes**:
verify …

DOC: Update pvalue description in weightstats.py of `ztest` and `ztest_mean`

---

statsmodels/genmod/generalized_linear_model.py
statsmodels/genmod/tests/test_glm.py
statsmodels/tools/data.py
statsmodels/tools/tests/test_data.py

Offset, exposure, freq_weights and var_weights have the name of the series saved on the model object. They can be accessed via the class properties.
Closes #9100
Getting this as a starting point.  This enables the feature for GLM's. Happy to make any recommended changes.
I didn't edit the release notes, wasn't sure if this would be worth mentioning. Kept the smaller notes in the commit message for now.
I opted for only doing one dimensional arrays in the helper because the caller would need to check the shape if it returned more than one name. Seems like a separate helper for multi dimensional might be needed unless there's a different way we were expecting to use …

ENH: GLM models now save the names of input Pandas Series

---

statsmodels/graphics/boxplots.py

MPL boxplot has replaced vert with orientation
<details>
**Notes**:
```
``` …

MAINT: Change future keyword argument

---

statsmodels/stats/rates.py
statsmodels/stats/tests/test_rates_poisson.py

<details>
Added the 'alternative' option to confint_poisson to enable the calculation of a one-sided CI. It has three options: two-sided(default), larger, and smaller. When either larger or smaller is selected, ci_low or ci_upp is returned as 0 or np.inf.
</details>

ENH: add alternative option to confint_poisson

---

setup.py

I'm rebuilding RPM packages to check build reproducibility (https://docs.fedoraproject.org/en-US/reproducible-builds/), and we got the result that rebuilds of statsmodels varies in this trivial way:
│ │          "include_dirs": [
│ │ -            "statsmodels/src",
│ │              "/usr/lib64/python3.13/site-packages/numpy/core/include",
│ │ +            "statsmodels/src",
│ │              "/usr/lib64/python3.13/site-packages/numpy/core/include"
│ │          ],
(the same pattern repeats hundreds of times).
sets are hash-ordered, not insertion ordered, so the order in list(set(…)) is not reproducible. Sort the entries instead.
<details>
**Notes**:
* It is essential …

Avoid random ordering in include_dirs lists

---

statsmodels/tsa/stattools.py
statsmodels/tsa/tests/test_stattools.py

Remove use of in-place op
Add test
<details>
**Notes**:
```
``` …

BUG: Ensure ZA does not overwrite

---

docs/source/dev/index.rst
docs/source/graphics.rst
statsmodels/graphics/tsaplots.py

Adds a reference to ``plot_ccf`` and ``plot_accf_grid`` in ``docs/source/graphics.rst`` so that the docs for the functions are included in the generated output. This was missed from #8783.
<details>
**Notes**:
verify you changes are …

DOC: Generate docs for plot_ccf and plot_accf_grid

---

statsmodels/tsa/statespace/mlemodel.py
statsmodels/tsa/statespace/sarimax.py
statsmodels/tsa/statespace/tests/test_mlemodel.py

Explictly call copy() to avoid setting attributes on data not owned by the model
<details>
**Notes**:
```
```
assuming …

ENH/BUG: Ensure array is owned

---

statsmodels/tsa/base/tests/test_tsa_indexes.py
statsmodels/tsa/base/tsa_model.py

Use element-wise comparrison eather than .equals() to avoid dtype changes
<details>
**Notes**:
```
``` …

MAINT: Change how indices are compared

---

lint.sh
setup.cfg

Move to 88 characters
closes #9347
<details>
**Notes**:
```
``` …

STY: Accept 88 characters in linting

---

setup.py
tools/ci/azure/azure_template_posix.yml

Simplify setup since NumPy wikk always be installed when using pip install.
Standardize library usage
xref #9333
<details>
**Notes**:
```
git diff upstream/main -u -- "*.py" | flake8 …
```

MAINT: Simplify and standardize setup

---

docs/source/regression.rst

Hi all, new contributor but very much enjoy the syntax and implementations of statistical models. As a tiny first contribution, I changed the \mu to \epsilon in the OLS documentation. I think this is more standard notation in statistics, I'm not sure about other fields but since it's mostly a statistical concept it seems like this would be more straightforward. I think \mu could be confused with a mean, which is usually its meaning. 
If you don't like the change, feel free to reject it :)

adjusting notation of error term in regression docs

---

statsmodels/tsa/vector_ar/svar_model.py

This PR corrects the LaTeX formula in the `SVAR` class docstring, ensuring proper display in the generated documentation.
- No code changes were made, so no tests were added.
- The updated docstring has been verified through a local documentation build and displays correctly.
**Notes**:
* New code additions must be well formatted. …

Fix docstring formula display in SVAR class

---

statsmodels/graphics/agreement.py

Avoids trailing digits bug that appears in matplotlib figure output
closes #9125
<details>
**Notes**:
```
```
assuming …

ENH: changed np.round(mean_dff,2) -> mean_diff:.3g

---

docs/source/stats.rst
examples/notebooks/regression_diagnostics.ipynb
statsmodels/regression/linear_model.py

regression diagnostics:
- Add explanations for Durbin-Watson and Kurtosis. 
- Include DW-test and Breusch-Godfrey test for autocorrelation. 
- Reorder some parts for better readability
stats.html
- Reorder and add subtitle
summary
- Add notes section link to regression diagnostics
closes #9099

DOC: Improve docs of `regression_diagnostics.html`, `stats.html`, `summary`

---

statsmodels/tools/docstring.py
statsmodels/tsa/ardl/model.py
statsmodels/tsa/ardl/tests/test_ardl.py
statsmodels/tsa/arima_process.py
statsmodels/tsa/stattools.py
statsmodels/tsa/vector_ar/tests/test_var_jmulti.py
statsmodels/tsa/vector_ar/tests/test_vecm.py
tools/nbgenerate.py

Override resid property to compute correct residuals
closes #9323
<details>
**Notes**:
```
``` …

BUG: Corect resid from UECM

---

statsmodels/tsa/statespace/dynamic_factor_mq.py
statsmodels/tsa/statespace/tests/test_dynamic_factor_mq.py

Replace Series.append() with pd.concat() to resolve AttributeError with factor_orders option
Update corresponding test to check that factor_orders can receive a dict
<details>
**Notes**:
verify you changes are well formatted by running …

MAINT: Replace deprecated Pandas append with concat in dynamic_factor_mq

---

INSTALL.txt

Also the [statsmodels.org](https://www.statsmodels.org/stable/install.html) has a message:
```
Python Support
statsmodels supports Python 3.8, 3.9, and 3.10.
```
But if you scroll to the Dependencies section, it says that Python 3.8 is not supported:
```
Dependencies[¶](https://www.statsmodels.org/stable/install.html#dependencies)
The current minimum dependencies are:
[Python](https://www.python.org/) >= 3.9
[NumPy](https://www.scipy.org/) >= 1.22.3
[SciPy](https://www.scipy.org/) >= 1.8
[Pandas](https://pandas.pydata.org/) >= 1.4
[Patsy](https://patsy.readthedocs.io/en/latest/) >= 0.5.6
```

Dependencies consistency

---

statsmodels/tsa/seasonal.py
statsmodels/tsa/tests/test_seasonal.py

Use freq rather than inferred freq
closes #9460
<details>
**Notes**:
```
``` …

BUG: Correct handleing of PeriodIndex in seasonal_decompose

---

statsmodels/robust/tests/test_covariance.py
statsmodels/tsa/statespace/tests/test_dynamic_factor.py

TST: Relax tolerance on overly tight test

---

statsmodels/tsa/ar_model.py
statsmodels/tsa/ardl/tests/test_ardl.py

The ARDL class constructor accepts a trend specification which must be one of 'n', 'c', 't', 'ct'.  This PR allows for one more option 'ctt' which provides for a quadratic trend. This is supported by other models and the infrastructure supports this with just a one or two line change.
Internally exogenous variables for 1, t, t**2 are generated and passed to OLS. I did not need to add code for that to take place. It was already available.

[ENH] Allow ARDL model trend 'ctt'

---

docs/source/index.rst

Fix Broken Link to Citation Paper of 2010 Conference
Before:
After:
Not a code change. Change to a broken link in the documentation.
<details>
**Notes**:
```
git diff upstream/main -u -- …
```

Fix Broken Link to Citation Paper of 2010 Conference

---

statsmodels/tsa/tests/test_x13.py
statsmodels/tsa/x13.py

This commit adds an option to pass in a raw `.spec` file to the `x13_arima_analysis()` function, either as a path or as a string. 
We needed a way to use more advanced configuration options for x13, but adding all the specifications to the statsmodels function itself seemed like an exercise in futility. (the manual for x13 is [nearly 300 pages](https://www2.census.gov/software/x-13arima-seats/x13as/windows/documentation/docx13as.pdf)) The string substitution is hopefully not too brittle.

Add optional raw spec parameter for x13_arima_analysis()

---

statsmodels/stats/tests/test_corrpsd.py
statsmodels/tsa/forecasting/tests/test_theta.py

Run test but allow xfail if it does not converge
<details>
**Notes**:
```
``` …

TST: Report xfail for flaky test

---

pyproject.toml
statsmodels/tools/tests/test_grouputils.py
statsmodels/tsa/vector_ar/vecm.py

MAINT: Remove panding deprecation matrix usage
