statsmodels/statsmodels

- statsmodels/base/distributed_estimation.py
- statsmodels/discrete/conditional_models.py
- statsmodels/discrete/count_model.py
- statsmodels/genmod/generalized_estimating_equations.py
- statsmodels/tsa/statespace/mlemodel.py
Fixed handful of spelling, and some minor doc string issues that were in the build log.
> DOC: Spelling and Doc String Fixes

- .travis.yml
- appveyor.yml
- requirements-dev.txt
- tools/ci/azure_template.yml
Set hashseed to avoid pytest issues
<details>
**Notes**:
```
``` …
> MAINT: Exclude pytest-xdist 1.30

- docs/source/install.rst
<details>
**Notes**:
```
```
using the …
> fix a typo

- docs/source/install.rst
<details>
**Notes**:
```
```
using the …
> fix typos in install.rst

- statsmodels/genmod/generalized_estimating_equations.py
- statsmodels/genmod/tests/test_gee.py
<details>
This makes scale parameter handling in GEE more consistent with GLM.
**Notes**:
```
``` …
> ENH: Scale parameter handling in GEE

- statsmodels/tsa/holtwinters.py
- statsmodels/tsa/tests/test_holtwinters.py
> BUG: division by zero in exponential smoothing if damping_slope=0

- statsmodels/tsa/statespace/dynamic_factor.py
- no tests added since this is just a change to start params computation
> BUG: dynamic factor model use AR model for error start params if error_var=False

- docs/source/endog_exog.rst
- statsmodels/base/model.py
- statsmodels/genmod/generalized_linear_model.py
- statsmodels/regression/linear_model.py
- statsmodels/regression/process_regression.py
- statsmodels/regression/recursive_ls.py
Minor fixes addressing some of the doc string issues in Travis CI logs.
<details>
**Notes**:
```
``` …
> DOC: docstring fixes

- statsmodels/tsa/base/tsa_model.py
- statsmodels/tsa/statespace/sarimax.py
- statsmodels/tsa/statespace/tests/test_sarimax.py
> BUG: SARIMAX index behavior with simple_differencing=True

- .travis.yml
- tools/ci/travis_conda.sh
- tools/ci/travis_pip.sh
Add Python 3.8 using pip
closes #6245
<details>
**Notes**:
```
``` …
> TST: Add Python 3.8 environment

- .gitignore
add .vscode to gitignore
vscode creates a .vscode folder whenever you open a folder/workspace. I wanted to change something very minor for my first PR just to make sure I understood the process.
> ignore vscode

- examples/notebooks/categorical_interaction_plot.ipynb
- examples/notebooks/wls.ipynb
Fixed typos in example notebooks.
> DOC: Fix spelling in notebooks

- statsmodels/tsa/arima/model.py
- statsmodels/tsa/arima/specification.py
- statsmodels/tsa/arima/tests/test_model.py
> BUG: cloning of arima.ARIMA models.

- .travis.yml
[skip appveyor]
<details>
**Notes**:
```
``` …
> DOC: Build v0.10.2 docs

- .travis.yml
- tools/ci/docbuild.sh
Ensure directory is correct
<details>
**Notes**:
```
``` …
> DOC: Fixes to get 0.10.2 docs to build

- .travis.yml
Restore test environments
<details>
**Notes**:
```
``` …
> MAINT: Revert tep changes to travis

- statsmodels/stats/tests/test_diagnostic.py
<details>
**Notes**:
```
```
using the …
> WIP: Relax precision for ppc64el

- statsmodels/tools/tests/test_grouputils.py
Update test tolerance due to future failures in grouping
<details>
**Notes**:
```
``` …
> MAINT: Update test tolerance

- statsmodels/emplike/api.py
- statsmodels/emplike/elanova.py
- statsmodels/emplike/elregress.py
- statsmodels/emplike/originregress.py
- statsmodels/formula/formulatools.py
- tools/generate_formula_api.py
- tools/github_stats.py
<details>
**Notes**:
```
```
using the …
> DOC: doc string changes

- statsmodels/nonparametric/bandwidths.py
- statsmodels/nonparametric/tests/test_kernel_density.py
<details>
**Notes**:
```
```
using the …
> Padarn singlepointkde patch

- statsmodels/stats/contingency_tables.py
- statsmodels/stats/tests/test_contingency_tables.py
<details>
Thanks @sam-data-guy, this should improve the argument checking that you encountered.
Also a bit of test improvement.
**Notes**:
``` …
```
> ENH: better argument checking for StratifiedTable

- examples/notebooks/gee_nested_simulation.ipynb
- examples/notebooks/gee_score_test_simulation.ipynb
- statsmodels/genmod/cov_struct.py
This notebook uses simulation to assess the performance of GEE score tests, and also serves to illustrate how they are used.
> DOC: Add example notebook for GEE score tests

- statsmodels/regression/linear_model.py
- statsmodels/regression/quantile_regression.py
- statsmodels/tools/tests/test_tools.py
- statsmodels/tools/tools.py
- statsmodels/tsa/vector_ar/irf.py
- statsmodels/tsa/vector_ar/var_model.py
- statsmodels/tsa/vector_ar/vecm.py
Remove chain dot in favor of using @
<details>
**Notes**:
```
``` …
> MAINT: Remove chain dot

- statsmodels/nonparametric/smoothers_lowess_old.py
- statsmodels/regression/quantile_regression.py
- statsmodels/sandbox/nonparametric/smoothers.py
- statsmodels/tsa/interp/denton.py
- statsmodels/tsa/vector_ar/var_model.py
Use NumPy for functions that are exported by NumPy and leave special
purpose functions to SciPy
closes #1218
<details>
**Notes**:
```
git diff upstream/master -u -- "*.py" | flake8 …
```
> MAINT: Use NumPy's linalg when available

- README.rst
- docs/source/dev/test_notes.rst
Provide a single preferred method to run tests
closes #4245
<details>
**Notes**:
```
``` …
> DOC: Update test running instructions

- statsmodels/sandbox/stats/multicomp.py
Restore deleted sandbox stats multicomp file
<details>
**Notes**:
```
``` …
> BUG: Restore multicomp

- examples/notebooks/statespace_varmax.ipynb
Repalce "nc" with now required "n"
<details>
**Notes**:
```
``` …
> BUG: Fix trend due to recent changes

- statsmodels/gam/generalized_additive_model.py
Ref #6192
<details>
**Notes**:
```
```
using …
> DOC: fix alpha description for GLMGam

- docs/source/regression.rst
- setup.cfg
- statsmodels/sandbox/stats/diagnostic.py
- statsmodels/sandbox/tools/mctools.py
- statsmodels/stats/tests/test_diagnostic.py
- statsmodels/tools/tools.py
- statsmodels/tsa/ar_model.py
- statsmodels/tsa/statespace/mlemodel.py
- statsmodels/tsa/tsatools.py
<details>
**Notes**:
```
```
using the …
> Improve ljung box

- statsmodels/tsa/arima/model.py
- statsmodels/tsa/arima/specification.py
- statsmodels/tsa/statespace/mlemodel.py
- statsmodels/tsa/statespace/sarimax.py
- statsmodels/tsa/statespace/tests/test_sarimax.py
> BUG: fix k_exog, k_trend in arima.ARIMA; raise error when cloning a model with exog if no new exog given

- statsmodels/tsa/base/tests/test_tsa_indexes.py
- statsmodels/tsa/base/tsa_model.py
> BUG: fix _get_index_loc with date strings

- docs/source/release/version0.11.rst
Update with latest information
<details>
**Notes**:
```
``` …
> DOC: Update Release Note

- docs/source/api.rst
- docs/source/datasets/index.rst
- docs/source/release/version0.11.rst
- docs/source/statespace.rst
- statsmodels/tsa/statespace/exponential_smoothing.py
- statsmodels/tsa/statespace/simulation_smoother.py
Fix errors foudn in doc build
<details>
**Notes**:
```
``` …
> DOC: Fix documentation errors

- docs/source/names_wordlist.txt
- docs/source/spelling_wordlist.txt
- examples/notebooks/autoregressions.ipynb
- examples/notebooks/gee_score_test_simulation.ipynb
- examples/notebooks/statespace_seasonal.ipynb
- examples/python/statespace_seasonal.py
- statsmodels/genmod/bayes_mixed_glm.py
- statsmodels/multivariate/factor_rotation/_gpa_rotation.py
- statsmodels/nonparametric/tests/test_lowess.py
- statsmodels/regression/process_regression.py
- statsmodels/sandbox/distributions/extras.py
- statsmodels/sandbox/distributions/otherdist.py
- statsmodels/sandbox/distributions/transform_functions.py
- statsmodels/sandbox/distributions/transformed.py
- statsmodels/sandbox/panel/panel_short.py
- statsmodels/sandbox/regression/tools.py
- statsmodels/tsa/ar_model.py
- statsmodels/tsa/arima/model.py
- statsmodels/tsa/statespace/mlemodel.py
- statsmodels/tsa/statespace/tests/test_exponential_smoothing.py
More doc fixes preparing for release
<details>
**Notes**:
```
``` …
> DOC: Further doc fixes

- docs/source/index.rst
- docs/source/names_wordlist.txt
- docs/source/release/version0.11.rst
- docs/source/spelling_wordlist.txt
- docs/source/statespace.rst
- docs/source/tsa.rst
Fix small errors in documentation
<details>
**Notes**:
```
``` …
> DOC: Fix minor doc errors

- docs/source/dev/index.rst
This is a small doc fix. 
**Notes**:
```
``` …
> DOC: git notes

- docs/source/release/version0.11.rst
- tools/releasing/release_note.py
- tools/releasing/release_note.tmpl
Finalize release notes to make an RC
<details>
**Notes**:
```
``` …
> DOC: Finalize release notes for 0.11

- docs/source/release/version0.11.rst
- statsmodels/graphics/tests/test_regressionplots.py
- statsmodels/multivariate/tests/test_factor.py
- tools/releasing/release_note.py
Finishing touches
Improve release note generator documentation
<details>
**Notes**:
```
``` …
> DOC: Finalize release note

- docs/source/_templates/autosummary/class.rst
Remove one level of generation
closes #6362
<details>
**Notes**:
```
``` …
> DOC: Change generated path

- statsmodels/stats/stattools.py
- statsmodels/stats/tests/test_statstools.py
Use std rather than var
closes #6373
<details>
**Notes**:
```
``` …
> BUG: Correct standardization in robust skewness

- statsmodels/sandbox/stats/diagnostic.py
Clarify demeaning
closes #6379
<details>
**Notes**:
```
``` …
> DOC: Clarify demeaning in ljungbox

- statsmodels/base/tests/test_data.py
- statsmodels/base/tests/test_shrink_pickle.py
- statsmodels/compat/pandas.py
- statsmodels/datasets/tests/test_utils.py
- statsmodels/discrete/tests/test_discrete.py
- statsmodels/formula/tests/test_formula.py
- statsmodels/genmod/generalized_estimating_equations.py
- statsmodels/imputation/tests/test_ros.py
- statsmodels/iolib/tests/test_foreign.py
- statsmodels/regression/rolling.py
- statsmodels/stats/tests/test_anova_rm.py
- statsmodels/tools/_testing.py
- statsmodels/tools/tests/test_grouputils.py
- statsmodels/tools/tests/test_tools.py
- statsmodels/tsa/filters/tests/test_filters.py
- statsmodels/tsa/tests/test_tsa_tools.py
- statsmodels/tsa/vector_ar/tests/test_var.py
Unify into compat to avoid future breaks
<details>
**Notes**:
```
``` …
> MAINT: Unify pandas testing import

- statsmodels/tsa/filters/hp_filter.py
This PR fixes a small yet important mistype in the documentation of the `hpfilter` function.
> DOC: fix ridge regression formula in hpfilter

- codecov.yml
Improve codecov to reduce false failure reports
<details>
**Notes**:
```
``` …
> MAINT: Clarify codecov

- docs/source/contrasts.rst
closes #6395
[skip ci]
<details>
**Notes**:
```
``` …
> DOC: Fix link

- docs/source/release/version0.11.rst
- docs/source/stats.rst
- statsmodels/stats/dist_dependence_measures.py
- statsmodels/stats/tests/test_dist_dependant_measures.py
An implementation of Distance dependence measures and the Distance Covariance (dCov) test, as introduced by Szekely, G.J., Rizzo, M.L., and Bakirov, N.K. (2007) “Measuring and testing dependence by correlation of distances”. Annals of Statistics, Vol. 35 No. 6, pp. 2769-2794.
Any and all feedback is most welcome and I'd be happy to make any changes if need be.
> ENH: Distance dependence measures

- .travis.yml
Swith to bionic and cache pip
<details>
**Notes**:
```
``` …
> MAINT: Switch to bionic

- statsmodels/tests/test_package.py
Use sys.executable inplace of hard coded name
closes #6420
<details>
**Notes**:
```
``` …
> BUG: Improve executable detection

- requirements-dev.txt
[skip appveyor] [skip travis]
Remove from requirements-dev to allow requirements to be satisfied
<details>
**Notes**:
``` …
```
> MAINT: Disable cvxopt for windows

- docs/source/release/version0.11.rst
- lint.sh
- setup.cfg
- statsmodels/stats/contingency_tables.py
- statsmodels/stats/diagnostic.py
- statsmodels/stats/tests/test_diagnostic.py
<details>
**Notes**:
```
```
using the …
> MAINT: Fix future issues

- statsmodels/tsa/tests/test_holtwinters.py
Reduce tolerance so that spurious fails stop
<details>
**Notes**:
```
``` …
> MAINT: Reduce tolerance on basin hopping test

- statsmodels/tsa/tests/test_holtwinters.py
Remove an unused import
<details>
**Notes**:
```
``` …
> MAINT: Remove unused import

- docs/source/release/version0.11.rst
<details>
**Notes**:
```
```
using the …
> DOC: Final release note change for 0.11

- .travis.yml
- tools/ci/docbuild.sh
Perform a special docbuild
Trick travis into rebuilding 0.11 docs.
closes #6455
xref pandas-dev/pandas#31212
> DOC: Special docbuild

- .travis.yml
- tools/ci/docbuild.sh
Reverts statsmodels/statsmodels#6457
> Revert "DOC: Special docbuild"

- statsmodels/nonparametric/bandwidths.py
> MAINT: correcting typo

- statsmodels/regression/linear_model.py
- statsmodels/regression/tests/test_regression.py
Intercept nan fvalue and return nan pvalue
<details>
**Notes**:
```
``` …
> MAINT: Avoid noise in f-pvalue

- azure-pipelines.yml
- tools/ci/azure_template.yml
Switch to 3.8
<details>
**Notes**:
```
``` …
> MAINT: Replace Python 3.5 with 3.8 on Azure

- .travis.yml
- INSTALL.txt
- appveyor.yml
- docs/source/install.rst
- pyproject.toml
- requirements.txt
- setup.py
Update to reflect 0.12 versions supports
<details>
**Notes**:
```
``` …
> MAINT: Update supported versions

- statsmodels/stats/libqsturng/qsturng_.py
- statsmodels/stats/tests/test_pairwise.py
Ensure function output is scalar
<details>
**Notes**:
```
``` …
> MAINT: Avoid future error

- .travis.yml
- pyproject.toml
- tools/ci/azure_template.yml
[skip appveyor] [skip travis]
Use pip to install on Azure
<details>
**Notes**:
```
``` …
> BLD: Use pip on Azure

- lint.sh
- pyproject.toml
- setup.cfg
- statsmodels/graphics/boxplots.py
- statsmodels/graphics/tests/test_boxplots.py
- statsmodels/nonparametric/bandwidths.py
- statsmodels/regression/linear_model.py
- statsmodels/regression/tests/test_regression.py
- statsmodels/stats/libqsturng/qsturng_.py
- statsmodels/stats/tests/test_pairwise.py
- statsmodels/tsa/innovations/tests/test_cython_arma_innovations_fast.py
- statsmodels/tsa/tests/test_arima.py
- tools/ci/azure_template.yml
- tools/ci/docbuild.sh
<details>
**Notes**:
```
```
using the Windows System for Linux once `flake8` is installed in the 
local Linux environment. While passing this test is not required, it …
> MAINT: Cherry pick recent pulls for 0.11

- statsmodels/sandbox/stats/multicomp.py
<details>
**Notes**:
```
```
using the …
> BUG: fix tukey-hsd for 1 pvalue 

- docs/source/examples/landing.yml
- statsmodels/graphics/tests/test_boxplots.py
- statsmodels/stats/tests/test_diagnostic.py
Silence warning for now
<details>
**Notes**:
```
``` …
> BUG: Silence expected visible deprecation warning

- .travis.yml
- requirements-dev.txt
- statsmodels/regression/tests/test_glsar_gretl.py
- statsmodels/tsa/statespace/tools.py
- statsmodels/tsa/tests/test_stattools.py
Use correct keyword
<details>
**Notes**:
```
``` …
> MAINT: Avoid calling depr code

- .travis.yml
- tools/ci/docbuild.sh
- tools/nbgenerate.py
Use travis cache to save notebook execution
Move linting to faster builds
<details>
**Notes**:
```
```
assuming …
> MAINT: Use travis cache and optimize build times

- statsmodels/tsa/statespace/tests/test_exact_diffuse_filtering.py
A test missing the `reset_randomstate` fixture.
> TST/BUG: use reset_randomstate

- statsmodels/nonparametric/bandwidths.py
- statsmodels/nonparametric/tests/test_bandwidths.py
<details>
**Notes**:
```
```
using the …
> BUG: fix #6511

- statsmodels/sandbox/multilinear.py
> Fix simple typo: variuos -> various

- statsmodels/gam/generalized_additive_model.py
- statsmodels/gam/tests/test_penalized.py
> BUG: fix GAM for 1-dim exog_linear 

- examples/notebooks/rolling_ls.ipynb
Capital Asset Pricing Model is abbreviated as CAPM no CAP-M.
also a couple of places where "on" is used instead of "of"
<details>
**Notes**:
``` …
```
> DOC: fix typos

- docs/source/release/verion0.11.1.rst
- statsmodels/gam/generalized_additive_model.py
- statsmodels/gam/tests/test_penalized.py
- statsmodels/genmod/generalized_linear_model.py
- statsmodels/genmod/tests/test_glm.py
- statsmodels/graphics/tests/test_boxplots.py
- statsmodels/nonparametric/bandwidths.py
- statsmodels/nonparametric/tests/test_bandwidths.py
- statsmodels/sandbox/stats/multicomp.py
- statsmodels/tsa/statespace/tests/test_exact_diffuse_filtering.py
> Backport 6433

- statsmodels/tsa/ar_model.py
- statsmodels/tsa/tests/test_ar.py
Could you point me to the tests that I should change or where I should add a new test?
> BUG: fixes #6553, sliced predicted values according to predicted index

- statsmodels/tsa/statespace/initialization.py
- statsmodels/tsa/statespace/kalman_filter.py
- statsmodels/tsa/statespace/tests/test_simulate.py
> BUG: state space: simulate with time-varying covariance matrices.

- statsmodels/tsa/statespace/_representation.pxd
- statsmodels/tsa/statespace/_representation.pyx.in
- statsmodels/tsa/statespace/tests/test_collapsed.py
Occasional error when collapsing the observation vector with certain combinations of missing data.
> BUG: state space: error with collapsed observations when missing

- appveyor.yml
- tools/ci/appveyor_conda.bat
Fix the recnt issue with appveyor and conda
[skip travis]
[azure skip]
<details>
**Notes**:
```
``` …
> MAINT: Fix appveyor/conda

- statsmodels/tsa/ar_model.py
Replace independent wtih dependent
[skip ci]
<details>
**Notes**:
```
``` …
> DOC: Fix AutoReg docstring

- statsmodels/regression/linear_model.py
This pull requests speeds up the calculation of HC2 and HC3 covariances in `statsmodels.regression.linear_model.OLS` for large N and uses much less memory when doing so: of the order of N rather than N^2 for a design matrix of size NxK. Without this improvement it's very impractical to estimate the HC2 covariance matrix for a problem with N=1e5 (would need >70gb of memory). Clearly HC2/3 covariances will be pretty similar to HC0 for large samples because both are consistent estimators, but it's important to be able to verify that sometimes.
The patch is tiny: instead of calculating the full hat matrix and then taking its diagonal with `h = diag(X C X')` where `C = inv(X'X)`, I produce the diagonal directly with `h(i) = Σi Σj Σk X(i,j)X(i,k)C(k,j)` via a call to `np.einsum`.
I've not …
> Speed up HC2/HC3 standard error calculation, using less memory

- statsmodels/iolib/openfile.py
- statsmodels/iolib/tests/test_pickle.py
> Handle pathlib.Path objects

- statsmodels/base/optimizer.py
- statsmodels/base/tests/test_optimize.py
<details>
**Notes**:
```
```
using the …
> BUG: fix constraints and bunds when use scipy.optimize.minimize

- statsmodels/stats/power.py
- statsmodels/stats/proportion.py
- statsmodels/stats/tests/test_proportion.py
> ENH: add two independent proportion inference rebased

- statsmodels/stats/rates.py
- statsmodels/stats/tests/results/results_rates.py
- statsmodels/stats/tests/test_rates_poisson.py
rebased version of #2723 from 2015
original draft version for stackoverflow is in issue #2718
link again to my initial notes
https://github.com/josef-pkt/misc/wiki/Exact-and-Asymptotic-Tests---Rates,-Poisson
> ENH: rates, poisson means two-sample comparison  rebased

- statsmodels/stats/multivariate.py
- statsmodels/stats/tests/test_multivariate.py
test for spherical, diagonal, ...  cov structures
based on Stata docs
based on script from https://github.com/statsmodels/statsmodels/issues/2765#issuecomment-342697378
> ENH: add covariance structure hypothesis tests

- statsmodels/tsa/statespace/mlemodel.py
- statsmodels/tsa/statespace/tests/test_exponential_smoothing.py
Thanks for pointing this out, @josef-pkt and @kshedden!
> CLN: Fix state space linting errors.

- statsmodels/base/elastic_net.py
- statsmodels/genmod/generalized_linear_model.py
- statsmodels/genmod/tests/test_glm.py
> ENH: Warn for non-convergence in elastic net

- README.rst
closes #6691
<details>
**Notes**:
```
``` …
> DOC: Add new badges

- statsmodels/tools/docstring.py
<details>
**Notes**:
```
```
using the …
> MAINT: Flake8 fixes

- statsmodels/tsa/ar_model.py
Remvoe deprecated keyword argument
<details>
**Notes**:
```
``` …
> MAINT: Remove deprecated keyword

- statsmodels/nonparametric/bandwidths.py
- statsmodels/nonparametric/tests/test_kde.py
Use standard deviation when IQR is zero
closes #6679
<details>
**Notes**:
```
``` …
> BUG: Ensure sigma estimate is positive in KDE

- statsmodels/iolib/summary2.py
- statsmodels/iolib/tests/test_summary2.py
Ensure consistent ordering
closes #6578
<details>
**Notes**:
```
``` …
> BUG: Fix summary col R2 ordering

- statsmodels/discrete/conditional_models.py
- statsmodels/duration/hazard_regression.py
- statsmodels/genmod/_prediction.py
- statsmodels/genmod/tests/test_bayes_mixed_glm.py
- statsmodels/graphics/functional.py
- statsmodels/graphics/mosaicplot.py
- statsmodels/graphics/tests/test_mosaicplot.py
- statsmodels/imputation/bayes_mi.py
- statsmodels/imputation/mice.py
- statsmodels/iolib/summary2.py
- statsmodels/regression/_prediction.py
- statsmodels/regression/linear_model.py
- statsmodels/regression/mixed_linear_model.py
- statsmodels/stats/libqsturng/make_tbls.py
- statsmodels/stats/multitest.py
- statsmodels/tsa/regime_switching/markov_switching.py
- statsmodels/tsa/statespace/dynamic_factor.py
- statsmodels/tsa/statespace/mlemodel.py
- statsmodels/tsa/statespace/sarimax.py
- statsmodels/tsa/statespace/structural.py
- statsmodels/tsa/statespace/tests/test_fixed_params.py
- statsmodels/tsa/statespace/varmax.py
All dictionaries are now ordered
<details>
**Notes**:
```
``` …
> MAINT: Remove OrderedDict

- statsmodels/multivariate/factor.py
<details>
**Notes**:
```
```
using the …
> DOC: Improve Factor and related docstrings

- setup.cfg
- statsmodels/tsa/stattools.py
- statsmodels/tsa/tests/test_stattools.py
- statsmodels/tsa/tests/test_tsa_tools.py
Explain drop and conservative.
closes #6641
<details>
**Notes**:
```
``` …
> DOC: Improve explantion of missing values in ACF and related

- examples/notebooks/quasibinomial.ipynb
Notebook illustating quasibinomial regression and custom variance functions.
> DOC: Notebook for quasibinomial regression

- setup.cfg
- statsmodels/genmod/bayes_mixed_glm.py
- statsmodels/graphics/tests/test_boxplots.py
- tools/ci/travis_pip.sh
Update pip-pre links for NumPy, SciPy and Pandas
<details>
**Notes**:
```
``` …
> MAINT: Update pip-pre links

- statsmodels/tsa/stattools.py
- statsmodels/tsa/tests/test_stattools.py
Explain that conservative is as if using nan-ops
closes #6729
<details>
**Notes**:
```
``` …
> DOC: Improve "conservative" doc

- statsmodels/graphics/functional.py
With this change, calculation of band depth for a 100-by-500 array reduces from 14 seconds to under 10ms (on a 2018 MacBook Pro).
> ENH: Speed up banddepth calculations

- examples/notebooks/variance_components.ipynb
> DOC: Demontrate variance components analysis

- appveyor.yml
- azure-pipelines.yml
- lint.sh
- setup.cfg
- statsmodels/compat/pandas.py
<details>
**Notes**:
```
```
using the …
> MAINT: Fix pandas assert_equal

- statsmodels/regression/mixed_linear_model.py
This PR modifies the internal handling of sparse matrices in MixedLM.  It leads to substantial performance improvements for certain variance components models.
> PERF: Sparse matrices in MixedLM

- examples/notebooks/mediation_survival.ipynb
- statsmodels/duration/hazard_regression.py
- statsmodels/stats/mediation.py
- statsmodels/stats/tests/test_mediation.py
Attempt to address #6781.
Needs a unit test.
> ENH: Mediation support for PH regression

- setup.cfg
Remove error used to trade warnings
<details>
**Notes**:
```
``` …
> MAINT: Remove error on FutureWarning

- statsmodels/base/tests/test_optimize.py
- statsmodels/compat/scipy.py
- statsmodels/tsa/tests/test_exponential_smoothing.py
Relax test in new Exponential Smoothing code
Fix powell due to changes in SciPy
<details>
**Notes**:
```
```
using the Windows System for Linux once `flake8` is …
> MAINT: Fix failing tests

- docs/source/conf.py
- tools/ci/docbuild_install.sh
I finally got https://github.com/numpy/numpydoc/pull/221 merged, so this is the next step.
<details>
**Notes**:
```
``` …
> DOC: numpydoc sigantures

- statsmodels/tsa/ar_model.py
- statsmodels/tsa/tests/test_ar.py
<details>
**Notes**:
```
```
using the …
> Fix autoreg

- statsmodels/tools/validation/__init__.py
- statsmodels/tools/validation/decorators.py
- statsmodels/tools/validation/tests/test_validation.py
- statsmodels/tools/validation/validation.py
Add str when appending using pandas wrapper
<details>
**Notes**:
```
``` …
> BUG: Fix missing str

- statsmodels/regression/linear_model.py
- statsmodels/regression/tests/test_regression.py
Ensure scalar statistics are scalars
closes #6778
<details>
**Notes**:
```
``` …
> BUG: Correct shape of fvalue and f_pvalue

- statsmodels/tsa/arima/model.py
- statsmodels/tsa/arima/specification.py
- statsmodels/tsa/arima/tests/test_model.py
- statsmodels/tsa/statespace/mlemodel.py
- statsmodels/tsa/statespace/tests/test_concentrated.py
In addition to fixing the problem, it adds a check for a constant column.
> BUG: error in append for ARIMA model with trend

- statsmodels/tsa/statespace/exponential_smoothing.py
[skip ci]
Point ot correct implementation
closes #6754
<details>
**Notes**:
```
``` …
> DOC: Correct reference in docs

- statsmodels/discrete/discrete_model.py
<details>
**Notes**:
```
```
using the …
> Catch warn discrete

- docs/source/graphics.rst
[skip ci]
closes #6638
<details>
**Notes**:
```
``` …
> DOC: Include dot_plot

- setup.cfg
- statsmodels/graphics/tsaplots.py
- statsmodels/regression/linear_model.py
- statsmodels/regression/tests/test_glsar_stata.py
- statsmodels/tsa/arima/estimators/durbin_levinson.py
- statsmodels/tsa/arima/estimators/yule_walker.py
- statsmodels/tsa/stattools.py
- statsmodels/tsa/tests/test_ar.py
- statsmodels/tsa/tests/test_stattools.py
- statsmodels/tsa/tests/test_tsa_tools.py
Rename unbiased in the context of autocov/corr estimation to
adjusted to better reflect what it does
<details>
**Notes**:
``` …
```
> REF: Rename unbiased to adjusted

- docs/source/api.rst
- docs/source/tools.rst
- statsmodels/genmod/tests/results/results_glm.py
- statsmodels/regression/tests/test_regression.py
- statsmodels/tools/tests/test_grouputils.py
- statsmodels/tools/tools.py
Deprecate categorical in favor of pandas versions
<details>
**Notes**:
```
``` …
> MAINT: Deprecate categorical

- statsmodels/regression/tests/test_rolling.py
Change warnign class to any warning to address changes in MPL
<details>
**Notes**:
```
``` …
> MAINT: Fix error on nightly build

- docs/source/stats.rst
add functions from my recently merged `stats` PRs
I don't build docs locally, so I don't know which mistakes there are
> DOC: add recent stats addition to docs

- docs/source/names_wordlist.txt
- docs/source/spelling_wordlist.txt
- statsmodels/graphics/dotplots.py
- statsmodels/imputation/mice.py
- statsmodels/tsa/mlemodel.py
- statsmodels/tsa/statespace/kalman_filter.py
- statsmodels/tsa/statespace/kalman_smoother.py
- statsmodels/tsa/statespace/mlemodel.py
- statsmodels/tsa/statespace/tools.py
- statsmodels/tsa/vector_ar/tests/test_var.py
- statsmodels/tsa/vector_ar/var_model.py
Limit maxlags so that the covariance could be positive definite
<details>
**Notes**:
```
``` …
> BUG: Limit maxlags in VAR

- statsmodels/tsa/vector_ar/var_model.py
Mark as not implemented to stop use
closes #2347
<details>
**Notes**:
```
``` …
> MAINT: Mark VAR from_formula as NotImplemented

- lint.sh
Improve linting of new files
<details>
**Notes**:
```
``` …
> MAINT: Improve lint

- statsmodels/stats/libqsturng/make_tbls.py
- statsmodels/stats/multivariate.py
- tools/enumerate-api.py
Add tool to walk API and generate a JSON
<details>
**Notes**:
```
``` …
> ENH: Add tool to simpligy documenting API in release notes

- docs/source/release/index.rst
- docs/source/release/version0.11.1.rst
- docs/source/release/version0.12.rst
- tools/releasing/enumerate-api.py
- tools/releasing/release_note.py
Begin 0.12 release process
<details>
**Notes**:
```
``` …
> DOC: Initial 0.12 Release Note

- statsmodels/tsa/vector_ar/api.py
- statsmodels/tsa/vector_ar/hypothesis_test_results.py
- statsmodels/tsa/vector_ar/irf.py
- statsmodels/tsa/vector_ar/plotting.py
- statsmodels/tsa/vector_ar/svar_model.py
- statsmodels/tsa/vector_ar/tests/JMulTi_results/parse_jmulti_var_output.py
- statsmodels/tsa/vector_ar/tests/JMulTi_results/parse_jmulti_vecm_output.py
- statsmodels/tsa/vector_ar/tests/example_svar.py
- statsmodels/tsa/vector_ar/tests/results/results_svar_st.py
- statsmodels/tsa/vector_ar/tests/test_coint.py
- statsmodels/tsa/vector_ar/tests/test_svar.py
- statsmodels/tsa/vector_ar/tests/test_var.py
- statsmodels/tsa/vector_ar/tests/test_var_jmulti.py
- statsmodels/tsa/vector_ar/tests/test_vecm.py
- statsmodels/tsa/vector_ar/util.py
- statsmodels/tsa/vector_ar/var_model.py
- statsmodels/tsa/vector_ar/vecm.py
<details>
**Notes**:
```
```
using the …
> BUG: Correct IRF nobs with exog

- statsmodels/tools/eval_measures.py
- statsmodels/tools/tests/test_eval_measures.py
<details>
**Notes**:
```
```
using the …
> ENH: Add Root Mean Square Percentage Error

- docs/source/tsa.rst
- examples/notebooks/autoregressions.ipynb
- statsmodels/base/data.py
- statsmodels/tsa/ar_model.py
- statsmodels/tsa/base/prediction.py
- statsmodels/tsa/base/tests/test_prediction.py
- statsmodels/tsa/deterministic.py
- statsmodels/tsa/holtwinters/model.py
- statsmodels/tsa/holtwinters/results.py
- statsmodels/tsa/statespace/mlemodel.py
- statsmodels/tsa/statespace/tests/test_dynamic_factor.py
- statsmodels/tsa/tests/test_ar.py
Add get_prediction for better compatibility
<details>
**Notes**:
```
``` …
> ENH: Add get_prediction to AutoReg

- statsmodels/genmod/generalized_linear_model.py
- statsmodels/iolib/foreign.py
- statsmodels/regression/linear_model.py
- statsmodels/stats/diagnostic.py
- statsmodels/tools/tools.py
- statsmodels/tsa/ar_model.py
- statsmodels/tsa/arima_model.py
- statsmodels/tsa/stattools.py
- statsmodels/tsa/tsatools.py
Clarify removal timeframe
<details>
**Notes**:
```
``` …
> DOC: Clarify deprecations

- statsmodels/tsa/ar_model.py
Standardize API to match statespace
<details>
**Notes**:
```
``` …
> MAINT: Standardize forecast API

- docs/source/tsa.rst
- examples/notebooks/stl_decomposition.ipynb
- statsmodels/tsa/_stl.pyx
- statsmodels/tsa/api.py
- statsmodels/tsa/base/tsa_model.py
- statsmodels/tsa/forecasting/stl.py
- statsmodels/tsa/forecasting/tests/test_stl.py
Add method that allows STL to be combined with an model to
produce forecasts and prediction intervals
closes #6372
<details>
**Notes**:
``` …
```
> ENH: Add STL Forecasting method

- setup.cfg
- statsmodels/tsa/exponential_smoothing/ets.py
- statsmodels/tsa/forecasting/tests/test_stl.py
- statsmodels/tsa/tests/test_exponential_smoothing.py
Correct interpretation of start and end
Silence warning
<details>
**Notes**:
```
``` …
> MAINT: Fix small issues post ETS get_prediction merge

- docs/source/stats.rst
- statsmodels/stats/oneway.py
- statsmodels/stats/proportion.py
- statsmodels/stats/rates.py
- statsmodels/stats/tests/test_oneway.py
- statsmodels/stats/tests/test_proportion.py
- statsmodels/stats/tests/test_rates_poisson.py
- statsmodels/stats/weightstats.py
some API refactor/cleanup, improve docstrings for recent stats additions
> REF/DOC: api cleanup and improve docstrings in stats, round 3

- .travis.yml
- statsmodels/distributions/discrete.py
- statsmodels/distributions/tests/test_discrete.py
<details>
**Notes**:
```
```
using the …
> ENH: Add improved .cdf() and .ppf() to discrete distributions

- statsmodels/discrete/discrete_margins.py
<details>
**Notes**:
```
```
using the …
> BUG: remove k_extra from effects_idx

- statsmodels/discrete/tests/test_count_model.py
<details>
**Notes**:
```
```
using the …
> TST: Improve count model tests

- statsmodels/tsa/statespace/tests/test_varmax.py
- statsmodels/tsa/statespace/varmax.py
> BUG: fix extend in VARMAX with trend

- setup.cfg
- statsmodels/base/tests/test_shrink_pickle.py
- statsmodels/discrete/tests/test_constrained.py
- statsmodels/genmod/generalized_linear_model.py
- statsmodels/genmod/tests/test_constrained.py
- statsmodels/genmod/tests/test_glm.py
<details>
**Notes**:
```
```
using the …
> REF: Change of BIC formula in GLM

- statsmodels/tsa/filters/hp_filter.py
> update pandas function in hp_filter example

- statsmodels/base/model.py
- statsmodels/base/tests/test_generic_methods.py
- statsmodels/nonparametric/linbin.pyx
- statsmodels/regression/dimred.py
- statsmodels/stats/dist_dependence_measures.py
- statsmodels/stats/tests/test_diagnostic.py
- statsmodels/stats/tests/test_dist_dependant_measures.py
- statsmodels/tools/tests/test_tools.py
- statsmodels/tools/validation/tests/test_validation.py
- statsmodels/tsa/exponential_smoothing/base.py
- statsmodels/tsa/holtwinters/model.py
- statsmodels/tsa/statespace/tests/test_dynamic_factor_mq.py
- statsmodels/tsa/statespace/tests/test_news.py
- statsmodels/tsa/statespace/tests/test_smoothing.py
- statsmodels/tsa/tests/test_exponential_smoothing.py
Relax very tight test coverage
<details>
**Notes**:
```
``` …
> MAINT: Relax test tolerance for future compat

- docs/source/duration.rst
- docs/source/release/version0.12.rst
- docs/source/statespace.rst
- docs/source/stats.rst
- docs/source/tsa.rst
- setup.py
- statsmodels/stats/meta_analysis.py
- statsmodels/tsa/deterministic.py
- statsmodels/tsa/tests/test_exponential_smoothing.py
<details>
**Notes**:
```
```
using the …
> Prepare docs

- statsmodels/tsa/tests/test_exponential_smoothing.py
Modify test that fails to converge on Windows
<details>
**Notes**:
```
``` …
> TST: Modify failing test on Windows

- docs/source/release/version0.12.rst
- docs/source/statespace.rst
- docs/source/tsa.rst
- statsmodels/tsa/api.py
- statsmodels/tsa/exponential_smoothing/ets.py
- statsmodels/tsa/statespace/dynamic_factor_mq.py
- statsmodels/tsa/statespace/exponential_smoothing.py
> DOC: improve ETS / statespace documentation and higlights for v0.12 

- statsmodels/graphics/tsaplots.py
- statsmodels/stats/tests/test_oneway.py
- statsmodels/tsa/tests/test_exponential_smoothing.py
Fix failures in wheel building
<details>
**Notes**:
```
``` …
> MAINT: Fixes for failures in wheel building

- statsmodels/tsa/tests/test_exponential_smoothing.py
Allow test to fail on Linux 32
<details>
**Notes**:
```
``` …
> MAINT: Fixes for wheel building

- statsmodels/genmod/generalized_linear_model.py
Check model not result for attribute
xref #6953
<details>
**Notes**:
```
``` …
> BUG: Fix check for offset_exposure in null

- statsmodels/genmod/tests/test_glm.py
Add test for #6953
<details>
**Notes**:
```
``` …
> TST: Add test for offset exposure null

- statsmodels/stats/descriptivestats.py
- statsmodels/stats/tests/test_descriptivestats.py
Catch internally generated warning
<details>
**Notes**:
```
``` …
> MAINT: Catch warning

- docs/source/release/version0.12.rst
Final doc changes for release 0.12.0rc0
[skip ci]
<details>
**Notes**:
```
``` …
> DOC: Final doc fixed for 0.12.0rc0

- statsmodels/tsa/deterministic.py
Update for missing docstrings
[skip ci]
<details>
**Notes**:
```
``` …
> DOC: Update DeterministicProcess docs

- docs/source/release/version0.12.rst
- docs/source/rlm.rst
- examples/notebooks/robust_models_1.ipynb
- statsmodels/robust/scale.py
- statsmodels/robust/tests/test_scale.py
- [Y] closes #6383
- [Y] tests added / passed. 
- [Y] code/documentation is well formatted.  
- [Y] properly formatted commit message. See 
The new function was tested against IQR from the stats R package.
**Notes**:
verify you …
> ENH add normalized iqr to robust.scales

- examples/notebooks/statespace_seasonal.ipynb
Fix LaTeX
Improve plots
closes #6975
<details>
**Notes**:
```
``` …
> DOC: Fix LaTeX in seasonal notebook

- docs/source/release/version0.12.rst
- docs/source/rlm.rst
- examples/notebooks/robust_models_1.ipynb
- setup.py
- statsmodels/robust/_qn.pyx
- statsmodels/robust/scale.py
- statsmodels/robust/tests/test_scale.py
<details>
**Notes**:
```
```
using the …
> ENH: Add robust qn scale

- azure-pipelines.yml
- tools/ci/azure_template.yml
Update images
<details>
**Notes**:
```
``` …
> MAINT: Update Azure images

- docs/source/release/version0.12.rst
add new stats features to release notes for 0.12
> DOC: add new stats to release notes for 0.12

- statsmodels/robust/scale.py
- statsmodels/robust/tests/test_scale.py
<details>
**Notes**:
```
```
using the …
> BUG: fix bug where mad ignores center if center is not callable

- docs/source/names_wordlist.txt
- docs/source/release/version0.12.rst
- docs/source/rlm.rst
- docs/source/spelling_wordlist.txt
- tools/releasing/enumerate-api.py
<details>
**Notes**:
```
```
using the …
> DOC: Final 0.12.0 release doc changes

- appveyor.yml
- azure-pipelines.yml
- tools/ci/azure_template.yml
try to temporarily fix #7012 with "setuptools<50.0"
> BLD: avoid setuptools version 50, windows build problem

- statsmodels/robust/scale.py
- statsmodels/robust/tests/test_scale.py
Correct axis None in mad
closes #7027
<details>
**Notes**:
```
``` …
> BUG: Correct axis None case

- statsmodels/regression/mixed_linear_model.py
- statsmodels/regression/tests/test_lme.py
> ENH: handle/warn for singularities in MixedLM

- statsmodels/genmod/cov_struct.py
- statsmodels/genmod/generalized_estimating_equations.py
- statsmodels/genmod/tests/test_gee.py
Initial commit, needs review and further checking.
#7005
> ENH: Unstructured covariance for GEE

- statsmodels/stats/effect_size.py
- statsmodels/stats/tests/test_effectsize.py
see #6983
This is mainly to collect some theoretical results and computation for now. 
I'm not sure yet what the user interface should be. 
There will be some internal applications similar to methods in `stats.oneway`, e.g. equivalence test for Hosmer-Lemeshow and similar tests. https://github.com/statsmodels/statsmodels/issues/6591#issuecomment-702099302
> ENH: estimate noncentrality parameter for t, f and chi2

- statsmodels/tsa/stattools.py
I just did some fixes in the documentation.
> some fixes in the doc of grangercausalitytests

- statsmodels/miscmodels/ordinal_model.py
- statsmodels/tsa/exponential_smoothing/initialization.py
- statsmodels/tsa/holtwinters/_smoothers.py
- statsmodels/tsa/holtwinters/model.py
- statsmodels/tsa/holtwinters/results.py
- statsmodels/tsa/holtwinters/tests/test_holtwinters.py
Fix issues due to changes in NumPy and Pandas
<details>
**Notes**:
```
``` …
> MAINT: Fix issues in master branches of dependencies

- docs/source/names_wordlist.txt
- docs/source/release/index.rst
- docs/source/release/version0.12.1.rst
> DOC: v0.12.1 release notes

- statsmodels/tsa/statespace/dynamic_factor.py
One final doc fix for 0.12.1
[skip ci]
<details>
**Notes**:
```
``` …
> DOC: Port missed doc fix

- statsmodels/examples/tests/test_notebooks.py
typo.
<details>
**Notes**:
```
```
using the …
> Update test_notebooks.py typo, s/not/no

- statsmodels/genmod/bayes_mixed_glm.py
- statsmodels/imputation/mice.py
> DOC:  Minor doc edits to MICE and BayesMixedGLM

- .travis.yml
https://docs.travis-ci.com/user/gui-and-headless-browsers/#using-services
https://docs.travis-ci.com/user/environment-variables
<details>
**Notes**:
```
git diff upstream/master -u -- …
```
> Travis CI:  Use services: xvfb and $TRAVIS_PYTHON_VERSION

- statsmodels/sandbox/stats/diagnostic.py
Finish removing unitroot_adf which was dropped in 0.12
<details>
**Notes**:
```
``` …
> MAINT: Remove unitroot_adf

- statsmodels/regression/quantile_regression.py
Documentation update. No bug report.
> DOC: Correct variable name in error message

- statsmodels/genmod/tests/test_gee.py
- statsmodels/tsa/arima/estimators/tests/test_gls.py
- statsmodels/tsa/statespace/dynamic_factor_mq.py
Fix bugs against scipy, numpy and pandas release candidates
<details>
**Notes**:
```
``` …
> MAINT: Fix future bugs

- statsmodels/tsa/arima/estimators/tests/test_gls.py
- statsmodels/tsa/statespace/dynamic_factor_mq.py
Fix bugs against scipy, numpy and pandas release candidates
<details>
**Notes**:
```
``` …
> MAINT: Backport fixes for 0.12.2 compat release

- statsmodels/tools/sm_exceptions.py
- statsmodels/tsa/stattools.py
- statsmodels/tsa/tests/test_stattools.py
Add checks for feasibility
closes #7218
<details>
**Notes**:
```
``` …
> MAINT: Add checks in granger causlaity

- tools/ci/azure/azure_template_posix.yml
- tools/ci/azure/install-posix.sh
Remove coveralls from Azure and add patsy
<details>
**Notes**:
```
``` …
> MAINT: Remove coveralls and add patsy

- statsmodels/stats/tests/test_weightstats.py
- statsmodels/stats/weightstats.py
rebased, squashed version of #7047
> BUG quantile only squeeze weights if more than 1D

- statsmodels/tsa/seasonal.py
Noticed a thinko in this old function then clarified the language a bit.
> Clarify seasonal_decompose docs

- statsmodels/genmod/cov_struct.py
- statsmodels/genmod/generalized_estimating_equations.py
- statsmodels/genmod/tests/test_gee.py
This PR addresses some numerical instabilities that may arise with large near-singular score tests in GEE.
> ENH: Improve numerical stability of GEE score testing

- statsmodels/distributions/tests/test_copula.py
- statsmodels/sandbox/distributions/copula.py
getting started with unit tests and bug fixes for copulas in sandbox
extreme value copulas are compared to R `evd` package (except ev-t).
other copulas are in R package `copula`
> ENH/BUG: work on copulas

- statsmodels/stats/contingency_tables.py
- statsmodels/stats/tests/test_contingency_tables.py
converts array for StratifiedTable to at least float
> BUG/TST: StratifiedTable allow int array, silence warnings in unit tests

- statsmodels/genmod/generalized_linear_model.py
- statsmodels/genmod/tests/test_glm.py
> qaic for GLM

- README.rst
<details>
**Notes**:
```
```
using the …
> Add Codecov badge to README

- statsmodels/tsa/exponential_smoothing/ets.py
- statsmodels/tsa/exponential_smoothing/initialization.py
- statsmodels/tsa/holtwinters/model.py
- statsmodels/tsa/holtwinters/tests/test_holtwinters.py
- statsmodels/tsa/tests/test_exponential_smoothing.py
> BUG: ExponentialSmoothing error for estimated initialization_method with fewer than 10 observations

- statsmodels/genmod/families/family.py
Fixes line length to stop a recent linting error showing up in Azure.
> CLN: Linting error for line length.

- statsmodels/tsa/exponential_smoothing/ets.py
Performs an ad-hoc adjustment (as described in a comment to #7331) that prevents problems in the log-likelihood computation.
> BUG: fix ETS logL if negative yhat and errors=M

- statsmodels/base/data.py
- statsmodels/tsa/tests/test_ar.py
Fix code to handle current behavior when creating a Series from a Series
<details>
**Notes**:
```
``` …
> BUG: Fix pandas wrapper code

- statsmodels/regression/tests/test_rolling.py
- statsmodels/stats/descriptivestats.py
- statsmodels/stats/stattools.py
Fix issues due to changes in SciPy and pandas
<details>
**Notes**:
```
``` …
> MAINT: Fix issues arising from future changes

- statsmodels/compat/scipy.py
- statsmodels/distributions/discrete.py
- statsmodels/genmod/_tweedie_compound_poisson.py
Remove vendored lazywhere since minimum SciPy is now 1.3
<details>
**Notes**:
```
``` …
> MAINT: Use scipy's lazywhere

- examples/notebooks/mixed_lm_example.ipynb
Profile likelihood plot is labeled incorrectly.
> DOC: fixed error in linear mixed effects example

- statsmodels/genmod/families/family.py
<details>
**Notes**: Docs only change to make it more clear that any of the aliases of `Power` can be used as tweedie links. Figured it might be beneficial to clarify, would have saved my team a couple hours.
verify you changes are well …
> DOC: update doc for tweedie allowed links

- statsmodels/stats/descriptivestats.py
Add special path for extension dtypes to remove N/A
<details>
**Notes**:
```
``` …
> MAINT: Fix descriptive stats with extension dtypes

- setup.cfg
- statsmodels/genmod/tests/test_gee.py
- statsmodels/tsa/ar_model.py
- statsmodels/tsa/base/datetools.py
- statsmodels/tsa/base/tests/test_tsa_indexes.py
- statsmodels/tsa/statespace/dynamic_factor_mq.py
- statsmodels/tsa/tests/test_ar.py
- statsmodels/tsa/tests/test_stl.py
Fix future issues from upstream
<details>
**Notes**:
```
``` …
> MAINT: Fix pip pre test failures

- README.rst
Fix small issues in README after move to main
<details>
**Notes**:
```
``` …
> MAINT: Fix README badges

- examples/notebooks/statespace_sarimax_pymc3.ipynb
Use current syntax in PyMC3 notebooks
closes #7398
<details>
**Notes**:
```
``` …
> MAINT: Fix for upstream changes in PyMC3 notebook

- examples/notebooks/autoregressions.ipynb
Just a little glitch I noticed while reading https://www.statsmodels.org/dev/examples/notebooks/generated/autoregressions.html.
> DOC: typo, plats->plots

- setup.cfg
- statsmodels/genmod/tests/test_glm.py
- statsmodels/miscmodels/tests/results/results_ordinal_model.py
- statsmodels/tools/tests/test_grouputils.py
- statsmodels/tsa/arima/tools.py
- statsmodels/tsa/tsatools.py
> MAINT: Fit future and deprecation warnings

- statsmodels/datasets/utils.py
Add a useful error message when data is not found.
<details>
**Notes**:
```
``` …
> ENH: Add an error message for not found data

- docs/source/release/version0.13.rst
- statsmodels/tsa/arima/estimators/hannan_rissanen.py
- statsmodels/tsa/arima/estimators/tests/test_hannan_rissanen.py
> ENH: Add fixed_params to Hannan Rissanen (GH7202)

- docs/source/release/version0.13.rst
- statsmodels/tsa/arima/estimators/hannan_rissanen.py
- statsmodels/tsa/arima/estimators/tests/test_hannan_rissanen.py
- statsmodels/tsa/arima/model.py
- statsmodels/tsa/arima/tests/test_model.py
> ENH: Enable ARIMA.fit(method='hannan_rissanen') with fixed parameters (GH7501)

- statsmodels/genmod/tests/results/results_glm.py
- statsmodels/stats/descriptivestats.py
- statsmodels/tools/tools.py
- statsmodels/tsa/base/tsa_model.py
- statsmodels/tsa/exponential_smoothing/ets.py
- statsmodels/tsa/holtwinters/tests/test_holtwinters.py
- statsmodels/tsa/tests/test_ar.py
- statsmodels/tsa/tsatools.py
> MAINT: Avoid future issues in pandas

- statsmodels/stats/proportion.py
Yes, it is the correct paper. I've read it and it explains how to calculate "normal", "agresti_coull", "beta", "wilson" and "jeffreys".
<details>
**Notes**:
```
git diff upstream/main -u …
```
> resolve TODO in proportion.py

- statsmodels/tsa/ar_model.py
- statsmodels/tsa/tests/test_ar.py
Fix bug in certain forecast cases
Add comprehensive tests
Import refactor from ARDL
<details>
**Notes**:
```
```
assuming …
> BUG: Fix errors when making dynamic forecasts

- examples/notebooks/theta-model.ipynb
Add frequency so plot renders correctly
<details>
**Notes**:
```
``` …
> DOC: Fix errors in theta notebook

- statsmodels/tsa/statespace/sarimax.py
- statsmodels/tsa/statespace/tests/test_save.py
Ensure attributes exist so that saving works
<details>
**Notes**:
```
``` …
> BUG: Ensure attributes exist

- .github/workflows/generate-documentation.yml
- examples/notebooks/contrasts.ipynb
- requirements-dev.txt
Add GH actions script to build docs
<details>
**Notes**:
```
``` …
> MAINT: Add github actions to build docs

- .github/workflows/generate-documentation.yml
- tools/ci/commit-docs.sh
> MAINT: Fix GH actions

- examples/notebooks/contrasts.ipynb
Use 4 cuts to get a cubic term
<details>
**Notes**:
```
``` …
> MAINT: Correct example implementation

- .github/workflows/generate-documentation.yml
> MAINT: Check push ability

- .github/workflows/generate-documentation.yml
> MAINT: Continue working on it

- .github/workflows/generate-documentation.yml
> MAINT: Continue working on push ability

- .github/workflows/generate-documentation.yml
> MAINT: Finalize push ability

- .github/workflows/generate-documentation.yml
> MAINT: Get doc push to work

- statsmodels/multivariate/pca.py
- statsmodels/multivariate/tests/test_pca.py
> Added the option `full_matrices=False` in the PCA method

- examples/notebooks/rolling_ls.ipynb
> DOC: Improve rolling OLS notebook

- statsmodels/tsa/holtwinters/results.py
- statsmodels/tsa/holtwinters/tests/test_holtwinters.py
> BUG: Handle non-date index with a freq  

- statsmodels/base/_penalties.py
- statsmodels/base/model.py
- statsmodels/base/tests/test_shrink_pickle.py
- statsmodels/genmod/families/family.py
- statsmodels/regression/mixed_linear_model.py
- statsmodels/sandbox/stats/diagnostic.py
- statsmodels/stats/contingency_tables.py
- statsmodels/stats/descriptivestats.py
Remove old deprecations
<details>
**Notes**:
```
``` …
> MAINT: Remove deprecated code

- statsmodels/base/elastic_net.py
- statsmodels/genmod/generalized_linear_model.py
- statsmodels/genmod/tests/test_glm.py
> BUG: Fix scale parameter in elastic net

- statsmodels/tsa/deterministic.py
closes #7585
<details>
**Notes**:
```
```
using …
> DOC: Correct docstring

- statsmodels/tsa/vector_ar/var_model.py
closes #7157
<details>
**Notes**:
```
```
using …
> BUG: Let VAR results complete when model has perfect fit

- statsmodels/tsa/vector_ar/var_model.py
Raise ValueError if insufficient data available to make forecast
closes #7315
<details>
**Notes**:
```
```
assuming …
> ENH: Add error if too few values

- statsmodels/graphics/agreement.py
closes #7420
<details>
**Notes**:
```
```
using …
> ENH: Improve limit format in diff plot

- statsmodels/base/model.py
- statsmodels/regression/rolling.py
- statsmodels/regression/tests/test_quantile_regression.py
> Allow remove_data to work when an attribute is not implemented

- docs/source/glm.rst
- statsmodels/genmod/families/family.py
- statsmodels/genmod/families/links.py
- statsmodels/genmod/families/tests/test_link.py
rebased version of and closes #7562
extra:
test that link functions are monotonically increasing.
The only exception is inversepower  1/x link,  (in general for negative powers)
> Enh glm loglog

- setup.cfg
- statsmodels/graphics/agreement.py
- statsmodels/graphics/api.py
- statsmodels/graphics/boxplots.py
- statsmodels/graphics/dotplots.py
- statsmodels/graphics/factorplots.py
- statsmodels/graphics/gofplots.py
- statsmodels/graphics/mosaicplot.py
- statsmodels/graphics/plot_grids.py
- statsmodels/graphics/plottools.py
- statsmodels/graphics/regressionplots.py
- statsmodels/graphics/tests/test_agreement.py
- statsmodels/graphics/tests/test_boxplots.py
- statsmodels/graphics/tests/test_correlation.py
- statsmodels/graphics/tests/test_dotplot.py
- statsmodels/graphics/tests/test_factorplots.py
- statsmodels/graphics/tests/test_gofplots.py
- statsmodels/graphics/tests/test_regressionplots.py
- statsmodels/graphics/tukeyplot.py
Clarify which series appears on the x-axis of 2-sample qq
Add test to verify
closes #7610
<details>
**Notes**:
```
``` …
> BUG/DOC: Clarify which series is on x-axis

- docs/source/examples/landing.yml
- examples/notebooks/copula.ipynb
- statsmodels/distributions/copula/copulas.py
Shorten name to improve appearance
<details>
**Notes**:
```
``` …
> DOC: Small clean of example

- statsmodels/regression/linear_model.py
A grammar mistake in the docs fixed
> spelling error in docs fixed

- statsmodels/miscmodels/tests/test_tarma.py
- statsmodels/stats/tests/test_descriptivestats.py
> MAINT: Silence future warnings

- tools/ci/azure/azure_template_posix.yml
Pin matplotlib to version available when pandas 0.25.3 was releases
to avoid CI failures with modern MPL
<details>
**Notes**:
```
git diff upstream/main -u -- "*.py" | flake8 --diff …
```
> MAINT: Pin matplotlib

- statsmodels/tools/web.py
- statsmodels/tsa/seasonal.py
- statsmodels/tsa/vector_ar/svar_model.py
- statsmodels/tsa/vector_ar/var_model.py
> ENH: Improve error message in seasonal for bad freq

- examples/notebooks/ols.ipynb
- examples/notebooks/robust_models_0.ipynb
- examples/notebooks/wls.ipynb
closes #7517
<details>
**Notes**:
```
```
using …
> MAINT: Modernize prediction in notebooks

- examples/notebooks/copula.ipynb
Ensure reprodicible values and explain
<details>
**Notes**:
```
``` …
> ENH: Improve copula notebook

- examples/notebooks/statespace_sarimax_faq.ipynb
- examples/notebooks/statespace_sarimax_stata.ipynb
> DOC: Add to the SARIMAX FAQ

- docs/source/api-structure.rst
- docs/source/api.rst
- docs/source/dev/naming_conventions.rst
- docs/source/release/version0.5.rst
- docs/source/release/version0.6.rst
- docs/source/tsa.rst
- examples/notebooks/copula.ipynb
- examples/notebooks/markov_autoregression.ipynb
- statsmodels/tsa/api.py
- statsmodels/tsa/ar_model.py
- statsmodels/tsa/arima/api.py
- statsmodels/tsa/arima/model.py
- statsmodels/tsa/statespace/mlemodel.py
> DOC: Improve ARIMA documentation

- docs/source/distributions.rst
- examples/notebooks/copula.ipynb
- statsmodels/distributions/copula/api.py
- statsmodels/distributions/copula/archimedean.py
- statsmodels/distributions/copula/copulas.py
- statsmodels/distributions/copula/depfunc_ev.py
- statsmodels/distributions/copula/elliptical.py
- statsmodels/distributions/copula/extreme_value.py
- statsmodels/distributions/copula/other_copulas.py
- statsmodels/distributions/copula/tests/test_copula.py
- statsmodels/distributions/copula/tests/test_model.py
- statsmodels/distributions/copula/transforms.py
- statsmodels/distributions/tests/test_bernstein.py
- statsmodels/tsa/api.py
> BUG/REF copula another round for 0.13

- statsmodels/discrete/count_model.py
- statsmodels/discrete/tests/test_count_model.py
closes #4757 closes #4952
cleanup conditions if auxiliary predict kwds are None, offset, exposure and exog_infl.
default, if offset is None, was offset=0. Now it uses insample offset if exog is None and offset is None.
exog_infl does not need to be specified if exog_infl in model creation was None.
> BUG: ZI predict, fix offset default if None, allow exog_infl None if constant

- statsmodels/graphics/regressionplots.py
- statsmodels/graphics/tests/test_regressionplots.py
closes #7672
adds eval_env option with default 1 (namespace calling plot_regress function)
> ENH/BUG: graphics.plot_partregress add eval_env options

- docs/source/_templates/autosummary/class.rst
closes #7667
<details>
**Notes**:
```
```
using …
> DOC: Remove duplication methods section

- docs/source/_templates/autosummary/class.rst
Explicitly exclude methods
<details>
**Notes**:
```
``` …
> DOC: Second try ixing duplicate methods

- docs/source/distributions.rst
- statsmodels/distributions/copula/copulas.py
- statsmodels/distributions/copula/tests/test_copula.py
- statsmodels/tools/rng_qrng.py
Change to the singleton generator for the 0.13 release only
Warn the user
<details>
**Notes**:
```
``` …
> MAINT: Temporarily change the default RNG in check_random_state

- statsmodels/distributions/copula/depfunc_ev.py
- statsmodels/genmod/families/links.py
- statsmodels/genmod/families/tests/test_link.py
- statsmodels/tools/numdiff.py
- statsmodels/tools/tests/test_numdiff.py
this is part of #7226 that is not included in #7286
related change that should be included here is numerical derivative #1783
> REF: change default derivative in CDFLink

- statsmodels/genmod/generalized_linear_model.py
- statsmodels/genmod/tests/results/results_glm.py
- statsmodels/genmod/tests/test_glm.py
rebased version of #7367  squashed 
api changes still open
> ENH: McFadden and Cox&Snell Pseudo R squared to GLMResults

- docs/source/api.rst
- statsmodels/tsa/api.py
Update TSA Api with recent changes
<details>
**Notes**:
```
``` …
> MAINT: Update TSA Api

- docs/source/conf.py
Update versions file to use new-format version information
<details>
**Notes**:
```
``` …
> MAINT: Update versions file

- statsmodels/stats/outliers_influence.py
- statsmodels/stats/tests/test_outliers_influence.py
> ENH: Enable VIF to work with DataFrames

- statsmodels/tsa/arima_process.py
- statsmodels/tsa/tests/test_arima_process.py
Correct from_estimation to work with ARIMA models
<details>
**Notes**:
```
``` …
> BUG: Correct ArmaProcess.from_estimation

- statsmodels/stats/descriptivestats.py
- statsmodels/stats/tests/test_descriptivestats.py
> BUG: describe / Description do not return percentiles

- statsmodels/stats/oaxaca.py
- statsmodels/stats/tests/test_oaxaca.py
> ENH: Oaxaca Variance/Other Models

- docs/source/other_models.rst
- statsmodels/base/model.py
- statsmodels/miscmodels/ordinal_model.py
- statsmodels/othermod/betareg.py
> DOC: improve docs and docstrings, mainly for recent additions

- tools/dataset_rst.py
- tools/export_notebooks_to_python.py
- tools/generate_formula_api.py
- tools/nbgenerate.py
- tools/releasing/enumerate-api.py
- tools/releasing/release_note.py
- tools/validate_docstrings.py
> MAINT: Fix style issue

- statsmodels/multivariate/multivariate_ols.py
> DOC: Correct MultivariateTestResults doc string

- statsmodels/discrete/tests/test_discrete.py
- statsmodels/iolib/summary.py
- statsmodels/regression/tests/test_regression.py
> BUG: fix summary().as_latex, line in top table dropped

- statsmodels/genmod/tests/test_glm.py
- statsmodels/miscmodels/ordinal_model.py
- statsmodels/miscmodels/tests/test_ordinal_model.py
collecting last pieces that I want to do for 0.13
closes #7692 closes #7354 closes #7353
I forgot about this PR #7354  I'm doing the same/similar fix here
> BUG/MAINT/DOC: more 0.13

- docs/source/release/version0.13.0.rst
Update release note
<details>
**Notes**:
```
``` …
> DOC: Update release notes for 0.13

- statsmodels/stats/meta_analysis.py
- statsmodels/stats/tests/test_meta.py
> ENH: add options to meta-analysis plot_forest

- docs/source/release/version0.13.0.rst
> DOC: Final update to change log

- docs/source/glm.rst
- statsmodels/genmod/families/links.py
DOC: Genmod's loglog Formula Fixes
<details>
**Notes**:
```
``` …
> BACKPORT: Merge pull request #7787 from gmcmacran/loglogDoc

- statsmodels/tsa/stattools.py
- statsmodels/tsa/tests/test_stattools.py
BUG: Handle None in kpss
<details>
**Notes**:
```
``` …
> BACKPORT: Merge pull request #7795 from bashtage/bug-none-kpss

- setup.py
- statsmodels/nonparametric/_smoothers_lowess.pyx
- statsmodels/nonparametric/linbin.pyx
- statsmodels/tsa/statespace/tests/test_dynamic_factor_mq.py
MAINT: Update setup to build normally when NumPy availble
<details>
**Notes**:
```
``` …
> BACKPORT: Merge pull request #7801 from bashtage/change-setup

- statsmodels/tsa/stattools.py
MAINT: fix ZivotAndrewsUnitRoot.run() docstring
<details>
**Notes**:
```
``` …
> BACKPORT: Merge pull request #7812 from joaomacalos/zivot-andrews-docs

- .travis.yml
- tools/ci/azure/azure_template_posix.yml
MAINT: Switch to new codecov upload method
<details>
**Notes**:
```
``` …
> BACKPORT: Merge pull request #7799 from bashtage/update-codecov

- statsmodels/compat/pandas.py
- statsmodels/regression/rolling.py
- statsmodels/tsa/ar_model.py
- statsmodels/tsa/ardl/model.py
MAINT: Protect against future pandas changes
<details>
**Notes**:
```
``` …
> BACKPORT Merge pull request #7844 from bashtage/future-pandas

- statsmodels/genmod/families/family.py
- statsmodels/genmod/families/tests/test_family.py
BUG: Allow all appropriate links in a Family
<details>
**Notes**:
```
``` …
> BACKPORT: Merge pull request #7816 from tncowart/unalias_links

- statsmodels/tools/numdiff.py
MAINT: Fix for deprecation of np.MachAr
<details>
**Notes**:
```
``` …
> BACKPORT: Merge pull request #7832 from larsoner/dep

- setup.cfg
- statsmodels/base/model.py
- statsmodels/base/tests/test_generic_methods.py
- statsmodels/discrete/tests/test_discrete.py
- statsmodels/gam/tests/test_penalized.py
- statsmodels/genmod/tests/test_constrained.py
- statsmodels/genmod/tests/test_score_test.py
- statsmodels/sandbox/regression/tests/test_gmm.py
- statsmodels/stats/diagnostic.py
- statsmodels/stats/tests/test_diagnostic.py
- statsmodels/stats/tests/test_oneway.py
- statsmodels/stats/tests/test_outliers_influence.py
- statsmodels/tools/_testing.py
- statsmodels/tsa/tests/test_ar.py
ENH: Start move to scalar test statistics
<details>
**Notes**:
```
``` …
> BACKPORT: Merge pull request #7874 from bashtage/scalar-wald

- statsmodels/base/tests/test_penalized.py
TST: add start_params to TestPenalizedPoissonOraclePenalized2
<details>
**Notes**:
```
``` …
> BACKPORT: Merge pull request #7868 from josef-pkt/tst_penalized_convergence

- pyproject.toml
> MAINT: Update pyproject for 3.10

- docs/source/release/index.rst
- docs/source/release/version0.13.1.rst
- tools/releasing/release_note.py
> RLS: Release 0.13.1 documentation

- statsmodels/gam/generalized_additive_model.py
> BUG: Use sorted residual to calcualte _cpr

- examples/notebooks/ols.ipynb
Uses correct object for lower and upper bounds. As it's part of the documentation no additional tests are needed.
<details>
**Notes**:
```
git diff upstream/main -u -- "*.py" | flake8 …
```
> DOC: Issue #7889

- statsmodels/discrete/diagnostic.py
- statsmodels/discrete/discrete_model.py
- statsmodels/discrete/tests/test_predict.py
another round of diagnostics, see #7894 for possible additional diagnostics
- add CountResults.get_diagnostic, and separate method for PoissonResults
> REF/ENH: add CountResults.get_diagnostic

- statsmodels/compat/numpy.py
- statsmodels/compat/pandas.py
- statsmodels/discrete/discrete_model.py
- statsmodels/discrete/tests/test_constrained.py
- statsmodels/discrete/tests/test_discrete.py
- statsmodels/graphics/functional.py
- statsmodels/multivariate/tests/test_factor.py
- statsmodels/stats/_diagnostic_other.py
- statsmodels/tools/tests/test_grouputils.py
- statsmodels/tsa/tests/test_deterministic.py
Silence or update code where needed
<details>
**Notes**:
```
``` …
> MAINT: Remove Future and Deprecation warnings

- statsmodels/base/covtype.py
> DOC: update maxlag to maxlags

- statsmodels/graphics/agreement.py
closes #7887
<details>
**Notes**:
```
```
using …
> BUG: Correct limit in mean diff plot

- statsmodels/tsa/stattools.py
> DOC: Fox ACF/PACF docstrings

- docs/source/statespace.rst
Add MLE prediction results
xref #7931
<details>
**Notes**:
```
``` …
> DOC: Add prediction results to docs

- statsmodels/tsa/_stl.pyx
Correct default arguments in STL
closes #7932 
<details>
**Notes**:
```
``` …
> DOC: Correct STL api

- statsmodels/graphics/functional.py
> MAINT: Future NumPy compat

- statsmodels/compat/tests/test_pandas.py
- statsmodels/tsa/forecasting/stl.py
Add tests
Fix stl docstring space
<details>
**Notes**:
```
``` …
> TST: Add tests for pandas compat

- requirements.txt
- setup.py
- statsmodels/compat/numpy.py
- statsmodels/compat/pandas.py
- statsmodels/compat/scipy.py
- statsmodels/tools/_testing.py
Use packaging for Version
<details>
**Notes**:
```
``` …
> MAINT: Switch to packaging

- statsmodels/compat/numpy.py
- statsmodels/compat/pandas.py
- statsmodels/compat/scipy.py
- statsmodels/multivariate/tests/test_factor.py
- statsmodels/regression/linear_model.py
- statsmodels/regression/tests/test_regression.py
Remove square root
closes #7938
<details>
**Notes**:
```
``` …
> BUG: Correct condition number

- examples/notebooks/recursive_ls.ipynb
> DOC: Fix heading level

- statsmodels/base/_prediction_inference.py
- statsmodels/discrete/discrete_model.py
- statsmodels/genmod/generalized_linear_model.py
Fix small issues in GLM docstrings
<details>
**Notes**:
```
``` …
> DOC: Fix prediction docstrings

- statsmodels/tsa/holtwinters/model.py
- statsmodels/tsa/holtwinters/tests/test_holtwinters.py
> BUG: Correct incorrect initial trend access

- statsmodels/src/math.pxd
Fix noise in build log due to aliasing
<details>
**Notes**:
```
``` …
> MAINT: Remove aliasing of type punned pointers

- .github/workflows/generate-documentation.yml
> MAINT: Update doc builder to Python 3.9

- setup.cfg
- statsmodels/distributions/copula/transforms.py
- statsmodels/distributions/tests/test_bernstein.py
- statsmodels/distributions/tools.py
- statsmodels/stats/proportion.py
- statsmodels/stats/tests/test_proportion.py
- tools/ci/azure/azure_template_posix.yml
Avoid unnecessary float conversion to improve accuracy
closes #7985
<details>
**Notes**:
```
``` …
> BUG: Correct prop ci

- .github/workflows/generate-documentation.yml
> MAINT: Resore doct build to 3.8

- statsmodels/tsa/statespace/_kalman_filter.pyx.in
- statsmodels/tsa/statespace/_kalman_smoother.pyx.in
- statsmodels/tsa/statespace/_representation.pyx.in
Cast non-negative int to unsigned int for comparison
<details>
**Notes**:
```
``` …
> CLN: Prevent signed and unsigned int comparison

- statsmodels/tsa/statespace/mlemodel.py
> DOC: Fix doc errors in MLEResults predict

- statsmodels/tools/typing.py
- statsmodels/tsa/ar_model.py
- statsmodels/tsa/tests/test_ar.py
Add apply to simplify cloning an AutoReg model
closes #7981
<details>
**Notes**:
```
``` …
> ENH: Add apply to AutoRegResults

- statsmodels/tsa/x13.py
Hi, I am working on linux and needed to additional binary types to get it to work.
one of my favorite python projects, its an honor to contribute
<details>
**Notes**:
```
git diff …
```
> new census binaries have different tails

- docs/source/api.rst
- statsmodels/api.py
- statsmodels/formula/api.py
closes #8008
<details>
**Notes**:
```
```
using …
> MAINT: Add conditional models to API

- statsmodels/tsa/statespace/mlemodel.py
> DOC: improve some state space docstrings.

- statsmodels/tsa/statespace/_tools.pyx.in
Small improvement to the performance of the state space weights computations.
> PERF: state space: improve weights performance

- docs/source/glm.rst
- statsmodels/tsa/statespace/representation.py
Fix missing reference
Correct name of class
<details>
**Notes**:
```
``` …
> DOC: Fix missing reference

- statsmodels/base/tests/test_generic_methods.py
- statsmodels/gam/tests/test_penalized.py
- statsmodels/stats/tests/test_diagnostic.py
- statsmodels/tsa/arima_process.py
- statsmodels/tsa/base/tsa_model.py
- statsmodels/tsa/statespace/dynamic_factor_mq.py
- statsmodels/tsa/statespace/tests/test_exponential_smoothing.py
- statsmodels/tsa/tests/test_bds.py
Switch indexing to be explicit to avoid issues in pandas
<details>
**Notes**:
```
``` …
> MAINT: Protect against future pandas changes

- requirements-dev.txt
> MAINT: Pin numpydoc

- statsmodels/discrete/count_model.py
- statsmodels/discrete/discrete_model.py
- statsmodels/distributions/mixture_rvs.py
- statsmodels/examples/ex_generic_mle_t.py
- statsmodels/examples/ex_generic_mle_tdist.py
- statsmodels/genmod/families/family.py
- statsmodels/graphics/mosaicplot.py
- statsmodels/miscmodels/count.py
- statsmodels/regression/linear_model.py
- statsmodels/robust/scale.py
- statsmodels/sandbox/panel/mixed.py
- statsmodels/tsa/innovations/arma_innovations.py
- statsmodels/tsa/stattools.py
> DOC: Apply small docstring corrections

- requirements-dev.txt
> MAINT: Unpin numpydoc

- .github/workflows/backport.yml
Add action to backport using labels
<details>
**Notes**:
```
``` …
> MAINT: Add backport action

- statsmodels/tsa/exponential_smoothing/ets.py
- statsmodels/tsa/statespace/exponential_smoothing.py
- statsmodels/tsa/tests/test_exponential_smoothing.py
> [maintenance/0.13.x] Merge pull request #7906 from bashtage/reverse-seasonal

- statsmodels/graphics/agreement.py
> [maintenance/0.13.x] Merge pull request #7921 from bashtage/mean-diff-plot

- statsmodels/discrete/count_model.py
- statsmodels/discrete/discrete_model.py
- statsmodels/distributions/mixture_rvs.py
- statsmodels/examples/ex_generic_mle_t.py
- statsmodels/examples/ex_generic_mle_tdist.py
- statsmodels/genmod/families/family.py
- statsmodels/graphics/mosaicplot.py
- statsmodels/miscmodels/count.py
- statsmodels/regression/linear_model.py
- statsmodels/robust/scale.py
- statsmodels/sandbox/panel/mixed.py
- statsmodels/tsa/innovations/arma_innovations.py
- statsmodels/tsa/stattools.py
> [maintenance/0.13.x] Merge pull request #8042 from bashtage/pin-numpydoc

- examples/notebooks/recursive_ls.ipynb
> [maintenance/0.13.x] Merge pull request #7954 from bashtage/recursive-ls-heading

- statsmodels/tsa/vector_ar/tests/test_var.py
> [maintenance/0.13.x] Merge pull request #7988 from bashtage/relax-tol-var-test

- statsmodels/src/math.pxd
> [maintenance/0.13.x] Merge pull request #7995 from bashtage/remove-aliasing

- statsmodels/tsa/holtwinters/model.py
- statsmodels/tsa/holtwinters/tests/test_holtwinters.py
> [maintenance/0.13.x] Merge pull request #7969 from bashtage/hw-wrong-param

- statsmodels/tsa/statespace/exponential_smoothing.py
- statsmodels/tsa/statespace/tests/test_exponential_smoothing.py
> [maintenance/0.13.x] Merge pull request #7991 from ChadFulton/ss-exp-smth-seasonals

- statsmodels/tsa/statespace/_kalman_filter.pyx.in
- statsmodels/tsa/statespace/_kalman_smoother.pyx.in
- statsmodels/tsa/statespace/_representation.pyx.in
> [maintenance/0.13.x] Merge pull request #8000 from bashtage/unsigned-int-comparrison

- statsmodels/tsa/exponential_smoothing/ets.py
> [maintenance/0.13.x] Merge pull request #8003 from pkaf/ets-loglike-doc

- statsmodels/tsa/x13.py
> [maintenance/0.13.x] Merge pull request #8007 from rambam613/patch-1

- statsmodels/tsa/statespace/mlemodel.py
> [maintenance/0.13.x] Merge pull request #8015 from ChadFulton/ss-docs

- lint.sh
Correct upstream target for maintenance branch
<details>
**Notes**:
```
``` …
> MAINT: Correct upstream target

- statsmodels/compat/tests/test_pandas.py
- statsmodels/tsa/forecasting/stl.py
> [maintenance/0.13.x] Merge pull request #7939 from bashtage/test-pandas-compat

- statsmodels/base/covtype.py
> [maintenance/0.13.x] Merge pull request #7916 from zprobs/main

- statsmodels/base/tests/test_generic_methods.py
- statsmodels/gam/tests/test_penalized.py
- statsmodels/stats/tests/test_diagnostic.py
- statsmodels/tsa/arima_process.py
- statsmodels/tsa/base/tsa_model.py
- statsmodels/tsa/statespace/dynamic_factor_mq.py
- statsmodels/tsa/statespace/tests/test_exponential_smoothing.py
- statsmodels/tsa/tests/test_bds.py
> [maintenance/0.13.x] Merge pull request #8037 from bashtage/future-pandas

- statsmodels/tsa/statespace/mlemodel.py
> [maintenance/0.13.x] Merge pull request #8005 from bashtage/mle-results-doc

- statsmodels/regression/linear_model.py
- statsmodels/regression/tests/test_regression.py
> [maintenance/0.13.x] Merge pull request #8004 from bashtage/doc-slim

- statsmodels/gam/generalized_additive_model.py
> [maintenance/0.13.x] Merge pull request #7875 from ZachariahPang/Fix-wrong-order-datapoints

- requirements.txt
- setup.py
- statsmodels/compat/numpy.py
- statsmodels/compat/pandas.py
- statsmodels/compat/scipy.py
- statsmodels/tools/_testing.py
> [maintenance/0.13.x] Merge pull request #7946 from bashtage/remove-looseversion

- tools/ci/azure/install-posix.sh
Ensure latest versions are always used
<details>
**Notes**:
```
``` …
> MAINT: Cleanup CI

- statsmodels/compat/pandas.py
- statsmodels/compat/scipy.py
- statsmodels/multivariate/tests/test_factor.py
- statsmodels/regression/linear_model.py
- statsmodels/regression/tests/test_regression.py
> [maintenance/0.13.x] Merge pull request #7950 from bashtage/cond-number

- tools/ci/azure/azure_template_posix.yml
Stop using conda to avoid timeouts
<details>
**Notes**:
```
``` …
> MAINT: Stop using conda temporarily

- setup.py
> MAINT: Correct setup for oldest supported

- statsmodels/sandbox/distributions/multivariate.py
> [maintenance/0.13.x] Merge pull request #8086 from xjcl/patch-1

- docs/source/release/index.rst
- docs/source/release/version0.13.1.rst
- docs/source/release/version0.13.2.rst
- tools/releasing/release_note.py
Final commit for 0.13.2
<details>
**Notes**:
```
``` …
> MAINT: Release note for 0.13.2

- pyproject.toml
- setup.py
> [maintenance/0.13.x] Merge pull request #8109 from henryiii/patch-2

- examples/python/copula.py
- examples/python/ols.py
- examples/python/recursive_ls.py
Export notebooks to python
<details>
**Notes**:
```
``` …
> MAINT: Update examples in python

- statsmodels/regression/linear_model.py
- statsmodels/regression/tests/test_robustcov.py
Ensure pinv_wexog gets greated even when using QR
closes #8157
<details>
**Notes**:
```
``` …
> BUG: Ensure pinv_wexog is available

- statsmodels/stats/proportion.py
- statsmodels/stats/tests/test_proportion.py
Allow arrays
Enforece symmetry
<details>
**Notes**:
```
``` …
> BUG: Allows arrays in porportions

- requirements-dev.txt
- statsmodels/sandbox/regression/penalized.py
- statsmodels/stats/proportion.py
- statsmodels/tools/eval_measures.py
- statsmodels/tsa/holtwinters/model.py
- statsmodels/tsa/tests/test_exponential_smoothing.py
- tools/ci/azure/install-posix.sh
CHeck eff dof and set aicc to inf when <= 0
closes #8172
<details>
**Notes**:
```
``` …
> BUG: Avoid divide by 0 in aicc

- statsmodels/stats/inter_rater.py
> DOC: Improve docs for using fleiss_kappa

- docs/source/api.rst
- docs/source/plots/mstl_plot.py
- docs/source/spelling_wordlist.txt
- docs/source/tsa.rst
- statsmodels/tsa/stl/mstl.py
This PR adds the docs and makes some minor changes to clarify doc strings to the MSTL class created in https://github.com/statsmodels/statsmodels/pull/8160.
> DOC: Add MSTL docs

- statsmodels/sandbox/distributions/tests/test_multivariate.py
closes #8195
<details>
**Notes**:
```
```
using …
> MAINT: Relax overly tight tolerance

- statsmodels/tsa/stattools.py
Switch to inexact match to avoid rare case where float equality fails
closes #8238
<details>
**Notes**:
```
```
assuming …
> BUG: Switch to inexact match

- statsmodels/stats/descriptivestats.py
> Missing `f` prefix on f-strings fix

- statsmodels/graphics/regressionplots.py
> Fix bug #8248

- requirements-dev.txt
- tools/ci/appveyor_conda.bat
- tools/ci/appveyor_pip.bat
- tools/ci/azure/install-posix.sh
Ensure Cython < 3
<details>
**Notes**:
```
``` …
> MAINT: Upper bound on Cython for CI

- statsmodels/graphics/regressionplots.py
> Fixed minor typo on matplotlib import alias

- setup.py
Add required abstract methods
<details>
**Notes**:
```
``` …
> BUG: Correct clean command

- statsmodels/tsa/base/tsa_model.py
N/A
This PR does not effect any tests.
<details>
This PR fix minor typo 'Covert' to 'Convert' in `statsmodels/tsa/base/tsa_base.py`
**Notes**:
```
git diff upstream/main -u -- "*.py" | …
```
> MAINT: fix typo comment in tsa_model.py

- requirements-dev.txt
- statsmodels/regression/linear_model.py
- statsmodels/stats/tests/test_sandwich.py
- tools/ci/azure/azure_template_windows.yml
Include oldest-supported-numpy so that isolated build can succeed
<details>
**Notes**:
```
``` …
> MAINT: Correct requirements-dev

- statsmodels/stats/diagnostic.py
- statsmodels/tsa/stattools.py
Add See Also between the two to show the difference
closes #4472
<details>
**Notes**:
```
``` …
> DOC: Clarify difference between q_stat and acorr_ljungbox

- lint.sh
Update lint list to be stricter
<details>
**Notes**:
```
``` …
> MAINT: Update lint

- statsmodels/discrete/diagnostic.py
- statsmodels/stats/diagnostic_gen.py
- statsmodels/stats/effect_size.py
- statsmodels/tsa/statespace/tests/results/frbny_nowcast/Nowcasting/functions/dfm.m
- ~closes #xxxx~
- ~tests added / passed.~ 
<details>
**Notes**:
```
``` …
> Easy PR! Fix minor typos

- docs/source/stats.rst
- statsmodels/stats/api.py
- statsmodels/stats/proportion.py
- statsmodels/stats/rates.py
doc, api fixes mainly for #8166
> ENH/DOC fixes in docs, missing in stats.api fpr rates

- azure-pipelines.yml
- statsmodels/stats/tests/test_effectsize.py
Change in result due to SciPy and Boost integration
<details>
**Notes**:
```
``` …
> MAINT: Relax tolerance due to Scipy changes

- statsmodels/regression/tests/test_regression.py
> TST: Add GLS singular test

- statsmodels/regression/linear_model.py
> ENH: faster whitening matrix calculation for sm.GLS()

- statsmodels/miscmodels/ordinal_model.py
> Fix typo in documentation

- docs/source/contrasts.rst
- examples/notebooks/contrasts.ipynb
this should fix pandas incompatibility in #8432
However, it doesn't fix why the pandas problem is fatal for the sphinx build
> Maint: use pandas loc in contrasts notebook

- pyproject.toml
- requirements.txt
- statsmodels/compat/scipy.py
- statsmodels/graphics/factorplots.py
- statsmodels/regression/tests/test_regression.py
- statsmodels/sandbox/predict_functional.py
- statsmodels/stats/contingency_tables.py
- statsmodels/stats/descriptivestats.py
- statsmodels/stats/mediation.py
- statsmodels/tools/tests/test_grouputils.py
> MAINT: Fix future warnings

- pyproject.toml
- requirements-dev.txt
- requirements.txt
- statsmodels/__init__.py
- statsmodels/tools/web.py
- tools/ci/azure/install-posix.sh
> MAINT: Fix Windows and SciPy issues

- .github/workflows/generate-documentation.yml
- requirements-dev.txt
- requirements-doc.txt
> MAINT: Refactor doc build

- statsmodels/base/tests/test_generic_methods.py
- statsmodels/base/tests/test_shrink_pickle.py
- statsmodels/genmod/tests/test_glm.py
- statsmodels/graphics/tests/test_gofplots.py
- statsmodels/graphics/tests/test_regressionplots.py
- statsmodels/imputation/tests/test_ros.py
- statsmodels/nonparametric/tests/test_kernel_density.py
- statsmodels/regression/tests/test_robustcov.py
- statsmodels/robust/tests/test_rlm.py
- statsmodels/stats/tests/test_proportion.py
> MAINT: Replave setup with setup_method in tests

- pyproject.toml
- setup.cfg
- statsmodels/base/tests/test_generic_methods.py
- statsmodels/base/tests/test_shrink_pickle.py
- statsmodels/duration/survfunc.py
- statsmodels/genmod/tests/test_gee.py
- statsmodels/genmod/tests/test_glm.py
- statsmodels/graphics/tests/test_gofplots.py
- statsmodels/graphics/tests/test_regressionplots.py
- statsmodels/imputation/tests/test_bayes_mi.py
- statsmodels/imputation/tests/test_mice.py
- statsmodels/imputation/tests/test_ros.py
- statsmodels/multivariate/factor_rotation/_gpa_rotation.py
- statsmodels/multivariate/tests/test_ml_factor.py
- statsmodels/nonparametric/tests/test_kernel_density.py
- statsmodels/regression/tests/test_robustcov.py
- statsmodels/robust/tests/test_rlm.py
- statsmodels/sandbox/bspline.py
- statsmodels/stats/mediation.py
- statsmodels/stats/tests/test_effectsize.py
- statsmodels/stats/tests/test_proportion.py
- statsmodels/stats/tests/test_sandwich.py
- statsmodels/tsa/regime_switching/markov_switching.py
- statsmodels/tsa/statespace/tests/test_collapsed.py
- statsmodels/tsa/statespace/tests/test_univariate.py
- statsmodels/tsa/tests/test_stattools.py
- statsmodels/tsa/vector_ar/tests/JMulTi_results/parse_jmulti_vecm_output.py
- statsmodels/tsa/vector_ar/tests/test_var.py
> TST: Relax tolerance on tests that marginally fail

- .github/workflows/generate-documentation.yml
> MAINT: Update doc build instructions

- docs/source/contrasts.rst
> DOC: Fix warnings

- .github/workflows/generate-documentation.yml
- docs/source/dev/test_notes.rst
- pyproject.toml
- requirements-dev.txt
- requirements.txt
- setup.py
- statsmodels/regression/linear_model.py
- statsmodels/sandbox/distributions/tests/test_multivariate.py
- statsmodels/stats/tests/test_effectsize.py
- statsmodels/stats/tests/test_sandwich.py
- tools/ci/azure/azure_template_posix.yml
- tools/ci/azure/azure_template_windows.yml
- tools/ci/azure/install-posix.sh
> MAINT: Backport Python 3.11 to 0.13.x branch

- pyproject.toml
> MAINT: Set some Pins

- docs/source/stats.rst
- docs/source/treatment.rst
- statsmodels/stats/proportion.py
- statsmodels/stats/rates.py
- statsmodels/stats/robust_compare.py
- statsmodels/treatment/treatment_effects.py
closes #7032
currently several docfixes in stats
I might add some api refactoring and cleanup to this PR
> DOC: fix docstrings

- pyproject.toml
- requirements.txt
> MAINT: Refine pins

- docs/source/release/index.rst
- docs/source/release/version0.13.4-5.rst
> DOC: Add release notes for .4 and .5

- docs/source/glm.rst
- statsmodels/genmod/families/family.py
- statsmodels/genmod/families/links.py
- statsmodels/genmod/families/tests/test_link.py
This pull request adds the logc link the binomial generalized linear model. 
Changes are
1 Define link's class.
2 Test link.
3 Add link to binomial family.
4 Add to doc.
5 Clip cauchy link for numerical approximation to be accurate. (Test failed before change.)
This PR is a rebase of https://github.com/statsmodels/statsmodels/pull/8153.
<details>
**Notes**:
then show that it is …
> ENH: Adding logc link

- statsmodels/genmod/tests/results/results_glm.py
- statsmodels/multivariate/tests/test_manova.py
- statsmodels/regression/tests/test_regression.py
- statsmodels/stats/tests/test_mediation.py
- statsmodels/tools/tests/test_grouputils.py
trying to fix #8538 errors in pre testing
pandas get_dummies add dtype=float
> MAINT: fix pre testing errors

- statsmodels/distributions/__init__.py
- statsmodels/distributions/empirical_distribution.py
- statsmodels/distributions/tests/test_ecdf.py
- [?] tests added / passed. (no tests for ECDF either)
<details>
Adding a new feature for weighted ECDF. It collapses to ECDF if weights are the same.
</details>
> adding weighted empirical CDF

- statsmodels/base/optimizer.py
- statsmodels/base/tests/test_optimize.py
- statsmodels/compat/scipy.py
closes #8317
rebased, squashed version of #8317
minor merge conflict in compat/scipy with version variables
> ENH: Nelder-Mead and Powell has bounds in scipy

- lint.sh
- statsmodels/distributions/empirical_distribution.py
- statsmodels/distributions/tests/test_ecdf.py
mainly whitespace fixes
for the record, the main part was:
```
if __name__ == "__main__":
from urllib.request import urlopen
import matplotlib.pyplot as plt
nerve_data = urlopen('http://www.statsci.org/data/general/nerve.txt')
nerve_data = np.loadtxt(nerve_data)
x = nerve_data / 50.  # was in 1/50 seconds
cdf = ECDF(x)
x.sort()
F = cdf(x)
plt.step(x, F, where='post')
lower, upper = _conf_set(F)
plt.step(x, lower, 'r', where='post')
plt.step(x, upper, 'r', where='post')
plt.xlim(0, 1.5)
plt.ylim(0, 1.05)
plt.vlines(x, 0, .05)
plt.show()
```
> STY: lint, pep-8 of empirical distribution, remove `__main__`

- statsmodels/discrete/discrete_model.py
- statsmodels/discrete/tests/test_truncated_model.py
- statsmodels/discrete/truncated_model.py
- statsmodels/genmod/generalized_linear_model.py
- statsmodels/regression/linear_model.py
follow up to #7973
I had left one change out of the PR, I merged too fast
new models still need a full review and improvements of docstrings
> ENH/REF/DOC  improve hurdle and truncated count models

- statsmodels/gam/smooth_basis.py
numer fixed to number in line 405
<details>
**Notes**:
```
``` …
> Orthographic fix

- statsmodels/genmod/families/family.py
- statsmodels/genmod/families/tests/test_family.py
- statsmodels/genmod/tests/results/res_R_var_weight.py
- statsmodels/genmod/tests/test_glm.py
rebased version of #8281
one bugfix
more unit tests using GLM
not checked yet: usage of new loglike as default and for fit with scipy optimizers
> ENH: Tweedie loglike

- docs/source/distributions.rst
- docs/source/rlm.rst
- statsmodels/base/_prediction_inference.py
- statsmodels/distributions/copula/elliptical.py
- statsmodels/genmod/families/family.py
- statsmodels/genmod/families/tests/test_family.py
- statsmodels/genmod/generalized_linear_model.py
- statsmodels/graphics/tests/test_dotplot.py
- statsmodels/regression/tests/test_regression.py
- statsmodels/stats/outliers_influence.py
- statsmodels/stats/proportion.py
- statsmodels/stats/weightstats.py
various small fixes from roadmap 0.14 list
adds MQuantileNorm and ECDFDiscrete to rst docs
> DOC: add to rst docs, fix docstrings

- statsmodels/tsa/x13.py
closes #8301
updated version
rebased and amended with changes suggested by Kevin
> ENH: x13.py option for location of temporary files

- docs/source/gam.rst
- docs/source/gee.rst
- docs/source/glm.rst
- setup.cfg
- statsmodels/base/_prediction_inference.py
- statsmodels/discrete/tests/test_discrete.py
- statsmodels/gam/tests/test_penalized.py
- statsmodels/genmod/families/family.py
- statsmodels/genmod/families/links.py
- statsmodels/genmod/tests/test_glm.py
- statsmodels/genmod/tests/test_glm_weights.py
- statsmodels/sandbox/predict_functional.py
- statsmodels/sandbox/tests/test_gam.py
> MAINT: Deprecate link aliases

- statsmodels/regression/linear_model.py
- statsmodels/stats/gof.py
- statsmodels/tsa/stattools.py
- statsmodels/tsa/tests/test_stattools.py
contains two small enhancements, bugs for problematic data
- allclose tolerance in powerdiscrepancy closes #8558
- yule walker singular closes #8363
> Ref/ENH misc, smaller fixes or enhancements

- statsmodels/imputation/tests/test_mice.py
- statsmodels/stats/tests/test_mediation.py
Do not merge for now. checking failing unit tests
> TST: disable failing random test, imputation, mediation

- setup.cfg
- statsmodels/tsa/base/tests/test_tsa_indexes.py
Also rename license_file
<details>
**Notes**:
```
``` …
> MAINT/TST: Fix test change due to pandas

- examples/notebooks/glm.ipynb
- examples/python/glm.py
- setup.cfg
- statsmodels/base/_prediction_inference.py
- statsmodels/discrete/tests/test_sandwich_cov.py
- statsmodels/examples/ex_feasible_gls_het_0.py
- statsmodels/examples/ex_predict_results.py
- statsmodels/genmod/families/tests/test_link.py
- statsmodels/genmod/qif.py
- statsmodels/genmod/tests/results/results_glm.py
- statsmodels/othermod/tests/test_beta.py
- statsmodels/regression/tests/test_predict.py
- statsmodels/sandbox/tests/test_gam.py
- statsmodels/stats/mediation.py
- statsmodels/stats/tests/test_influence.py
- statsmodels/stats/tests/test_mediation.py
- statsmodels/tsa/tests/test_seasonal.py
> MAINT: Clean up deprecations

- requirements-doc.txt
> MAINT: Pin sphinx

- docs/source/dev/test_notes.rst
- docs/source/treatment.rst
- requirements-doc.txt
- statsmodels/treatment/treatment_effects.py
> DOC: Fix doc build

- statsmodels/tsa/statespace/mlemodel.py
> DOC: Fix indent

- docs/source/tsa.rst
- statsmodels/tsa/ar_model.py
- statsmodels/tsa/ardl/model.py
- statsmodels/tsa/arima/model.py
- statsmodels/tsa/deterministic.py
- statsmodels/tsa/filters/bk_filter.py
- statsmodels/tsa/filters/cf_filter.py
- statsmodels/tsa/filters/hp_filter.py
- statsmodels/tsa/forecasting/stl.py
- statsmodels/tsa/holtwinters/model.py
- statsmodels/tsa/regime_switching/markov_autoregression.py
- statsmodels/tsa/regime_switching/markov_regression.py
- statsmodels/tsa/stattools.py
- statsmodels/tsa/stl/_stl.pyx
> DOC: added notebook links to TSA documentation and doc strings

- statsmodels/tsa/arima/model.py
> DOC: Remove dupe section

- docs/source/conf.py
- requirements-doc.txt
> DOC: Fix extlinks

- statsmodels/stats/multitest.py
- statsmodels/stats/tests/test_multi.py
This fixes bugs reported in #8619
no enhancements, refactoring yet, maxiter and HolderTuple
> BUG: fix fdrcorrection_twostage, order, pvals>1

- statsmodels/distributions/copula/archimedean.py
- statsmodels/distributions/copula/tests/test_copula.py
closes #8657
add taylor series expansion for tau of FrankCopula
> BUG/ENH: correct tau for small theta in FrankCopula 

- statsmodels/discrete/discrete_model.py
- statsmodels/discrete/tests/test_discrete.py
> BUG: MNLogit if endog is series with no name 

- statsmodels/iolib/summary2.py
- statsmodels/iolib/tests/test_summary2.py
- statsmodels/regression/linear_model.py
> BUG: Adding extra text in html of summary2.Summary #8663

- statsmodels/regression/mixed_linear_model.py
- statsmodels/regression/tests/test_lme.py
> BUG: mixedlm fit_regularized, missing vcomp in results

- examples/notebooks/mixed_lm_example.ipynb
"imputation" here probably should be "implementation".
> DOC: Fix typo in examples/notebooks/mixed_lm_example.ipynb

- docs/source/conf.py
Update copyright end date in documentation from 2019 to 2023
> Update copyright date in docs/source/conf.py

- statsmodels/base/model.py
- statsmodels/base/optimizer.py
- statsmodels/discrete/count_model.py
- statsmodels/discrete/truncated_model.py
- statsmodels/multivariate/manova.py
- statsmodels/multivariate/multivariate_ols.py
- statsmodels/multivariate/tests/test_manova.py
- catch Convergence warning when computing start_params. I had missed  few
https://stats.stackexchange.com/questions/608609/statsmodels-zeroinflatedpoisson-unable-to-converge 
- closes #8726
I still have 2 or 3 uncommitted changes to the code, not sure yet about which way to fix
#8729
manova skip intercept https://github.com/statsmodels/statsmodels/issues/8713#issuecomment-1458655396
> BUG: a few more small bug fixes

- statsmodels/formula/tests/test_formula.py
- statsmodels/iolib/tests/test_table.py
- statsmodels/tools/rootfinding.py
- statsmodels/tools/tests/test_rootfinding.py
- statsmodels/tsa/tests/test_deterministic.py
> MAINT/TST  unit test failures, compatibility changes

- docs/source/release/version0.14.rst
> DOC: Merge existing highlights

- setup.cfg
- statsmodels/base/tests/test_data.py
- statsmodels/conftest.py
- statsmodels/formula/tests/test_formula.py
- statsmodels/genmod/tests/test_glm.py
- statsmodels/genmod/tests/test_glm_weights.py
- statsmodels/imputation/bayes_mi.py
- statsmodels/imputation/mice.py
- statsmodels/imputation/ros.py
- statsmodels/imputation/tests/test_mice.py
- statsmodels/regression/tests/test_robustcov.py
- statsmodels/stats/anova.py
- statsmodels/stats/tests/test_deltacov.py
- statsmodels/stats/tests/test_panel_robustcov.py
- statsmodels/tools/validation/validation.py
- statsmodels/tsa/holtwinters/_exponential_smoothers.pyx
- statsmodels/tsa/holtwinters/tests/test_holtwinters.py
- statsmodels/tsa/statespace/dynamic_factor_mq.py
- statsmodels/tsa/statespace/varmax.py
- statsmodels/tsa/stl/_stl.pyx
- statsmodels/tsa/stl/tests/test_stl.py
- tools/ci/azure/azure_template_posix.yml
> MAINT: Ensure statsmodels test suite passes with pandas CoW

- requirements-doc.txt
> MAINT: Cap sphinx in the doc build

- statsmodels/nonparametric/_smoothers_lowess.pyx
- statsmodels/nonparametric/tests/test_kde.py
- statsmodels/nonparametric/tests/test_lowess.py
> MAINT: Fix lowess Cython to handle read-only

- statsmodels/discrete/discrete_model.py
> MAINT: numpy compat, indexed assignment shape in NegativeBinomial

- statsmodels/tsa/statespace/tools.py
closes #8401
<details>
**Notes**:
```
```
using …
> DOC: Correct docstring for diff

- statsmodels/__init__.py
- statsmodels/compat/patsy.py
> MAINT: Monkey deprecated patsy function

- statsmodels/tsa/holtwinters/_smoothers.py
- statsmodels/tsa/holtwinters/model.py
- statsmodels/tsa/holtwinters/results.py
- statsmodels/tsa/holtwinters/tests/test_holtwinters.py
Correct these so that they are not estimated when set
closes #8634
<details>
**Notes**:
```
``` …
> BUG: Correct initial level, treand and seasonal

- statsmodels/tsa/forecasting/tests/test_theta.py
- statsmodels/tsa/forecasting/theta.py
> Theta method bug

- statsmodels/graphics/regressionplots.py
Clarified plot_fit in the documentation
<details>
* Included fact that uncertainty is pointwise prediction intervals
* Added explanation for vertical lines in example plot
</details>
> DOC: Add a better description of the plot generated by plot_fit

- .gitignore
- docs/source/_static/stylesheets/deprecation.css
- docs/source/conf.py
- docs/source/examples/index.jinja2
- docs/source/index.rst
- docs/source/release/version0.10.rst
- docs/source/release/version0.11.rst
- docs/source/release/version0.12.rst
- docs/source/release/version0.13.0.rst
- docs/source/release/version0.14.rst
- requirements-doc.txt
- tools/ci/docbuild_install.sh
- tools/releasing/release_note.tmpl
Switch from the not maintained sphinx-material to sphinx-immaterial
<details>
**Notes**:
```
``` …
> DOC: Change to improved theme

- docs/source/conf.py
- docs/source/version_info/versions-v3.json
> DOC: Use JSON for versioning

- statsmodels/discrete/discrete_model.py
- statsmodels/discrete/tests/test_truncated_model.py
- statsmodels/discrete/truncated_model.py
- statsmodels/robust/tests/test_norms.py
> BUG/ENH: support offset in truncated count models

- statsmodels/tsa/forecasting/stl.py
> DOC: Small fix for STLForecast example

- examples/notebooks/statespace_sarimax_internet.ipynb
> DOC: Fix internet address of dataset

- docs/source/release/version0.14.rst
- statsmodels/distributions/copula/copulas.py
- statsmodels/robust/norms.py
- statsmodels/tsa/statespace/kalman_filter.py
- statsmodels/tsa/statespace/simulation_smoother.py
> DOC: Small additional fixes

- docs/source/conf.py
> DOC: Add version

- statsmodels/multivariate/factor.py
> MAINT: Move from Styler.applymap to map

- docs/source/_static/stylesheets/deprecation.css
- docs/source/release/index.rst
- docs/source/release/version0.14.0.rst
- statsmodels/discrete/discrete_model.py
- statsmodels/discrete/truncated_model.py
- statsmodels/stats/_diagnostic_other.py
- statsmodels/stats/multitest.py
- statsmodels/stats/rates.py
- statsmodels/treatment/treatment_effects.py
- statsmodels/tsa/ar_model.py
- statsmodels/tsa/statespace/simulation_smoother.py
- statsmodels/tsa/stl/mstl.py
> DOC: Add admonitions for changes and deprecations

- setup.py
> TST: install missing *.csv files needed by tsa.stl tests

- tools/ci/azure/azure_template_posix.yml
- tools/ci/azure/install-posix.sh
> MAINT: Add CI for install and sdist install

- setup.py
- tools/ci/azure/azure_template_posix.yml
- tools/ci/azure/install-posix.sh
> Backport of #8870 and #8872

- statsmodels/robust/tests/test_norms.py
> TST: Relax tolerance on overly tight test

- docs/source/anova.rst
- docs/source/discretemod.rst
- docs/source/glm.rst
- docs/source/large_data.rst
- docs/source/mixed_linear.rst
- docs/source/regression.rst
- docs/source/rlm.rst
- docs/source/statespace.rst
- docs/source/stats.rst
- docs/source/treatment.rst
- docs/source/tsa.rst
- requirements-dev.txt
closes #8885
<details>
**Notes**:
```
```
using …
> DOC: Correct links to notebooks

- statsmodels/base/model.py
- statsmodels/discrete/tests/test_discrete.py
closes #8905
no unit tests yet
I only ran the discrete tests locally.
> BUG: mnlogit wald tests, ravel, string cov_names

- docs/source/pitfalls.rst
- statsmodels/tsa/stl/_stl.pyx
- statsmodels/tsa/stl/tests/test_stl.py
(waiting for the CI bot to test it)
> CLN: Fix typos

- tools/ci/azure/install-posix.sh
> MAINT: Update nightly location

- statsmodels/graphics/correlation.py
- statsmodels/graphics/plot_grids.py
Fixes inclusion of plots in generated documentation for `plot_corr` and `plot_corr_grid`.
> DOC: Fix inclusion of plots

- statsmodels/distributions/copula/copulas.py
Fixes https://github.com/statsmodels/statsmodels/issues/8933
> DOC: correct signature of `CopulaDistribution`

- pyproject.toml
- requirements-doc.txt
- requirements.txt
- tools/ci/azure/install-posix.sh
Currently require NumPy<2
<details>
**Notes**:
```
``` …
> MAINT: Insert some initial NumPy caps

- statsmodels/graphics/plot_grids.py
Includes the correct source file to produce the figure in the API doc of `statsmodels.graphics.plot_grids.scatter_ellipse`.
> DOC: Include correct plot in scatter_ellipse

- statsmodels/base/tests/test_optimize.py
> TST: Ensure value is float

- statsmodels/multivariate/cancorr.py
> DOC: fix typo

- statsmodels/tools/_testing.py
- tools/ci/azure/azure_template_posix.yml
> CI: Ensure non-zero exit fails

- statsmodels/imputation/tests/test_mice.py
- tools/ci/azure/azure_template_posix.yml
> MAINT: Use RandomState in-place of np.random.seed

- statsmodels/iolib/summary2.py
- statsmodels/iolib/tests/test_summary2.py
- statsmodels/regression/tests/test_lme.py
- statsmodels/tsa/statespace/structural.py
- statsmodels/tsa/statespace/tests/test_structural.py
> MAINT: Protect against future pandas changes to merge/sorting

- statsmodels/stats/oneway.py
> DOC: fix small typo

- setup.cfg
- statsmodels/stats/_adnorm.py
- statsmodels/stats/diagnostic.py
- statsmodels/stats/tests/test_diagnostic.py
Fix issues related to multi-dimensional indexing in pandas
closes #8879
<details>
**Notes**:
```
``` …
> BUG: Correct diagnostics for changes in pandas

- statsmodels/tsa/statespace/dynamic_factor_mq.py
> MAINT: Fix future issues in pandas

- INSTALL.txt
- docs/source/install.rst
- pyproject.toml
- requirements-dev.txt
- requirements.txt
- setup.py
- tools/ci/azure/azure_template_posix.yml
- tools/ci/azure/azure_template_windows.yml
Update minimums using Decembr 2021 as the start date
<details>
**Notes**:
```
``` …
> BLD: Update minimums

- statsmodels/discrete/truncated_model.py
- statsmodels/distributions/discrete.py
- statsmodels/tsa/ar_model.py
Avoid log of 0
Avoid legend with no labels
<details>
**Notes**:
```
``` …
> MAINT: Remove conditions producing warnings

- statsmodels/base/model.py
- statsmodels/discrete/tests/test_discrete.py
- statsmodels/graphics/tests/test_tsaplots.py
- statsmodels/graphics/tsaplots.py
- statsmodels/tsa/base/tests/test_tsa_indexes.py
- statsmodels/tsa/base/tsa_model.py
- statsmodels/tsa/holtwinters/tests/test_holtwinters.py
- statsmodels/tsa/statespace/sarimax.py
- statsmodels/tsa/statespace/tests/test_prediction.py
- statsmodels/tsa/stl/mstl.py
Ensure warnings are provided about future changes
<details>
**Notes**:
```
``` …
> MAINT: Clean up and silence some warnings

- tools/ci/azure/azure_template_posix.yml
> CI: Update pip pre to 3.12

- statsmodels/regression/linear_model.py
- statsmodels/tools/grouputils.py
- statsmodels/tsa/statespace/dynamic_factor_mq.py
> MAINT: Fix future issues due to array shapes

- requirements.txt
> edited requirements.txt

- requirements.txt
- statsmodels/graphics/tests/test_tsaplots.py
> MAINT: Replace quarterly string identified

- statsmodels/regression/tests/test_predict.py
- statsmodels/tools/tests/test_grouputils.py
> MAINT: Fixes for future changes

- .github/workflows/codeql.yml
- .github/workflows/generate-documentation.yml
- examples/notebooks/linear_regression_diagnostics_plots.ipynb
- examples/python/linear_regression_diagnostics_plots.py
- requirements.txt
- statsmodels/base/model.py
- statsmodels/discrete/truncated_model.py
- statsmodels/distributions/discrete.py
- statsmodels/graphics/gofplots.py
- statsmodels/graphics/mosaicplot.py
- statsmodels/graphics/tsaplots.py
- statsmodels/tsa/arima/tests/test_model.py
- statsmodels/tsa/deterministic.py
- statsmodels/tsa/seasonal.py
- statsmodels/tsa/statespace/mlemodel.py
- statsmodels/tsa/statespace/sarimax.py
- statsmodels/tsa/statespace/tests/results/results_structural.py
- statsmodels/tsa/stl/mstl.py
- tools/ci/azure/azure_template_posix.yml
> Cherry pick commits from 0.15 for 0.14.3

- statsmodels/tsa/exponential_smoothing/base.py
- statsmodels/tsa/statespace/mlemodel.py
- [ x] code/documentation is well formatted.  
- [ x] properly formatted commit message. See 
<details>
**Notes**:
```
``` …
> DOC: fixed boxpierece typos

- statsmodels/robust/norms.py
- statsmodels/robust/tests/test_norms.py
- statsmodels/robust/tests/test_tools.py
- statsmodels/robust/tools.py
related
#8808
#1372
this adds tools for asymptotic efficency, breakdown point computation and choice of tuning parameter of norms.
currently only for univariate
this adds some additional norms, TukeyQuartic and StudentT (I also have Cauchy norm, but might leave it out as special case of StudentT with df=1)
plan for next, either in this PR or next PR are more general (M-)scale estimators #9171
> ENH: robust: tools and more norms

- docs/source/install.rst
- requirements-dev.txt
> DOC: Final docs for 0.14.2

- examples/notebooks/interactions_anova.ipynb
- examples/notebooks/recursive_ls.ipynb
- examples/notebooks/statespace_arma_0.ipynb
- examples/notebooks/statespace_local_linear_trend.ipynb
- examples/notebooks/statespace_news.ipynb
> DOC: Fix interactions notebook

- statsmodels/stats/proportion.py
- statsmodels/stats/tests/test_proportion.py
<details>
I added the 'side' parameter to proportion_confint to enable the calculation of a one-sided CI.
The parameter has three options: two-sided(default), upper, and lower.
When either upper or lower is selected, ci_low or ci_upp is returned as np.nan.
> added "one-sided" alternative for proportion_confint

- statsmodels/iolib/summary2.py
- statsmodels/iolib/tests/test_summary2.py
rebased version of #9191
changes startswith to `in`, adds unit tests
closes #9191
> ENH: Add optional parameters for summary_col to indicate FEs (rebased)

- statsmodels/tsa/statespace/dynamic_factor_mq.py
> DOC: Replace `postive` by `positive`

- statsmodels/tsa/ar_model.py
> DOC: Fix documentation of `statsmodels.tsa.ar_model.AutoReg`

- pyproject.toml
- requirements-doc.txt
- requirements.txt
- setup.py
- tools/ci/azure/azure_template_posix.yml
- tools/ci/azure/install-posix.sh
Update requirements to reflect recentl dep min versions
<details>
**Notes**:
```
``` …
> MAINT: Update requirements

- CITATION.cff
Add citation for for github integration
<details>
**Notes**:
```
``` …
> DOC: Add citation file

- statsmodels/graphics/tsaplots.py
- statsmodels/tsa/stattools.py
Improve documentation to explain the difference between the acf calcuation and the standard plot
closes #8362
<details>
**Notes**:
```
git diff upstream/main -u -- "*.py" | flake8 --diff …
```
> DOC: Improve documentation of acf and plot_acf

- statsmodels/tsa/statespace/tests/test_dynamic_factor.py
> TST: Relax tolerance on test that fails for dynamic factor

- examples/python/contrasts.py
- examples/python/statespace_tvpvar_mcmc_cfa.py
- setup.py
- tools/nbgenerate.py
> MAINT: Run pyupgrade on main  branch

- docs/source/dev/index.rst
- docs/source/graphics.rst
- docs/source/install.rst
- docs/source/optimization.rst
- docs/source/regression.rst
- docs/source/release/index.rst
- docs/source/release/version0.14.3.rst
- docs/source/release/version0.6.rst
- docs/source/version_info/versions-v3.json
- statsmodels/graphics/tsaplots.py
> DOC: Add release note for 0.14.3

- docs/source/release/version0.14.3.rst
> DOC: Spelling

- docs/source/release/index.rst
- docs/source/release/version0.14.4.rst
- statsmodels/distributions/discrete.py
- statsmodels/tsa/arima/estimators/tests/test_gls.py
- statsmodels/tsa/arima/estimators/tests/test_hannan_rissanen.py
> DOC: Add release note for 0.14.4

- docs/source/release/version0.14.4.rst
Fix number
[skip ci]
<details>
**Notes**:
```
``` …
> DOC: Fix version number

- statsmodels/distributions/empirical_distribution.py
- statsmodels/distributions/tests/test_ecdf.py
- statsmodels/gam/smooth_basis.py
- statsmodels/graphics/gofplots.py
- statsmodels/imputation/ros.py
- statsmodels/sandbox/nonparametric/dgp_examples.py
- statsmodels/sandbox/nonparametric/smoothers.py
- statsmodels/tools/grouputils.py
- statsmodels/tsa/arima/estimators/tests/test_hannan_rissanen.py
Fix in-place modification in ECDF
Remove potential issues by moving from arr.sort() to np.sort(arr)
closes #9383
<details>
**Notes**:
```
git diff upstream/main -u -- "*.py" | flake8 …
```
> BUG: Avoid modification in place

- statsmodels/distributions/discrete.py
- statsmodels/tsa/arima/estimators/tests/test_gls.py
> MAINT: Fix scalar assignment 

- docs/source/about.rst
- docs/source/dev/index.rst
- docs/source/install.rst
- docs/source/plots/mstl_plot.py
- docs/source/plots/stl_plot.py
- docs/source/release/index.rst
- docs/source/release/version0.14.3.rst
- docs/source/release/version0.14.4.rst
- docs/source/release/version0.6.rst
- docs/source/version_info/versions-v3.json
- statsmodels/graphics/plot_grids.py
- statsmodels/tsa/arima/model.py
- statsmodels/tsa/holtwinters/model.py
> DOC: Imroves docs for exponentialsmoothing and other places

- statsmodels/tsa/arima/model.py
> DOC: Fix typo in previous fix

- statsmodels/discrete/conditional_models.py
- statsmodels/discrete/tests/test_conditional.py
> BUG: Ensure hessian is skipped

- statsmodels/tsa/exponential_smoothing/ets.py
> BUG: Correct LLF for ETSModel 

- statsmodels/base/data.py
- statsmodels/base/tests/test_data.py
> ENH: more reliable casting of pandas data

- statsmodels/stats/mediation.py
This PR updates the mediation tutorial documentation where missing `Mediation` import, `data` variable creation and `probit` object instantiation are fixed.
**Notes**:
```
git diff …
```
> DOC: updated mediation tutorial documentation

- statsmodels/tsa/tests/test_x13.py
- statsmodels/tsa/x13.py
Switch to daterange
Add tests for numpy input
<details>
**Notes**:
```
``` …
> BUG: Correct DatetimeIndex use

- statsmodels/tsa/tests/test_x13.py
> TST: Restore skip when no x13 available

- examples/notebooks/mixed_lm_example.ipynb
> DOC: Corrected a typo in chi^2

- docs/source/conf.py
Update the year from 2023 to 2025.
Happy New Year!
> Update conf.py year

- statsmodels/tsa/vector_ar/svar_model.py
- statsmodels/tsa/vector_ar/tests/test_svar.py
> BUG: svar, A,B dtype, one parameter score shape, closes #9302

- requirements.txt
- tools/ci/azure/azure_template_windows.yml
- tools/ci/azure/install-posix.sh
Bump formulaic
Remove install from git
<details>
**Notes**:
```
``` …
> MAINT: Bump formulaic to 1.1.0

- examples/notebooks/tsa_arma_0.ipynb
This PR updates the [Sunspots data](https://www.statsmodels.org/stable/examples/notebooks/generated/tsa_arma_0.html#Sunspots-Data) tutorial documentation by removing the empty cell.
> DOC: remove empty cell in tsa_arma_0.ipyb file

- statsmodels/sandbox/stats/multicomp.py
- statsmodels/stats/multicomp.py
- statsmodels/stats/tests/test_pairwise.py
rebased version closes #9175
see also PR #7332  which has additional unit test and api with connecting_letters
currently only rebased with fixing merge conflicts, 
no squashing of commits yet.
> BUG/ENH: Tukeyhsd, fix unused variance, add Games-Howell 

- statsmodels/tsa/tests/test_x13.py
- statsmodels/tsa/x13.py
> Modify x13_arima_analysis to produce seasonality fit diagnostics

- statsmodels/compat/scipy.py
- statsmodels/distributions/discrete.py
- statsmodels/genmod/_tweedie_compound_poisson.py
Add shim to simplify transition between the two
<details>
**Notes**:
```
``` …
> MAINT: Remove _lazywhere in favor of apply_where

- statsmodels/compat/pandas.py
- statsmodels/compat/scipy.py
- statsmodels/iolib/tests/test_summary2.py
- statsmodels/regression/tests/test_regression.py
- statsmodels/regression/tests/test_theil.py
- statsmodels/sandbox/distributions/extras.py
- statsmodels/sandbox/distributions/tests/test_multivariate.py
- statsmodels/sandbox/stats/tests/test_multicomp.py
> MAINT: Improve handeling of missing mvndst

- statsmodels/regression/tests/test_theil.py
> STY: Remove unused import

- statsmodels/graphics/gofplots.py
- statsmodels/graphics/tests/test_gofplots.py
* Add plotkwargs to qqplot_2samples()
> ENH: add plotkwargs for qqplot_2samples()

- statsmodels/stats/tests/test_corrpsd.py
- tools/ci/azure/azure_template_posix.yml
- tools/ci/azure/azure_template_windows.yml
> CI: Fix flaky test and add 3.13 jobs

- examples/notebooks/autoregressions.ipynb
- examples/notebooks/autoregressive_distributed_lag.ipynb
- examples/notebooks/categorical_interaction_plot.ipynb
- examples/notebooks/chi2_fitting.ipynb
- examples/notebooks/contrasts.ipynb
- examples/notebooks/copula.ipynb
- examples/notebooks/count_hurdle.ipynb
- examples/notebooks/deterministics.ipynb
- examples/notebooks/discrete_choice_example.ipynb
- examples/notebooks/discrete_choice_overview.ipynb
- examples/notebooks/distributed_estimation.ipynb
- examples/notebooks/ets.ipynb
> DOC: Check, fix and format some notebooks

- examples/notebooks/statespace_local_linear_trend.ipynb
closes #9298
<details>
**Notes**:
```
```
using …
> DOC: Fix statespace local linear

- statsmodels/tsa/vector_ar/var_model.py
> DOC: Fixed typo in VARResults Attribute docstring : params -> coefs.

- statsmodels/base/l1_slsqp.py
- statsmodels/base/optimizer.py
- statsmodels/base/tests/test_shrink_pickle.py
- statsmodels/compat/scipy.py
- statsmodels/discrete/tests/test_discrete.py
- statsmodels/discrete/tests/test_predict.py
- statsmodels/discrete/tests/test_truncated_model.py
- statsmodels/distributions/copula/tests/test_copula.py
- statsmodels/distributions/discrete.py
- statsmodels/duration/hazard_regression.py
- statsmodels/genmod/_tweedie_compound_poisson.py
- statsmodels/genmod/tests/test_glm.py
- statsmodels/graphics/boxplots.py
- statsmodels/iolib/tests/test_summary2.py
- statsmodels/multivariate/tests/test_factor.py
- statsmodels/regression/tests/test_regression.py
- statsmodels/regression/tests/test_theil.py
- statsmodels/sandbox/distributions/extras.py
- statsmodels/sandbox/distributions/tests/test_multivariate.py
- statsmodels/sandbox/predict_functional.py
- statsmodels/sandbox/stats/tests/test_multicomp.py
- statsmodels/stats/libqsturng/qsturng_.py
- statsmodels/tools/tests/test_tools.py
- statsmodels/tsa/holtwinters/_smoothers.py
- statsmodels/tsa/holtwinters/model.py
- statsmodels/tsa/holtwinters/results.py
- statsmodels/tsa/holtwinters/tests/test_holtwinters.py
- statsmodels/tsa/statespace/tests/test_dynamic_factor.py
- statsmodels/tsa/tests/test_deterministic.py
> MAINT: Remove lazywhere

- statsmodels/discrete/tests/test_count_model.py
- statsmodels/discrete/tests/test_truncated_model.py
- statsmodels/distributions/copula/tests/test_copula.py
- statsmodels/formula/formulatools.py
- statsmodels/tsa/tests/test_x13.py
- statsmodels/tsa/x13.py
> Xfail regularized problems

- statsmodels/miscmodels/nonlinls.py
> Fix import error

- .github/workflows/cron-test.yml
> CI: Add 3.14 in GH actions
